### ISSUE TITLE
Modificar el modelo de bd de revisión cumplidos proveedores

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#101]
Se requiere realizar la modificación necesaria al modelo de [revisión de cumplidos proveedores](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EnIJcmsffY5PuVo2qTJjMUcB_WRR44DrFoG0a-7PlQYJsg?e=tez51l) para recibir la información necesaria para el documento ["CUMPLIDO A SATISFACCION POR PARTE DE LA DEPENDENCIA"](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EWeJnpy9-H5JpICoM2dYFAEBrgStQMIuwxuPDvvzhmtiHw?e=adeC8o)

**Sub Tareas**

- [x] Tomar como ejemplo el [mockup](https://udistritaleduco-my.sharepoint.com/:i:/g/personal/computo_udistrital_edu_co/ESuYSJn_hzlIkWUgnfKx1g4BCGB6dT5q09Vi6whMX7F5Kg?e=YhEfPi)
- [ ] Agregar las tablas necesarias siguiendo los lineamientos.

**Criterios de aceptación**

- [x] Modelo actualizado en la carpeta del proyecto.
- [x] Issue documentada

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by stevencol** [comment]
## Se inicia con actividad :

**Comment by stevencol** [comment]
Se realizan cambios solicitados 
![propuesta revision cumplidos v4](https://github.com/user-attachments/assets/867d5792-55cc-492d-8832-dad43a18cade)

**Comment by JuanCamiloMartinezLopez** [comment]
@stevencol Buen trabajo, 
Se solicitaron más ajustes por parte de los DBA:
- Cambio nombre de tabla "soporte_pago" por "soporte_cumplido"
- Cambio nombre de tabla "informe_satisfaccion" por "informacion_pago"
- Quitar tabla "tipo_cuenta_bancaria" y poner como referencia a una tabla externa (ej: banco)
- Quitar tabla "tipo_factura"  y poner como referencia a una tabla externa (ej: banco)
- Revisar el orden de las columnas

**Comment by stevencol** [comment]
Modificaciones realizadas 
![propuesta revision cumplidos v5](https://github.com/user-attachments/assets/676bfde9-981a-410b-a0d0-b322bb6b38ba)

**Comment by stevencol** [comment]
Se realizan cambios indicados en Daily : renombrando tipo factura por  tipo_documento_pago, , se ajustan relaciones y se indica relaciones externas : 

![propuesta revision cumplidos v5](https://github.com/user-attachments/assets/839fd7d4-e38f-4d71-9f7e-e5736d2b275f)


- Los documentos de esta versión se encuentran en:  [carperta](https://udistritaleduco-my.sharepoint.com/personal/computo_udistrital_edu_co/_layouts/15/onedrive.aspx?FolderCTID=0x012000126D0396B17002409C7255322B2A7B42&id=%2Fpersonal%2Fcomputo%5Fudistrital%5Fedu%5Fco%2FDocuments%2FINVERSI%C3%93N%2FPROYECTOS%20DE%20INVERSI%C3%93N%2FGERENCIA%20DE%20PROYECTOS%2FPROYECTOS%20OAS%2FPROYECTO%20CUMPLIDOS%20Y%20CERTIFICACIONES%2F2024%2FEjecuci%C3%B3n%2FGesti%C3%B3n%20t%C3%A9cnica%2FCUMPLIDOS%2FProveedores%2FModelos%20de%20base%20de%20datos%2FRevisi%C3%B3n%20cumplidos%20proveedores%2FV5)

**Comment by JuanCamiloMartinezLopez** [comment]
@stevencol Buen trabajo.
