### ISSUE TITLE
Preparar ambiente de pruebas para cumplidos CPS - Parte II

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#102]
Se requiere realizar los cambios necesarios en titán  para los contratos creados en la issue #91 

**Sub Tareas**

- [x] Realizar el proceso de pre liquidación para cada contrato creado.
```
POST http://pruebasapi.intranetoas.udistrital.edu.co:8082/v1/preliquidacion
```
```json
{
    "Activo": true,
    "Cdp": "",
    "DependenciaId": "",
    "Documento": "",
    "FechaFin": "",
    "FechaInicio": "",
    "NombreCompleto": "",
    "NumeroContrato": "",
    "TipoNominaId": 411,
    "ValorContrato": "",
    "Vigencia": "",
    "PersonaId": "",
    "Rp": "",
    "Completo": true
}
```

- [x] Validar con la petición http://busservicios.intranetoas.udistrital.edu.co:8282/wso2eiserver/services/administrativa_pruebas/contratos_contratista/{documento_contratista} 
- [x]  Revisar el entorno de pruebas.

**Criterios de aceptación**

- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
Al principio se estaban presentando problemas al hacer la petición POST decia que el formato de los datos era incorrecto pero esto se debia al formato de las fechas, se deja la manera correcta de estructurar el JSON.

```json
{
    "Activo": true,
    "Cdp": 1411,
    "DependenciaId": 27299,
    "Documento": "2222222",
    "FechaInicio": "2024-04-08T12:00:00Z",
    "FechaFin": "2025-02-07T12:00:00Z",
    "NombreCompleto": "Ana Sofía Torres García",
    "NumeroContrato": "3029",
    "TipoNominaId": 411,
    "ValorContrato": 35000000,
    "Vigencia": 2024,
    "PersonaId": 17225,
    "Rp": 3154,
    "Completo": true
}
```


Se actualiza el proveedor_id de todos los contratos puesto que antes se habían cambiado, se colocan nuevamente los proveedores de prueba, se crean las preliquidaciones de todos los contratos creados, los Json no están cargando del todo bien, pero se pueden distinguir los contratos de cada proveedor.

## 123456789

![Image](https://github.com/user-attachments/assets/5ea8464c-74d4-4552-99ba-852c236f7a12)

## 987654321


![Image](https://github.com/user-attachments/assets/34f30a52-f44a-4d4f-b5d4-132becf7bc00)


## 555555555


![Image](https://github.com/user-attachments/assets/cc7ef5fb-161d-4b46-9b49-cbe6bf4ef5c4)


## 2222222


![Image](https://github.com/user-attachments/assets/4b2bf19a-9f83-4b95-84ab-d572440f0bb2)

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 Buen trabajo.
