### ISSUE TITLE
Concertar, desarrollar y levantar del acta de sesión de requerimientos y/o refinamiento con el cliente

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/Cumplidos_y_certificaciones_documentacion#103]
Se requiere realizar la concertación, desarrollo y levantamiento del acta de sesión de requerimientos y/o refinamiento con el cliente

**Sub Tareas**

- [x] Concertar reunión con el cliente.
- [x] Desarrollar la reunión con el cliente.
- [x] Diligenciamiento y aprobación del formato de historias de usuario o Mockup por parte del cliente (si aplica).
- [x] Proyectar acta de la reunión.
- [ ] Recolectar las firmas correspondientes.

**Criterios de aceptación**

- [x] Acta revisada por el líder de proyecto.
- [x] Acta firmada por las partes con anexo de historias de usuario o mockup.
- [x] Acta y anexos documentados.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se ha agendado la reunión con el cliente para el día 02/08/2024 a las 10 am 

[Link reunión](https://teams.microsoft.com/l/meetup-join/19%3ameeting_NWRjODQzZGEtMjkzYS00NGY2LWIxMTItMTI3ZTJiM2Y5OTlm%40thread.v2/0?context=%7b%22Tid%22%3a%22d51388ef-6ab0-4363-9f94-d56644a45970%22%2c%22Oid%22%3a%22b989c328-89fa-4486-abfe-df75fdd723ba%22%7d)

**Comment by mantnicot** [comment]
Se adjunta el acta de la reunión , se da espera a la aceptación del Gerente para enviar a firmar

[Acta sin firmas](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/ETH7pQB7ZNBJqnl-UXxpX4wBLgjuciCY94nNrL3sZ0hGZQ?e=8AK2rR)

**Comment by jcmurilloa** [comment]
Acta aprobada para iniciar la recolección de firmas, buen trabajo @mantnicot

**Comment by mantnicot** [comment]
Se ha completado la recolecta de firmas 

[Acta firmada](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EQeOZoSKf09Louvytr_lhuIBomJySuft-bue0TnPuI60Ag?e=qzxARy)

**Comment by jcmurilloa** [comment]
Muy buen trabajo @mantnicot !
