### ISSUE TITLE
Agregar funcionalidad al frontend - Rol Supervisor

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#104]
Se requiere realizar la conexión entre las funciones desarrolladas en el mid #93 y #95 al [microfrontend](https://github.com/udistrital/revision_cumplidos_proveedores_mfhttps://github.com/udistrital/revision_cumplidos_proveedores_mf) desarrollado.

**Sub Tareas**

- [x] Conectar los diferentes endpoint segun su funcion en el mf y validar su funcionamiento.

**Criterios de aceptación**

- [x] Funciones del mid funcionando desde el mf.
- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
## :triangular_flag_on_post: **Conexión Endpoints Cliente**  :triangular_flag_on_post:


Se comienza con la tarea de unir los endpoints al cliente.

**Comment by faidercamilo26** [comment]
Por el momento se ha finalizado la obtención de los datos de los contratos de un supervisor, como no hay contratos de prueba de proveedores se edita la función para que traiga datos y probar la tabla. Ya se creo el servicio y las funciones correspondientes para hacer las peticiones al mid, solo falta conectar algunos endpoints.



![Image](https://github.com/user-attachments/assets/ea12738f-246e-47bd-ac13-13a82e7a3c2b)

**Comment by faidercamilo26** [comment]
Se realiza la integración de todos los endpoints del mid en el cliente a excepción de la parte de informe de seguimiento que todavía esta generando un pequeño inconveniente al momento de hacer la petición para obtener el balance financiero de un contrato, ya se esta trabajando para solucionarlo.

## Carga soportes

En esta parte se recuperan los datos del supervisor que inicie sesión y con estos datos se hace la búsqueda de los contratos que tiene vigentes.


![Image](https://github.com/user-attachments/assets/2f4286ee-d2a9-4029-861d-20d93ef43754)


## Histórico solicitudes contrato

Ya se consultan las solicitudes que ha tenido un mismo contrato para mostrar el histórico y también es posible crear una nueva solicitud con un estado inicial de cargando documentos. Por el momento el campo de periodo en esta tabla se esta quemando en código pero en próximas tareas se espera hacer el refactor con los nuevos datos del modelo para hacerlo dinamico.



![Image](https://github.com/user-attachments/assets/d5e43a50-bbd1-4340-accd-aef0d2bc6952)


## Cargar documento a un cumplido

Ya es posible cargar un documento a un cumplido, se desplegá el listado de los posibles documentos que se pueden subir en un cumplido, para que el supervisor seleccione el documento que desea subir y al darle en el boton de "Cargar Soportes" se asocia el documento al cumplido y se sube al gestor documental. Tambien se muestra todo el historial de archivos subidos en un cumplido. Se puede eliminar un documento pero la visualización por el momento no esta mostrando el pdf, se esta trabajando en la solución.

 

![Image](https://github.com/user-attachments/assets/6afedbb8-8c98-418a-90f5-57627529e977)



![Image](https://github.com/user-attachments/assets/56f6a0fe-8033-405f-9d36-f4e3b2fdd8ea)




![Image](https://github.com/user-attachments/assets/0ec10990-298c-4fb6-a2b9-7412ba094951)


## Informe de seguimiento 



![Image](https://github.com/user-attachments/assets/46418dfa-93fc-4487-abf5-bafc2777d7a7)

**Comment by faidercamilo26** [comment]
Se trabaja para mostrar un pdf de un cumplido al hacer click en la opción de ver documento sin embargo aparece el siguiente error y el modal se queda en blanco, puesto que por políticas de seguridad no se puede cargar la el pdf.



![Image](https://github.com/user-attachments/assets/b8e5f051-b41b-4581-ad00-650b84c2a308)


```
Política de seguridad de contenido: Las opciones de esta página han bloqueado la carga de un recurso en blob:http://localhost:4200/eca0a4a3-295d-4f4f-aa7d-16a132ea2eb1 ("default-src").

```

Este es el codigo del modal

``` javaScript

import { Component, Inject } from '@angular/core';
import { MAT_DIALOG_DATA, MatDialogRef } from '@angular/material/dialog';

@Component({
  selector: 'app-ver-soporte-modal',
  templateUrl: './ver-soporte-modal.component.html',
  styleUrls: ['./ver-soporte-modal.component.css']
})
export class VerSoporteModalComponent {

  pdfSrc: string;

  constructor(
    public dialogRef: MatDialogRef<VerSoporteModalComponent>,
    @Inject(MAT_DIALOG_DATA) public data: { fileURL: string },
  ) {
    this.pdfSrc = data.fileURL;
  }

  close(): void {
    this.dialogRef.close();
  }
}

```

## HTML

```
<div class="modal-header">
  <button mat-icon-button (click)="close()" >
    <mat-icon color="warn">close</mat-icon>
  </button>
</div>
<div mat-dialog-content>
  <iframe [src]="pdfSrc | safeUrl" width="100%" height="500px"></iframe>
</div>

```

## Pipe 

Se crea el pipe safeUrl para indicar que la URL es segura y que se pueda mostrar en el modal.

``` Angular
import { Pipe, PipeTransform } from '@angular/core';
import { DomSanitizer, SafeResourceUrl } from '@angular/platform-browser';

@Pipe({
  name: 'safeUrl'
})
export class SafeUrlPipe implements PipeTransform {

  constructor(private sanitizer: DomSanitizer) {}

  transform(value: string): SafeResourceUrl {
    return this.sanitizer.bypassSecurityTrustResourceUrl(value);
  }

}


```

##  Codigo para abrir el modal

```Angular
getDocument(documentBase64: string, nameWindow: string) {
    const arrayBuffer = this.utilsService.base64ToArrayBuffer(documentBase64);
    const file = new Blob([arrayBuffer], { type: 'application/pdf' });
    const fileURL = URL.createObjectURL(file);

    const dialogRef = this.dialog.open(VerSoporteModalComponent, {
      width: '53%',
      height: '70%',
      panelClass: 'custom-dialog-container',
      data: { fileURL: fileURL }
    });


    /*
    window.open(
      fileURL,
      nameWindow,
      "resizable=yes,status=no,location=no,toolbar=no,menubar=no,fullscreen=yes,scrollbars=yes,dependent=no,width=800,height=900"
    );
    */

  }
```

**Comment by faidercamilo26** [comment]
Por el momento se soluciona haciendo una ventana emergente.



![Image](https://github.com/user-attachments/assets/bdb84141-f948-499b-86be-13b3a912fec8)

**Comment by faidercamilo26** [comment]
Se finaliza con la unión del mid y del cliente, solo faltaba implementar la parte del informe de seguimiento, se genera un botón interactivo para que el supervisor pueda subir un documento, o al darle click en el informe de seguimiento le aparezca la opción de crear el documento y lo redirija a la sección para poder hacerlo.



![Image](https://github.com/user-attachments/assets/953d10dc-4560-47e1-a1c6-97fbd3ab3db8)


También se completa la funcionalidad de crear el informe de seguimiento, y para poderlo visualizar, por el momento se muestra en una nueva ventana, pero se están consultando librerías para no poderlo visualizar en un modal.



![Image](https://github.com/user-attachments/assets/545cc530-866e-421d-84a8-5f98f8de0fb5)

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 Buen trabajo.
