### ISSUE TITLE
Agregar funcionalidad al frontend - Rol Contratación y Ordenador

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#105]
Se requiere realizar la conexión entre las funciones desarrolladas en el mid #94 y #95 al [microfrontend](https://github.com/udistrital/revision_cumplidos_proveedores_mfhttps://github.com/udistrital/revision_cumplidos_proveedores_mf) desarrollado.

**Sub Tareas**

- [ ] Conectar los diferentes endpoint segun su funcion en el mf y validar su funcionamiento.

**Criterios de aceptación**

- [ ] Funciones del mid funcionando desde el mf.
- [ ] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by JuanCamiloMartinezLopez** [comment]
@stevencol por favor comenzar con la tarea

**Comment by stevencol** [comment]
Se inicia con actividad

**Comment by stevencol** [comment]
Se encuentran en el mid, que fueron causados al refactorizar el crud : udistrital/Cumplidos_y_certificaciones_documentacion#94
![errores](https://github.com/user-attachments/assets/8c2b34fe-9e5e-4461-bd87-16a8785decb9)

- Se evidencia que es por en nombramiento de algunas variables ejemplo
-  ruta anterior (con error por la actualización):  
  http://localhost:8080/v1/cambio_estado_cumplido/?query=DocumentoResponsable:52622477,EstadoCumplidoId.Abreviacion:PRO,Activo:true

- ruta nueva sin error: http://localhost:8080/v1/cambio_estado_cumplido/?query=DocumentoResponsable:52622477,EstadoCumplidoId.CodigoAbreviación:PRO,Activo:true

**Comment by stevencol** [comment]
ara realizar la tarea, se hizo un pull request para consolidar todo el servicio en un solo aplicativo. Sin embargo, esto generó errores. Se intentó usar el servicio en una rama funcional, pero al realizar la consulta de los documentos, que es una tarea fundamental para este paso, se produjeron varios errores. Estos errores parecen ser los mismos que se generaron al cambiar el CRUD.

Por lo tanto, para asegurar la funcionalidad, se reemplazó el servicio, aunque parcialmente, ya que, debido a pruebas, se imprime la respuesta de la petición. Sin embargo, por alguna razón, después se genera un error. La respuesta es

![image](https://github.com/user-attachments/assets/ba6ff28d-a884-4e57-8e0e-5306c906eb8b)

![image](https://github.com/user-attachments/assets/8fc0f5cb-b4c0-4458-b739-3215c6b58ee0)

**Comment by stevencol** [comment]
La causa del problema eran errores en los puertos. La rama feature/EndpointsOrdenador funcionaba bajo el puerto 8080, y su CRUD bajo el puerto 8090, mientras que feature/EndpointsSupervisor funcionaba bajo el puerto 8090 y su CRUD bajo el 8080. Esto se soluciona cambiando el puerto utilizado por el CRUD y ajustando el del servidor.

**Comment by stevencol** [comment]
Se tiene que modificar la respuesta del backend, ya que en la respuesta falta el número de cumplido, el cual es útil para la consulta de los documentos cargados, 
Respuesta actual: 
![image](https://github.com/user-attachments/assets/486d6572-e80e-49c0-8f7d-5dbad32b13b2)

**Comment by stevencol** [comment]
Se ajusta a respuesta requerida para ordenador, 
![image](https://github.com/user-attachments/assets/d603052e-0699-49e8-95ec-02d29fedb121)
faltantes , contratación

**Comment by stevencol** [comment]
Se termina de ajustar respuesta para los helpers de consulta
![image](https://github.com/user-attachments/assets/7e6d44b7-7c8d-4526-9241-0137fbd2e465)

**Comment by stevencol** [comment]
Se comienza con el listado de los cumplidos pendientes: 
Contratacion:
![image](https://github.com/user-attachments/assets/524c36b6-6205-4014-8a67-65aaa1ed7973)

Ordenador: 
![image](https://github.com/user-attachments/assets/3c0f84c5-0087-4500-94e5-daaec66af830)

**Comment by stevencol** [comment]
Se sigue avanzando y ya se lista documentos cargados
![errores (-1)](https://github.com/user-attachments/assets/f480f8c3-c7d8-4fe5-904b-56937d0ddad2)

**Comment by stevencol** [comment]
Los documentos se listan pero se produce un error en la visualización:
![errores (-1)](https://github.com/user-attachments/assets/c9c4bda8-c0c0-4b8d-98ff-7d01d6ecbdaa)


El error de la consola del navegador es: 
``` JavaScript
Refused to frame '' because it violates the following Content Security Policy directive: "default-src 'self' https: localhost:*". Note that 'frame-src' was not explicitly set, so 'default-src' is used as a fallback.

VM39640:647  Uncaught TypeError: Cannot read properties of null (reading 'classList')
    at HTMLDocument.onDocumentLoad (VM39640:647:19)
```

Se soluciona con: 
``` html
 <meta http-equiv="Content-Security-Policy" content="default-src 'self' https: data: blob: localhost:*; script-src 'unsafe-inline' 'unsafe-eval' https: localhost:*; connect-src https: localhost:* ws://localhost:*; style-src 'unsafe-inline' https:; object-src 'none';">

```

- Se avanza en La visualización del del documento
- 
![errores (-1)](https://github.com/user-attachments/assets/545af16a-e5b6-4b4a-9fb0-72538ec18471)

**Comment by stevencol** [comment]
Al momento de que el contratista apruebe el pago, se tiene que generar el documento y guardarlo en los soportes cargados, como inicialmente solo se generaba el pdf , se tuvo que cambiar respuesta para que no entregara el archivo sino la respuesta en base64:
![errores (-1)](https://github.com/user-attachments/assets/625dd62a-c58a-49a0-a56d-38670b75849d)

Se modifica a:
* Donde se responde el archivo en base64, y se responde temporalmente el base64 con el fin de cargar el documento:
![errores (-1)](https://github.com/user-attachments/assets/adb101dc-2438-4a33-8694-c1532d46cf4a)

**Comment by stevencol** [comment]
Se crea función en el cliente para consultar, el id des estado para realizar la petición y registrar el cambio estado : 

``` JavaScript
  ObtenerEstadoId(codigoAbreviacion: string): Observable<number | null> {
    return this.ordenadorService
      .getCumplidosProveedoresCrud(
        `/estado_cumplido?query=CodigoAbreviación:${codigoAbreviacion}`
      )
      .pipe(
        map((response: any) => {
          if (response.Data != null && response.Data.length > 0) {
            return response.Data[0].Id;
          }
          return null;
        }),
        catchError((error) => {
          console.error('Error', error);
          return of(null);
        })
      );
  }
```

- Y se aplica en : 
``` JavaScript
async aprobarSoporte(idCumplido: number) {
    let x = await this.alertService.alertConfirm(
      '¿Esta seguro de aprobar los soportes?'
    );
    console.log(idCumplido);
    if (x.isConfirmed) {
      const id = await this.ObtenerEstadoId('AO').toPromise();
      console.log('log' + id);

      if (id === null || id === undefined) {
        throw new Error('El ID obtenido es nulo o indefinido.');
      }
      const cambioEstado = new CambioEstado(
        id,
        idCumplido,
        '111111',
        'Contratacion'
      );
      this.CambiarEstado(cambioEstado);
      console.log(cambioEstado);
      await this.CargarTablaCumplidos();
      this.alertService.showSuccessAlert('Aprobado', '!se Aprobo con exito!');
    } else {
      this.alertService.showCancelAlert(
        'Cancelado',
        'No se pudo relizar la accion'
      );
    }
  }
```

**Comment by stevencol** [comment]
Al momento de que Contratación apruebe el cumplido se tendrá que generar la autorización de pago, el cual se tendrá que cargar en los documentos cargados, se inicia creando la función que recibirá el base64 :  
![errores (-1)](https://github.com/user-attachments/assets/0ff364b9-7fa7-444b-a845-4133c38a3c53)

**Comment by stevencol** [comment]
Se crea función para obtener el id del tipo de documento para su posterior registro:
``` JavaScript

    ObternerIdTipoDocumento(codigoAbreviacion:string){
      return this.contratacionService
      .getDocumnetosCrud(`tipo_documento/?query=DominioTipoDocumento.CodigoAbreviacion:CUMP_PROV,CodigoAbreviacion:${codigoAbreviacion}`)
      .pipe(
        map((response: any) => {
          if (response.Data != null && response.Data.length > 0) {
            console.log(response)
          }
          return null;
        }),
        catchError((error) => {
          console.error('Error', error);
          return of(null);
        })
      
      );
    }
```

y se implementa en : 

``` JavaScript

    let x= await this.alertService.alertConfirm("¿Esta seguro de aprobar los soportes?");
    console.log(idCumplido)
    if(x.isConfirmed){
      
      const id = await this.ObtenerEstadoId("PRO").toPromise();
      const tipo_documento = await this.ObternerIdTipoDocumento("AP").toPromise();
      console.log(tipo_documento)
      console.log("log"+id)
     
      if (id === null || id === undefined) {
        throw new Error("El ID obtenido es nulo o indefinido.");
      }

      const cambioEstado = new CambioEstado(
        id,                    
        idCumplido,            
        '52622477',             
        'Contratacion'          
    );

  /// this.CambiarEstado(cambioEstado);
  const autorizacionPago = await this.GenerarSoporte(idCumplido).toPromise();
    console.log(autorizacionPago);
    console.log(cambioEstado)
    this.CargarTablaCumplidos();
     this.alertService.showSuccessAlert("Aprobado","!se Aprobo con exito!");
    }else{
     this.alertService.showCancelAlert("Cancelado","No se pudo relizar la accion");
    }
   
    
   }
```


Genera el error en consola : 
``` JavaScript
zone.min.js:132 
 Refused to connect to 'http://pruebasapi.intranetoas.udistrital.edu.co:8094/v1/tipo_documento/?query=DominioTipoDocumento.CodigoAbreviacion:CUMP_PROV,CodigoAbreviacion:AP' because it violates the following Content Security Policy directive: "connect-src https: localhost:* ws://localhost:*".
errorManager.ts:20 
 Backend returned code 0, body was:  
ProgressEvent {isTrusted: true, lengthComputable: false, loaded: 0, total: 0, type: 'error', …}
tabla-aprobacion-pago.component.ts:185 
 Error 
ProgressEvent {isTrusted: true, lengthComputable: false, loaded: 0, total: 0, type: 'error', …}
```

**Comment by stevencol** [comment]
Cuando la persona de contratación aprueba el cumplido ya carga la autorización de pago:
![errores (-1)](https://github.com/user-attachments/assets/fcc077ed-41af-49b8-b609-356e5e69861c)

**Comment by stevencol** [comment]
Inicialmente, por error, se implementó la funcionalidad para generar la autorización de pago en el rol de contratación. Sin embargo, esta funcionalidad corresponde al rol de ordenador. Por lo tanto, se ha trasladado al rol de ordenador.

Además, se ha modificado el modal de generación de la autorización de pago para que, cuando se realice la generación de la aprobación de pago, se muestren los botones de aprobación correspondientes. lo que permitirá el cargue adecuado del documento de aprobación pago a los documentos:
![errores (-1)](https://github.com/user-attachments/assets/9bdf5b54-de7e-4323-ba29-3fd681def79c)

**Comment by stevencol** [comment]
Se modifica estructura del proyecto para unificar un solo componente que liste los documentos cargados:
de:
![image](https://github.com/user-attachments/assets/bb2287ce-0767-4176-98c3-d65250b32708)

a: 
![image](https://github.com/user-attachments/assets/6871df29-1d08-4255-9b87-427ee8f53b67)


## Eliminando modal-ver-soportes en paquete ordenadory contratacion

**Comment by JuanCamiloMartinezLopez** [comment]
@stevencol Buen trabajo.
