### ISSUE TITLE
Ajustar y conectar el mf de revisión al root de cumplidos proveedores

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#106]
Se requiere realizar la conexión del mf de [revision](https://github.com/udistrital/revision_cumplidos_proveedores_mf) con el [root](https://github.com/udistrital/cumplidos_proveedores_root_mf) de cumplidos proveedores.

**Sub Tareas**

- [x] Revisar la autenticación en el root.
- [x] la carga del menú con las diferentes opciones (el registro en configuracion_crud)
- [x] Solucionar los posibles errores.

**Criterios de aceptación**

- [x] mf y root funcionando.
- [x] issue documentado.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
Se realiza la configuración del root con el core, se verifica la autenticación y esta funcionando correctamente


![Image](https://github.com/user-attachments/assets/37019a6d-afe3-4022-b055-50ae3f97b396)



![Image](https://github.com/user-attachments/assets/6d054ec3-0bd5-4e84-83bd-f4503a838daf)




![Image](https://github.com/user-attachments/assets/505511d6-0eed-41f7-98ec-75d7fb78ba18)

**Comment by faidercamilo26** [comment]
Se crea el sistema de cumplidos proveedores, Se crean los roles correspondientes y se les asignan los menús correspondientes a su rol.

![Image](https://github.com/user-attachments/assets/249ef38d-7c11-4605-ac27-b7b9fc0a8116)



![Image](https://github.com/user-attachments/assets/51fdc78b-738a-4870-bd6e-16b4985e3c0c)



![Image](https://github.com/user-attachments/assets/b4ccebb7-91c6-4e3e-bf2b-23c8f0bb0af5)



![Image](https://github.com/user-attachments/assets/786f032a-192f-41ae-a8a2-3cdbfd56288b)




![Image](https://github.com/user-attachments/assets/f23beb3e-324a-4eed-84a4-b6bf011e070c)

**Comment by faidercamilo26** [comment]
Muestra del menú funcionando para el rol de supervisor.



![Image](https://github.com/user-attachments/assets/b96ce37b-3561-4ac0-aba3-fcdd0035e194)

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 Buen trabajo.
