### ISSUE TITLE
Ajustar CRUD de revisión de cumplidos proveedores

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#107]
Se requiere realizar el ajuste y adicción de acuerdo al ultimo modelo de [revisión](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EsoUT-TJycNIvy1TSIlAsSoBRVU77d397qj3cEzf7twMpw?e=J532wI)

**Sub Tareas**

- [ ] Agregar la nueva tabla de informacion_pago con sus respectivos ajustes (permitir consulta por múltiples valores, softdelete. etc)
- [ ] Realizar cambios a las demás tablas existentes.

**Criterios de aceptación**

- [ ] Crud actualizado según el modelo.
- [ ] workspace de postman actualizado.
- [ ] issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by stevencol** [comment]
Se inicia con actividad

**Comment by stevencol** [comment]
"Se asigna estado activo por defecto en todos los modelos."

"Se modifica el código para que automáticamente se asigne el estado como Activo."

**Comment by JuanCamiloMartinezLopez** [comment]
@stevencol Buen trabajo
