### ISSUE TITLE
Pruebas funcionales del módulo de revision de cumplidos proveedores

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#108]
Se requiere realizar las pruebas funcionales para el módulo de revisión cumplidos proveedores.

**Sub Tareas**

- [x] Probar el flujo según se indica en el mockup.
- [x] Validar las funciones desarrolladas (filtros, visualización del estados, visualización de documentos, descarga compilado, etc).
- [x] Registrar en el formato de pruebas los resultados.

**Criterios de aceptación**

- [x] Documentación de la validación y/o casos encontrados. [Pruebas.Funcionales.xlsx](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/files/15377288/Pruebas.Funcionales.xlsx)
- [x] Documentacion del issue.

 Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
Se realizan las pruebas funcionales de los enpoints utilizados en el sistema de cumplidos proveedores, se sube el excel a la carpeta del proyecto y se adjunta aqui la tabla para que quede constancia en la issue del trabajo.


[Pruebas Funcionales Cumplidos Proveedores](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/ER9tW3wKb5hJqzHY2CBVN08Blc7koM1pucNAbtLS4eQhbA?e=QmHX2R)

| Hallazgo | Encontrado por  | Dependencia | Fecha    | Módulo                | Formulario/Sección   | Contexto                                                                                                                                                                                                                      | Ruta de ingreso                                                                                                                                                                                                        | PRUEBAS EN LOCAL | AMBIENTE DE PRUEBAS | Comportamiento esperado                                                                                                                                                                                                                | Comportamiento actual                                                                                                                                                                                                               | Observaciones Adicionales                                                                                                                                                                                                                                                                         |
| -------- | --------------- | ----------- | -------- | --------------------- | -------------------- | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ---------------- | ------------------- | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| 1        | Faider Trujillo | OAS         | abril 11 | Cumplidos Proveedores | pages/subir-soportes | Se hace testeo de la peticion encargada de consultar los contratos activos de un supervisor para poder crear un nuevo cumplido.                                                                                               | [http://localhost:8080/v1/supervisor/contratos-supervisor/{documento_supervisor}](http://localhost:8080/v1/supervisor/contratos-supervisor/%7bdocumento_supervisor%7d)                                                 | OK               |                     | <br><br>Petición GET exitosa a Revision Cumplidos Proveedores Mid al enviar el número documento del supervisor, retornando, el nombre del supervisor, las depepndecias asociadas y los contratos disponibles para generar un cumplido. | <br><br>Respuesta a peticion GET pasando el número de documento del supervisor exitosa, retorno de Status 200 retornando, el nombre del supervisor, las dependecias asociadas y los contratos disponibles para generar un cumplido. | Temporalmente la consulta esta trayendo informacion de tipos de contrato número 6 lo cual no deberia estar haciendo, sin embargo, se hace esto porque en las base de datos de prueba no hay contratos de proveedores activos y al crear uno o editar uno existente las peticiones no los retorna. |
| 2        | Faider Trujillo | OAS         | abril 11 | Cumplidos Proveedores | pages/subir-soportes | Se hace testeo de la peticion encargada de consultarel historico de solicitudes de pago que tiene un proveedor.                                                                                                               | [http://localhost:8080/v1/supervisor/solicitudes-contrato](http://localhost:8080/v1/supervisor/solicitudes-contrato)                                                                                                   | OK               |                     | <br><br>Petición GET exitosa a Revision Cumplidos Proveedores Mid al enviar el numero de contrato suscrito y la vigencia, retornando, un listados de todas las solicitudes de pago del proveedor con su ultimo estado.                 | <br><br>Respuesta a peticion GET pasando el número de documento del supervisor exitosa, retorno de Status 200 retornando, un listados de todas las solicitudes de pago del proveedor con su ultimo estado.                          | N/A                                                                                                                                                                                                                                                                                               |
| 3        | Faider Trujillo | OAS         | abril 11 | Cumplidos Proveedores | pages/subir-soportes | Se hace testeo del endpoint POST encargado de crear un nuevo cumplido para un proveedor específico.                                                                                                                           | localhost:8080/v1/cumplido_proveedor                                                                                                                                                                                   | OK               |                     | Petición POST exitosa a Cumplidos Proveedores CRUD al enviar el número de contrato y la vigencia, creando el nuevo cumplido y retornando el ID del cumplido generado y los datos asociados.                                            | Respuesta a petición POST exitosa, retorno de Status 201 con el ID del cumplido generado y los datos asociados al nuevo cumplido.                                                                                                   | N/A                                                                                                                                                                                                                                                                                               |
| 4        | Faider Trujillo | OAS         | abril 11 | Cumplidos Proveedores | pages/subir-soportes | Se hace testeo del endpoint POST encargado de cambiar el estado de un cumplido.                                                                                                                                               | [http://localhost:8080/v1/solicitud-pago/cambio-estado](http://localhost:8080/v1/solicitud-pago/cambio-estado)                                                                                                         | OK               |                     | Petición POST exitosa a Cumplidos Proveedores MID al enviar los parámetros requeridos, actualizando el estado del cumplido y retornando los datos del nuevo estado.                                                                    | Respuesta a petición POST exitosa, retorno de Status 200 con los datos del nuevo estado del cumplido actualizado.                                                                                                                   | N/A                                                                                                                                                                                                                                                                                               |
| 5        | Faider Trujillo | OAS         | abril 11 | Cumplidos Proveedores | pages/subir-soportes | Se hace testeo del endpoint GET encargado de traer la lista de documentos que se pueden subir a un cumplido.                                                                                                                  | [http://localhost:8080/v1/supervisor/tipos-documentos-cumplido](http://localhost:8080/v1/supervisor/tipos-documentos-cumplido)                                                                                         | OK               |                     | Petición GET exitosa a Cumplidos Proveedores Mid al acceder a la ruta sin parámetros, retornando una lista de tipos de documentos permitidos.                                                                                          | Respuesta a petición GET pasando la ruta sin parámetros exitosa, retorno de Status 200 con una lista de tipos de documentos permitidos (e.g., ARL, fotocopia de documento, etc.).                                                   | N/A                                                                                                                                                                                                                                                                                               |
| 6        | Faider Trujillo | OAS         | abril 11 | Cumplidos Proveedores | pages/subir-soportes | Se hace testeo del endpoint POST encargado de subir un documento a un cumplido. El cual recibe, e documento encriptado en base 64, el tipo de documento, las observaciones, el item id del documento y el nombre del archivo. | [http://localhost:8080/v1/supervisor/solicitud-pago/soportes](http://localhost:8080/v1/supervisor/solicitud-pago/soportes)                                                                                             | OK               |                     | Petición POST exitosa a Cumplidos Proveedores Mid al enviar el documento adjunto, retornando el ID del documento subido al gestor documental y los datos del cumplido.                                                                 | Respuesta a petición POST exitosa, retorno de Status 200 con el ID del documento subido y los datos del cumplido.                                                                                                                   | N/A                                                                                                                                                                                                                                                                                               |
| 7        | Faider Trujillo | OAS         | abril 11 | Cumplidos Proveedores | pages/subir-soportes | Se hace testeo del endpoint GET encargado de retornar un listado de documentos subidos a un cumplido, con cada documento encriptado en base64.                                                                                | [http://localhost:8080/v1/supervisor/solicitud-pago/soportes/{cumplido_proveedor_id}](http://localhost:8080/v1/supervisor/solicitud-pago/soportes/%7bcumplido_proveedor_id%7d)                                         | OK               |                     | Petición GET exitosa a Cumplidos Proveedores Mid al enviar el ID del cumplido, retornando un listado de documentos con cada uno encriptado en base64.                                                                                  | Respuesta a petición GET exitosa, retorno de Status 200 con un listado de documentos encriptados en base64 correspondientes al ID del cumplido.                                                                                     | N/A                                                                                                                                                                                                                                                                                               |
| 8        | Faider Trujillo | OAS         | abril 11 | Cumplidos Proveedores | pages/subir-soportes | Se hace testeo del endpoint DELETE encargado de cambiar el estado del campo "activo" a \`false\` para un documento especificado por su ID, y retornar un mensaje de confirmación.                                             | [http://localhost:8080/v1/supervisor/solicitud-pago/soportes/{documento_id}](http://localhost:8080/v1/supervisor/solicitud-pago/soportes/%7bdocumento_id%7d)                                                           | OK               |                     | Petición DELETE exitosa a Cumplidos Proveedores Mid  al enviar el ID del documento, cambiando el estado a \`false\` y retornando un mensaje indicando que el soporte fue eliminado correctamente.                                      | Respuesta a petición DELETE exitosa, retorno de Status 200 con un mensaje confirmando que el soporte fue eliminado correctamente y el campo "activo" del documento está establecido en \`false\`.                                   | Se debe hacer un refactor de la funcion para que retorne los datos del soporte que fue eliminado del cumplido.                                                                                                                                                                                    |
| 9        | Faider Trujillo | OAS         | abril 11 | Cumplidos Proveedores | pages/subir-soportes | Se hace testeo del endpoint GET encargado de retornar el valor total y el saldo pendiente de un contrato especificado por su número de contrato y vigencia.                                                                   | [http://localhost:8080/v1/supervisor/balance-financiero-contrato/{numero_contrato_suscrito}/{vigencia}](http://localhost:8080/v1/supervisor/balance-financiero-contrato/%7bnumero_contrato_suscrito%7d/%7bvigencia%7d) | OK               |                     | Petición GET exitosa al enviar el número de contrato y la vigencia, retornando el valor total del contrato y el saldo pendiente de pago.                                                                                               | Respuesta a petición GET exitosa, retorno de Status 200 con el valor total del contrato y el saldo pendiente de pago correspondiente al número de contrato y vigencia proporcionados.                                               | N/A                                                                                                                                                                                                                                                                                               |
| 10       | Faider Trujillo | OAS         | abril 11 | Cumplidos Proveedores | pages/subir-soportes | Se hace testeo del endpoint POST encargado de crear un informe de seguimiento.                                                                                                                                                | [http://localhost:8080/v1/supervisor/informe-seguimiento](http://localhost:8080/v1/supervisor/informe-seguimiento)                                                                                                     | OK               |                     | Petición POST exitosa a Cumplidos Proveedores MID al enviar los datos requeridos, generando el informe de seguimiento y retornando el nombre del informe junto con el archivo PDF en base 64.                                          | Respuesta a petición POST exitosa, retorno de Status 200 con el nombre del informe y el archivo PDF en base 64 correspondiente.                                                                                                     | N/A                                                                                                                                                                                                                                                                                               |
| 11       | Faider Trujillo | OAS         | abril 11 | Cumplidos Proveedores | pages/subir-soportes | Se hace testeo del endpoint GET encargado de recibir el número de documento de un ordenador y retornar la información de las solicitudes de pago pendientes para su aprobación o rechazo.                                     | localhost:8080/v1/ordenador/solicitudes-pago/{documento_ordenador}                                                                                                                                                     | OK               |                     | Petición GET exitosa a Cumplidos Proveedores MID al enviar el número de documento del ordenador, retornando la lista de solicitudes de pago pendientes con los detalles necesarios para aprobarlas o rechazarlas.                      | Respuesta a petición GET exitosa, retorno de Status 200 con la lista de solicitudes de pago pendientes, incluyendo los detalles para la toma de decisión (aprobar o rechazar).                                                      | El enpoint no esta retornando datos posiblemente por el numero de documento y la falta de datos de prueba pero  el status de la respuesta es 200 sin errores                                                                                                                                      |
| 12       | Faider Trujillo | OAS         | abril 12 | Cumplidos Proveedores | pages/subir-soportes | Se hace testeo del endpoint GET encargado de recibir el número de documento de un ordenador y retornar un listado de las solicitudes de pago aprobadas que pueden ser revertidas.                                             | localhost:8080/v1/ordenador/revertir-solicitud-pago/{documento_ordenador}                                                                                                                                              | OK               |                     | Petición GET exitosa a Cumplidos Proveedores MID al enviar el número de documento del ordenador, retornando un listado de las solicitudes de pago aprobadas que permiten su reversión a estado rechazado.                              | Respuesta a petición GET exitosa, retorno de Status 200 con un listado de las solicitudes de pago aprobadas que el ordenador puede revertir a rechazadas.                                                                           | El enpoint no esta retornando datos posiblemente por el numero de documento y la falta de datos de prueba pero  el status de la respuesta es 200 sin errores.                                                                                                                                     |
| 13       | Faider Trujillo | OAS         | abril 12 | Cumplidos Proveedores | pages/subir-soportes | Se hace testeo del endpoint GET encargado de recibir el ID de un cumplido,  y retornar el  PDF de aprobación de pago.                                                                                                         | localhost:8080/v1/ordenador/certificado-aprobacion-pago/{id_cumplido_proveedor}                                                                                                                                        | OK               |                     | Petición GET exitosa a Cumplidos Proveedores MID al enviar el ID del cumplido, retornando un archivo PDF de aprobación de pago en base 64.                                                                                             | Respuesta a petición POST exitosa, retorno de Status 200 con un archivo PDF de aprobación de pago  correspondiente al cumplido aprobado.                                                                                            | Aunque el endpoint esta retornando un codigo de status 200 el pdf que esta retornando no tiene el formato correcto y adicionalmente se deberia estar retornando codificado en base 64 para despues ser descargado en el cliente, pero se esta retornando el pdf sin encriptar.                    |
| 14       | Faider Trujillo | OAS         | abril 12 | Cumplidos Proveedores | pages/subir-soportes | Se hace testeo del endpoint GET encargado de retornar los cumplidos que están en estado "pendiente aprobación contratación" para ser aprobados o rechazados.                                                                  | localhost:8080/v1/contratacion/solicitudes-pago                                                                                                                                                                        | OK               |                     | Petición GET exitosa a Cumplidos Proveedores MID al acceder a la ruta sin parámetros, retornando una lista de cumplidos que están en estado pendiente de aprobación contratación, para su respectiva aprobación o rechazo.             | Respuesta a petición GET exitosa, retorno de Status 200 con una lista de cumplidos en estado pendiente de aprobación contratación, listos para ser aprobados o rechazados.                                                          | N/A                                                                                                                                                                                                                                                                                               |

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 Buen trabajo.
