### ISSUE TITLE
Revision de firma electrónica para su implementacion

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#109]
Se requiere revisar el servicio de firma electrónica para su implementación en el módulo de revisión de cumplidos proveedores.

**Sub Tareas**

- [ ] Revisar requisitos y funcionamiento de sistema de [firma electrónica](https://github.com/udistrital/firma_electronica_mid).
- [x] Implementar la firma electrónica para los documentos de cumplido a satisfacción y autorización de pago.

**Criterios de aceptación**

- [ ] firma electronica implementada..
- [x] Issue documentado.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by stevencol** [comment]
Se está investigando cómo implementar la firma electrónica, utilizando el repositorio creado para este fin. Para su implementación, se propone modificar la respuesta generada por el mid, ya que la respuesta actual solo retorna el archivo en base64 y no incluye los datos necesarios en el cuerpo de la solicitud para la firma electrónica.
La repuesta propuesta para cumplir la solicitud es : 

``` json
{
"tipo_documento":"",
"nombre":"", 
"firmantes:[],
"descripcion":"", 
"file":""
}

```

**Comment by stevencol** [comment]
En el momento de realizar pruebas con la carga del archivo se encuentran inconvenientes, ya que el base64 generado, aunque se visualice en el cliente, no es detectado como PDF, por lo cual el servicio de firma electrónica rechaza la solicitud.

![image](https://github.com/user-attachments/assets/d784f05a-1d6c-49b7-8f64-6d6f2959ef89)

**Comment by stevencol** [comment]
- Se sigue manteniendo manteniendo el error se preuba con aplicación externa, ya que el pdf no se detecta  como “application/pdf” sino como “application/octet-stream”
Por lo que la firma electrónica no detecta el archivo
![image](https://github.com/user-attachments/assets/22ec3ce5-5a67-4823-8cf5-24432420786e)

- Se tiene el archvio: 

``` JavaScript
func GenerarPdf(atorizacion *models.DocuementoAutorizacionPago) string {

	if atorizacion == nil {
		fmt.Println("Error al generar el documento")
		return ""

	}
	pdf := gofpdf.New("P", "mm", "A4", "")
	now := time.Now()
	//////Header
	cellX, cellY := 30.0, 10.0
	cellX2, cellY2 := 55.0, 10.0
	cellWidth, cellHeight := 25.0, 25.0
	cellWidth2, cellHeight2 := 55.0, 7.5
	formattedDate := now.Format("02/01/2006")
	month := int(now.Month())
	year := now.Year()
	day := now.Day()
	fmt.Print("Generando documento")
	pdf.SetFont("Times", "", 12)
	pdf.SetMargins(15, 10, 15)

	pdf.SetFillColor(240, 240, 240)

	pdf.SetFooterFunc(func() {
		pdf = footer(pdf, cellX, cellY)
	})
	pdf = footer(pdf, cellX, cellY)
	pdf.SetHeaderFunc(func() {
		pdf = header(pdf, cellX, cellY, cellX2, cellY2, cellWidth, cellHeight, cellWidth2, cellHeight2, formattedDate)
	})
	pdf.AddPage()
	pdf = header(pdf, cellX, cellY, cellX2, cellY2, cellWidth, cellHeight, cellWidth2, cellHeight2, formattedDate)

	pdf = body(pdf, cellX, cellY, month, day, year, atorizacion)

	file_name := fmt.Sprintf("AutorizacionPago_%s.pdf", atorizacion.NombreProveedor+"-"+atorizacion.DocumentoProveedor)
	err := pdf.OutputFileAndClose(file_name + ".pdf")
	if err != nil {
		fmt.Println("Error al guardar el archivo PDF:", err)
	} else {
		fmt.Println("PDF generado exitosamente")

	}

	fileData, err := ioutil.ReadFile(file_name + ".pdf")
	if err != nil {
		fmt.Println("Error al leer el archivo PDF:", err)
		return ""
	}

	base64Data := base64.StdEncoding.EncodeToString(fileData)

	err = os.Remove(file_name)
	if err != nil {
		fmt.Println("Error al eliminar el archivo temporal:", err)
	}
	return base64Data
}
```


y se intenta convertir en base64 de otra manera pero se sigue presentando el error se prueba: 

``` JavaScript
func GenerarPdf(atorizacion *models.DocuementoAutorizacionPago) string {

	if atorizacion == nil {
		fmt.Println("Error al generar el documento")
		return ""

	}
	pdf := gofpdf.New("P", "mm", "A4", "")
	now := time.Now()
	//////Header
	cellX, cellY := 30.0, 10.0
	cellX2, cellY2 := 55.0, 10.0
	cellWidth, cellHeight := 25.0, 25.0
	cellWidth2, cellHeight2 := 55.0, 7.5
	formattedDate := now.Format("02/01/2006")
	month := int(now.Month())
	year := now.Year()
	day := now.Day()
	fmt.Print("Generando documento")
	pdf.SetFont("Times", "", 12)
	pdf.SetMargins(15, 10, 15)

	pdf.SetFillColor(240, 240, 240)

	pdf.SetFooterFunc(func() {
		pdf = footer(pdf, cellX, cellY)
	})
	pdf = footer(pdf, cellX, cellY)
	pdf.SetHeaderFunc(func() {
		pdf = header(pdf, cellX, cellY, cellX2, cellY2, cellWidth, cellHeight, cellWidth2, cellHeight2, formattedDate)
	})
	pdf.AddPage()
	pdf = header(pdf, cellX, cellY, cellX2, cellY2, cellWidth, cellHeight, cellWidth2, cellHeight2, formattedDate)

	pdf = body(pdf, cellX, cellY, month, day, year, atorizacion)
	encodedFile := encodePDF(pdf)
	//	base64Data := base64.StdEncoding.EncodeToString(fileData)
	fmt.Println(encodedFile)
	return encodedFile
}

func encodePDF(pdf *gofpdf.Fpdf) string {
	var buffer bytes.Buffer
	writer := bufio.NewWriter(&buffer)
	//pdf.OutputFileAndClose("/home/faidercamilo/go/src/github.com/udistrital/prueba.pdf") // para guardar el archivo localmente
	pdf.Output(writer)
	writer.Flush()
	encodedFile := base64.StdEncoding.EncodeToString(buffer.Bytes())
	return encodedFile
}
```

**Comment by stevencol** [comment]
Como no se logra avanzar por el error al encodear correctamente el base64, en el daily de hoy, se establece crear una comunicación con la persona encargada del aplicativo de firma electrónica

**Comment by stevencol** [comment]
Se logra solucionar el problema al generar el archivo y ya queda en MIME application/pdf. se realiza prueba en app externa, convirtiendo el base64 a pdf
![image](https://github.com/user-attachments/assets/78fbfe54-e0a7-421c-a19b-98dde39bf805)

**Comment by stevencol** [comment]
El archivo se envía para la firma electrónica y se firma correctamente, pero la posición de la firma no es la deseada, ya que se coloca en la página siguiente en 
[download.pdf](https://github.com/user-attachments/files/16630753/download.pdf),

1.    Actualmente, el backend solo responde con el archivo en formato base64. Se propone ajustar esta respuesta para cumplir con los requisitos necesarios.
Se propone:
``` JavaScript
{
"nombre":"Archivo de prueba",
"nombreOrdenador":""
"cargoOrdenador":""
"tipoIdentificacionOrdenador":""
"descripcionDelDocumento:""
"file":""

}
```
-- Cuerpo requerido 
``` JavaScript
[
    {
        "IdTipoDocumento": 168,
        "nombre": "test de firma de archivo",
        "metadatos": {},
        "firmantes": [
            {
                "nombre": "Pepetito el Ordenador",
                "cargo": "Ordenador del gasto",
                "tipoId": "cc",
                "identificacion": "1111111"
            }
        ],
        "representantes": [],
        "descripcion": "Documento  de pago para pruebas ",
 "file":""
    }
]
```
*IdTipoDocumento   hace referencia al id que se le asigna a Aprobacion pago en tipo documento


3.  El servivio de firma respone 
 ``` JavaScript
{
    "Status": "200",
    "res": {
        "Id": 155639,
        "Nombre": "test de firma de archivo",
        "Descripcion": "Documento  de pago para pruebas ",
        "Enlace": "bad73ca4-3f15-4541-8600-2e6aa4c33fb5",
        "TipoDocumento": {
            "Id": 168,
            "Nombre": "Aprobacion pago",
            "Descripcion": "Documento que aprueba el pago",
            "CodigoAbreviacion": "AP",
            "Activo": true,
            "NumeroOrden": 2,
            "Tamano": 5,
            "Extension": "pdf",
            "Workspace": "/desarrollo/workspaces/pruebas",
            "TipoDocumentoNuxeo": "File",
            "FechaCreacion": "2024-07-28 21:37:26.060903 +0000 +0000",
            "FechaModificacion": "2024-07-28 21:37:26.060903 +0000 +0000",
            "DominioTipoDocumento": {
                "Id": 12,
                "Nombre": "",
                "Descripcion": "",
                "CodigoAbreviacion": "",
                "Activo": false,
                "NumeroOrden": 0,
                "FechaCreacion": "",
                "FechaModificacion": ""
            }
        },
        "Metadatos": "{\"codigo_autenticidad\":\"2259092593108490323\",\"firmantes\":{\"nombre\":\"Pepetito el Ordenador\",\"cargo\":\"Ordenador del gasto\",\"tipoId\":\"cc\",\"identificacion\":\"1111111\"},\"representantes\":\"\"}",
        "Activo": true,
        "FechaCreacion": "",
        "FechaModificacion": "2024-08-15T17:40:39.333153587-05:00"
    }
}
```

3- Con la respuesta anterior se planea obtener el id del documento cargado y registrarlo en los documentos del cumplido y con este mismo id, mostrar el documento firmado

**Comment by stevencol** [comment]
El documento se firma de la siguiente : 
![image](https://github.com/user-attachments/assets/7831f698-e3d2-4f22-97c1-8ea7c9e15255)

**Comment by JuanCamiloMartinezLopez** [comment]
@stevencol  Buen trabajo
