### ISSUE TITLE
Concertar, desarrollar y levantar acta de sesión requerimientos cliente evaluación órdenes compra

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/Cumplidos_y_certificaciones_documentacion#11]
Se requiere realizar el 

**Sub Tareas**

- [x] Concertar reunión exploratoria con el cliente
- [x] Desarrollar la reunión exploratoria
- [x] Proyectar acta de la reunión

**Criterios de aceptación**

- [x] Acta revisada por el líder de proyecto
- [ ] Acta firmada por las partes

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico/SoSM.
- [ ] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se agrega el acta con las firmas de los asistentes

[Acta con firmas](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EY5lqGGpp71NvQnwqvh6guMBXaDRsX_wMIrT38VM9oz2yg?e=bG0snj)

**Comment by jcmurilloa** [comment]
Muy buen desempeño en recolección de firmas @mantnicot
