### ISSUE TITLE
Revisión de notificaciones para su implementación 

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#110]
Se requiere revisar el servicio de notificaciones para su implementación en el módulo de revisión de cumplidos proveedores.

**Sub Tareas**

- [ ] Revisar requisitos y funcionamiento de sistema de [notificaciones](https://github.com/udistrital/notificacion_mid).
- [ ] Realizar una propuesta de implementación de notificaciones.
- [ ] Implementar notificaciones dentro y fuera del sistema para los diferentes roles y flujos.

**Criterios de aceptación**

- [ ] notificaciones implementadas.
- [ ] Issue documentado.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JuanCamiloMartinezLopez** [comment]
@stevencol se realiza una reunión con el equipo encarga de notificaciones para revisar el estado, se comparte la grabación y documentación

- [grabación](https://udistritaleduco-my.sharepoint.com/:v:/r/personal/blsierraf_udistrital_edu_co/Documents/Grabaciones/Revisi%C3%B3n%20Notificaciones%20-20240805_190114-Meeting%20Recording.mp4?csf=1&web=1&e=zmGdPD)
- [Documento técnico notificacion_crud](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EagFPm9pKfRLn1JZrfVCl9EBPye3vjDMgIbNMdwFwGOobg?e=iVXdV9) 
- [Documento técnico notificaciones via email](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EWyWVY8EuIBEidY3ScBXSfkBDZEx2Xdv2QSbvUnm8U6MZw?e=0WYnOB)

**Comment by stevencol** [comment]
Se revisó el video compartido de la reunión de Notificaciones Mid, en el cual se evidencia que, si se desea implementar las notificaciones en Cumplidos proveedores Mid, la mejor manera de hacerlo es mediante las notificaciones internas. Esto se debe a que las notificaciones por correo electrónico no siempre se envían por alguna razón y son menos seguras, ya que pueden presentarse problemas como la suplantación de identidad. En las notificaciones por correo electrónico, el remitente puede ser falsificado, lo que permite que alguien envíe un correo a nombre de otra persona. Además, solo se pueden enviar 1000 correos por hora.

En cuanto a las notificaciones internas, ya existe un cliente que puede implementarse en los microfrontend.

**Comment by stevencol** [comment]
Para la implementación de notificaciones se debe:

1- Registrar el sistema en el endpoint
https://autenticacion.portaloas.udistrital.edu.co/apioas/notificaciones_crud/v1/sistema

``` JavaScript
{
"nombre":"cumplidos proveedores",
"descripcion":"",
codigo_abreviacion:"CUMPV"
}

```

2 - Registar Plantilla
``` JavaScript
{
"sistema_id: ":"{id_sistema}",
"nombre":"nombre descriptivo",
"descripcion":"",
"codigo_abreviacion":""
"plantilla_mensaje":"{mensaje predefinido},
"metadatos":"",
"activo":true,
"fecha_creacion":"",
"fecha_modificacion":""
}

```

3- Tipo_notificacion
``` JavaScript
{
  "nombre": "Nombre del tipo de notificación",
  "descripcion": "Descripción detallada del tipo de notificación.",
  "codigo_abreviacion": "Código único"
}

```



4- notificacion
``` JavaScript
{
  "sistema_id": "{identificador_del_sistema}",
  "tipo_notificacion_id": "{identificador_del_tipo_notificacion}",
  "destinatarios": ["{id_usuario_1}", "{id_usuario_2}", "{id_usuario_3}"],
  "remitente": "{usuario_remitente}",
  "asunto": "Título o encabezado de la notificación",
  "mensaje": "Contenido completo de la notificación.",
  "lectura": false,
  "fecha_lectura": null,
  "metadatos": ""
  "activo": true,
  "fecha_creacion": "{fecha_y_hora_creacion}",
  "fecha_modificacion": "{fecha_y_hora_modificacion}"
}
```

## Microcliente

- Agregar en el Microfrontend  la variable:  
``` JavaScript
- notificaciones:true  -> Habilitara el icono de notificaciones (la campana) y el panel  usando 
(“services/notificaciones.service”),
```

el Core debe contener las variables de entorno 👍🏽 
 
``` JavaScript
  NOTIFICACION_MID_WS: "ws://autenticacion.portaloas.udistrital.edu.co/apioas/notificacion_mid/v1/ws",
  NOTIFICACIONES_CRUD: "https://autenticacion.portaloas.udistrital.edu.co/apioas/notificaciones_crud/",
```

**Comment by stevencol** [comment]
La actividad estuvo en pausa debido a dudas sobre el funcionamiento de las notificaciones. Se llevó a cabo una reunión con el desarrollador para resolver estas dudas. La actividad ha sido reanudada y se encuentra en progreso: [reunión:](https://udistritaleduco-my.sharepoint.com/personal/juacmartinezl_udistrital_edu_co/_layouts/15/stream.aspx?id=%2Fpersonal%2Fjuacmartinezl%5Fudistrital%5Fedu%5Fco%2FDocuments%2FGrabaciones%2FAclaraci%C3%B3n%20dudas%20de%20notificaciones%20para%20cumplidos%20proveedores%2D20240822%5F110105%2DGrabaci%C3%B3n%20de%20la%20reuni%C3%B3n%2Emp4&referrer=StreamWebApp%2EWeb&referrerScenario=AddressBarCopied%2Eview%2E47bc2b50%2D2a2e%2D4dbb%2D8ec4%2Dcbe53c54eba5&ga=1)

**Comment by stevencol** [comment]
Como parte de la reanudación, se ha registrado el sistema en Notificaciones/Sistema.

![Image](https://github.com/user-attachments/assets/0da72536-2e53-4155-8639-def7c75716e1)

y se comprueba: 


![Image](https://github.com/user-attachments/assets/85cb8c59-f892-4738-82ed-243935541d49)

**Comment by stevencol** [comment]
Se realiza pruebas de la notificaciones
1: se propone Crear Modelo en el cliente para representar la siguiente petición: 
``` JavaScript
{
  "sistema_id": "66c8afeca6ee77849101664d",  --> Id  correspondiente a -> revisión de cumplidos proveedores
  "tipo_notificacion_id": "66ac05deb6d4007375621835", -->Tipo de notificación ya registrado que corresponde a Notificación informativa  
  "destinatarios": ["79777053"]-->,
  "remitente": "79777053",
  "asunto": "Notificación De prueba",
  "mensaje": "Esto es una notificación de prueba",
  "lectura": false,
  "metadatos": {},
  "activo": true

}
```
Se planea implementar función de aprobación contratación en: 
``` JavaScript
async aprobarSoportes(idCumplido: number) {
    let confirm = await this.alertService.alertConfirm(
      '¿Esta seguro de aprobar los soportes?'
    );
    console.log(idCumplido);
    if (confirm.isConfirmed) {
      try{

      const idEstado = await this.ObtenerEstadoId('PRO').toPromise();
      const tipo_documento = await this.ObternerIdTipoDocumento(
        'AP'
      ).toPromise();


      if (idEstado === null || idEstado === undefined) {
        throw new Error('El ID obtenido es nulo o indefinido.');
      } else {


          const cambioEstado = new CambioEstado(
            idEstado,
            idCumplido,
            '52622477',
            'Contratacion'
          );
           this.CambiarEstado(cambioEstado);
          this.CargarTablaCumplidos();

      }

      this.alertService.showSuccessAlert('Aprobado', '!se Aprobo con exito!');
      }catch(error){
        this.alertService.showCancelAlert(
          'Cancelado',
          'No se pudo relizar la accion'+error
        );
      }
    } else {
      this.alertService.showCancelAlert(
        'Cancelado',
        'No se pudo relizar la accion'
      );
    }
  } 
```
En esta caso se creará función que permita traer el ordenador actual con el fin de   asignarle el cumplido y ser notificado del mismo.

**Comment by stevencol** [comment]
En dado caso que el ordenador rechace el cumplido se realizaría el mismo proceso, pero se traerá el supervisor encargado

**Comment by stevencol** [comment]
Por el momento El módulo de contratación no podrá recibir notificaciones m pero si emitirá la notificación al ordenador encaso de que rechace el cumplido

**Comment by JuanCamiloMartinezLopez** [comment]
@stevencol Buen trabajo.
