### ISSUE TITLE
Refactorización del mid de revisión de cumplidos proveedores - Parte I

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#111]
Se requiere realizar el proceso de refactorización y refinamiento de las funciones del mid.

**Sub Tareas**

- [x] Revisar el funcionamiento de los endpoint según su implementación en el cliente y las pruebas funcionales.
- [x] Proponer simplificaciones de consultas para la generación de servicios jbpm dedicados.
- [x] Revisar la generación de documentos con gofpdf.
- [x] Revisar oportunidades de mejora del código con herramientas como SonarQube

**Criterios de aceptación**

- [x] Propuestas de cambio.
- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.
Se requiere realizar el 

**Sub Tareas**

- [ ] 

**Criterios de aceptación**

- [ ] 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 para que el proyecto sea escaneado y se pueda revisar desde [sonarqube](https://sonarqube.portaloas.udistrital.edu.co/projects?sort=-name) es necesario agregar un documento de [configuración](https://github.com/udistrital/sga_inscripcion_mid/blob/develop/sonar-project.properties)

**Comment by faidercamilo26** [comment]
Se verifica en la parte de los helpers del supervisor y se evidencia que la consulta es muy larga porque trae demasiados datos de distintas partes,  se evidencia que si es posible la creación de un servicio en JBPM principalmente para traer los datos de los contratos del supervisor, puesto que en estos momentos se verifica el acta de inicio, si hay alguna novedad post-contractual, con eso se recuperan las fechas, y se verifican si esta activo, se puede solucionar esto con una petición similar a la usada en cumplidos CPs.

```sql

SELECT numero_contrato_suscrito, vigencia,fecha_inicio_val,fecha_fin_val FROM (SELECT cs.numero_contrato_suscrito, cs.vigencia, ip.nom_proveedor, (SELECT fecha_inicio FROM argo.acta_inicio WHERE numero_contrato=cg.numero_contrato and vigencia=cg.vigencia) fecha_inicio_val, CASE WHEN (cs.numero_contrato_suscrito IN (SELECT numero_contrato FROM argo.novedad_postcontractual WHERE vigencia=cg.vigencia and tipo_novedad!=216)) THEN (SELECT fecha_fin FROM argo.novedad_postcontractual WHERE numero_contrato= cs.numero_contrato_suscrito and vigencia=cg.vigencia and tipo_novedad!=216 ORDER BY id DESC limit 1) ELSE (SELECT fecha_fin FROM argo.acta_inicio WHERE numero_contrato=cg.numero_contrato and vigencia=cg.vigencia) END fecha_fin_val FROM argo.contrato_general cg JOIN argo.supervisor_contrato sc ON sc.id=cg.supervisor JOIN argo.contrato_suscrito cs ON cs.numero_contrato=cg.numero_contrato JOIN agora.informacion_proveedor ip ON ip.id_proveedor=cg.contratista WHERE sc.dependencia_supervisor=? AND cg.tipo_contrato in (9,12,14,15,7,5)) as r1 WHERE r1.fecha_inicio_val is not null AND r1.fecha_fin_val is not null and TO_CHAR(r1.fecha_fin_val,'YYYY-MM')>=? and TO_CHAR(r1.fecha_inicio_val,'YYYY-MM')<=? ORDER BY numero_contrato_suscrito,vigencia

```

**Comment by faidercamilo26** [comment]
Se sube el proyecto a SonarQube se verifican desde el programa las posibilidades de mejora del código.  


![Image](https://github.com/user-attachments/assets/8d5625a1-f7bd-4c65-80b5-1701424b9819)


Se evidencia que más que todo hay incidencias o posibilidades de mejora en la complejidad de las funciones, sin embargo, muchas de estas no tienen posibilidad de reducirse. Sin embargo hay otras que constan de varias funciones anidadas y se podrian simplificar con servicios de JBPM.



![Image](https://github.com/user-attachments/assets/ca0fad7b-8f9d-42d9-863f-543d0066f850)

**Comment by faidercamilo26** [comment]
## Creacion de los pdf
### Header

Se evidencia que los headers tanto de  Cumplido Satisfacción como de la aprobación de pago son exactamente el mismo con variaciones en algunos valores los cuales se le pueden pasar dinámicamente para dejar esto en una sola función general, a continuación se propone el encabezado de esta función para que se pueda construir la lógica más adelante.


```go

func header(pdf *gofpdf.Fpdf, tipo_documento string, proceso string, codigo string, version int, fecha_aprobacion Date) *gofpdf.Fpdf {

}

```



![Image](https://github.com/user-attachments/assets/2f9e0c4f-84a4-4064-96e5-0b6cecf41101)



![Image](https://github.com/user-attachments/assets/916cfd9e-f475-4d0a-9cf2-588da048024b)


### Utlidades

Se puede notar que es viable crear un archivo de utilidades donde se puedan almacenar funciones generales entre los dos documentos, por ejemplo la función del header anteriormente descrita puede ir en este archivo y también se puede agregar la función de codificar el pdf generado para poderlo retornar.


```go
func encodePDF(pdf *gofpdf.Fpdf) string {
	var buffer bytes.Buffer
	writer := bufio.NewWriter(&buffer)
	//pdf.OutputFileAndClose("/home/faidercamilo/go/src/github.com/udistrital/prueba.pdf") // para guardar el archivo localmente
	pdf.Output(writer)
	writer.Flush()
	encodedFile := base64.StdEncoding.EncodeToString(buffer.Bytes())
	return encodedFile
}
```

Además, Aunque por el momento en el documento de aprobación pago no se estan utilizando se podrian guardar las siguientes funciones que son transversales a la creacion de documentos pdf: 

``` go

func image(pdf *gofpdf.Fpdf, image string, x, y, w, h float64) *gofpdf.Fpdf {
	pdf.ImageOptions(image, x, y, w, h, false, gofpdf.ImageOptions{ImageType: "PNG", ReadDpi: true}, 0, "")
	return pdf
}



```

**Comment by faidercamilo26** [comment]
## Utilidades General

En los helpers de supervisor , cambio estado, y soporte se tiene un archivo de utilidades único, dicho archivo tiene las funciones encargadas de hacer las peticiones al crud, entre otras funcionalidades, sin embargo, este archivo se puede generalizar para que se cree un solo archivo para todos los helper, se tendría que cambiar un poco la firma de los métodos definidos en la OATI pero es un cambio mínimo. Como por ejemplo:

Nombre Actual:  getJsonWSO2Test()
Nombre Refactor: GetJsonWSO2Test()

Esto puesto que en go las funciones que se pueden compartir en distintas partes del código deben iniciar con mayúscula.

**Comment by faidercamilo26** [comment]
## Cambio estado cumplido Proveedor


Esta función está algo extensa, puesto que se realizan varios procesos, se verifica si el cumplido tiene cambios anteriores y en caso de que tenga cambios anteriores se recuperan, en caso de que existan se modifican los estados anteriores para desactivarlos y que solo quede activo el nuevo, se verifica que el cumplido proveedor exista y también que el estado al cual se quiere cambiar el cumplido exista, esto para no tener inconsistencia, este gran método se podría dividir en sub métodos para mejorar la legibilidad y mantenimiento del código.

**Comment by faidercamilo26** [comment]
## Refactorización de modelos

Se evidencian modelos repetidos con distintos nombres, se debe eliminar una de las dos definiciones y modificar las partes del código donde se estén usando.


```go

type EstadoCumplidoId struct {
	Id                int    `json:"Id"`
	Nombre            string `json:"Nombre"`
	Descripcion       string `json:"Descripcion"`
	Activo            bool   `json:"Activo"`
	CodigoAbreviación string `json:"CodigoAbreviación"`
}

type EstadoCumplido struct {
	Id          int
	Nombre      string
	Descripcion string
	Activo      bool
	Abreviacion string
}

```

``` go

type ContratoGeneral struct {
	Id                           string
	VigenciaContrato             int
	ObjetoContrato               string
	PlazoEjecucion               int
	FormaPago                    *Parametros
	OrdenadorGasto               int
	ClausulaRegistroPresupuestal bool
	SedeSolicitante              string
	DependenciaSolicitante       string
	Contratista                  int
	ValorContrato                float64
	Justificacion                string
	DescripcionFormaPago         string
	Condiciones                  string
	FechaRegistro                time.Time
	TipologiaContrato            int
	TipoCompromiso               int
	ModalidadSeleccion           int
	Procedimiento                int
	RegimenContratacion          int
	TipoGasto                    int
	TemaGastoInversion           int
	OrigenPresupueso             int
	OrigenRecursos               int
	TipoMoneda                   int
	ValorContratoMe              float64
	ValorTasaCambio              float64
	TipoControl                  int
	Observaciones                string
	Supervisor                   *SupervisorContrato
	ClaseContratista             int
	Convenio                     string
	NumeroConstancia             int
	Estado                       bool
	TipoContrato                 *TipoContrato
	LugarEjecucion               *LugarEjecucion
	UnidadEjecucion              *Parametros
	UnidadEjecutora              int
	ContratoSuscrito             []*ContratoSuscrito
}


type NumeroContrato struct {
	Id                           string             `json:"Id"`
	VigenciaContrato             int                `json:"VigenciaContrato"`
	ObjetoContrato               string             `json:"ObjetoContrato"`
	PlazoEjecucion               int                `json:"PlazoEjecucion"`
	FormaPago                    FormaPago          `json:"FormaPago"`
	OrdenadorGasto               int                `json:"OrdenadorGasto"`
	ClausulaRegistroPresupuestal bool               `json:"ClausulaRegistroPresupuestal"`
	SedeSolicitante              string             `json:"SedeSolicitante"`
	DependenciaSolicitante       string             `json:"DependenciaSolicitante"`
	Contratista                  int                `json:"Contratista"`
	ValorContrato                int                `json:"ValorContrato"`
	Justificacion                string             `json:"Justificacion"`
	DescripcionFormaPago         string             `json:"DescripcionFormaPago"`
	Condiciones                  string             `json:"Condiciones"`
	FechaRegistro                string             `json:"FechaRegistro"`
	TipologiaContrato            int                `json:"TipologiaContrato"`
	TipoCompromiso               int                `json:"TipoCompromiso"`
	ModalidadSeleccion           int                `json:"ModalidadSeleccion"`
	Procedimiento                int                `json:"Procedimiento"`
	RegimenContratacion          int                `json:"RegimenContratacion"`
	TipoGasto                    int                `json:"TipoGasto"`
	TemaGastoInversion           int                `json:"TemaGastoInversion"`
	OrigenPresupueso             int                `json:"OrigenPresupueso"`
	OrigenRecursos               int                `json:"OrigenRecursos"`
	TipoMoneda                   int                `json:"TipoMoneda"`
	ValorContratoMe              int                `json:"ValorContratoMe"`
	ValorTasaCambio              int                `json:"ValorTasaCambio"`
	TipoControl                  int                `json:"TipoControl"`
	Observaciones                string             `json:"Observaciones"`
	Supervisor                   Supervisor         `json:"Supervisor"`
	ClaseContratista             int                `json:"ClaseContratista"`
	Convenio                     string             `json:"Convenio"`
	NumeroConstancia             int                `json:"NumeroConstancia"`
	Estado                       bool               `json:"Estado"`
	TipoContrato                 TipoContrato       `json:"TipoContrato"`
	LugarEjecucion               LugarEjecucion     `json:"LugarEjecucion"`
	UnidadEjecucion              UnidadEjecucion    `json:"UnidadEjecucion"`
	UnidadEjecutora              int                `json:"UnidadEjecutora"`
	ContratoSuscrito             []ContratoSuscrito `json:"ContratoSuscrito"`
}

```
``` go 
type Parametros struct {
	Id                int
	Descripcion       string
	CodigoContraloria string
	EstadoRegistro    bool
	FechaRegistro     time.Time
}

type FormaPago struct {
	Id                int    `json:"Id"`
	Descripcion       string `json:"Descripcion"`
	CodigoContraloria string `json:"CodigoContraloria"`
	EstadoRegistro    bool   `json:"EstadoRegistro"`
	FechaRegistro     string `json:"FechaRegistro"`
}

```



``` go
type CumplidoProveedorId struct {
	Id                int    `json:"Id"`
	NumeroContrato    string `json:"NumeroContrato"`
	VigenciaContrato  int    `json:"VigenciaContrato"`
	FechaModificacion string `json:"FechaModificacion"`
	FechaCreacion     string `json:"FechaCreacion"`
	Activo            bool   `json:"Activo"`
}

type CumplidoProveedor struct {
	Id                int       "json:id"
	NumeroContrato    string    "json:numero_contrato"
	VigenciaContrato  int       "json:vigencia_contrato"
	FechaModificacion time.Time "json:fecha_modificacion"
	FechaCreacion     time.Time "json:fecha_creacion"
	Activo            bool      "json:activo"

}
```
``` go

type ContratoEstado struct {
	Id                   int                 `json:"Id"`
	EstadoCumplidoId     EstadoCumplidoId    `json:"EstadoCumplidoId"`
	CumplidoProveedorId  CumplidoProveedorId `json:"CumplidoProveedorId"`
	DocumentoResponsable int                 `json:"DocumentoResponsable"`
	CargoReponsable      string              `json:"CargoReponsable"`
	FechaCreacion        string              `json:"FechaCreacion"`
	FechaModificacion    string              `json:"FechaModificacion"`
	Activo               bool                `json:"Activo"`
}

type CambioEstadoCumplido struct {
	Id                   int
	EstadoCumplidoId     *EstadoCumplido
	CumplidoProveedorId  *CumplidoProveedor
	DocumentoResponsable int
	CargoReponsable      string
	FechaCreacion        time.Time
	FechaModificacion    time.Time
	Activo               bool
}

```

Este modelo es poco diciente, respuesta general de que?

```
type RespuestaGeneral struct {
	Data    []map[string]interface{}
	Message string
	Status  string
	Success bool
}
```

**Comment by faidercamilo26** [comment]
## Organización proyecto

Se ha identificado que, según los lineamientos actuales, es posible mejorar la organización del código para aumentar su legibilidad y facilitar la comprensión, asegurando además una clara separación de las funcionalidades por rol. Para lograr esto, se propone la creación de una carpeta dedicada a los servicios. Cada controlador tendrá un documento de servicio correspondiente, en el que se almacenará toda la lógica de negocio. Estos servicios seguirán una convención de nomenclatura consistente, utilizando el mismo nombre que su controlador correspondiente, seguido del sufijo service. Por ejemplo:

    Controlador: revision_cumplid.go
    Servicio: revision_cumplido.service.go

Asimismo, se recomienda que las utilidades se organicen en la carpeta de helpers, lo que permitirá que la estructura del proyecto sea más descriptiva y se alinee con las mejores prácticas actuales.

Por otro lado, se propone establecer un estándar general para la nomenclatura de los servicios recién creados. Actualmente, se observa una inconsistencia en el uso de términos como get, obtener, y otros sinónimos. Para uniformar el código, se sugiere que los servicios utilicen prefijos en español como Obtener, Actualizar, Crear, Eliminar, entre otros.

**Comment by faidercamilo26** [comment]
## ObtenerCumplidosPendientesContratacion

Vemos que la función ObtenerCumplidosPendientesContratacion() realiza una petición a contrato general y despues utiliza 3 métodos cada uno con su respectiva consulta para llenar la información que requiere retornar, sin embargo, en los helpers de contrato supervisor la función ContratosContratista() trae exactamente la misma información que debe retornar este método, por este motivo se puede usar esta función como una utilidad para no repetir codigo. 


``` go
func ObtenerCumplidosPendientesContratacion(estado string) (cumplidosInfo []models.SolicituRevisionCumplidoProveedor, errorOutput interface{}) {
	defer func() {
		if err := recover(); err != nil {
			errorMessage := fmt.Sprintf("%v", err)
			errorOutput = map[string]interface{}{
				"Success": false,
				"Status":  400,
				"Message": "Error al consultar las dependencias: " + " - " + errorMessage,
				"Error":   errorMessage,
			}
			fmt.Println("Error recuperado:", errorMessage)
		}
	}()

	cumplidos, e := obtenerCumplidos(estado)

	if e != nil || cumplidos == nil {

		return nil, e
	}

	var info_contrato []models.ContratoGeneral
	for _, cumplido := range cumplidos {

		urlRequest := beego.AppConfig.String("UrlcrudAgora") + "/contrato_general/?query=ContratoSuscrito.NumeroContrato:" + cumplido.CumplidoProveedorId.NumeroContrato
		//fmt.Println("Pendiente contratacion: ", urlRequest)
		response, err := helpers.GetJsonWSO2Test(urlRequest, &info_contrato)

		if err != nil || response != 200 {

			errorMessage := fmt.Sprintf("%v", err)
			errorOutput = map[string]interface{}{
				"Success": false,
				"Status":  400,
				"Message": "Error el consultar los contratros para el ordenador en .GetContratos" + errorMessage,
				"Error":   errorMessage,
			}
			logs.Error(err)
			return nil, errorOutput
		}

		var ultimoContrato = len(info_contrato[0].ContratoSuscrito) - 1

		if proveedor, err := helpers_ordenador.ObtenerInfoProveedor(strconv.Itoa(info_contrato[0].Contratista)); err == nil && proveedor != nil {

			if proveedor != nil {
				contrato_disponibilidad, _ := helpers_ordenador.ObtenerContratoDisponiblidad(info_contrato[0].ContratoSuscrito[ultimoContrato].NumeroContrato.Id)

				if contrato_disponibilidad != nil {

					cdprp, _ := helpers_ordenador.ObtenerCrdp(strconv.Itoa(contrato_disponibilidad.NumeroCdp), strconv.Itoa(contrato_disponibilidad.Vigencia))
					if cdprp != nil {

						contrato := models.SolicituRevisionCumplidoProveedor{
							TipoContrato:     info_contrato[0].TipoContrato.TipoContrato,
							NumeroContrato:   info_contrato[0].ContratoSuscrito[ultimoContrato].NumeroContrato.Id,
							VigenciaContrato: info_contrato[0].ContratoSuscrito[ultimoContrato].Vigencia,
							Dependencia:      info_contrato[0].DependenciaSolicitante,
							NombreProveedor:  proveedor.NomProveedor,
							Cdp:              strconv.Itoa(contrato_disponibilidad.NumeroCdp),
							Rp:               cdprp.CDPNumeroDisponibilidad,
							VigenciaRP:       cdprp.RPVigencia,
							Id:               cumplido.CumplidoProveedorId.Id,
							Activo:           cumplido.Activo,
						}
						cumplidosInfo = append(cumplidosInfo, contrato)
					}
				}
			}

		}
	}

	return cumplidosInfo, nil
}

```

**Comment by faidercamilo26** [comment]
## Ordenador - ObtenerSolicitudesCumplidos() 

Para obtener los datos de este cumplido se supone que se retorna un listado de SolicituRevisionCumplidoProveedor() sin embargo en ninguna parte del método se esta llenando NombreOrdenador  y DocumentoOrdenador, posiblemente al unificar el mid se puso un retorno incorrecto, además tal como en el método utilizado para contratación se puede utilizar la función ContratosContratista() y prescindir de las funciones ObtenerInfoProveedor(), ObtenerContratoDisponiblidad() y  ObtenerCrdp()

**Comment by faidercamilo26** [comment]
## Soportes - SubirSoporte()  

Se propone cambiar el nombre de la variable solicitud_pago_id que recibe esta función por cumplido_id para que sea mas diciente.

**Comment by faidercamilo26** [comment]
## GetSolicitudesCumplidosProveedor()

Por el momento el retorno de esta funcion es ```go []models.CambioEstadoCumplido ```, sin embargo, por temas de calidad en el código y buenas prácticas, se debe crear un modelo de una solución personalizada que retorne únicamente los datos que se necesitan.

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 Buen trabajo
