### ISSUE TITLE
Articular con el responsable el flujo del desarrollo de proyectos de la OATI

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/Cumplidos_y_certificaciones_documentacion#112]
Se requiere realizar la articulación con el responsable del flujo del desarrollo de proyectos de la OATI

**Sub Tareas**

- [x] Contactar con el responsable.
- [x] Generar los comentarios derivados de la revisión de los flujos de desarrollo de proyectos.
- [x] Comunicar resultados con responsable.

**Criterios de aceptación**

- [x] Documento con el análisis y comentarios de los flujos.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se esta creando el documento para entregar las recomendaciones sobre el flujo


[Documento de flujo](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EfhhpQ6s64lNrIbX2HvUOi0Bo7-vvV2olbc7T3cWSZmh2w?e=AkvTeK)

**Comment by jcmurilloa** [comment]
Muy buen avance @mantnicot, estaremos atentos a la realimentación del área responsable.

**Comment by mantnicot** [comment]
Se termina la issue se ha terminado , se ha podido completar la retroalimentación con la responsable y se deja a espera futuras actualizaciones

**Comment by jcmurilloa** [comment]
Excelente documento @mantnicot, esperamos que sea de utilidad al responsable y la OATI.
