### ISSUE TITLE
Gestionar la elaboración del boletín para la promoción de históricos cumplidos

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/Cumplidos_y_certificaciones_documentacion#113]
Se requiere realizar la gestión para la generación de un boletín relacionado con el uso de históricos cumplidos

**Sub Tareas**

- [x] Generar contacto con responsable de boletines.
- [x] Levantar requerimientos de elaboración.
- [x] Generar el requerimiento de elaboración de boletín
- [x] Revisión de boletín generado

**Criterios de aceptación**

- [x] Solicitud de creación de boletín con responsable
- [x] Manuales e instructivos actualizados

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Ya se ha hablado con viviana y se entregara para el día 15/08/2024

**Comment by mantnicot** [comment]
Se ha presentado demoras de parte de Viviana , se espera poder obtener respuesta esta semana de la realización del boletín.

**Comment by jcmurilloa** [comment]
@mantnicot la demora continúa? a la espera de tus comentarios relacionados con la emisión del boletín.

**Comment by mantnicot** [comment]
Se ha presentado una demora por aprobación del boletín



![Image](https://github.com/user-attachments/assets/c82203e2-cc6d-476b-ab85-133de760622c)


Esperar que se pueda solucionar eso

**Comment by jcmurilloa** [comment]
Quien debe aprobar este boletín? Podemos gestionar su aprobación de alguna manera?

**Comment by mantnicot** [comment]
El formato del boletín debe ser aprobado por el coordinador de comunicaciones , pero no me han podido dar evidencia de este proceso


![Image](https://github.com/user-attachments/assets/d4baeb79-745f-42b4-b750-6cad76559b37)

**Comment by mantnicot** [comment]
Se ha enviado el boletin en el canal oficial de la universidad 



![Image](https://github.com/user-attachments/assets/7ec38808-e4e0-4c0a-bb51-242d71124f16)



![Image](https://github.com/user-attachments/assets/fc0e4feb-ff8d-4773-86f7-f9cd62477f8d)

**Comment by jcmurilloa** [comment]
Que buen comunicado! Espero que este nuevo módulo sea bastante útil para estos usuarios! Excelente articulación @mantnicot!
