### ISSUE TITLE
Concertar y desarrollar sesión de exploración con Vicerrectoría (ordenador)

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/Cumplidos_y_certificaciones_documentacion#114]
Se requiere realizar la concertación y desarrollo de sesión de exploración con Vicerrectoría (ordenador) para la determinación del flujo y el rol de la oficina de contratación

**Sub Tareas**

- [ ] Concertar reunión con el cliente.
- [ ] Desarrollar la reunión con el cliente.
- [ ] Proyectar acta de la reunión.
- [ ] Recolectar las firmas correspondientes.

**Criterios de aceptación**

- [ ] Acta revisada por el líder de proyecto.
- [ ] Acta firmada por las partes con anexo de historias de usuario o mockup.
- [ ] Acta y anexos documentados.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico/SoSM.
- [ ] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se ha intentado comunicar con el vicerectoria para obtener un cliente pero no se ha dado respuesta de alguien que pueda ayudarnos.



![Image](https://github.com/user-attachments/assets/6ce47bd6-74e5-40aa-af47-983b171f1cfb)


Se informe a Diana sobre esto y ella esta gestionando y se quedo a espera de poder obtener respuesta

**Comment by mantnicot** [comment]
![Image](https://github.com/user-attachments/assets/b37f112e-7553-4e21-80bc-a832ce3dfa3c)

Se espera entonces que generen una persona de contratación para poder gestionar la reunión.

**Comment by jcmurilloa** [comment]
Según los comentarios acerca de la gestión de esta actividad, se hace necesario trasladar la issue al siguiente sprint.

**Comment by mantnicot** [comment]
Se iba a ir presencial pero por cosas de mantenimiento de aguas , no hay personal en la oficina.

Se ha podido hablar con Diana y comento que realizaría la comunicación directamente en la oficina de vicerrectoría

**Comment by jcmurilloa** [comment]
Debemos persistir en este contacto con esta área, es fundamental para el avance de varios proyectos del equipo.

**Comment by jcmurilloa** [comment]
Se da como cerrada la issue, debido a no encontrar respuesta por parte de la dependencia.
