### ISSUE TITLE
Integración del mf de revision_cumplidos_proveedores_mf

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#116]
Se requiere realizar la integración de las diferentes funcionalidades desarrolladas en las diferentes ramas para dejar en develop el módulo funcional de forma correcta.

**Sub Tareas**

- [x] Integrar las diferentes vistas y funciones creadas en el mf.
- [x] Configurar los menús en el root con las diferentes vistas funcionando según el flujo indicado.

**Criterios de aceptación**

- [x] mf en develop estable y funcionando según lo indicado.
- [x] issue documentado.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
Se intenta realizar la conexión del mf, sin embargo, github estaba caído y no fue posible hacer la integración de los códigos temprano cuando se intentó, en la noche que empezó a funcionar github se hace el merge para unir las distintas ramas, se solucionan los conflictos, pero aparecen errores al ejecutar el proyecto, errores que ya se están analizando para solucionarlos.



![Image](https://github.com/user-attachments/assets/00578370-c715-47c8-aaba-5f032cd9eb52)




![Image](https://github.com/user-attachments/assets/54cd6990-9a27-4d61-a074-1db5bda38d7d)

**Comment by faidercamilo26** [comment]
El objetivo del día de hoy es reunirme nuevamente con @stevencol para completar esta issue y solucionar los errores, por el momento se está averiguando como solucionar este error porque angular material está instalado y se están importando los módulos que tienen errores.

**Comment by stevencol** [comment]
En la reunión con @faidercamilo26  se integran las diferentes ramas del proyecto

**Comment by faidercamilo26** [comment]
Se realiza la reunión de con @stevencol se unen todas las ramas del microcliente, se solucionan los problemas y se configura el menú de los supervisores, ordenadores y de contratación, se probaron los menús y estan funcionando correctamente.
 

[Reunion de teams para unir las ramas ](https://udistritaleduco-my.sharepoint.com/:v:/g/personal/fctrujilloo_udistrital_edu_co/EQ_9mCuzqOdLkO2ovZZiSDUBS4aTiMQBVtAhDrX7HQY-0g?referrer=Teams.TEAMS-WEB&referrerScenario=MeetingChicletGetLink.view)

**Comment by faidercamilo26** [comment]
## Menu inicio



![Image](https://github.com/user-attachments/assets/2c899e71-6292-402a-98b4-4d047e0503c6)


## Vista subir soporte por parte supervisor con funcionalidad



![Image](https://github.com/user-attachments/assets/5d1f8c91-cdf9-4fae-8f28-db832e9a7991)

## Historico de cumplidos anteriores



![Image](https://github.com/user-attachments/assets/eb4f938f-11ca-4b14-904b-a3e93b3c4275)

## Subir soportes



![Image](https://github.com/user-attachments/assets/e03ef27b-77f6-40ba-bf4b-847fc72c5f46)


## Generar informe seguimiento


![Image](https://github.com/user-attachments/assets/e75e4f3e-c577-4c3a-80c2-578a7729d10f)

**Comment by stevencol** [comment]
funcionalidad de agregar comentarios
![image](https://github.com/user-attachments/assets/04c4ec86-4c05-4bcb-9e70-f348cca5310c)
![image](https://github.com/user-attachments/assets/80b15553-dbbd-47d7-a4c0-8414263c757e)

Visualización de documentos:
![firma](https://github.com/user-attachments/assets/3ab6a71f-08e0-446e-b40f-000e10cac93c)

**Comment by JuanCamiloMartinezLopez** [comment]
@stevencol @faidercamilo26 Buen trabajo.
