### ISSUE TITLE
Integración del mid de revision_cumplidos_proveedores

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#117]
Se requiere realizar la integración de modelos, helpers y demás funciones creadas en las diferentes ramas.

**Sub Tareas**

- [x] Integrar las diferentes ramas trabajadas para dejar el mid funcional y estable en develop.

**Criterios de aceptación**

- [x] Mid funcional y estable en develop.
- [x] Issue documentado.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
Se realiza la integración de todas las distintas ramas trabajadas en el mid, surgen varios errores principalmente por los modelos puesto que se estaban repitiendo distintos modelos con el mismo nombre y tambien habían modelos de nombres distintos pero con la misma informacion, se modifican los modelos para que se ajusten al código se realizan las correcciones pertinentes para dejar todo estable y funcionando el mid, se probaron los endpoints después de esta integración y se evidencia que siguen funcionando con total normalidad por eso se da por terminada la integración del mid, ya todo el código está disponible en la rama de develop del repositorio.



![Image](https://github.com/user-attachments/assets/5b87ba80-a7d0-40f6-be87-f7359df065f6)



![Image](https://github.com/user-attachments/assets/4e40ebcd-7efb-46f0-ba29-738b6b14c876)

**Comment by stevencol** [comment]
Después de realizar la integración, modificaciones en algunos modelos y eliminación de algunos modelos, se realizan pruebas para verificar la funcionalidad de las respuestas, en las cuales se comprueba que siguen respondiendo de manera correcta
![errores (-1)](https://github.com/user-attachments/assets/cb1d9507-8ad5-463f-bc2d-86e7cc6f8abd)
![errores (-2)](https://github.com/user-attachments/assets/b3cb4db1-9f5c-4492-bb79-efae9e20dcce)
![errores (-3)](https://github.com/user-attachments/assets/a93b4209-962c-42d3-9bba-78c338e8d03e)

**Comment by JuanCamiloMartinezLopez** [comment]
@stevencol @faidercamilo26 Buen trabajo.
