### ISSUE TITLE
Refactorización del mf de revisión de cumplidos proveedores - Parte I

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#119]
Se requiere realizar la propuesta de refactorización del mf de revisión cumplidos proveedores.

**Sub Tareas**

- [ ] Revisar el código realizados y proponer ajustes para la refinación del código.
- [ ] Revisar el sonarqube para ajustar los codesmell.

**Criterios de aceptación**

- [ ] Propuesta de refactorizaciones.
- [ ] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by stevencol** [comment]
Después de realizar la integración, modificaciones en algunos modelos y eliminación de algunos modelos, se realizan pruebas para verificar la funcionalidad de las respuestas, en las cuales se comprueba que siguen respondiendo de manera correcta

![errores (-1)](https://github.com/user-attachments/assets/4796fdf8-9766-4740-9756-f1f2e323d0b9)
![errores (-2)](https://github.com/user-attachments/assets/fe30904b-94e3-45d4-aa36-83e57173909d)
![errores (-3)](https://github.com/user-attachments/assets/1e478f66-081d-41c9-9b41-d6375395e2d3)

**Comment by stevencol** [comment]
Se propone eliminar componentes repetidos que hacen exactamente los mismo:
Como en le caso de;
![image](https://github.com/user-attachments/assets/755e23dd-3597-4eed-9519-b08ead3697ba)

ambos tienen el mismo código y su función es convertir URLs en un formato seguro, permitiendo que se muestren sin problemas en iframes o elementos similares.

**Comment by stevencol** [comment]
En vistas del ordenador usar el nombre guardado en el token actualmente no se estaba haciendo ya que no estaba integrado con el corre ni con el root
![image](https://github.com/user-attachments/assets/812931d9-fb45-435c-86ab-58f3db99fbe8)

**Comment by stevencol** [comment]
usar el mismo modal en todos los componentes para abrir los documentos  en la visualización

**Comment by stevencol** [comment]
Eliminar los componentes replicados modal-ver-soportes que se encuentran en los paquetes ordenador y contratación


![image](https://github.com/user-attachments/assets/56fdbfce-e0d7-422c-b438-eb9f75a94a3d)
E implementar modal-listar-soportes que cumple con la misma funcionalidad

**Comment by stevencol** [comment]
Usar camelCase en todos los metodos : 
1. FormularioInformeSeguimientoComponent
![image](https://github.com/user-attachments/assets/0cc7e96e-4e44-4ace-94d9-bb73aec3f567)
2.  TablaAproabacionPagoComponent
![image](https://github.com/user-attachments/assets/51f62975-65d5-4c3b-a3b9-2cc00f1c209f)
![image](https://github.com/user-attachments/assets/104bed20-18b8-486a-aa42-7ca04ef8cab9)

**Comment by stevencol** [comment]
Agregar mensaje de espera, para indicar que el documento se encuentra en proceso de firma:
![firmasss](https://github.com/user-attachments/assets/8bca72bf-49da-4478-86f9-60525736856d)

**Comment by stevencol** [comment]
Agregar mensaje de espera indicando que la búsqueda se está realizando en  supervisor/subir-soportes:


![Image](https://github.com/user-attachments/assets/19e5bc00-aba1-4ddb-93bb-8393220bf9d5)

**Comment by stevencol** [comment]
User info del token para cambiar el estado : 
![image](https://github.com/user-attachments/assets/c499e50c-833a-4ce2-a96d-4b9927be340c)

**Comment by stevencol** [comment]
Remplazar servicies ya que se estan replicando y tiene las misma funciones: 
![image](https://github.com/user-attachments/assets/9d667140-224b-4678-880a-b3a5de77ae71)

**Comment by stevencol** [comment]
Se escanea con sonnarqube y entrega estos resultados
![image](https://github.com/user-attachments/assets/4a28847e-e4d9-46dc-b036-74edcce9d820)
![image](https://github.com/user-attachments/assets/70977399-3dce-45a5-aadd-c2d156311198)

**Comment by stevencol** [comment]
Crear un servicio único para cambiar el estado:
![image](https://github.com/user-attachments/assets/ee8c0619-c756-4bf6-8d9c-c4decfd971fb)

**Comment by stevencol** [comment]
En la vista de cumplido de satisfacción se encuentran tres botones: 'Crear Informe', 'Ver' y 'Guardar'. Actualmente, para visualizar el informe es necesario hacer clic en 'Crear' y luego en 'Ver'. Se propone eliminar el botón 'Crear' y sustituir la funcionalidad directamente en el botón 'Ver', donde se encuentra la opción de firma, responsable de guardar el documento directamente.

![image](https://github.com/user-attachments/assets/19230985-70ce-4882-9d06-8a994126e5f5)

**Comment by stevencol** [comment]
> Remplazar servicies ya que se estan replicando y tiene las misma funciones: ![image](https://private-user-images.githubusercontent.com/51761184/359194566-9d667140-224b-4678-880a-b3a5de77ae71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxOTIzNzQsIm5iZiI6MTcyNDE5MjA3NCwicGF0aCI6Ii81MTc2MTE4NC8zNTkxOTQ1NjYtOWQ2NjcxNDAtMjI0Yi00Njc4LTg4MGEtYjNhNWRlNzdhZTcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDIyMTQzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyMjIxYmI3OWE2NWNhZTUwOTJjOGVlNWU0NWVlMzU2ZDkyYTA0NzkwOTcyYjE1YTI0Y2IwNTg1ZDBiZjZjYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w2oaStYMssuKqw4sqxO1bbtCH-aEBInRSJGXc7SFXiE)
Se propone eliminar services.service y generalService.service, y crear un servicio específico para la firma electrónica, con el fin de mantener un único servicio para cada módulo/CRUD.


![image](https://github.com/user-attachments/assets/633d6134-69aa-40ee-81ba-b5c264aaab94)

**Comment by stevencol** [comment]
Muestra de Services

![image](https://github.com/user-attachments/assets/ea38c13e-7518-4896-a14a-71a37236795b)

**Comment by stevencol** [comment]
# Recopilación: #

1. Usar información de token para los nombres: 


![Image](https://github.com/user-attachments/assets/1e7bc509-34df-40d9-bfa6-c55185cf26f6)

2. Usar Token: Para obtener documento del ordenador para la carga de cumplido: 



![Image](https://github.com/user-attachments/assets/fd15a061-831d-40a8-ace0-f93dd5dc8624)

3. crear Servicio para saber cuál es el ordenador actual y asignarle los cumplidos


![Image](https://github.com/user-attachments/assets/d5dcf8fa-8df5-496a-8e53-f551c25807eb)


4. implementar modal para ver-soportes en el módulo superior 

5. Eliminar los componentes replicados modal-ver-soportes que se encuentran en los paquetes ordenador y contratación


![Image](https://github.com/user-attachments/assets/7946923e-8478-473b-bef7-4a9ca34f24fb)


6.  Usar camel en todas los metodos: 
FormularioInformeSeguimientoComponent
![Image](https://github.com/user-attachments/assets/6e4894c1-9e46-4779-80bb-64bccf9284b0)


TablaAproabacionPagoComponent

![Image](https://github.com/user-attachments/assets/b6ad1b8c-4230-4c71-b0a5-cc23137e5432)


![Image](https://github.com/user-attachments/assets/cbdae02e-8afa-44ca-adcf-18c4af903367)


7. Agregar mensaje de carga al firmar-cargar documentos 


![Image](https://github.com/user-attachments/assets/73652274-6576-43f6-94a8-e8cf8c3ef2ad)



![Image](https://github.com/user-attachments/assets/f21dc380-ea99-494c-a22f-8dd4a41f7523)

8. Crear/usar Services por sistema utilizado: 



![Image](https://github.com/user-attachments/assets/bca9945c-de8c-4774-928d-84fe25795c89)


9.Permitir guardar información del formulario en la tabla 'Información de pago' para permitir editar y modificar si aún no se ha firmado el documento o tiene tiene algún tipo de rechazo 

10. Listar bancos en formulario informe de satisfacción 

![Image](https://github.com/user-attachments/assets/cf5b9aee-5d0b-4ff3-9335-7eb2337bf3f2)

11. Ajustar diseños en modal listar-documento

![Image](https://github.com/user-attachments/assets/d0878674-d244-492c-9c82-d884c1f452e7)


Ajustar diseños en tabla ordenador

![Image](https://github.com/user-attachments/assets/bd6d492b-dbdd-4f22-9a9f-533ca75a8d1c)

**Comment by stevencol** [comment]
11- Mostrar tipo de contrato que tiene en proveedor

**Comment by JuanCamiloMartinezLopez** [comment]
@stevencol Buen trabajo.
