### ISSUE TITLE
Generar acercamiento con SICOPI por medio de SISPRO

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/Cumplidos_y_certificaciones_documentacion#12]
Se requiere realizar el 

**Sub Tareas**

- [x] Explorar forma contacto con SISPRO
- [x] Generar comunicación de contacto

**Criterios de aceptación**

- [x] Recopilar la información de canales de contacto
- [x] Intento de contacto realizado

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación 
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se ha dado respuesta del ministerio de salud y protección social , se adjunta la respuesta.

Se hará un nuevo de correo , a petición de conocer cual es procedimiento comentado en la respuesta.

[Documento de respuesta ](https://github.com/user-attachments/files/15849122/2024_1330_docs_1202442301287432_00001.1.pdf)

**Comment by mantnicot** [comment]
Se ha enviado el correo a petición de reconocer el procedimiento indicado en la respuesta anterior

![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/85162258/9237007e-9204-41ac-b694-854a77c7a55b)

**Comment by mantnicot** [comment]
Se ha generado respuesta de radicado , por el cual se identifica la necesidad 



![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/85162258/9598e7c8-0732-4187-bc6f-33f64adf7ab3)


Se queda a espera a la respuesta
