### ISSUE TITLE
Implementación de firma electronica en cumplidos proveedores.

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#120]
Se requiere realizar la implementación de firma electrónica en los documentos.

**Sub Tareas**

- [x] Implementar firma electrónica para los documentos de cumplido a satisfacción y autorización de giro según #109.
- [ ] Agregar alertas que indiquen que el aceptar la previsualización del documento autoriza la firma electrónica.

**Criterios de aceptación**

- [x] Firma electronica implementada.
- [x] issue documentada. 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by stevencol** [comment]
Como esta issue depende de  [109](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/issues/109) ,  se tienen inconvenientes al crear el documento con el MIME correcto. Tan pronto se logre solucionar, se podrá continuar con esta tarea.

**Comment by stevencol** [comment]
Se inicia con actividad, 
Como se mencionó en [109](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/issues/109)
es necesario crear/cambiar la respuesta para el documento de aprobación de pago por lo que se crea :

``` JavaScript
type AutorizacionDePago struct {
	NombreArhivo        string
	NombreResponsable   string
	CargoResponsable    string
	DescricionDocumento string
	Archivo             string
}

```

El cual cumple con lo requerido por firma electronica

**Comment by stevencol** [comment]
Con el fin de avanzar, se le dará prioridad a esta tarea, una vez terminada se continuará con  [111](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/issues/111)
El día de hoy se realizarán los ajustes en el cliente, para que una vez firmando el documento se obtenga el id y este se registre en la bd de cumplidos_proveedores

**Comment by stevencol** [comment]
Se están teniendo dificultades para  lograr enviar la petición a la firma electrónica ya que se el servidor rechaza la conexión

``` JavaScript
Refused to connect to 'http://pruebasapi2.intranetoas.udistrital.edu.co:8560/v1/firma_electronica' because it violates the following Content Security Policy directive: "connect-src https: localhost:* ws://localhost:*".
```

**Comment by stevencol** [comment]
Se inicia con cambiando la manera de que se recibe la respuesta en el cliente ay que para cumplir con respuesta de firma se realizaron cambios en el back, se comprueba funcionalidad:
![firmasss](https://github.com/user-attachments/assets/eb9be946-8c63-4cc5-af8d-2e28da40952b)

**Comment by stevencol** [comment]
Se logra solucionar el problema 
![image](https://github.com/user-attachments/assets/c07406df-d326-4111-b8db-a2cb3a0baac1)

**Comment by stevencol** [comment]
La solución propuesta no es adecuada. Se busca ayuda técnica para encontrar una solución óptima al problema, la cual permitirá obtener el mismo resultado pero de una manera mejorada. También se ofrece una solución alternativa que cumple con estos requisitos

![image](https://github.com/user-attachments/assets/36add598-ea70-4dc9-a543-aa58946c106f)

**Comment by stevencol** [comment]
Se implementa firma electrónica en la autorización de pago, y se registra en la base de datos de cumplidos_proveedores. Internamente, se siguen estos pasos:

Se genera la autorización de pago.
Se muestra la autorización de pago.
Si es aprobado, se envía a firma electrónica; si no, no se realiza nada.
La firma electrónica retorna el ID de documento CRUD que obtiene el documento.
Se toma ese ID y el del cumplido y se registra en la base de datos de cumplidos_mid, donde solo se asocia a cumplido_proveedor.
Se consulta con el ID del documento.
Se muestra el documento firmado.
![firmasss](https://github.com/user-attachments/assets/f9b04735-d59e-45fd-abe1-cfdde116bf43)

**Comment by stevencol** [comment]
Se continua con el informe de gestión

**Comment by stevencol** [comment]
Se modifica respuesta en el mi para el informe de gestión para cumplir con lo requerido 

repuesta anterior en el helper:

``` Go
informe_seguimiento = models.InformeSeguimiento{File: encodedFile, Archivo: nombre}

```

Respuesta nueva:
``` Go
solicitud_de_firma := models.SolicituDeFirma{
NombreArchivo: nombre,
NombreResponsable: "", 
CargoResponsable: "", 
DescripcionDocumento: "Informe de seguimiento", 
Archivo: encodedFile}

```

**Comment by stevencol** [comment]
En el routing se modifica para obtener el ID del cumplido cuando se está generando el informe de gestión, ya que no hay otra manera de capturarlo debido a que se redirige a otra página

``` js
 path: 'informe-seguimiento/:cumplidoId',
    component: ComponentePrincipalComponent,
```

**Comment by stevencol** [comment]
- Se captura 

``` Go
  this.route.paramMap.subscribe(params => {
      const idParam = params.get('cumplidoId');
      this.cumplidoId = idParam ? +idParam : 0;
    });
```

- se modifica función submitFormularioInformeSeguimiento()  pra crear el Objeto requerido por la firma electrónica 


``` JavaScript
submitFormularioInformeSeguimiento(){
    this.cumplidosMidServices.contrato$.subscribe(contrato => {
      if (contrato){
        this.numeroContrato = contrato.Contrato.NumeroContratoSuscrito;
        this.vigencia = contrato.Contrato.Vigencia;
      }else{
        this.popUpManager.showErrorAlert('No se registra informacion del contrato');
      }
    })
    if(this.formularioInformeSeguimiento.valid){

      const body = {
        "BancoId": 1,
        "NumeroContratoSuscrito": Number(this.numeroContrato),
        "NumeroCuenta": this.formularioInformeSeguimiento.value.numero_cuenta,
        "NumeroCuentaFactura": this.formularioInformeSeguimiento.value.numero_cuenta,
        "PeiodoInicio": this.convertirFechaFormato(this.formularioInformeSeguimiento.value.fecha_inicio),
        "PeriodoFin": this.convertirFechaFormato(this.formularioInformeSeguimiento.value.fecha_fin),
        "TipoCuenta": this.formularioInformeSeguimiento.value.tipo_cuenta.nombre,
        "TipoPagoId": this.formularioInformeSeguimiento.value.tipo_pago.nombre,
        "TipoDocumentoCobroId": this.formularioInformeSeguimiento.value.cuenta_cobro.nombre,
        "ValorPagar": Number(this.formularioInformeSeguimiento.value.valor_pagar),
        "VigenciaContrato": this.vigencia
      }
      this.cumplidosMidServices.post('/supervisor/informe-seguimiento', body)
      .subscribe({
        next: (res: any) => {

          this.solicituDeFirma= new SolicituDeFirma(res.Data.NombreArchivo,
            res.Data.NombreResponsable ,
            res.Data.CargoResponsable, 
            res.Data.DescripcionDocumento, 
            res.Data.Archivo);
  
          this.pdfBase64 = this.solicituDeFirma.Archivo;
          this.nameFile = this.solicituDeFirma.NombreArchivo;
          console.log("#-----")
          console.log(this.solicituDeFirma.Archivo)
          console.log("#-----")
          
          this.popUpManager.showSuccessAlert('Informe de seguimiento creado exitosamente');
          console.log("#-----")
          console.log(this.solicituDeFirma)
          console.log("#-----")
          
        },
        
        error: (error: any) => {
          this.popUpManager.showErrorAlert('Error al crear el informe de seguimiento');
        }
      });
    }else{
      this.popUpManager.showErrorAlert('Datos incorrectos o faltantes');
    }
  }
```

- y se envia al modal que muestra el informe y el encargado de firmar el documneto

``` JavaScript

  modalVerSoporte() {
    this.dialog.open(ModalVerSoporteComponent, {
      disableClose: true,
      height: '70vh',
      width: '40vw',
      maxWidth: '60vw',
      maxHeight: '80vh',
      panelClass: 'custom-dialog-container',
      data: {
        documentoAFirmar: this.solicituDeFirma,
        aprobarSoportes: true,
        idCumplido: this.cumplidoId,
        tipoDocumento:168,
        base64:this.pdfBase64,
        cargoResponsable:"Supervisor",
      },
    });
  }


```

**Comment by stevencol** [comment]
Se realiza prueba de firmado 👍🏽 
![firmasss](https://github.com/user-attachments/assets/788f8228-fa79-49a3-a014-76e64e0d7ef9)

**Comment by JuanCamiloMartinezLopez** [comment]
@stevencol Buen trabajo.
