### ISSUE TITLE
Exploración y apropiación de usuario institucional en SISPRO para revisión de planilla de seguridad social

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/Cumplidos_y_certificaciones_documentacion#122]

**Comment by mantnicot** [comment]
Se ha realizado un documento donde se coloco evidencia de la exploración realizada en el sistema 

Se concluye que el sistema de SISPRO no puede dar solución a el requerimiento


[Documento de evidencia](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/ERWSfSAmq4lFvJtXQHLOk6UBAoLCuEL7tkNJDeb6wzddlg?e=rrzUT9)

**Comment by jcmurilloa** [comment]
Se hace necesario de esta manera explorar nuevamente con Colombia Compra Eficiente, la manera en que se consulta la planilla por medio de SECOP II. Se asignará issue para este siguiente paso en un nuevo sprint.
