### ISSUE TITLE
Gestionar la actualización de formato de evaluación de proveedores ante el SIGUD

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/Cumplidos_y_certificaciones_documentacion#123]
Se requiere realizar la actualización de formato de evaluación de proveedores, cumplido y actualización de giro ante el SIGUD

**Sub Tareas**

- [x] Adelantar contacto para desarrollo de aprobación del formato de evaluación en vicerectoría
- [x] Generar el seguimiento a la actualización del formato de cumplido en contratación
- [x] Adelantar contacto para la actualización de autorización de giro por parte de Financiera 

**Criterios de aceptación**

- [x] Envío ante el SIGUD de plantilla evaluación para aprobación.
- [x] Envío ante el SIGUD de plantilla cumplido para aprobación.
- [x] Envío ante el SIGUD de plantilla autorización de giro para aprobación.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.

**Comment by mantnicot** [comment]
Se ha enviado el correo a computo para su envió a planeación

La ruta de actualización fue dada por Jhon de parte del Sigud 

[Formato de actualización](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/caescorciab_udistrital_edu_co/EVCtxVMWZthCk-E5bXV6NdkB3EZM-p3F8D1_i_w3C34F3w?e=G1UyQW)

![Image](https://github.com/user-attachments/assets/cde87f9a-555a-45cd-9f82-869e92dac076)

**Comment by jcmurilloa** [comment]
Buen trabajo @mantnicot, estaremos atentos de la evolución de la solicitud en el sigud.

**Comment by mantnicot** [comment]
Se ha enviado el correo a planeación directamente , se espera respuesta


Archivo de solicitud
[GI-PR-005-FR-012 (2) (2).xlsx](https://github.com/user-attachments/files/16721663/GI-PR-005-FR-012.2.2.xlsx)



![Image](https://github.com/user-attachments/assets/301220ec-599b-432e-a9ed-c8703bb68909)

**Comment by mantnicot** [comment]
Se ha enviado el correo a tesorería para que puedan gestionar la actualización del formato



![Image](https://github.com/user-attachments/assets/2c4e9f19-853a-480a-8597-9a2c2cff0033)

**Comment by jcmurilloa** [comment]
Tengo inquietud sobre si a los tres formatos descritos como subtareas se les realizó su respectiva gestión. Revisando la issue se evidencia la gestión sobre el formato de financiera y de evaluación, mas no está claro el de contratación.

**Comment by mantnicot** [comment]
Se intento tener información de parte de contratación el día viernes pero no hubo respuesta de evidencia



![Image](https://github.com/user-attachments/assets/28d34a81-880f-4003-8130-853ff216b4fb)

**Comment by mantnicot** [comment]
Se ha podido hablar con contratación y se llego al acuerdo que 29/08/2024 se hara el envio del correo para planeación

**Comment by mantnicot** [comment]
Se ha realizado el envió de parte de contratación

![Image](https://github.com/user-attachments/assets/bd2ddb3d-d1ac-461d-a7ed-30b700e595a3)

**Comment by jcmurilloa** [comment]
Muy buena gestión @mantnicot para la actualización de estos formatos en cada dependencia, recuerda mantener un contacto con el SIGUD para la aprobación y salida de cada uno de los formatos.
