### ISSUE TITLE
Refactorización del mf de revisión de cumplidos proveedores - Parte II

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#124]
Se requiere realizar parte de los ajustes indicados en la primera parte de la tarea.

**Sub Tareas**

- [x] Crear los servicios individuales para cada api que se use.
- [x] Crear modals de spinner para la carga y de mensajes de confirmación para los diferentes flujos que lo requieran.
- [x] Ajustar el flujo del formulario de información bancaria en la vista de informe de cumplido a satisfacción.
- [x] Guardar la información del informe en la tabla de informacion_pago según lo indicado. 

**Criterios de aceptación**

- [ ] Cambios realizados.
- [ ] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by stevencol** [comment]
Se inicia con actividad

**Comment by stevencol** [comment]
Se  crean modals de spinner para la carga y de mensajes de confirmación para los diferentes flujos
Supervisor:
![cargaContratos](https://github.com/user-attachments/assets/d6a56306-f26d-4b86-b248-0e9ef77fca99)

Ordenador: 
![ordenador](https://github.com/user-attachments/assets/3568b444-cab8-40f2-a5f9-b3089044ef12)

Contratación:
![contratacion](https://github.com/user-attachments/assets/4d1cdef0-d926-4e1a-9e42-c550849dba0c)

**Comment by stevencol** [comment]
Como se han presentados errores con el mid en la rama DEVELOP , se decide por usar rama (feature/RefactorizacionMid)  y ene esa rama se crea modelo:


https://github.com/user-attachments/assets/ba9d8a56-07f4-42d3-bdb8-e2bd12b6ffc1

**Comment by stevencol** [comment]
Se logra solucionar el error: 
Se cambia en el cliente de : 
``` JavaScript
 getSolicitudesContrato(numero_contrato: string, vigencia_contrato: string){
    this.cumplidosMidServices.contrato$.subscribe(contrato  => {
      if (contrato) {
        this.cumplidosMidServices.get('/supervisor/solicitudes-contrato/' + numero_contrato + '/' + vigencia_contrato)
          .subscribe({
            next: (res: any) => {
              var count = 1
              this.solicitudes_contrato = res.Data;
              console.log(res.Data)
              this.dataSource = this.solicitudes_contrato.map((solicitud: any) => {
                return {
                  noSolicitud: count++,
                  numeroContrato: solicitud.CumplidoProveedorId.NumeroContrato,
                  fechaCreacion: new Date(solicitud.FechaCreacion),
                  periodo: "11/04/2024 - 11/05/2024",
                  estadoSoliciatud: solicitud.EstadoCumplidoId.Nombre,
                  acciones: 'Editar, Eliminar',
                  cumplidoProveedor: solicitud.CumplidoProveedorId
                };
              })
            },
            error: (error: any) => {
              this.popUpManager.showErrorAlert('El Proveedor no tiene ninguna solicitud reciente');
            }
          });
      }
    })
  }
```
a

``` JavaScript
  getSolicitudesContrato(numero_contrato: string, vigencia_contrato: string){
    this.cumplidosMidServices.contrato$.subscribe(contrato  => {
      if (contrato) {
        this.cumplidosMidServices.get('/supervisor/solicitudes-contrato/' + numero_contrato + '/' + vigencia_contrato)
          .subscribe({
            next: (res: any) => {
              var count = 1
              this.solicitudes_contrato = res.Data;
              console.log(res.Data)
              this.dataSource = this.solicitudes_contrato.map((solicitud: any) => {
                return {
                  noSolicitud: count++,
                  numeroContrato: solicitud.CumplidoProveedorId.NumeroContrato,
                  fechaCreacion: new Date(solicitud.FechaCreacion),
                  periodo: "11/04/2024 - 11/05/2024",
                  estadoSoliciatud: solicitud.EstadoCumplido,
                  acciones: 'Editar, Eliminar',
                  cumplidoProveedor: solicitud.CumplidoProveedorId
                };
              })
            },
            error: (error: any) => {
              this.popUpManager.showErrorAlert('El Proveedor no tiene ninguna solicitud reciente');
            }
          });
      }
    })
  }
```

**Comment by stevencol** [comment]
Se avanza con la Refactorización:
para listar los bancos se crea funcion obtenerBancos()  

``` JavaScript
  obtenerBancos() {
    this.coreApiService.get('/banco?limit=-1').subscribe(
      (respose: any) => {
        this.listaBancos = respose;
        console.log(respose);
      },
      (error) => {
        this.alertService.showErrorAlert(error.Error);
      }
    );
  }
```

Para listar el tipo de cuenta se creó una función, la cual por el momento no funciona ya que el método del backend aún no ha desplegado esta funcionalidad. Sin embargo, se ha creado siguiendo el modelo y la ruta del backend.

``` JavaScript
  obtenerTipoCuentaBancaria(bancoId: number) {
    this.coreApiService.get(`/tipo_cuenta_bancaria/${bancoId}`).subscribe(
      (respose: any) => {
        this.listaTiposCuentaBancaria = respose?.Data || [];
      },
      (error) => {
        console.error('Error al obtener tipos de cuenta', error);
        this.listaTiposCuentaBancaria = [];
      }
    );
  }

```


Se procede a crear un método que realice la consulta para listar los tipos de pago, que por el momento se está inicializando en el cliente  disponible en el cliente.
![image](https://github.com/user-attachments/assets/d18b58d4-6b5b-49f1-9e22-bd6276215416)

**Comment by stevencol** [comment]
Se avanza con a la refactorización y se remplazan las listas estáticas de tipos cuenta y tipo cobro por consultas a la basde de datos; 
![cargaContratos](https://github.com/user-attachments/assets/40be9a7d-8caa-46c5-9d06-4eb2d9366bb2)
Anteriormente ya se estaba  guardando la inflo pero por las modificaciones por alguna razón el formulario está llegando vacío, se esta trabajado en ello

**Comment by stevencol** [comment]
Se termina con el flujo del   información bancaria
![cargaContratos](https://github.com/user-attachments/assets/8d12e5f2-e3f3-44bf-8a2a-444a8c1b763a)

**Comment by JuanCamiloMartinezLopez** [comment]
@stevencol Buen trabajo.
