### ISSUE TITLE
Crear documentación para el módulo de revisión cumplidos proveedores

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#125]
Se requiere realizar la documentación técnica requerida para el módulo de revisión de cumplidos proveedores basandose en los [documentos](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/Eo8tqC5GQnNKhI18i9nX0goBz1JCokLP5ujjCsv9yx5W8A?e=ElUHyJ) realizados para el modulo de históricos de cumplidos cps.

**Sub Tareas**

- [x] Realizar documento de Casos de soporte.
- [x] Realizar documento de Descripción técnica.
- [x] Realizar documento de Diagnóstico final.
- [x] Realizar documento de Matriz de accesos.
- [x] Guardar documentos en la carpeta correspondiente del proyecto.

**Criterios de aceptación**

- [x] Documentos realizados.
- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
### Documentación de Casos de Soporte del Sistema de Revisión Cumplidos Proveedores

**Descripción del avance:**  
Se ha elaborado el documento de casos de soporte para el Sistema de Revisión Cumplidos Proveedores de la Universidad Distrital Francisco José de Caldas. Este documento es fundamental para la gestión técnica y el soporte del sistema, proporcionando un marco detallado para la identificación, diagnóstico y resolución de los problemas más comunes que pueden enfrentar los usuarios y el equipo técnico.

**Avances y contenido actualizado:**

1. **Estructura del Documento:**
   - Se definió una estructura clara y organizada que incluye secciones clave como la **Introducción**, **Tipos de Casos de Soporte**, **Posibles Causas** y **Procedimientos de Resolución**.
   - La **Introducción** establece el propósito, alcance y audiencia del documento, asegurando que su uso esté alineado con las necesidades del equipo de soporte y los usuarios del sistema.

Se añade este documento a la [carpeta](https://udistritaleduco-my.sharepoint.com/shared?id=%2Fpersonal%2Fcomputo%5Fudistrital%5Fedu%5Fco%2FDocuments%2FINVERSI%C3%93N%2FPROYECTOS%20DE%20INVERSI%C3%93N%2FGERENCIA%20DE%20PROYECTOS%2FPROYECTOS%20OAS%2FPROYECTO%20CUMPLIDOS%20Y%20CERTIFICACIONES%2F2024%2FEjecuci%C3%B3n%2FGesti%C3%B3n%20t%C3%A9cnica%2FCUMPLIDOS%2FProveedores%2FDocumentacion&listurl=%2Fpersonal%2Fcomputo%5Fudistrital%5Fedu%5Fco%2FDocuments) del proyecto

**Comment by faidercamilo26** [comment]
### Descripción Técnica del Sistema de Revisión Cumplidos Proveedores

**Descripción del cambio:**  
Se ha elaborado y actualizado el documento de descripción técnica del Sistema de Revisión Cumplidos Proveedores para la Universidad Distrital Francisco José de Caldas. Este documento es esencial para comprender en detalle la arquitectura, las funcionalidades y las limitaciones actuales del sistema, permitiendo una gestión técnica efectiva y facilitando futuras mejoras y mantenimientos.

**Avances y contenido actualizado:**

1. **Estructura del Documento:**
   - Se definió una estructura clara que abarca desde la **Introducción** hasta las **Limitaciones** actuales del sistema.
   - La **Introducción** incluye una descripción del módulo, destacando su propósito en la gestión eficiente de los cumplidos asociados a los pagos de proveedores, y establece los **Objetivos** de la documentación, que son proporcionar claridad en los componentes del sistema, facilitar el mantenimiento, y asegurar la trazabilidad del proceso de revisión de cumplidos.

2. **Repositorios del Código:**
   - Se listaron los repositorios GitHub del API Cliente, Mid y Crud asociados al sistema de Revisión Cumplidos Proveedores, proporcionando enlaces directos a cada uno de ellos.

3. **APIs y Endpoints Usados:**
   - Se documentaron los principales endpoints utilizados por el sistema, detallando su método HTTP, la URL de acceso, los datos requeridos, y la función que cumplen dentro del sistema.
   - Incluye endpoints para operaciones como la creación, modificación, y eliminación lógica de cumplidos, la gestión de soportes, la obtención de contratos y dependencias, entre otros.

4. **Interacción con la Base de Datos:**
   - Se describió la interacción del sistema con las bases de datos, especificando los esquemas y tablas relevantes, tales como `cambio_estado_cumplido`, `cumplido_proveedor`, `acta_inicio`, `informacion_proveedor`, y más.

5. **Limitaciones del Sistema:**
   - Se identificaron y documentaron varias limitaciones actuales del sistema, incluyendo:
     - **Falta del Módulo de Histórico de Cumplidos:** Ausencia de un módulo que permita realizar filtros avanzados sobre el historial de cumplidos.
     - **Imposibilidad de Descargar Soportes en un Archivo Comprimido:** Falta de opción para descargar todos los soportes asociados a un cumplido en un único archivo comprimido.
     - **Falta de Parametrización de Fechas para Subida de Documentos:** No es posible establecer fechas específicas para la carga de documentos.
     - **Incapacidad de Asignar Cumplidos a Personas Específicas:** Actualmente, todos los miembros del equipo de contratación pueden revisar cualquier cumplido, sin asignaciones específicas.

6. **Consideraciones para Futuras Mejoras:**
   - Se sugirió que estas limitaciones sean abordadas en futuras actualizaciones del sistema para mejorar su funcionalidad y adaptabilidad a las necesidades de los usuarios.

**Comment by faidercamilo26** [comment]
Se ha añadido el documento completo de diagnóstico final y plan de mejoramiento del Sistema de Revisión de Cumplidos Proveedores. Este documento ha sido elaborado para evaluar el estado actual del sistema, identificar errores críticos, limitaciones funcionales y proponer un plan de mejoramiento detallado. A continuación, se describen los principales avances realizados en esta entrega:

## 1. Diagnóstico del Estado Actual del Sistema
- Se evaluó el sistema en su entorno de pruebas, identificando que, aunque varias funcionalidades clave están implementadas, el sistema no está listo para un entorno de producción debido a errores y limitaciones.
- Las funcionalidades implementadas incluyen la carga y gestión de soportes documentales, la aprobación y rechazo de cumplidos, así como la generación de informes de satisfacción o autorización de pagos.

## 2. Identificación de Bugs y Errores Conocidos
- Se documentaron los errores críticos como la creación de múltiples cumplidos en estado "Cargando Documentos", problemas en la previsualización de documentos, y errores de solicitud desde otro origen, entre otros.
- Estos errores se consideraron prioritarios para su resolución en futuras iteraciones del sistema.

## 3. Limitaciones Identificadas
- Se señalaron limitaciones clave como la falta de un módulo de histórico de cumplidos, la imposibilidad de descargar soportes en un archivo comprimido, y la incapacidad de asignar cumplidos a personas específicas dentro del equipo.
- Estas limitaciones resaltan la necesidad de mejorar la funcionalidad del sistema para cumplir con las expectativas de los usuarios finales.

## 4. Desarrollo del Plan de Mejoramiento
- Se diseñó un plan de mejoramiento con cuatro secciones clave: Corrección de Errores Críticos, Mejoras Funcionales, Pruebas y Validación, y Documentación.
- Este plan aborda cada uno de los errores y limitaciones identificados, proponiendo soluciones específicas como la implementación de validaciones adicionales, ajustes en configuraciones de seguridad, y desarrollo de nuevas funcionalidades.

## 5. Pruebas y Validación
- Se incluyó un enfoque en reforzar las pruebas unitarias y de integración para asegurar que las nuevas funcionalidades y correcciones se implementen sin afectar negativamente otros componentes del sistema.
- Además, se priorizará la revisión de la experiencia de usuario (UX/UI) para mejorar la usabilidad general del sistema.

## 6. Actualización de Documentación
- Se hará una actualización completa de la documentación técnica y de usuario para reflejar los cambios y mejoras implementadas, asegurando que todos los usuarios tengan acceso a información actualizada y relevante.

Este avance marca un paso importante hacia la estabilización y optimización del Sistema de Revisión de Cumplidos Proveedores, sentando las bases para su eventual despliegue en un entorno de producción.

**Comment by faidercamilo26** [comment]
### Implementación de la Matriz de Acceso para el Sistema de Revisión Cumplidos Proveedores

**Descripción de lo realizado:**

Se ha elaborado y documentado la **Matriz de Acceso** para el **Sistema de Revisión Cumplidos Proveedores.** Este documento es esencial para definir claramente los roles, funciones y limitaciones de acceso de los usuarios dentro del sistema, asegurando el control y la seguridad adecuados.

**Avances y contenido actualizado:**

1. **Estructura del Documento:**
   - Se creó una estructura clara que incluye la **Introducción**, donde se describe el propósito y la importancia de la matriz de acceso.
   - Se definió un formato estándar para la identificación de la **versión**, **elaboración** y **revisión** del documento, asegurando su correcta trazabilidad.

2. **Roles y Funciones Documentados:**
   - **Supervisor:** Puede crear solicitudes de cumplidos, subir y gestionar documentos de soporte, y generar informes de seguimiento. Sin embargo, tiene limitaciones en cuanto a la aprobación o rechazo de cumplidos.
   - **Contratación:** Encargado de revisar, aprobar o rechazar cumplidos, y solicitar modificaciones o documentación adicional. No tiene acceso a la generación de cumplidos o documentos de soporte.
   - **Ordenador del Gasto:** Tiene la capacidad de revisar y aprobar cumplidos aprobados por Contratación, generar certificados de aprobación de pago y revertir estados de un cumplido bajo ciertas condiciones. Sin embargo, no puede modificar cumplidos ni documentos de soporte, y está limitado en su capacidad de revertir estados fuera del tiempo especificado.

3. **Limitaciones Específicas:**
   - Cada rol tiene limitaciones claras definidas, lo que asegura que los usuarios solo pueden realizar acciones correspondientes a sus responsabilidades, evitando accesos o modificaciones no autorizadas.

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 Buen trabajo.
