### ISSUE TITLE
Refactorización del mid de revisión de cumplidos proveedores - Parte III

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#127]
Se requiere realizar las refactorizaciones restantes del mid

**Sub Tareas**

- [x] implementantar los servicios jbpm creados:

-  http://busservicios.intranetoas.udistrital.edu.co:8282/wso2eiserver/services/administrativa_pruebas/contratos_proveedor_dependencia/{codigo_dependencia}

- http://busservicios.intranetoas.udistrital.edu.co:8282/wso2eiserver/services/administrativa_pruebas/informacion_contrato_proveedor/{numero_contrato_suscrito}/{vigencia}

- http://busservicios.intranetoas.udistrital.edu.co:8282/wso2eiserver/services/administrativa_pruebas/informacion_ordenador_contrato/{numero_contrato_suscrito}/{vigencia}

- http://busservicios.intranetoas.udistrital.edu.co:8282/wso2eiserver/services/administrativa_pruebas/informacion_supervisor_contrato/{numero_contrato_suscrito}/{vigencia}

- [x] Realizar una revisión de lógica y flujo de los servicios.
- [x] Realizar pruebas del correcto funcionamiento del mid.

**Criterios de aceptación**

- [x] Mid funcional en pruebas.
- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
## :triangular_flag_on_post: **Refactorizacion Mid III**  :triangular_flag_on_post:

Se inicia con la parte 3 de la refactorización, en el proceso de utilizar los servicios JBPM para factorizar el MID surge una duda con el servicio que trae la información de los contratos por proveedor, se realiza la consulta correspondiente, pero la respuesta trae dos contratos, trae la misma información menos el número de cdp, no se sabe cual se debe retornar o si se retornan los dos contratos. Por el momento se están retornando los dos contratos.



![Image](https://github.com/user-attachments/assets/62491cd1-bb47-481e-98d4-4a76f808dea7)

**Comment by faidercamilo26** [comment]
Se llevó a cabo una refactorización exhaustiva de toda la funcionalidad responsable de obtener los contratos activos asociados a un supervisor. Anteriormente, el sistema presentaba problemas tanto en los tiempos de respuesta como en la precisión de los datos recuperados.

Durante la refactorización, se implementaron los servicios JBPM adecuados, lo que resultó en una mejora significativa en la velocidad de carga del sistema. Esta optimización no solo reduce considerablemente el tiempo de espera para el usuario final, sino que también asegura que los datos obtenidos sean precisos y relevantes.

Un aspecto crítico que se corrigió en este proceso fue la naturaleza de los contratos recuperados. Antes de la refactorización, el sistema estaba obteniendo contratos de contratistas en lugar de los contratos correspondientes a proveedores. Con esta actualización, ahora se garantizan que los contratos recuperados son los correctos, es decir, los contratos de proveedores, alineándose con los requerimientos específicos de la aplicación.

Este cambio no solo mejora el rendimiento del sistema, sino que también garantiza la integridad y exactitud de los datos mostrados al usuario, lo cual es fundamental para la operación diaria de la plataforma.



![Image](https://github.com/user-attachments/assets/3c157799-9699-4e79-baff-ec6c84b48a59)



![Image](https://github.com/user-attachments/assets/3f6232ae-74ce-4708-bd94-84e6b8b16606)


```golang
func ObtenerContratosSupervisor(documento_supervisor string) (contratos_supervisor models.ContratoSupervisor, outputError map[string]interface{}) {

	defer func() {
		if err := recover(); err != nil {
			outputError = map[string]interface{}{"funcion": "/ContratosSupervisor", "err": err, "status": "502"}
			panic(outputError)
		}
	}()

	dependencias_supervisor, err := ObtenerDependenciasSupervisor(documento_supervisor)
	if err == nil {
		for _, dependencia := range dependencias_supervisor {
			contratos_supervisor.Dependencias_supervisor = append(contratos_supervisor.Dependencias_supervisor, dependencia)
			contratos_dependencia, err := ObtenerContratosDependencia(dependencia.Codigo)
			if err == nil {
				for _, contrato := range contratos_dependencia.Contratos.Contrato {
					informacion_contrato_proveedor, err := ObtenerInformacionContratoProveedor(contrato.NumeroContrato, contrato.Vigencia)
					if err == nil {
						for _, contrato_proveedor := range informacion_contrato_proveedor {
							contratos_supervisor.Contratos = append(contratos_supervisor.Contratos, contrato_proveedor)
						}
					} else {
						logs.Error(err)
						outputError = map[string]interface{}{"funcion": "/ContratosSupervisor", "err": err, "status": "502"}
						return contratos_supervisor, outputError
					}
				}
			} else {
				logs.Error(err)
				outputError = map[string]interface{}{"funcion": "/ContratosSupervisor", "err": err, "status": "502"}
				return contratos_supervisor, outputError
			}
		}
	} else {
		logs.Error(err)
		outputError = map[string]interface{}{"funcion": "/ContratosSupervisor", "err": err, "status": "502"}
		return contratos_supervisor, outputError
	}
	return contratos_supervisor, nil
}

func ObtenerInformacionContratoProveedor(numero_contrato_suscrito string, vigencia string) (contratos_proveedor []models.InformacionContratoProveedor, outputError map[string]interface{}) {
	defer func() {
		if err := recover(); err != nil {
			outputError = map[string]interface{}{
				"Success": false,
				"Status":  502,
				"Message": "Error al obtener la informacion del contrato del proveedor",
				"Error":   err,
			}
		}
	}()

	var respuesta_peticion map[string]interface{}
	if response, err := helpers.GetJsonWSO2Test(beego.AppConfig.String("UrlAdministrativaJBPM")+"/informacion_contrato_proveedor/"+numero_contrato_suscrito+"/"+vigencia, &respuesta_peticion); err == nil && response == 200 {
		if respuesta_peticion != nil {
			if contratosMap, exito := respuesta_peticion["proveedor"].(map[string]interface{}); exito {
				for _, contratoList := range contratosMap {
					if list, exito := contratoList.([]interface{}); exito {
						for _, contrato := range list {
							contratoMap := contrato.(map[string]interface{})
							rp, err := helpers.ObtenerRP(contratoMap["numero_cdp"].(string), contratoMap["vigencia_cdp"].(string))
							if err == nil {
								contrato_proveedor := models.InformacionContratoProveedor{
									TipoContrato:           contratoMap["tipo_contrato"].(string),
									NumeroContratoSuscrito: contratoMap["numero_contrato_suscrito"].(string),
									Vigencia:               contratoMap["vigencia"].(string),
									NumeroRp:               rp.CdpXRp.CdpRp[0].RpNumeroRegistro,
									VigenciaRp:             rp.CdpXRp.CdpRp[0].RpVigencia,
									NombreProveedor:        contratoMap["proveedor"].(string),
									NombreDependencia:      contratoMap["dependencia"].(string),
									NumeroCdp:              contratoMap["numero_cdp"].(string),
									VigenciaCdp:            contratoMap["vigencia_cdp"].(string),
									Rubro:                  contratoMap["rubro"].(string),
								}
								contratos_proveedor = append(contratos_proveedor, contrato_proveedor)
							} else {
								logs.Error(err)
								outputError = map[string]interface{}{"funcion": "/ObtenerInformacionContratoProveedor/", "err": err, "status": "502"}
								return contratos_proveedor, outputError
							}
						}
					} else {
						logs.Error("Error al obtener la informacion del contrato del proveedor")
						outputError = map[string]interface{}{"funcion": "/ObtenerInformacionContratoProveedor/", "err": "Error al obtener la informacion del contrato del proveedor", "status": "502"}
						return contratos_proveedor, outputError
					}
				}
			} else {
				logs.Error("Error al obtener la informacion del contrato del proveedor")
				outputError = map[string]interface{}{"funcion": "/ObtenerInformacionContratoProveedor/", "err": "Error al obtener la informacion del contrato del proveedor", "status": "502"}
				return contratos_proveedor, outputError
			}
		} else {
			logs.Error("Error al obtener la informacion del contrato del proveedor")
			outputError = map[string]interface{}{"funcion": "/ObtenerInformacionContratoProveedor/", "err": "Error al obtener la informacion del contrato del proveedor", "status": "502"}
			return contratos_proveedor, outputError
		}
	} else {
		logs.Error(err)
		outputError = map[string]interface{}{"funcion": "/ObtenerInformacionContratoProveedor/", "err": err, "status": "502"}
		return contratos_proveedor, outputError
	}

	return contratos_proveedor, nil
}

func ObtenerContratosDependencia(dependencia string) (contratos_dependencia models.ContratoDependencia, outputError map[string]interface{}) {
	defer func() {
		if err := recover(); err != nil {
			outputError = map[string]interface{}{
				"Success": false,
				"Status":  502,
				"Message": "Error al obtener los contratos de la dependencia: " + dependencia,
				"Error":   err,
			}
		}
	}()

	var respuesta_peticion map[string]interface{}
	if response, err := helpers.GetJsonWSO2Test(beego.AppConfig.String("UrlAdministrativaJBPM")+"/contratos_proveedor_dependencia/"+dependencia, &respuesta_peticion); err == nil && response == 200 {
		respuesta_json, err_json := json.Marshal(respuesta_peticion)
		if err_json == nil {
			if err := json.Unmarshal(respuesta_json, &contratos_dependencia); err == nil {
				return contratos_dependencia, nil
			} else {
				logs.Error(err)
				outputError = map[string]interface{}{"funcion": "/ObtenerContratosDependencia/", "err": err.Error(), "status": "502"}
				return contratos_dependencia, outputError
			}
		} else {
			logs.Error(err_json)
			outputError = map[string]interface{}{"funcion": "/ObtenerContratosDependencia/", "err": err_json.Error(), "status": "502"}
			return contratos_dependencia, outputError
		}
	} else {
		logs.Error(err)
		outputError = map[string]interface{}{"funcion": "/ObtenerContratosDependencia/", "err": err, "status": "502"}
		return contratos_dependencia, outputError
	}

}

func ObtenerDependenciasSupervisor(documento_supervisor string) (dependencias_supervisor []models.Dependencia, outputError map[string]interface{}) {
	defer func() {
		if err := recover(); err != nil {
			outputError = map[string]interface{}{
				"Success": false,
				"Status":  502,
				"Message": "Error al consultar las dependencias del supervisor identificado con el documento: " + documento_supervisor,
				"Error":   err,
			}
		}
	}()

	var respuesta_peticion map[string]interface{}
	if response, err := helpers.GetJsonWSO2Test(beego.AppConfig.String("UrlAdministrativaProduccionJBPM")+"/dependencias_supervisor/"+documento_supervisor, &respuesta_peticion); err == nil && response == 200 {
		if respuesta_peticion != nil {
			if dependenciasMap, ok := respuesta_peticion["dependencias"].(map[string]interface{}); ok {

				for _, depList := range dependenciasMap {

					if list, ok := depList.([]interface{}); ok {

						for _, dep := range list {

							depMap := dep.(map[string]interface{})
							dependencia := models.Dependencia{

								Codigo: depMap["codigo"].(string),
								Nombre: depMap["nombre"].(string),
							}
							dependencias_supervisor = append(dependencias_supervisor, dependencia)
						}

					}
				}
			}
		}
	}
	return dependencias_supervisor, nil
}

```

**Comment by faidercamilo26** [comment]
### Resumen de las correcciones realizadas en la refactorización de los cambios de estado

Se han implementado las siguientes modificaciones como parte del proceso de refactorización para la gestión de los cambios de estado:

1. **Simplificación del cambio de estado**:  
   Anteriormente, para realizar un cambio de estado, era necesario enviar el ID del nuevo estado, el ID del cumplido proveedor, el documento del responsable del nuevo estado y el cargo de dicho responsable. Con la refactorización, ahora solo es necesario proporcionar el código de abreviación del nuevo estado y el ID del cumplido proveedor. Los demás datos requeridos en la petición se consultan de manera dinámica según el nuevo estado.

2. **Funciones para obtener supervisor y ordenador**:  
   Se han creado funciones específicas para obtener el supervisor y el ordenador de un contrato, con el fin de construir el cuerpo de la petición para el cambio de estado cumplido.

3. **Abstracción de la lógica de búsqueda**:  
   La lógica para realizar las búsquedas del supervisor o del ordenador, en función del nuevo estado, se ha abstraído en una función denominada `CrearBodyCambioEstadoCumplido()`.

Estas mejoras optimizan el proceso y reducen la complejidad de la implementación.

Por el momento, al intentar probar esta nueva implementación está apareciendo un error el cual ya se está trabajando para solucionar. Se adjunta captura del error y el código que se realizó


![Image](https://github.com/user-attachments/assets/b68816c6-37f0-47d8-9ab2-7a48b013884f)

``` golang

func CambioEstadoCumplido(codigo_abreviacion_cumplido string, cumplido_proveedor_id int) (respuesta_cambio_estado models.CambioEstadoCumplidoResponse, outputError map[string]interface{}) {
	defer func() {
		if err := recover(); err != nil {
			outputError = map[string]interface{}{"funcion": "CambioEstadoCumplido", "err": err, "status": "502"}
			panic(outputError)
		}
	}()

	// Verificar que se envien todos los datos
	if codigo_abreviacion_cumplido == "" || cumplido_proveedor_id == 0 {
		outputError = map[string]interface{}{"funcion": "CambioEstadoCumplido", "status": "502", "mensaje": "Faltan datos por enviar"}
		return respuesta_cambio_estado, outputError
	}

	var cumplido_proveedor []models.CumplidoProveedor
	var estado_cumplido []models.EstadoCumplido

	fmt.Println(beego.AppConfig.String("UrlCrudRevisionCumplidosProveedores") + "/cumplido_proveedor/?query=Id:" + strconv.Itoa(cumplido_proveedor_id))
	if response, err := helpers.GetJsonTest(beego.AppConfig.String("UrlCrudRevisionCumplidosProveedores")+"/cumplido_proveedor/?query=Id:"+strconv.Itoa(cumplido_proveedor_id), &cumplido_proveedor); (err == nil) && (response == 200) {
		if cumplido_proveedor != nil {
			if response, err := helpers.GetJsonTest(beego.AppConfig.String("UrlCrudRevisionCumplidosProveedores")+"/estado_cumplido/?query=CodigoAbreviacion:"+codigo_abreviacion_cumplido, &estado_cumplido); (err != nil) || (response != 200) {
				outputError = map[string]interface{}{"funcion": "CambioEstadoCumplido", "status": "502", "mensaje": "Error al consultar el estado del cumplido"}
				return respuesta_cambio_estado, outputError
			}
		} else {
			outputError = map[string]interface{}{"funcion": "CambioEstadoCumplido", "status": "502", "mensaje": "No se encontró el cumplido proveedor"}
			return respuesta_cambio_estado, outputError
		}
	} else {
		outputError = map[string]interface{}{"funcion": "CambioEstadoCumplido", "status": "502", "mensaje": "Error al consultar el cumplido proveedor"}
		return respuesta_cambio_estado, outputError
	}

	body_cambio_estado, outputError := CrearBodyCambioEstadoCumplido(codigo_abreviacion_cumplido, cumplido_proveedor[0], estado_cumplido[0])
	if outputError != nil {
		return respuesta_cambio_estado, outputError
	}

	ultimo_cambio_estado_cumplido, err := DesactivarCambiosAnterioresCumplido(cumplido_proveedor_id)
	if err != nil {
		outputError = map[string]interface{}{"funcion": "CambioEstadoCumplido", "status": "502", "mensaje": "Error al desactivar los cambios anteriores"}
		return respuesta_cambio_estado, outputError
	}

	if body_cambio_estado.DocumentoResponsable == ultimo_cambio_estado_cumplido.DocumentoResponsable && body_cambio_estado.EstadoCumplidoId.Id == ultimo_cambio_estado_cumplido.EstadoCumplidoId.Id {
		outputError = map[string]interface{}{"funcion": "CambioEstadoCumplido", "status": "200", "mensaje": "El cumplido ya se encuentra en este estado"}
		return respuesta_cambio_estado, outputError
	} else {
		var respuesta_peticion map[string]interface{}
		if err := helpers.SendJson(beego.AppConfig.String("UrlCrudRevisionCumplidosProveedores")+"/cambio_estado_cumplido", "POST", &respuesta_peticion, body_cambio_estado); err == nil {
			respuesta_cambio_estado.CumplidoProveedorId = cumplido_proveedor_id
			respuesta_cambio_estado.DocumentoResponsable = body_cambio_estado.DocumentoResponsable
			respuesta_cambio_estado.CargoReponsable = body_cambio_estado.CargoResponsable
			respuesta_cambio_estado.EstadoCumplido = &estado_cumplido[0]
			return respuesta_cambio_estado, nil
		} else {
			outputError = map[string]interface{}{"funcion": "CambioEstadoCumplido", "status": "502", "mensaje": "Error al actualizar el cumplido proveedor"}
			return respuesta_cambio_estado, outputError
		}
	}

	return respuesta_cambio_estado, outputError
}


```

##  Solución errores

Se han solucionado los errores detectados al probar la función de **Cambio de Estado de Cumplido**. Ahora es posible realizar los cambios de estado sin inconvenientes. Además, se ha implementado funcionalidad adicional para manejar automáticamente algunos estados específicos:

- **Rechazado por Contratación**: Cuando el estado del cumplido cambia a "Rechazado por Contratación", se actualiza automáticamente a "Cargando Documentos". Esto permite llevar la traza de que el cumplido fue rechazado por el área de contratación y permite al supervisor subir nuevamente los archivos o corregir los errores detectados.

- **Aprobado por Contratación**: Cuando el estado del cumplido cambia a "Aprobado por Contratación", se actualiza automáticamente a "Pendiente de Revisión por Ordenador". Esto asegura que el proceso continúe de manera fluida hacia la siguiente etapa de aprobación.

- **Rechazado por Ordenador**: Cuando el estado del cumplido cambia a "Rechazado por Ordenador", se actualiza automáticamente a "Cargando Documentos" para que el supervisor pueda realizar las correcciones correspondientes.




![Image](https://github.com/user-attachments/assets/87ecef40-e214-433f-a678-2d83efd3016b)

**Comment by faidercamilo26** [comment]
# Avances en la Refactorización del MID

Se han realizado los siguientes cambios como parte del proceso de refactorización:

- **Cumplido Satisfacción:**
    - Se ha actualizado la lógica para utilizar las funciones establecidas en el proyecto.

- **Función `ObtenerInformacionContratoProveedor()`:**
    - Esta función se ha movido a la carpeta de _helpers_ para que pueda ser utilizada de manera transversal en todo el proyecto. Ahora es responsable de retornar la información necesaria para supervisores, contratación y ordenadores.

- **Cumplidos Pendientes (Equipo de Contratación):**
    - Se ha refactorizado el proceso de obtención de cumplidos pendientes. Se han eliminado funciones innecesarias, optimizando así el flujo del proyecto, que ahora funciona correctamente.

- **Cumplidos Pendientes por Aprobar (Ordenador):**
    - La lógica ha sido simplificada y se ha optimizado la eficiencia de la función. Además, se ha ajustado el código para integrar la función `ObtenerInformacionContratoProveedor()`.

- **Listado de Cumplidos Reversibles (Ordenador):**
    - Se ha refactorizado la función de listar cumplidos reversibles, garantizando su correcto funcionamiento.

## Próximos Pasos

- **Revisión de la Creación de Autorización de Pago:**
    - Queda pendiente revisar esta parte del proceso para identificar posibles mejoras o cambios en la lógica actual.



![Image](https://github.com/user-attachments/assets/1d04ff25-91c9-4244-b29a-0679207ecac0)




![Image](https://github.com/user-attachments/assets/d191525f-4e3c-48a7-8209-1d2cc4e6c065)




![Image](https://github.com/user-attachments/assets/1410bad2-9f03-43c0-a300-9ec96848777a)

**Comment by faidercamilo26** [comment]
- **Refactorización de `GenerarAutorizacionPago()`**:
  - Se refactorizó completamente la función debido a que la gestión de errores no era adecuada y dificultaba la comprensión del código.
  - Se eliminó lógica innecesaria utilizando funciones ya disponibles en los helpers.
  - La URL para buscar documentos en `documentos_crud` estaba hardcodeada en el código; ahora se maneja a través de una variable de entorno para mejorar la seguridad.
  - Se renombraron variables mal nombradas, como `response_docuementos_gestion`, para mejorar la legibilidad.
  - Se modificó el modelo utilizado en la función para retornar la respuesta. Anteriormente se llamaba `DocuementoAutorizacionPago`, ahora se llama `DocumentoAutorizacionPago` para corregir el error tipográfico.

- **Refactorización en el controlador de autorización de pago**:
  - En el controlador, se eliminó la lógica de negocio que se implementaba para realizar validaciones antes de llamar a `GenerarPdfAutorizacionPago()`.
  - Ahora, el controlador solo realiza la llamada a `GenerarAutorizacionPago()`, que internamente se encarga de utilizar `GenerarPdfAutorizacionPago()` y realizar las validaciones necesarias.

- **Modificación de la ruta para generar el cumplido de satisfacción**:
  - La ruta `supervisor/informe-satisfaccion` se cambió a `supervisor/cumplido-satisfaccion` para que la URL refleje mejor la funcionalidad a la que se accede.

- **Modificación de `GenerarPdfAutorizacionPago()`**:
  - Se actualizó la función para que utilice `encodePDF`, la misma función utilizada para codificar el cumplido de satisfacción, lo que permite reducir el código duplicado y hacer el código más reutilizable.

- **Creación del modelo `DocumentoAutorizacionPago`**:
  - Se creó este modelo para que `GenerarAutorizacionPago()` retorne un objeto de este tipo en lugar de un simple string, mejorando así la estructura y claridad del código.

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 buen trabajo.
