### ISSUE TITLE
Refactorización del mf de revisión de cumplidos proveedores - Parte III

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#128]
Se requiere realizar las refactorizaciones del mf faltantes.

**Sub Tareas**

- [ ] Realizar refactorizaciones faltantes de la issue #119 
- [ ] Realizar ajustes gráficos y de textos.

**Criterios de aceptación**

- [ ] Cambios realizados.
- [ ] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by stevencol** [comment]
Se inicia con actividad

**Comment by jcmurilloa** [comment]
Buen día, es una actividad que se debió iniciar el sprint anterior @stevencol, por favor poner el acelerador a esta tarea, culminar lo antes posible para dar comienzo a las establecidas en el sprint 19!

**Comment by stevencol** [comment]
Se corrige diseño del formulario, para hacerlo más responsivo:

Antes:
![antes](https://github.com/user-attachments/assets/ab173dcb-9b15-4a48-93c7-45e9b740c4b5)

Despues: 
![final](https://github.com/user-attachments/assets/26b16f6e-23c1-4c0d-b340-22cb06197d3d)

**Comment by stevencol** [comment]
Se modifica el archivo CSS de  componente carga-soportes  para hacerlo más responsive 


Antes: 

![antes](https://github.com/user-attachments/assets/34bfd223-1897-45c9-85d0-6bda63c02421)

despues: 
![final](https://github.com/user-attachments/assets/8a7904ee-d657-4bde-b1b1-48180811c39f)

**Comment by JuanCamiloMartinezLopez** [comment]
@stevencol Buen trabajo.
