### ISSUE TITLE
Concertar, desarrollar y levantar el acta de sesión de refinamiento con el cliente muestra múltiples firmantes

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/Cumplidos_y_certificaciones_documentacion#129]
Se requiere realizar la concertación, desarrollo y levantamiento del acta de sesión de  refinamiento con el cliente muestra múltiples firmantes

**Sub Tareas**

- [x] Concertar reunión con el cliente.
- [x] Desarrollar la reunión con el cliente.
- [x] Diligenciamiento y aprobación del formato de historias de usuario o Mockup por parte del cliente (si aplica).
- [x] Proyectar acta de la reunión.
- [x] Recolectar las firmas correspondientes.

**Criterios de aceptación**

- [x] Acta revisada por el líder de proyecto.
- [x] Acta firmada por las partes con anexo de historias de usuario o mockup.
- [x] Acta y anexos documentados.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se ha podido agendar la reunión para el 2/09/2024 

[enlace reunión](https://teams.microsoft.com/l/meetup-join/19%3ameeting_NDcyODliNTctZWIzMy00NTliLWE4ODYtOGRlYzU2ODMxMmJi%40thread.v2/0?context=%7b%22Tid%22%3a%22d51388ef-6ab0-4363-9f94-d56644a45970%22%2c%22Oid%22%3a%221dd8bdce-0185-41b4-8caa-01da7e5506b2%22%7d)

**Comment by mantnicot** [comment]
Se ha creado el acta correspondiente 

[acta sin firmas](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EU0GwpDVV01NkWoxQvB8f8cB_5bTALP5J7buQZlAHDh_Cw?e=rBi0wC)

**Comment by jcmurilloa** [comment]
Acta revisada y aprobada para recolección de firmas.

**Comment by mantnicot** [comment]
Se ha recolectado todas las firmas

[Acta firmada](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EXaKrwqK2MxNmDAaTIpKNykBlGrQKrQBnvMeVKK6sLw_8Q?e=1S15XS)

**Comment by jcmurilloa** [comment]
Muy buen trabajo @mantnicot!
