### ISSUE TITLE
Concertar, desarrollar y levantar acta de mesa de trabajo con cliente job acta de inicio

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/Cumplidos_y_certificaciones_documentacion#13]
Se requiere realizar el 

**Sub Tareas**

- [x] Concertar reunión exploratoria con el cliente
- [x] Desarrollar la reunión exploratoria
- [x] Proyectar acta de la reunión

**Criterios de aceptación**

- [x] Acta revisada por el líder de proyecto
- [x] Acta firmada por las partes

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

---
Se requiere realizar el 

**Sub Tareas**

- [ ] Concertar reunión exploratoria con el cliente
- [ ] Desarrollar la reunión exploratoria
- [ ] Proyectar acta de la reunión

**Criterios de aceptación**

- [ ] Acta revisada por el líder de proyecto
- [ ] Acta firmada por las partes

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [ ] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [ ] No tiene bloqueos que impidan su ejecución.
- [ ] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico/SoSM.
- [ ] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se ha recogido todas las firmas gracias a al gestión del gerente del proyecto , muchas gracias.

[Acta firmada](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EeofhFg3HL9Ig-nwhPnDc4kBNuLSe_s8YeyH2TyFQAx6-w?e=vtFdRd)
