### ISSUE TITLE
Integracion del mf revision_cumplidos_proveedores - Parte I

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#130]
Se requiere realizar una reunión para realizar la integración de las diferentes ramas del mf de revision_cumplidos_proveedores.

**Sub Tareas**

- [x] Realizar el merge de forma exitosa de las diferentes ramas.
- [x] Dejar en develop una versión sin errores del mf.
- [x] Solucionar los posibles errores que surgan.

**Criterios de aceptación**

- [ ] mf estable en develop.
- [x] issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
Se llevó a cabo la primera reunión para la integración del microcliente del sistema de cumplido proveedores. Sin embargo, debido a limitaciones de tiempo, no fue posible finalizar completamente la sesión. Se ha programado una segunda reunión para hoy a las 10:00 a.m. para continuar con este proceso. Se adjunta el link de la reunión.

[Reunión  Viernes 30/09/2024](https://teams.microsoft.com/l/meetup-join/19%3ameeting_YzU3MjI3MTEtNjllOC00ZTA5LThjMjEtYTljOWFkYjZhOGQ3%40thread.v2/0?context=%7b%22Tid%22%3a%22d51388ef-6ab0-4363-9f94-d56644a45970%22%2c%22Oid%22%3a%22e79ddc6c-1555-42d8-83fe-5a759905daaf%22%7d)

**Comment by stevencol** [comment]
Se realizó una reunión con el fin de integrar los nuevos cambios e implementar las modificaciones necesarias para la firma electrónica. La idea original era integrar el micro cliente, pero debido a los cambios realizados, es necesario integrar primero el MID. Se intentaron solucionar los problemas surgidos en la integración, pero por motivos de tiempo no se logró realizar las correcciones necesarias, por lo que la reunión se pospuso
[Reunión Lunes  2/09/2024](https://udistritaleduco-my.sharepoint.com/personal/juacmartinezl_udistrital_edu_co/_layouts/15/stream.aspx?id=%2Fpersonal%2Fjuacmartinezl%5Fudistrital%5Fedu%5Fco%2FDocuments%2FGrabaciones%2FIntegracion%20del%20mf%20revision%5Fcumplidos%5Fproveedores%20%2D%20Parte%20II%2D20240902%5F100811%2DGrabaci%C3%B3n%20de%20la%20reuni%C3%B3n%2Emp4&referrer=StreamWebApp%2EWeb&referrerScenario=AddressBarCopied%2Eview%2E9a7d3784%2De592%2D4964%2D8030%2D6019b477f4e9)

**Comment by faidercamilo26** [comment]
Se realiza la reunión para estabilizar el *mid*.
- Se deja una versión del *mid* totalmente funcional en la rama `develop`.
- Se cambia la lógica de algunos modelos que se estaban definiendo directamente en los controladores; ahora se definen en la carpeta de `models` y en los controladores solo se utilizan.
- Se manejan errores en una función que faltaba.
- Se implementa lógica en los cambios de estados para que no sea posible pasar de un estado a otro sin ninguna restricción.

**Comment by stevencol** [comment]
El día 6 de septiembre Se trabajo en la integración
-Se Soluciono El problema de CORS
-Se modifico El cuerpo de la petición para cambiar el estado 
-Se modificaron nombres del formulario
-Se nidificaron Algunos modelos para forma las peticiones
https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/issues/128

**Comment by JuanCamiloMartinezLopez** [comment]
@stevencol @faidercamilo26 Buen trabajo.
