### ISSUE TITLE
Implementar notificaciones por correo

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#131]
Se requiere realizar la implementación del envió de notificaciones por correo con base en las plantillas creadas #126 

**Sub Tareas**

- [x] Implementar en el flujo (cambios de estado) las notificaciones por correo.
- [x] Utilizar en el endpoint:
` POST http://pruebasapi.intranetoas.udistrital.edu.co:8527/v1/enviar_templated_email`
```JSON
{
    "Source": {{remitente}},
    "Template": {{nombre plantilla}},
    "Destinations": {
        "Destination": {
            "BccAddresses": [],
            "CcAddresses": [],
            "ToAddresses": [
                {{destinatario}}
            ]
        },
        "ReplacementTemplateData": {
           {{json data para reemplazar }}
        },
        "Attachments": []
    },
    "DefaultTemplateData": {
        {{json data default }}
    }
}
```
- [x] Consultar la obtención del correo destinatario según los diferentes casos.

**Criterios de aceptación**

- [ ] Notificaciones por correo implementadas.
- [ ] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
## :triangular_flag_on_post: **Implementación Notificaciones por correo**  :triangular_flag_on_post:

### Variables de Entorno
- Se crea una variable de entorno llamada UrlAutenticacionMid la cual va a contener la Url de autenticación api mid para realizar la busqueda del correo electronico del responsable.
- Se crea la variable de entorno UrlNotificacionesMid la cual va a contener la URL para realizar el post al sistema de notificaciones para enviar el correo electronico.
- Se crea la variable de entorno UrlRevisionCumplidosProveedoresCliente la cual va a contener la URL del sistema Revisión Cumplidos Proveedores para redirigir a la api cuando se haga click en el botón de acceder al sistema.

### Modelos 

- Se crea el modelo AutenticacionPersona() para contener la respuesta de las consultas realizadas al api de autenticacion.
- Se crean los modelos NotificacionEmail, DestinationItem, Destination, TemplateData usados para contruir el json usado en el body del post al api de notificaciones.

### Función

Se crea la función EnviarNotificacionCambioEstado() La cual es la encargada de enviar las notificaciones por correo electrónico de los cambios de estado.


### Problemas

Al usar la funcion normal para realizar los post que es la de SendJson() al hacer una petición post al api de notificaciones aparece el siguiente error 


![Image](https://github.com/user-attachments/assets/a452efd0-5161-43d8-b384-487bd0e588f7)


Para solucionar este error se crea la siguiente funcion, con la cual si se puede hacer la peticion pero el problema esque esto ignora las validaciones TLS/SSL, lo cual no es muy seguro:

```golang

func SendJson2(url string, trequest string, target interface{}, datajson interface{}) error {
	// Crear un buffer para el cuerpo de la solicitud
	b := new(bytes.Buffer)
	if datajson != nil {
		if err := json.NewEncoder(b).Encode(datajson); err != nil {
			beego.Error(err)
		}
	}

	// Configurar el transporte del cliente para que ignore las validaciones de certificado
	tr := &http.Transport{
		TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
	}
	client := &http.Client{Transport: tr}

	// Crear la solicitud HTTP
	req, err := http.NewRequest(trequest, url, b)
	if err != nil {
		beego.Error("error creando la solicitud", err)
		return err
	}
	req.Header.Set("Content-Type", "application/json")

	// Enviar la solicitud
	r, err := client.Do(req)
	if err != nil {
		beego.Error("error", err)
		return err
	}
	defer func() {
		if err := r.Body.Close(); err != nil {
			beego.Error(err)
		}
	}()

	// Decodificar la respuesta en la variable target
	return json.NewDecoder(r.Body).Decode(target)
}

``` 

- Cuando se envia un correo a outlook en el computador no se carga bien el botón de Acceder al sistema 


![Image](https://github.com/user-attachments/assets/25edf5f4-47c7-4b45-9fdd-000612e04251)

Sin embargo, al visualizar el correo de outlook en un dispositivo móvil el botón carga correctamente y el link funciona para redirigir.




![Image](https://github.com/user-attachments/assets/890c8c10-4a4b-4b9f-bfa8-a185bf87cc2a)


Al enviar el correo a gmail tanto en dispositivos moviles como en computador carga correctamente el boton y la informacion del correo.

 



![Image](https://github.com/user-attachments/assets/cca69528-eca0-4992-8394-3fb2a44b879d)

**Comment by faidercamilo26** [comment]
**Se ha completado la implementación de las notificaciones por correo electrónico cuando se cambia el estado de un cumplido.** Se han gestionado correctamente los casos en los que el equipo de contratación es el responsable anterior o nuevo del cumplido. Se ha incorporado el envío de notificaciones tanto al correo del equipo de contratación como al responsable correspondiente, utilizando la dirección de correo configurada para el envío de estas notificaciones.

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 Buen trabajo.
