### ISSUE TITLE
Generar el seguimiento a la aprobación de los formatos por parte del SIGUD

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/Cumplidos_y_certificaciones_documentacion#133]
Se requiere realizar el 

**Sub Tareas**

- [ ] Aprobación formato evaluación proveedores
- [x] Aprobación formato orden de pago
- [x] Aprobación formato cumplido y seguimiento

**Criterios de aceptación**

- [ ] Formato evaluación aprobado
- [x] Formato orden de pago aprobado
- [x] Formato cumplido y seguimeinto aprobado

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by mantnicot** [comment]
Se ha escrito a Jhon del Sigud para pedir avances de estos formatos



![Image](https://github.com/user-attachments/assets/ff0f88f1-1971-4fca-b50e-c3f9b8b06a75)

**Comment by mantnicot** [comment]
Se ha podido charla con el sigud con respecto a los formatos de cumplidos y los apartados de firmas en la parte inferior 
Pero al no tener un un cambio en el formato solo en el firmado , los formatos de informe de seguimiento y la autorización de giro.

Faltaría la actualización para el formato de evaluación proveedores

**Comment by mantnicot** [comment]
![image](https://github.com/user-attachments/assets/4d684cca-5b4c-4bef-85dd-f5fb968ee79d)

![image](https://github.com/user-attachments/assets/e874f07c-edb4-4672-9060-5ceb34cd0fee)


Se ha intentado comprender por que no hay respuesta de parte de los formatos , se seguira preguntando

**Comment by jcmurilloa** [comment]
Podremos desde las respectivas áreas responsables de los formatos, generar una comunicación vía correo electrónico indagando sobre el estado del trámite en el SIGUD?

**Comment by mantnicot** [comment]
![Image](https://github.com/user-attachments/assets/d4be8fcd-88ff-4f69-b1e8-e8d7a25f4bd5)


Se ha intentado seguir teniendo comunicación pero se ha dado respuesta para este semana

**Comment by mantnicot** [comment]
Ya que no se ha dado respuesta del formato se establece cambiar el formato .

Cambiando el encabezado del formato 

![Image](https://github.com/user-attachments/assets/0f98bc14-4960-43e6-bf81-95f31db96d64)

Dejando el formato ya aprobado y enviado por el cliente

![Image](https://github.com/user-attachments/assets/82496d3c-95b8-497c-b976-2eb58f20adf1)

**Comment by jcmurilloa** [comment]
Trabajaremos bajo este formato establecido por el cliente, y hasta no contar con la aprobación del SIGUD, no referenciaremos su respectiva identificación.
