### ISSUE TITLE
Concertar, desarrollar y levabtar acta de sesión de muestra sistema cumplidos proveedores

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/Cumplidos_y_certificaciones_documentacion#134]
Se requiere realizar la concertación, desarrollo y levantamiento del acta de sesión de muestra sistema cumplidos proveedores con el cliente

**Sub Tareas**

- [x] Concertar reunión con el cliente.
- [x] Desarrollar la reunión con el cliente.
- [x] Diligenciamiento y aprobación del formato de historias de usuario o Mockup por parte del cliente (si aplica).
- [x] Proyectar acta de la reunión.
- [x] Recolectar las firmas correspondientes.

**Criterios de aceptación**

- [x] Acta revisada por el líder de proyecto.
- [x] Acta firmada por las partes con anexo de historias de usuario o mockup.
- [x] Acta y anexos documentados.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [X] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [X] No tiene bloqueos que impidan su ejecución.
- [X] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Por problemas en el desarrollo se pospone la presentación de muestra del sistema de cumplidos al cliente , se espera para la otra semana realizar la reunión

**Comment by jcmurilloa** [comment]
Esperemos no pasar del sprint que inicia el día de hoy para sacar adelante esta presentación.

**Comment by mantnicot** [comment]
Se ha establecido la reunión para el 13/09/2024 a las 12 pm 

[enlace reunión](https://teams.microsoft.com/l/meetup-join/19%3ameeting_YTg0M2IzYjYtNjVhMC00MTZkLWI4YzAtZDcwNmFiYTMyYjc3%40thread.v2/0?context=%7b%22Tid%22%3a%22d51388ef-6ab0-4363-9f94-d56644a45970%22%2c%22Oid%22%3a%22b989c328-89fa-4486-abfe-df75fdd723ba%22%7d)

**Comment by mantnicot** [comment]
Se ha realizado la reunión y se adjunta el acta correpondiente

[Acta sin firmas](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EQwxi-h1-15Akb67Vx5cFr0BdCNwDsH-tu40N-BbbpWqow?e=UeXxH2)

**Comment by jcmurilloa** [comment]
Acta revisada y aprobada para recolección de firmas.

**Comment by mantnicot** [comment]
Se ha recolectado las firmas

[Acta firmada](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EUltp3DH4YZKmmLSGWOYtvIBdSoib5oeaC8tnk6N0oY9BA?e=kSzudc)

**Comment by jcmurilloa** [comment]
Excelente trabajo @mantnicot!
