### ISSUE TITLE
Crear vista para la consulta de históricos de cumplidos proveedores

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#135]
Se requiere realizar la creacion de la vista del [mockup](https://udistritaleduco-my.sharepoint.com/:i:/g/personal/computo_udistrital_edu_co/EbkeBG_w0vZPot1yNwqNq_wBT3d3zRVu4z75TSdS48pSgw?e=pldjpj) 

**Sub Tareas**

- [ ] Realizar vista para el módulo de históricos.

**Criterios de aceptación**

- [ ] Vista creada.
- [ ] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by stevencol** [comment]
Se inicia con actividad

**Comment by stevencol** [comment]
Se está trabajando para que desde el inicio el diseño sea responsivo.

* Temporalmente se están usando bordes para identificar la posición de los inputs y selects.

![grid](https://github.com/user-attachments/assets/af57fd32-5238-4633-adf6-06cdd8e16f06)

**Comment by stevencol** [comment]
Se avanza en la actividad,  da por terminado la parte del formulario,
* Lista años del 2017 al  actual automáticamente
* mes trae todos los meses desde una función, 
* Vigencia utiliza la misma lista de Años
* Funcionalidad del bonton agregada
* El modal de espera no hace nada es simplemente para su demostración 
* 
![grid](https://github.com/user-attachments/assets/3a325c4c-5e98-46a7-b0b8-94d8399a2dc5)

**Comment by stevencol** [comment]
Se continúa con el proceso de creación de la vista, por lo que se crea una tabla con diseño responsivo. Se agrega paginación para su implementación posterior y se incorporan algunos mensajes según la lógica. Aún, temporalmente, Los mensajes y  datos  son solo demostrativos.
![final](https://github.com/user-attachments/assets/cced25f7-4973-4b0c-8925-dad3da004f48)

**Comment by stevencol** [comment]
Se completa la creación de la vista para la consulta de históricos de cumplidos de proveedores.

**Comment by stevencol** [comment]
![final](https://github.com/user-attachments/assets/7c1abdad-60fc-44bf-9dc0-57951ea18768)

**Comment by JuanCamiloMartinezLopez** [comment]
@stevencol Buen trabajo.
