### ISSUE TITLE
Desarrollar el endpoint de consulta de los diferentes estados para un cumplido proveedor.

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#138]
Se requiere realizar un endpoint para la consulta del flujo de cambios de estados para un determinado cumplido tomando como ejemplo https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/issues/2

**Sub Tareas**

- [x] Crear un endpoint (controllador, servicios, modelos, etc) para la consulta del flujo de estados.

**Criterios de aceptación**

- [x] Endpoint desarrollado.
- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by stevencol** [comment]
Se crea modelo pare representar respuesta:

``` Go
package models

type HistoricoCumplido struct {
	NombreResponsable string `json:"nombreResponsable"`
	Estado            string `json:"estado"`
	Fecha             string `json:"fecha"`
	Cargo             string `json:"cargo"`
}

```

**Comment by stevencol** [comment]
Se avanza con creación de servicie encargado de realizar la petición  pero por alguna razón no es reconocido:

``` Go
func historicoEstado(cumplido_proveedor_id int) (historico []models.HistoricoCumplido, outputError error) {
	defer func() {
		if err := recover(); err != nil {
			outputError = fmt.Errorf("%v", err)
			panic(outputError)
		}
	}()

	var respuesta_histricos []models.CambioEstadoCumplido
	var respuesta_peticion map[string]interface{}

	if response, err := helpers.GetJsonTest(beego.AppConfig.String("UrlCrudRevisionCumplidosProveedores")+"/cambio_estado_cumplido/?query=CumplidoProveedorId.Id:"+strconv.Itoa(cumplido_proveedor_id)+"&sortby=FechaCreacion&order=desc", &respuesta_peticion); err == nil && response == 200 {
		data := respuesta_peticion["Data"].([]interface{})
		if len(data[0].(map[string]interface{})) == 0 {
			outputError = nil
			return
		}
		helpers.LimpiezaRespuestaRefactor(respuesta_peticion, &respuesta_histricos)

		for _, historico_estado := range respuesta_histricos {
			if response , err helpers.GetJsonTest()
		}
	} else {
		outputError = fmt.Errorf("Error al consultar el historico del cumplido")
		return historico, outputError
	}
	return historico, outputError

}

```
![image](https://github.com/user-attachments/assets/da5e89fc-4782-4df1-99ae-f189d9d203ed)

**Comment by stevencol** [comment]
Se presentaron algunos inconvenientes con la tarea debido a que el proyecto no reconocía los archivos locales. Se encontró una solución y se renombró la carpeta contenedora de revision_cumplido_prov_mid a revision_cumplidos_proveedores_mid.

- La tarea se completa correctamente 
![final](https://github.com/user-attachments/assets/a16c6a77-4835-47ce-aebb-8b3003888222)

**Comment by JuanCamiloMartinezLopez** [comment]
@stevencol Buen trabajo.
