### ISSUE TITLE
Concertar, desarrollar y levantar acta de sesión de requerimientos cliente evaluación proveedores

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/Cumplidos_y_certificaciones_documentacion#140]
Se requiere realizar la concertación, desarrollo y levantamiento del acta de sesión de requerimientos con el cliente evaluación proveedores

**Sub Tareas**

- [x] Concertar reunión con el cliente.
- [x] Desarrollar la reunión con el cliente.
- [x] Diligenciamiento y aprobación del formato de historias de usuario o Mockup por parte del cliente (si aplica).
- [x] Proyectar acta de la reunión.
- [x] Recolectar las firmas correspondientes.

**Criterios de aceptación**

- [x] Acta revisada por el líder de proyecto.
- [x] Acta firmada por las partes con anexo de historias de usuario o mockup.
- [x] Acta y anexos documentados.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico/SoSM.
- [ ] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se queda a espera de confirmación de parte de la otra persona que es la cliente

![Image](https://github.com/user-attachments/assets/b5f32b1d-bb0e-460b-8686-9cac6b8bd701)

**Comment by mantnicot** [comment]
Se ha podido asignar la reunión para 12/09/2024 a las 10:00 am

[link reunión](https://teams.microsoft.com/l/meetup-join/19%3ameeting_ODg1MmIyNjQtNTllNS00OTZkLWE5OGEtYzE1MmEwNTFkMTBl%40thread.v2/0?context=%7b%22Tid%22%3a%22d51388ef-6ab0-4363-9f94-d56644a45970%22%2c%22Oid%22%3a%22b989c328-89fa-4486-abfe-df75fdd723ba%22%7d)

**Comment by mantnicot** [comment]
Se adjunta el acta correspondiente a la reunión

[acta sin firmas](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EQyQ-Tx-BnpItCAtlhnbX1sB6vabjcsDllztaUHrMhlfUg?e=Yhx1W6)

**Comment by jcmurilloa** [comment]
Acta revisada y aprobada para el inicio de recolección de firmas.

**Comment by mantnicot** [comment]
Se adjunta acta con firmada
[acta firmada](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EfKJ8TUwIzJLlXYj3Tyyr5IBMIArK_ZDPEOJj7uGzdgf1Q?e=RNJsem)

**Comment by jcmurilloa** [comment]
Excelente trabajo @mantnicot
