### ISSUE TITLE
Concertar y desarrollar la sesión sobre ERP

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/Cumplidos_y_certificaciones_documentacion#141]
Se requiere realizar la concertación, desarrollo de sesión de requerimientos con responsable ERP

**Sub Tareas**

- [x] Concertar reunión con el cliente.
- [x] Desarrollar la reunión con el cliente.
- [x] Diligenciamiento y aprobación del formato de historias de usuario o Mockup por parte del cliente (si aplica).
- [x] Recolectar las firmas correspondientes.

**Criterios de aceptación**

- [x] Sesión grabada en teams
- [x] Documentación relacionada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se ha agendado la reunión para el día 12/09/2024 a las 9 am 

[link de reunión](https://teams.microsoft.com/l/meetup-join/19%3ameeting_MWM0ZDc1NmEtMDczMi00ZGRjLWIyZGQtMTYzMDIxYjQyNjUz%40thread.v2/0?context=%7b%22Tid%22%3a%22d51388ef-6ab0-4363-9f94-d56644a45970%22%2c%22Oid%22%3a%221dd8bdce-0185-41b4-8caa-01da7e5506b2%22%7d)

**Comment by mantnicot** [comment]
Se realizo la reunión la persona encargada y se llego al compromiso de que se enviara un reporte de necesidades ( almacén ) para comprender más del tema y poder generar una petición de servicio directamente a infotic.

EL objetivo de la petición es que con base a la necesidad de obtener los items de estas necesidades

**Comment by jcmurilloa** [comment]
Buen trabajo, se dejará alguna evidencia sobre la sesión? A partir de estos resultados se proyectará el siguiente paso.

**Comment by jcmurilloa** [comment]
Se continuá el desarrollo de esta línea en la issue #157
