### ISSUE TITLE
Integracion del mf revision_cumplidos_proveedores - Parte II

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#142]
Se requiere continuar con el proceso de integración del mf de revision_cumplido_prov 

**Sub Tareas**

- [x] Realizar el merge de forma exitosa de las diferentes ramas.
- [x] Dejar en develop una versión sin errores del mf.
- [x] Solucionar los posibles errores que surjan.

**Criterios de aceptación**

- [x] mf estable.
- [x] issue documentado.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by stevencol** [comment]
El día 10 de septiembre, se llevó a cabo una reunión con @JuanCamiloMartinezLopez y @faidercamilo26 para integrar MF revision_cumplidos_proveedores. Durante la reunión, se realizaron varias correcciones en MF y MID, y se identificaron las siguientes mejoras:

- Validación en el manejo de errores
- Validación de formularios
- Revisar modal de soportes(revisar responsive de steven feature/issue-135)
- implementar transacción 
- Actualización de las tablas después de un cambio de estado
- Revisar modelos (Posible cambio de clases a interfaces)
-
Reunion: [Link](https://teams.microsoft.com/l/meetup-join/19%3ameeting_OGRkY2FhNWItMTJjNS00MjVlLWI0NTgtNTMwMTA4Nzg2NzJk%40thread.v2/0?context=%7b%22Tid%22%3a%22d51388ef-6ab0-4363-9f94-d56644a45970%22%2c%22Oid%22%3a%22e79ddc6c-1555-42d8-83fe-5a759905daaf%22%7d)

**Comment by faidercamilo26** [comment]
Se realiza la reunion para ajustar el microcliente y dejarlo estable, se hace una verificacion general de todo el flujo de la aplicacion mientras se resolvian los problemas que iban surgiendo, con las funcionalidades, los estilos, etc. Se modifica la logica de las funciones que no estaban realizando la funcion correspondiente, se ajustaron los estilos de tablas y otros componenetes para que se rigieran a los estandares de  la Oati y del proyecto.

El día viernes se realiza la presentacion de un primer avance del proyecto donde se muestran todos los cambios realizados en la cual en terminos generales salio bien.

Reunion: [estabilizacion microcliente](https://teams.microsoft.com/l/meetup-join/19%3ameeting_ZTRhMDQwOGYtYWU4Zi00MDhhLTkyM2YtNDQ0YTJlMDA2NGNl%40thread.v2/0?context=%7b%22Tid%22%3a%22d51388ef-6ab0-4363-9f94-d56644a45970%22%2c%22Oid%22%3a%22e79ddc6c-1555-42d8-83fe-5a759905daaf%22%7d)
Reunion muestra al cliente: [Primera reunion muestra de avances](https://udistritaleduco-my.sharepoint.com/personal/computo_udistrital_edu_co/_layouts/15/stream.aspx?id=%2Fpersonal%2Fcomputo%5Fudistrital%5Fedu%5Fco%2FDocuments%2FGrabaciones%2FCumplidos%20proveedores%20%2D%20Primera%20muestra%20cliente%2D20240913%5F120150%2DGrabaci%C3%B3n%20de%20la%20reuni%C3%B3n%2Emp4&referrer=StreamWebApp%2EWeb&referrerScenario=AddressBarCopied%2Eview%2E3f10ee22%2Db9e0%2D4e15%2D83bb%2D60176193f8cb)

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 y @stevencol Buen trabajo.
