### ISSUE TITLE
Desarrollar el endpoint de consulta de cumplidos para el módulo de históricos cumplidos proveedores - Parte II

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#143]
Se requiere continuar con el desarrollo del endpoint desarrollado en el issue #137 

**Sub Tareas**

- [x] Agregar filtro por tipo de contrato.
- [x] Filtro por proveedor_id (id de informacion_proveedores)
- [x] Revisar posibles cambios y otros filtros necesarios.
- [x] Revisar el código para que sea lo mas optimo posible.
- [x] Revisar el manejo de errores

**Criterios de aceptación**

- [x] Codigo de la función de filtro.
- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
## :triangular_flag_on_post: **Historico cumplidos**  :triangular_flag_on_post:

Se realizó la corrección en el filtro de proveedores, de manera que ahora recibe el `id_proveedor` en lugar del nombre del proveedor, mejorando así la eficiencia del filtro. Además, se añadió un filtro para el tipo de contrato.

Se realizaron modificaciones en el modelo, específicamente, se cambió el nombre del atributo `FechaAprobacion` por `FechaCambioEstado` y se agregó el campo `TipoContrato`, con el fin de mostrar esta información en la tabla, dado que es un dato relevante.

![Image](https://github.com/user-attachments/assets/76c386a1-55b2-4d29-814a-c330e96e84de)

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 Buen trabajo.
