### ISSUE TITLE
Desarrollar el endpoint de consulta de cumplidos para el módulo de reversión cumplidos aprobados proveedores

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#144]
Se requiere terminar el desarrollo de la función para consultar cumplidos de proveedores revertibles por ordenador

**Sub Tareas**

- [x] Tener en cuenta el posible cambio de ordenador
- [x] así como validar si no tiene orden de pago
- [x] Revisar que este dentro del periodo de 15 desde que se aprobó.

**Criterios de aceptación**

- [x] Endpoint funcionando.
- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
## :triangular_flag_on_post: **Listado de reversion cumplidos**  :triangular_flag_on_post:

Se realiza una consulta SQL para la posible creacion de un servicio JBPM el cual su finalidad seria buscar con un numero de documento de ordenador, todos los ordenadores que tengan el mismo rol_id y retornar sus numeros de documento, buscar todos los cumplidos que esten en estado aprobado ordenador en los ultimos 15 días y cuyo responsable sea alguno de los ordenadores retornados anteriormente. Sin embargo, este servicio presenta una imposibilidad puesto que para dichas consultas se usan dos bases de datos distintas, udistrital y udistrital_administrativa.

```SQL

SELECT * 
FROM udistrital_administrativa.revision_cumplidos_proveedores.cambio_estado_cumplido
WHERE documento_responsable in (
    SELECT documento 
    FROM udistrital.argo.ordenadores 
    WHERE rol_id = (
		SELECT rol_id
		FROM udistrital.argo.ordenadores
		WHERE documento = ?
	)
)
AND fecha_creacion >= (CURRENT_DATE - INTERVAL '15 days')
AND estado_cumplido = 7;

```

### Posibles soluciones 

- Se puede crear solo un servicio JBPM que dado un numero de documento de ordenador, retorne los datos de los ordenadores anteriores que tengan el mismo rol id, esto se puede lograr con la siguiente consulta SQL.

```SQL

SELECT documento 
FROM argo.ordenadores 
WHERE id in (
    SELECT id
    FROM argo.ordenadores
    WHERE documento = 79657603 AND (now() - ('15 DAY')::INTERVAL Between fecha_inicio and fecha_fin) AND (now() Between fecha_inicio and fecha_fin)
) 
```

- La otra posible solucion seria agregar al modelo del crud de amazon api el campo rol_id para que toda la logica se pueda realizar directamente desde el mid de revision cumplidos proveedores.

**Comment by faidercamilo26** [comment]
## :no_entry_sign:  **Inconvenientes**  :no_entry_sign:

Durante el transcurso de la semana debido a la primera presentacion al cliente se estuvo trabajando en solucionar inconvenientes que se estaban presentando en el microcliente a nivel de funcionalidad y de vistas, debido a las varias reuniones y para estabilizar el microclientes y los ajustes pertinentes que se tenian que realizar no me fue posible avanzar al 100% en el desarollo de esta tarea, me disponia a trabajar en esto el fin de semana pero el inconveniente es que en el modelo que retorna los datos de la tabla ```argo.ordenadores``` no retorna el campo ```rol_id``` el cual es indispensable para manejar el caso cuando haya un cambio de ordenador, por el momento ya se tiene el codigo disponible en el mid para listar los cumplidos reversibles de cada ordenador sin tener en cuenta si hubo un cambio de ordenador. Para manejar esta parte es indispensable o crear un servicio JBPM o modificar el modelo de Administrativa Amazon Api para que esta tabla retorne el campo ```rol_id``` lo cual no es posible desarollarlo el fin de semana, puesto que se necesita autorizaciones y/o permisos manejados por otras areas. Sin embargo, en la issue ya se encuentra documentado el avance en el desarollo del codigo SQL de un posible servicio JBPM.

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 Buen trabajo.
