### ISSUE TITLE
Ajustes modals mf revision_cumplido_proveedores

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#146]
Se requiere realizar correcciones graficas para los modales de la generales del mf de revision_cumplidos_proveedores

**Sub Tareas**

- [x] Revisar el css de los modales
- [x] Ajustar y mejorar la presentación del mf

**Criterios de aceptación**

- [x] modals ajustados
- [x] issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by stevencol** [comment]
Se comienza con al actividad

**Comment by stevencol** [comment]
Se inicia por hacer responsive el componente principal
![final](https://github.com/user-attachments/assets/ee29925f-2d92-4eb8-ab18-b4afb3077ef5)

**Comment by stevencol** [comment]
Se termina modificación del Modal cargar soporte haciéndolo más responsivo
![final](https://github.com/user-attachments/assets/cdd98f82-7f4c-4d18-bc0c-e0e5e67f88c5)

De paso se modifica como se muestra la información del supervisor 
![image](https://github.com/user-attachments/assets/fb85af0e-15ca-4658-822a-2ab863fb0997)

**Comment by JuanCamiloMartinezLopez** [comment]
@stevencol Buen trabajo.
