### ISSUE TITLE
Revisión de generación de documentos en mid desplegado.

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#148]
Se requiere revisar la generación de documentos en pdf en el mid de revisión cumplido proveedores desplegado en pruebas

**Sub Tareas**

- [x] Revisar versiones de go, y otras herramientas, así como otros posibles errores
- [x] Solucionar el error al generar el base64

**Criterios de aceptación**

- [x] Investigación de posibles errores.
- [x] Solución del problema.
- [x] Issue documentado.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
Se evalua el motivo por el cual no se pueden crear archivos en el mid desplegado, tanto de cumplido satisfaccion como las autorizaciones de pago puesto que siempre nos da un error de tipo 500, exactamente: 
``` json
{
    "Success": false,
    "Status": 500,
    "Message": "Error service cumplidos_proveedores_mid: An internal server error occurred. Request Info: URL: /v1/supervisor/cumplido-satisfaccion, Method: POST Time: 2024-09-17T16:11:56Z",
    "Data": null
}
```

- Se valida que la version en local y en el desplegado sean las mismas.
- Se valida que las variables de entorno que se estan utilizando no tengan diferencias.
- Se realizan pruebas y debuggin en local pero esta funcionando correctamente la generacion de documentos y se contrasta minuciosamente este codigo con el que esta desplegado pero no hay diferenecias.

**Comment by faidercamilo26** [comment]
Se revisa con lider tecnico la consola del mid que esta desplegado se realiza el cambio de la libreria de gofpdf, se usa ```github.com/phpdave11/gofpdf``` ahora el proyecto no retorna un 500 ahora retorna 200 pero no esta encriptando y retornando el documento pero no se puede identificar la causa de este error.

```Json
{
    "Success": true,
    "Status": 200,
    "Message": "Solicitud exitosa",
    "Data": {
        "NombreArchivo": "CumplidoSatisfaccion_CBWAGENCIASAS_2026_2023",
        "NombreResponsable": "DAZA CORREDOR ALEJANDRO PAOLO",
        "CargoResponsable": "JEFE DE OFICINA ASESORA DE TECNOLOGÍAS E INFORMACIÓN",
        "DescripcionDocumento": "Autorización de pago para el cumplido 2026 de 2023 con actividades compredidas entre 2024-09-01T05:00:00.000Z al 2024-09-13T05:00:00.000Z",
        "Archivo": ""
    }
}
```

![Image](https://github.com/user-attachments/assets/396bc9b4-2d2e-480e-91a0-9e9281222a31)

**Comment by faidercamilo26** [comment]
Se realizan impresiones de prueba para que en la consola del proyecto desplegado nos indique por medio de estas en que parte se esta rompiendo o esta fallando el codigo, sin embargo, aunque en local aparecen las impresiones cuando se desplega el codigo estas impresiones no se estan realizando, es como si estuviera fallando todo el metodo, no es posible replicar el error que esta apareciendo en local, por eso no se puede finalizar esta funcion y se le escribe a infraestructura para intentar soluciona este inconveniente.

## Impresiones en consola local

![Image](https://github.com/user-attachments/assets/82c1a590-3928-45e5-9de9-c0eb3c629bbf)

## Consola proyecto desplegado

![Image](https://github.com/user-attachments/assets/914b88a7-53db-444b-b730-adbc9c5c9ddb)

**Comment by faidercamilo26** [comment]
El día de ayer en la reunion que se tuvo con el equipo tecnico se puedo notar que el error se podia estar debiendo a configuraciones en el documento Dockerfile, se evidencia que no se estaba importando la carpeta de static que es la que contiene los logos de la universidad y del sigup, por lo cual no se estaba pudiendo crear el documento, mi lider tecnico que es el que se percato de este inconveniente corrige agrega esta parte al documento y funciona correctamente el mid desplegado, por lo que se soluciona este inconveniente y se da por terminada la issue.

![Image](https://github.com/user-attachments/assets/6050cbb9-1e36-4a00-8afa-db6217c7f302)

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 Buen trabajo.
