### ISSUE TITLE
Ajuste formulario de cumplido a satisfacción para mf revision_cumplido_prov

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#149]
Se requiere realizar la revisión del correcto funcionamiento de la vista para la generación de cumpido a satisfaccion con todas sus funcionalidades.

**Sub Tareas**

- [x] Revisar el correcto funcionamiento de la vista de generación del cumplido a satisfacción.

**Criterios de aceptación**

- [x] Correcto funcionamiento de la vista.
- [x] Issue documentado.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by stevencol** [comment]
Se restaura funcionalidad del guardar del formulario

**Comment by stevencol** [comment]
1- carga información Guarda anteriormente 
 
![formulario1](https://github.com/user-attachments/assets/0c63f253-5439-4fcd-9097-3c9947e1b196)

**Comment by stevencol** [comment]
- Se soluciona el error al consultar el tipo de cuenta.

Se corrige el problema que causaba que no se cargara el tipo de cuenta al seleccionar el banco.

![formulario1](https://github.com/user-attachments/assets/a44fc1d0-8dc7-4710-9076-570fe76fcd4d)

**Comment by stevencol** [comment]
2 -Ya se carga la información bancaria desde la sección de 'Información del Contrato'. Si el formulario es nuevo, se cargará desde ahí; si no es nuevo, se cargará desde la sección de 'Información de Pago
![informacionBancaria](https://github.com/user-attachments/assets/0f05d8c5-cacf-4f75-8449-aaf516a6a446)

**Comment by stevencol** [comment]
- Se prueba guardar información
![informacionBancaria](https://github.com/user-attachments/assets/e490e5ba-a46a-4ff5-bb29-1e04c186536e)

**Comment by stevencol** [comment]
-Cuando se habilita la edición de información bancaria el botón se deshabilita
![boton](https://github.com/user-attachments/assets/fd2bb56e-a4f1-4855-a3c2-1527331098a4)

**Comment by stevencol** [comment]
Se Ajustan validaciones: 

Para ver documento:
![image](https://github.com/user-attachments/assets/042c1032-0b55-4b35-804e-f745f243864a)


Para Guardar información: 

![image](https://github.com/user-attachments/assets/1cb8ffa7-6656-479f-8e67-8215e1bf7a28)

**Comment by JuanCamiloMartinezLopez** [comment]
@stevencol Buen trabajo.
