### ISSUE TITLE
Ajustes mf - formularios

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#150]
Se requiere realizar el cambio para que todos los formularios usen form-group, así como sus respectivas validación y mensajes 

**Sub Tareas**

- [x] Ajustar formularios al uso de form group
- [x] Agregar validaciones para estos formularios.

**Criterios de aceptación**

- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
## :triangular_flag_on_post: **Formularios  **  :triangular_flag_on_post:


Se cambian en el modal de soportes los cambos para que se manejen con formularios y se puedan agregar validaciones, por el momento no se tiene en cuenta el aspecto visual porque para los comentarios se va a implementar un modal.

![Image](https://github.com/user-attachments/assets/03cdfe56-a557-4706-be29-21ff365cb75a)

En la parte del formulario de los soportes tambien se implemento un formulario para manejar los campos del tipo documento, nombre del documento y las observaciones, se tiene un inconveniente que el tipo documento seleccionado no se esta actualizando se esta trabajando para resolverlo.

![Image](https://github.com/user-attachments/assets/bba6b3d8-53d1-4198-af55-4a625b315bef)

En este caso se deberia haber cambiado el boton al de crear documentos dinamicamente pero no esta funcionando porque no esta recibiendo en tiempo real la informacion del tipo documento seleccionado.

**Comment by faidercamilo26** [comment]
Se finaliza la implementacion de los formularios en la vista de los soportes, se agregan validaciones en la parte de los comentarios y en el formulario para subir un documento, en los comentarios y en las observaciones se coloco un minimo de 10 caracteres y una validacion para que no se pueda enviar un comentario que solo tenga espacios o que inicie o finalice con espacios en blanco.

![Image](https://github.com/user-attachments/assets/3b83e277-918a-463a-b773-88ee167d0fd1)

**Comment by faidercamilo26** [comment]
### Modificación Final de los Formularios

- Se completa la modificación de los formularios.
- Se verifican todas las condiciones de validación.
- Se soluciona el error relacionado con las observaciones, que causaba el desbordamiento de la caja cuando el formulario era inválido.
- Se aplica un cambio global al color de los bordes de los inputs y comentarios, editando el color primario de todo el proyecto al vinotinto utilizado en el proyecto de Cumplidos Proveedores.
- El botón de envío se modifica para que se desactive cuando el formulario es inválido.

https://github.com/user-attachments/assets/bcc979f6-5b1d-4bd3-b407-feabd8b95689

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 Buen trabajo.
