### ISSUE TITLE
Ajustes mf - modal visualización pdf

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#151]
Se requiere realizar el ajuste al componente de visualización de soportes para permitir el uso de boton con sus diferentes acciones, así como el redireccionamiento después de cerrado.

**Sub Tareas**

- [x] Añadir la configuración para las diferentes acciones que lleguen por la data injection.
- [x] Revisar el posible redireccionamiento dinámico.

**Criterios de aceptación**

- [ ] Modal ajustado.
- [ ] Issue documentado.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by stevencol** [comment]
Se inicia con actividad

**Comment by stevencol** [comment]
Se crea una interfaz para representar un botón y lograr que sea reutilizable:

``` Js
export interface Button {
    Color:string,
     FontIcon: string,
     Function: (data:any)=> any,
     Classes:string,
     Text:string,
     TextColor:string
    

    
}
```

**Comment by stevencol** [comment]
Con el modelo se ha modificado la función que muestra la lista de soportes, donde se envía un botón con la función ver y las propiedades del botón, y la función para abrir el modal, el cual a su vez lleva la función de cerrar el modal, ya que este caso  no requiere más funciones:

``` JavaScript
penDialog(cumplido: any) {
    console.log('cumplido', cumplido);
    const dialog = this.dialog.open(ModalSoportesCumplidoComponent, {
      disableClose: true,
      maxHeight: '80vw',
      maxWidth: '100vw',
      height: '80vh',
      width: '80vw',
      data: {
        CumplidoProveedorId: cumplido.cumplidoProveedor.Id,
        Buttons: [
          {
            Color: 'white',
            FontIcon: 'visibility',
            Function: (file: any) => {
              this.dialog.open(ModalVisualizarSoporteComponent, {
                disableClose: true,
                height: '70vh',
                width: '50vw',
                maxWidth: '60vw',
                maxHeight: '80vh',
                panelClass: 'custom-dialog-container',
                data: {
                  url: file.Archivo.File,
                  ModalButtonsFunc: [
                    {
                      Color: '#F5B907',
                      FontIcon: 'visibility',
                      Function: (dialog: MatDialogRef<any>) => {
                        dialog.close;
                      },
                      Classes: 'ver-documentos-button',
                      Text: 'Cerrar',
                    },
                  ],
                },
              });
            },
            Classes: 'ver-documentos-button',
            Text: 'Ver',
          },
        ],
        Config: {
          mode: this.obtenerModo(cumplido.CodigoAbreviacionEstadoCumplido),
          rolUsuario: RolUsuario.S,
        },
      } as ModalSoportesCumplidoData,
    });
  }
```

**Comment by stevencol** [comment]
## Se completa Ajustes del Modal

## Supervisor *Solo visualizar* 
![versoporteSupervisor](https://github.com/user-attachments/assets/901c83ca-6aff-4e42-9f52-7b7b82e3cd42)

## Supervisor *visualizar con función firmar* 
![versoporteSupervisorFimar](https://github.com/user-attachments/assets/5816a4ad-b7f5-4d43-85c8-0a1a004ecbc9)


## Supervisor *visualizar con función  después de firmar* 

![versoporteSupervisorFimar](https://github.com/user-attachments/assets/3181a007-838f-4f08-8141-130ec221711f)

**Comment by stevencol** [comment]
## Contratación *Solo visualizar* 

![solovercontratacion](https://github.com/user-attachments/assets/a9489a9c-c204-45cf-b083-21adaa611cb8)

**Comment by stevencol** [comment]
## Ordenador *Solo visualizar* 
![ordenador ver](https://github.com/user-attachments/assets/792992da-9f10-47ab-a575-b9d7bbf44a58)

## Ordenador *Firmar* 
![ordenador verFirma](https://github.com/user-attachments/assets/df45dfa8-dab7-4949-9212-fb022bd294fa)

**Comment by stevencol** [comment]
# Nota 
"Nota: En el caso de ordenador al aprobar el documento se está usando un documento de facto, ya que por alguna razón no se está generando."
![image](https://github.com/user-attachments/assets/162210a5-1114-4664-b727-128041b27a69)

**Comment by JuanCamiloMartinezLopez** [comment]
@stevencol Buen trabajo.
