### ISSUE TITLE
Ajustes mf - cambio de clases por interfaces

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#152]
Se requiere realizar el cambio de definición de los modelos como clases a usar interfaces 

**Sub Tareas**

- [x] Cambiar clases por interfaces, y ajustar el código según este cambio.
- [x] Organizar los modelos según a qué sistema pertenezco.

**Criterios de aceptación**

- [x] Modelos cambiados y organizados.
- [x] Issue comentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
## :triangular_flag_on_post: **Cambio clases por interfaces**  :triangular_flag_on_post:

Se reemplazaron todas las interfaces por clases con el objetivo de mejorar la consistencia del código y las estructuras utilizadas en el sistema. Además, se creó la carpeta `revision_cumplidos_proveedores_mid` dentro de `modelos` para organizar adecuadamente los modelos provenientes del MID.

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 buen trabajo.
