### ISSUE TITLE
Ajuste mf - Creación de modal y flujo para comentarios

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#153]
Se requiere realizar el diseño de una modal para comentarios de soportes

**Sub Tareas**

- [x] Mostrar un modal que permita la creación y visualización de comentarios de un determinado soporte.
- [x] Mostrar cargo, hora y comentario de cada comentario del soporte

**Criterios de aceptación**

- [x] Modal creado y funcionando.
- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
## :triangular_flag_on_post: **Modal flujo de comentarios**  :triangular_flag_on_post:

- Se crean los componentes ModalComentariosSoporteComponent, ComentarioIndividualSoporteComponent y GenerarComentarioSoporteComponent encargados de abrir el modal de los comentarios, mostrar un comentario individual mostrando el rol, la fecha y el comentario; Generar un comentario nuevo para el soporte, respectivamente.

![Image](https://github.com/user-attachments/assets/ad8e38ef-8a9d-44e6-ab0a-ab96998109e2)

- Se crea la interfaz export interface ModalComentariosSoporteData para que sea el modelo que va recibir el componente del modal.
```typescript
export interface ModalComentariosSoporteData{
  SoporteId: number;
  Config: ConfigSoportes;
}
``` 
Esto quiere decir que el modal de los comentarios va a recibir solo el soporteId y la configuracion de rol y estado, para que solo los ordenadores y el equipo de contratacion puedan crear nuevos comentarios y para que el supervisor solo pueda visualizar los comentarios.

Dentro del modal ya se implemento la funcionalidad para buscar los comentarios de un soporte, recuperarlos, manejarlos y pasarselos a los otros componentes.

### Propositos día de hoy

- Me quedo a la espera de la finalizacion de los mockups para los componentes, sin embargo, si no se tienen para el dia de hoy se va a ir avanzando con el primer ezboso del componente y los colores definidos para este proyecto.

![Image](https://github.com/user-attachments/assets/c14e6257-ff56-4de9-883b-f6cba5494c00)

- Por el momento lo unico que falta de logica es una funcion para registrar un nuevo comentario para un soporte en el componente GenerarComentarioSoporteComponent, se va a realizar el día de hoy, del resto ya se realizo toda la logica de este modal.

**Comment by faidercamilo26** [comment]
### Implementación de los estilos y creación de componentes

Se han aplicado los estilos proporcionados en el mockup por el analista de requerimientos. Además, se han creado las vistas de los componentes correspondientes. Entre las funcionalidades desarrolladas, destaca la creación de un formulario que valida los comentarios bajo los siguientes criterios:

- No deben contener únicamente espacios en blanco.
- No deben tener espacios en blanco al inicio ni al final de la cadena.
- Deben tener una longitud mínima de 10 caracteres.

Asimismo, se ha implementado toda la funcionalidad correspondiente al flujo de comentarios. A partir de este momento es posible crear y visualizar los comentarios asociados a un soporte. La función de crear comentarios está habilitada únicamente para los roles de **Ordenador** y **Contratación**, mientras que todos los roles podrán visualizar los comentarios.

Cada componente se ha desarrollado de forma modular, permitiendo su futura extensión o reutilización. 

Finalmente, queda pendiente aplicar un tema de diseño a los componentes para alinearlos de forma más precisa con el mockup, ya que toda la funcionalidad ha sido implementada y los componentes ya están creados.

![Image](https://github.com/user-attachments/assets/90137972-7c6e-4445-841f-61f75549cdce)


![Image](https://github.com/user-attachments/assets/efb20cd1-ec66-4528-b35d-066710b0a2c0)

**Comment by faidercamilo26** [comment]
### Finalización de la creación del modal

Se ha completado la implementación del modal con todas las funcionalidades correspondientes:

- **Supervisores:** Solo podrán visualizar los comentarios, sin la opción de crear uno nuevo.

![Image](https://github.com/user-attachments/assets/b4e0981e-c25b-45af-ad9d-4d5a9f723682)


- **Ordenadores y equipo de contratación:** Tendrán acceso a la lista de comentarios anteriores y dispondrán de la opción para crear un nuevo comentario.

https://github.com/user-attachments/assets/9482b7e0-cab6-4ad7-a3c0-76d32656edac

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 Buen trabajo.
