### ISSUE TITLE
Plantilla de correos para evaluación proveedores

### ISSUE THREAD

**Issue by mantnicot** [udistrital/Cumplidos_y_certificaciones_documentacion#154]

**Comment by mantnicot** [comment]
Se ha creado las plantillas de correos evaluación proveedores
[Documento plantillas](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EY1ejueYGNRJifHz9FWToc0BMr8q7z6-v5iN6FaxZq0rKg?e=azvUyr)

**Comment by mantnicot** [comment]
Se han realizado los cambios en el documento que se comentaron en el dayli con el  lider tecnico

[Documento plantillas](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EY1ejueYGNRJifHz9FWToc0BMr8q7z6-v5iN6FaxZq0rKg?e=azvUyr)

**Comment by jcmurilloa** [comment]
Muy buen trabajo.
