### ISSUE TITLE
Actualizar mockups cumplidos proveedores

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/Cumplidos_y_certificaciones_documentacion#155]
Se requiere generar la actualización del mockup de cumplidos proveedores, teniendo en cuenta nuevos requerimientos por parte del cliente. 

**Sub Tareas**

- [x] Actualizar el diseño del mockup inicial con base en las actualizaciones.
- [x] Presentar el mockup al equipo SoS.
- [x] Realizar ajustes según comentarios del equipo SoS.
- [x] Presentar al equipo el mockup definitivo para presentar al cliente.

**Criterios de aceptación**

- [x] Mockup aprobado por equipo SoS.
- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se ha realizado los mockups 
[Mockups nuevos](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/Ej0ZH_RvNSdMkV26DYPBA2UBgrCN0lrrZRb0VELm5wcvxg?e=94zrvW)

![Image](https://github.com/user-attachments/assets/143b1069-0a3c-4579-9151-2e3a71b75f2e)
![Image](https://github.com/user-attachments/assets/52621707-4e01-4b62-b499-efffa25355e6)

**Comment by jcmurilloa** [comment]
Muy buen trabajo @mantnicot, revisaremos el detalle del diseño en el review del sprint.

**Comment by jcmurilloa** [comment]
Mockups aprobados, excelente trabajo.
