### ISSUE TITLE
Investigar acerca de la documentación de reporte de necesidades de parte de ERP

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/Cumplidos_y_certificaciones_documentacion#157]
Se requiere realizar una investigación para generar la documentación de reporte de necesidades de parte de ERP

**Sub Tareas**

- [x] Realizar investigación
- [x] Documentar en el issue las opciones encontradas.

**Criterios de aceptación**

- [x] Investigación realizada.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by mantnicot** [comment]
Maria Claudia propuso una reunión con respecto a explicar como funciona el sistema de SOFIA 

[Link de la grabación](https://udistritaleduco-my.sharepoint.com/:v:/g/personal/caescorciab_udistrital_edu_co/Efs6-OH_HEFOgkYzbNMYbJQBYQ1y1cZkm9gKzYJN8N2GpA?e=tB6Xxj)

María Claudia nos muestra junto al líder la información de las necesidades por lo cual se puede que no esta relacionado los ítems del contrato , para poder tenerlos uno a uno. Pero después nos muestra el apartado del almacén en el cual se muestra que si están por separados este ingreso de ítems delos proveedores, dándonos una primera parte para obtener los items a evaluar.

Pero con el problema de los items que no entran por almacén , pero se puede comenzar con esta información

Se sabe que Cristian Alape hizo petición de un servicio a infotic para poder obtener información y se hablará con él de parte del líder técnico para poder para saber si toca pedir otro servicio o se puede solo esperar ese.


se adjunta los documentos de reportes 
[A06._Reporte_Almacén_Entrada.xlsx](https://github.com/user-attachments/files/17063810/A06._Reporte_Almacen_Entrada.xlsx)
[PP25._Relacion_Necesidades_Detallado.xlsx](https://github.com/user-attachments/files/17063809/PP25._Relacion_Necesidades_Detallado.xlsx)

**Comment by jcmurilloa** [comment]
Estaremos atentos a los avances para cotinuar con esta investigación y el docuemnto producto.

**Comment by mantnicot** [comment]
Se agrega el documento , falta solo la inforamción del lider para sumarle
[documento de ERP](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/ET7wa-RSkZhCgmlFtQ5ucdwBP07WSGKEsyXXFIfzTr40DQ?e=7r9Jgi)

**Comment by jcmurilloa** [comment]
Muy buen trabajo @mantnicot!
