### ISSUE TITLE
Ajuste mf - formularios - Parte II

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#158]
Se requiere realizar ajustes finales a los formularios tomando como referencia la documentación de [angular material](https://v16.material.angular.io/components/categories).

**Sub Tareas**

- [x] Hacer uso de etiquetas mat-hint,mat-error, etc.
- [x] Ajustar el uso de trim para el tratamiento de espacios en blanco.

**Criterios de aceptación**

- [x] Formularios ajustados.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
## :triangular_flag_on_post: **Ajustes Formularios Parte II**  :triangular_flag_on_post:

Se realizan los ajustes pertienentes, se valida que esten funcionando bien y se resuelven errores que estaban ocurriendo con los formularios.
- Se elimina la validacion para que un formulario no inicie ni finalice con espacios en blanco, ahora se formatea la cadena usando la funcion trim() para que la observacion o el comentario se guarde sin espacios en blanco al principio ni al final de la cadena.
- Se arregla el formato del error en la parte de observaciones, antes el error aparecia dentro del text area quitandole espacio al texto que se estaba escribiendo, ahora aparece normal en la parte inferior como cualquier error.

![Screenshot from 2024-09-24 20-09-03](https://github.com/user-attachments/assets/098fa0b0-904f-460d-be80-612c2c683fe6)

- Se arregla el problema al subir un soporte, antes por el estilo parecia que el boton estaba deshabilitado pero al hacer click se intentaba subir el soporte, y lo mismo pasaba con el modal para crear un comentario.

![Image](https://github.com/user-attachments/assets/4d8b6fa7-5692-4bf2-bfd6-0310040fc67e)

**Comment by faidercamilo26** [comment]
Se redimensiona el modal de comentarios de un soporte porque en la parte de abajo estaba quedando mucho espacio, parecia un padding o que se necesitaba aumentar el tamaño de este componente, pero ninguna de las dos acciones se pudo realizar, en este caso se tiene que redimensionar el modal para que no sobre tanto espacio en la parte de abajo.

![Screenshot from 2024-09-26 08-56-33](https://github.com/user-attachments/assets/c93a814c-489a-40a4-a129-64b5178c19f4)

![Screenshot from 2024-09-26 08-57-10](https://github.com/user-attachments/assets/afa2838b-a16a-4fab-8dc6-59381add1240)

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26
