### ISSUE TITLE
Ajuste administrativa_amazon_api controlador ordenador

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#159]
Se requiere realizar el ajuste al modelo de [ordenadores](https://github.com/udistrital/administrativa_amazon_api/blob/develop/models/ordenadores.go) del api administrativa_amazon_api para que retorne tambien el valor de rol_id.

**Sub Tareas**

- [x] Realizar el ajuste en una rama aparte de develop
- [ ] Validar el correcto funcionamiento.

**Criterios de aceptación**

- [ ] Pr a develop con el cambio realizado.
- [ ] Issue documentado.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by stevencol** [comment]
Se agrega variable RolId

``` Go
type Ordenadores struct {
	Id              int       `orm:"column(id);pk"`
	IdOrdenador     int       `orm:"column(id_ordenador);null"`
	InfoResolucion  string    `orm:"column(info_resolucion);null"`
	IdCiudad        int       `orm:"column(id_ciudad);null"`
	FechaInicio     time.Time `orm:"column(fecha_inicio);type(date);null"`
	FechaFin        time.Time `orm:"column(fecha_fin);type(date);null"`
	Estado          bool      `orm:"column(estado);null"`
	Documento       int       `orm:"column(documento);null"`
	NombreOrdenador string    `orm:"column(nombre_ordenador);null"`
	RolOrdenador    string    `orm:"column(rol_ordenador);null"`
	RolId           int       `orm:"column(rol_id);null"`
}

```

![image](https://github.com/user-attachments/assets/b0cadfc5-94ed-4590-b420-8fcfb30a6904)

**Comment by JuanCamiloMartinezLopez** [comment]
@stevencol Buen trabajo.
