### ISSUE TITLE
Realizar pruebas funcionales mf revision_cumplido_prov

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#160]
Se requiere realizar pruebas funcionales del cliente estabilizado para el flujo completo de los tres roles (supervisor, contratación, ordenador)

**Sub Tareas**

- [ ] Pruebas funcionales con el formato en la carpeta correspondiente del sistema.

**Criterios de aceptación**

- [ ] Documento de pruebas.
- [ ] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by stevencol** [comment]
Se ha iniciado con la actividad. Inicialmente realizando los posibles casos de prueba para el módulo del Supervisor.

**Comment by stevencol** [comment]
[Pruebas Funcionales Cumplidos Proveedores-Supervisor.xlsx](https://github.com/user-attachments/files/17172358/Pruebas.Funcionales.Cumplidos.Proveedores-Supervisor.xlsx)

**Comment by stevencol** [comment]
Posibles casos  de prueba para supervisor y ordenador 
[Pruebas Funcionales Cumplidos Proveedores-Contratacion.xlsx](https://github.com/user-attachments/files/17177548/Pruebas.Funcionales.Cumplidos.Proveedores-Contratacion.xlsx)
[Pruebas Funcionales Cumplidos Proveedores-Ordenador.xlsx](https://github.com/user-attachments/files/17177549/Pruebas.Funcionales.Cumplidos.Proveedores-Ordenador.xlsx)

**Comment by stevencol** [comment]
Errores desconocidos
El sistema lanza una alerta  de manera automática indicando : El proveedor no tiene ninguna solicitud reciente: 
![image](https://github.com/user-attachments/assets/7899fa30-07bc-4a1d-8221-94edce05770b)

Como generarlo:
1: Ingresar a :  http://localhost:4200/pages/supervisor/subir-soportes o aplicativo desplegado
2: Seleccionar un proveedor 
3: Dar clic en el botón subir 
4: El sistema mostrara un modal con las solicitudes del proveedor  
5: Cerrar el modal 
6: en aproximadamente 25- 40 segundos el sistema mostrara la alerta 

* Al abrir la lista de solicitudes y esperar el mismo periodo de tiempo también saldrá la alerta

**Comment by stevencol** [comment]
Si el ordenador no tiene solicitudes pendientes se queda cargado y nunca sale del mensaje de carga:
![image](https://github.com/user-attachments/assets/664936e5-3bbe-4320-843e-39e6800e4205)

**Comment by stevencol** [comment]
✅Mejora✅

Al momento de firmar el documento el sistema lanza en modal  pero este es mas grande que el documeto firmado 
![image](https://github.com/user-attachments/assets/8bed4815-c2b4-4db4-93ee-daa3ae1faf99)

**Comment by stevencol** [comment]
Finalización de pruebas de Supervisor:
[Pruebas Funcionales Cumplidos Proveedores-Supervisor.xlsx](https://github.com/user-attachments/files/17183226/Pruebas.Funcionales.Cumplidos.Proveedores-Supervisor.xlsx)

**Comment by stevencol** [comment]
✅Mejora✅
en caso de que un un ordenador cancele el proceso de rechazo el sistema muestra una alerta malescrita 
![image](https://github.com/user-attachments/assets/51e3c95e-4292-4244-88d1-d4dd5384fc3f)

**Comment by stevencol** [comment]
❌Error❌
Al ingresar directamente a http://localhost:4200/pages/ordenador/aprobacion-pago  se muestra mensaje de cargando
![image](https://github.com/user-attachments/assets/c1e7736c-fff6-47e7-9fe2-168ad2a3346e)

**Comment by stevencol** [comment]
❌Error❌
Al ingresar directamente a http://localhost:4200/pages/supervisor/subir-soportes  sin iniciar sección  se muestra mensaje de error indicando que no hay contratos para el supervisor 
![image](https://github.com/user-attachments/assets/70d760de-d1e5-4e9f-afdd-e9ece21d9131)

**Comment by stevencol** [comment]
❌Error❌
Al ingresar directamente a http://localhost:4200/pages/contratacion/aprobacion-pago   sin iniciar sección  se muestra mensaje de cargando
![image](https://github.com/user-attachments/assets/bfd20caa-f359-4c94-8d04-f0663a3f8ba3)

**Comment by stevencol** [comment]
❌Error❌
En el módulo de supervisor  en el panel de listar contratos de proveedor se muestra el siguiente mensaje 
![image](https://github.com/user-attachments/assets/f7662043-36e2-4640-abfd-c79598c39071)
- indicando que hay un error en la line 25 , que parece generarse con la obtención del token de acceso

**Comment by stevencol** [comment]
❌Error❌
En consola a ingresar a http://localhost:4200/pages/contratacion/aprobacion-pago
![image](https://github.com/user-attachments/assets/54d2530d-4d0e-4fb9-88c4-7ef5dd533e2a)

Esto es debido a una petición que se realiza al root_mf

**Comment by stevencol** [comment]
Archivos finales con casos de pruebas : 
[Pruebas Funcionales Cumplidos Proveedores-Contratacion.xlsx](https://github.com/user-attachments/files/17184066/Pruebas.Funcionales.Cumplidos.Proveedores-Contratacion.xlsx)
[Pruebas Funcionales Cumplidos Proveedores-Ordenador.xlsx](https://github.com/user-attachments/files/17184067/Pruebas.Funcionales.Cumplidos.Proveedores-Ordenador.xlsx)
[Pruebas Funcionales Cumplidos Proveedores-Supervisor.xlsx](https://github.com/user-attachments/files/17184068/Pruebas.Funcionales.Cumplidos.Proveedores-Supervisor.xlsx)

**Comment by stevencol** [comment]
Se cargan los archivos al one drive
Pruebas Supervisor: [Link](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/ERgPORgi2rdInwXu2CkuArUBNdOr_tw4XdQK44gzV6T0Sg?e=SSWAxD)
Pruebas Ordenador: [Link](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EZGbtZ7oqfxOuU1uBt0bV-sBs4lkjLW69Y-UrYn6C1dsmQ?e=eqbFqV)
Pruebas Contratacion : [link](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EYXnEir6RvVGrD7iYe9W79ABbpWj4uwu6g-mU7tX9g-U8w?e=6AOe3b)

**Comment by JuanCamiloMartinezLopez** [comment]
@stevencol Buen trabajo.
