### ISSUE TITLE
Actualizar mockups módulo evaluación proveedores

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/Cumplidos_y_certificaciones_documentacion#161]
Se requiere generar la actualización del módulo evaluación proveedores, teniendo en cuenta nuevos requerimientos por parte del cliente. 

**Sub Tareas**

- [x] Actualizar el diseño del mockup inicial con base en las actualizaciones.
- [x] Presentar el mockup al equipo SoS.
- [x] Realizar ajustes según comentarios del equipo SoS.
- [x] Presentar al equipo el mockup definitivo para presentar al cliente.

**Criterios de aceptación**

- [x] Mockup aprobado por equipo SoS.
- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se han creado los mockups actualizados , se han quitado los bordes del cliente pues ahora la prioridad es crear componentes separados para así poder tener un mejor manejo de la evaluación e involucrarla en el sistema de cumplidos proveedores

[Carpeta de mockups](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EjsGhgzcwN1BtsYIFpuCtVsBrfHk0-n-nM5f0QT2uSjMXw?e=WyZfc5)

![Image](https://github.com/user-attachments/assets/adbe83cd-ba85-479c-8a7c-3e30fbbafe60)
![Image](https://github.com/user-attachments/assets/66a10d7b-9208-47f6-85f8-0f045ee275be)
![Image](https://github.com/user-attachments/assets/1605cabd-cfc5-4ccf-a766-935554a89450)
![Image](https://github.com/user-attachments/assets/f5a69e53-a35d-4a1a-9f11-9ff5d0c39471)
![Image](https://github.com/user-attachments/assets/7245697a-90ac-408f-be58-92a8f790b820)
![Image](https://github.com/user-attachments/assets/6bd6b86f-1732-416b-94b8-24b5be487c19)

**Comment by jcmurilloa** [comment]
Se ven muy bien los diseños @mantnicot, los repasaremos al detalle en el review.

**Comment by jcmurilloa** [comment]
Muy buen trabajo, pendiente ajustar las sugerencias realizadas por el equipo SoS.

**Comment by mantnicot** [comment]
Se ha realizado los cambios pedidos por el equipo

[carpeta mockups 3.1](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EqR-kDug4dpBoEKviPKbDK8Bwt_DtyvUElg9k8MQ6p4yTw?e=g2LOEi)

![Image](https://github.com/user-attachments/assets/9826a259-e0c7-4f4a-b7f3-d601fff4c2ca)
![Image](https://github.com/user-attachments/assets/ede9727a-ccd9-4be0-bc4d-04686991d684)

**Comment by jcmurilloa** [comment]
Gracias por atender los cambios @mantnicot, ahora a pasar por aprobación del cliente!

**Comment by mantnicot** [comment]
![Image](https://github.com/user-attachments/assets/f996d73d-1226-4614-b5d9-7c27861b1192)

Se ha dado aprobación de los mockups de parte del cliente

**Comment by jcmurilloa** [comment]
Muy buen trabajo @mantnicot
