### ISSUE TITLE
Mejorar las plantillas de correo de cumplidos CPS

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/Cumplidos_y_certificaciones_documentacion#162]
Se requiere realizar la mejora de los templates que se van a usar para el envío de notificaciones, tener presente las diferentes modalidades y notificaciones que se deben realizar e ir creando los templates.

**Sub Tareas**

- [x] Actualizar templates según requerimientos.
- [x] Documentar templates actualizados.

**Criterios de aceptación**

- [x] Templates actualizados.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by mantnicot** [comment]
Con base a lo que se realizo en el cumplido proveedores , se establece una plantilla general y concisa de la información

![Image](https://github.com/user-attachments/assets/f2b675dc-d1a4-46bd-ab91-bae7060b6900)


[Documento de plantilla](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EQeV8iHvn-ZHhURx19v0t8YBK25Ho7IRZVuHjZJiGoYLCg?e=gxVpzy)

**Comment by jcmurilloa** [comment]
No me queda claro el tiítulo de cambio de estado cumplido, así como su mención en el contenido. Puedes por favor proyectar una notificación como ejemplo, de lo que se mostraria al usuario.

**Comment by mantnicot** [comment]
![Image](https://github.com/user-attachments/assets/385ac391-99bd-41fe-b404-c4446b8e7e29)

Este sería ele ejemplo de notificación

**Comment by jcmurilloa** [comment]
Gracias por aclarar mediante el ejemplo, el diseño quedó excelente!
