### ISSUE TITLE
Integrar notificaciones por email - mf revisión

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#164]
Se requiere realizar la integración de notificaciones por correo.

**Sub Tareas**

- [x] Integrar el desarrollo previo al mf.
- [x] Validar el correcto funcionamiento. 

**Criterios de aceptación**

- [x] Issue documentado.
- [x] Notificaciones por correo funcionando en el mf.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
## :triangular_flag_on_post: **Integracion notificaciones por email**  :triangular_flag_on_post:

- Se actualiza la rama `develop` con los últimos cambios disponibles.
- Se descarga la rama que contiene la funcionalidad de las notificaciones por correo.
- Se procede a fusionar ambas ramas.
- Se verifica el correcto funcionamiento de la funcionalidad de notificaciones por correo.
- Se valida que el resto de las funcionalidades no hayan sido afectadas tras la fusión.

![Image](https://github.com/user-attachments/assets/11c8657a-1224-4b33-9b7f-6e1de046cf2d)

![Image](https://github.com/user-attachments/assets/6b903074-62a5-4dbf-86ea-d360e0f2b03a)

![Image](https://github.com/user-attachments/assets/94d39ede-244f-43c5-8935-71b7eab74e0a)

![Image](https://github.com/user-attachments/assets/bc18dd30-0d05-458b-b38a-7a85c499b9d3)


### :x: **Inconvenientes** :x:

Por el momento no se da por finalizada la tarea puesto que surgen unas dudas acerca de la funcionalidad:

Cuando el equipo de contratacion o el ordenador rechazan un cumplido el responsable sigue siendo el ordenador, por lo que la notificacion solo le llega al ordenador o al equipo de contratacion pero no le llega al supervisor, cuention que se debe solucionar porque el supervisor tambien debe estar enterado de que se rechazo el cumplido, las posibles soluciones que se tienen para este inconveniente son: 

- Cambiar la logica para que cuando se rechace un cumplido ya sea por el ordenador o el equipo de contratación el responsable sea el supervisor.
- Cambiar la logica en el mid para que cuando se rechace un cumplido por parte del equipo de contratación o el ordenador, se envie una notificacion tanto al supervisor, como al ordenador o equipo de contratación dependiendode quien realizo el cambio.

**Comment by faidercamilo26** [comment]
- Se finaliza con el merge de las notificaciones por correo, se cambia la logica para que cuando un oredenador o el equipo de contratacion rechacen un cumplido el nuevo responsable de ese estado sea el supervisor y asi le puedan llegar las notificaciones.
- Se agrega el ```&limit:-1``` a la consulta que se realiza para traer las solicitudes de un contrato para que se traigan todas las solicitudes y no solo las ultimas 10.
- En el endpoint de listar los soportes de un cumplido se quita la parte de listar los comentarios del cumplido puesto que no son necesarios en este modelo y no se esta utilizando.

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 Buen trabajo.
