### ISSUE TITLE
Endpoint reversibles - Parte II

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#165]
Se requiere realizar la terminacion del endpoint para filtrar los cumplidos reversibles, tomando como base el cambio realizado en el issue #159 

**Sub Tareas**

- [x] Implementar el endpoint cambiado de ordenadores de administrativa_amazon_api
- [x] Terminar la funcionalidad.

**Criterios de aceptación**

- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
## :triangular_flag_on_post: **Endpoint Reversibles**  :triangular_flag_on_post:

Se ha actualizado la funcionalidad para listar los cumplidos de proveedores revertibles por parte de un ordenador. Para ello, se utiliza el *endpoint* correspondiente de la API administrativa de Amazon (`administrativa_amazon_api`) con el fin de verificar un posible cambio en el ordenador, considerando dicho factor en el proceso. La funcionalidad ha sido finalizada y se ha probado, confirmando que funciona correctamente. No obstante, aún falta realizar pruebas en situaciones donde se produzca un cambio en el ordenador, aunque la lógica ha sido implementada de manera adecuada.


![Image](https://github.com/user-attachments/assets/c5205d10-15a3-4a50-89aa-fe620111d73c)

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 Buen trabajo.
