### ISSUE TITLE
Ajustes margen documentos y actualización de tablas

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#166]
Se requiere realizar ajustes a problemas hallados 

**Sub Tareas**

- [x] En el mid ajustar la generación de documentos para mantener las márgenes indicadas en todas las páginas. 
- [x] En el cliente se requiere realizar una recarga de las tablas después de acciones como aprobar o rechazar.

**Criterios de aceptación**

- [x] Cambios funcionando.
- [x] Issue documentado.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
## :triangular_flag_on_post: **Ajustes documentos y Actualizacion tablas**  :triangular_flag_on_post:

### Margen en Documentos

Se ha corregido en el  MID el problema relacionado con el margen de los documentos. Se realizaron ajustes para que, cuando se genere una nueva hoja en el pdf, el margen de los elementos no se desacomoden como estaba ocurriendo previamente.

![Image](https://github.com/user-attachments/assets/45cd16cc-4806-40e1-8416-20f0f0ca8fde)

### Actualización de Tablas

Se ha modificado el componente general de las tablas para que, cada vez que se produzca un cambio en el datasource, el contenido de las tablas se actualice automáticamente, mejorando así la consistencia de la información mostrada.

![Image](https://github.com/user-attachments/assets/b1711b67-a852-40bb-a4fe-61e789053822)

![Image](https://github.com/user-attachments/assets/09da2383-3b76-4611-8943-af6b85a4d909)


### Función de Eliminación de Soportes

Se ha actualizado la función encargada de eliminar documentos. Ahora, la solicitud de eliminación se realiza directamente al CRUD, en lugar de pasar por el MID. Además, se ha eliminado la función correspondiente del MID para evitar la presencia de código innecesario.

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 Buen trabajo.
