### ISSUE TITLE
Concertar, desarrollar y levantar acta de sesión de refinamiento con cliente Cumplidos proveedores

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/Cumplidos_y_certificaciones_documentacion#168]
Se requiere realizar la concertación, desarrollo y levantamiento del acta de sesión de requerimientos y/o refinamiento con el cliente cumplidos proveedores

**Sub Tareas**

- [x] Concertar reunión con el cliente.
- [x] Desarrollar la reunión con el cliente.
- [x] Diligenciamiento y aprobación del formato de historias de usuario o Mockup por parte del cliente (si aplica).
- [x] Proyectar acta de la reunión.
- [x] Recolectar las firmas correspondientes.

**Criterios de aceptación**

- [x] Acta revisada por el líder de proyecto.
- [x] Acta firmada por las partes con anexo de historias de usuario o mockup.
- [x] Acta y anexos documentados.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [X] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [X] No tiene bloqueos que impidan su ejecución.
- [X] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se ha agendado la sesión para el día 08/10/2024 a las 10:00 am

[Enlace reunión](https://teams.microsoft.com/l/meetup-join/19%3ameeting_ZDAzOTI1MjAtMDFmMS00ZDc2LThlM2YtNmZhNDVkYjM3NmIy%40thread.v2/0?context=%7b%22Tid%22%3a%22d51388ef-6ab0-4363-9f94-d56644a45970%22%2c%22Oid%22%3a%221dd8bdce-0185-41b4-8caa-01da7e5506b2%22%7d)

**Comment by mantnicot** [comment]
Se ha generado el acta de la reunión

[acta sin firmas](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/Eb02n5eX1d1DgmnoG9L9vI8B_Ln3hrwk01HhJP1D_obvVA?e=cyfmhp)

**Comment by jcmurilloa** [comment]
Con base en lo comentado en la sesión, podríamos invitar a la jefe de contratación a la muestra que se realice con funcionamiento, con el ánimo de que también pueda visualizar el primer alcance del sistema.

**Comment by mantnicot** [comment]
Se ha recolectado las firmas de parte del cliente , por cuestiones de vacaciones la jefe de contratación vuelve hasta el 21 a la oficina , pero se debe tener ene cuenta que estara reducido el tiempo por cuestiones del paro

[Acta firmada](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EYHtOVZ9gnZOr4JYh21ConIB5K6lq2hlmwP5poAOKCAqng?e=NqZRZb)

**Comment by jcmurilloa** [comment]
Excelente trabajo @mantnicot!
