### ISSUE TITLE
Revisar error consulta nombre usuario

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#169]
Se requiere revisar la consulta  de información para el nombre del usuario para las vistas de supervisor, contratación, ordenador.

**Sub Tareas**

- [x] Revisar el flujo actual de consulta.
- [x] Revisar si esta información puede obtenerse de otro lugar.

**Criterios de aceptación**

- [ ] 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
## :triangular_flag_on_post: **Consulta nombres de usuarios**  :triangular_flag_on_post:

Se realizan varias pruebas en los distintos roles y se puede evidenciar que los nombres no se cargan cuando no se ha conectado la VPN, caso contrario, cuando se conecta la VPN los nombres se cargan correctamente.

## Rol Supervisor

### Sin VPN

![Image](https://github.com/user-attachments/assets/d0245e53-e062-487a-a4f8-f3d4ed21d52f)

### Con VPN

![Image](https://github.com/user-attachments/assets/41b33def-dd90-4154-bb6b-32f396272be1)

## Rol Contratación

### Sin VPN

![Image](https://github.com/user-attachments/assets/e8f30843-b850-4a9a-94dd-11a2caba63a4)

### Con VPN

![Image](https://github.com/user-attachments/assets/b020e70d-dd7b-458a-962a-9f7c8edc75b4)

## Rol Ordenador

### Sin VPN

![Image](https://github.com/user-attachments/assets/7ad5fef9-d48c-49c7-918b-3851c141034d)

### Con VPN

![Image](https://github.com/user-attachments/assets/ab332ba3-084e-447d-b4da-d763fdedf164)

**Comment by faidercamilo26** [comment]
Se cambia el metodo para obtener el supervisor del contrato con el servicio JBPM, sin embargo, la peticion esta fallando con un error 500 aunque la peticion esta bien formada, se verifica la peticion por postman y funciona correctamente pero en el cliente esta dando error.

![Image](https://github.com/user-attachments/assets/b83add88-eccd-443f-8898-b1d11a48ac9b)

![Image](https://github.com/user-attachments/assets/5360b21b-995c-471a-901f-adabf74baf38)

![Image](https://github.com/user-attachments/assets/a791308f-e5bb-4e44-967c-339a684d1a47)

**Comment by faidercamilo26** [comment]
Se soluciona el inconveniente que se tenia para recuperar el cargo del supervisor desde el servicio JBPM, se nota que el inconveniente se debia a la cabezera ```'Content-Type': 'application/json'``` la cual estaba especificandole al servicio que la respuesta era un json, sin embargo, el servicio respondia un xml y debido a esta difereencia de formatos estaba fallando la peticion, se crea un cumplido, esto retorna un status 200 y se nota que la peticion para crear un nuevo cumplido se esta enviando completa incluyendo el cargo del supervisor.

![Image](https://github.com/user-attachments/assets/709f9070-74dd-4895-ad7a-717b1c169dac)

![Image](https://github.com/user-attachments/assets/f2171386-1f35-4d27-808e-c0902ba97bf4)

![Image](https://github.com/user-attachments/assets/cc6f0586-313b-4508-8df0-a329ed6b633e)

![Image](https://github.com/user-attachments/assets/9cb9c260-42cd-4329-8861-88f738f41bb9)

**Comment by faidercamilo26** [comment]
Se ha agregado la configuración correspondiente para que el encabezado `'Content-Type': 'application/json'` se incluya únicamente en las solicitudes de tipo `POST` o `PUT`, ya que, por definición, son las únicas que requieren este encabezado.

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 Buen trabajo.
