### ISSUE TITLE
Revisar el componente de formulario de soportes para los estados de rechazado.

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#170]
Se requiere revisar y ajustar la aparición del formulario de soportes para los diferentes estados que corresponda

**Sub Tareas**

- [x] Revisar condicional del componente.
- [x] Ajustar para los estados que correspondan.

**Criterios de aceptación**

- [x] Issue documentado.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
## :triangular_flag_on_post: **Formulario soportes estados rechazados**  :triangular_flag_on_post:

Se realiza el ajuste para que cuando haya un cumplido en estado rechazado ordenador o contratación se habilite la opcion de subir o eliminar nuevamente soportes.

![Image](https://github.com/user-attachments/assets/97a25092-5e95-4cb2-90fe-572a49b0c8d7)

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 Buen trabajo.
