### ISSUE TITLE
Implementar guards para el acceso de rutas

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#172]
Se requiere implementar guards para el acceso de las rutas 

**Sub Tareas**

- [x] Implementar guards tomando como ejemplo [sga](https://github.com/udistrital/sga_cliente_inscripcion_mf/blob/develop/src/_guards/auth.guard.ts)
- [x] Validar su correcto funcionamiento.

**Criterios de aceptación**

- [x] Issue documentado.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
## :triangular_flag_on_post: **Implementación Guards**  :triangular_flag_on_post:

Se inicia con la tarea verificando el proyecto de SGA para entender la manera en que se maneja el tema de guards, tambien se consulta información tecnica en documentacion contenida en internet para dar inicio a la implementación.

![Image](https://github.com/user-attachments/assets/b44a5954-d6ac-4b69-a2cb-8788705fbe4c)

[Recurso documentación guards](https://dev.to/this-is-angular/demystifying-angular-route-guards-a-beginners-guide-to-secure-navigation-597b)

![Image](https://github.com/user-attachments/assets/3cf9edd2-d82e-433a-a070-1f4705a9abdf)

**Comment by faidercamilo26** [comment]
Se finaliza la implementación de los guards para el proyecto, siguiendo el ejemplo de SGA. Se verifica que las rutas se estén protegiendo para que no se permita ingresar a las rutas sin haber iniciado sesión, y que un supervisor no pueda ingresar a las rutas del ordenador,  el ordenador a las de contratación, etc.

### Prueba 1

Aqui se evidencia que no se puede ingresar a una ruta sin haber iniciado sesión, al iniciar sesión la ruta ya funciona puesto que se esta ingresando a una ruta del supervisor.
  
![Image](https://github.com/user-attachments/assets/3b3f6fd9-7f90-44d1-94f1-79c8cd4b65db)

### Prueba 2

En esta prueba vemos que se inició sesión con el rol de supervisor, por eso al intentar ingresar a una ruta del rol del ordenador o de contratación va a fallar.

![Image](https://github.com/user-attachments/assets/8e7ec05f-1282-4567-8750-3286bf837783)


### Prueba 3

Se accede a una cuenta del rol de ordenador y se prueban las urls.

![Image](https://github.com/user-attachments/assets/b30e6715-b3e6-45b1-945a-f5a6b35ff555)

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 Buen trabajo.
