### ISSUE TITLE
Ajustar servicio de pop ups

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#174]
Se requiere realizar el ajuste para manejar solo un servicio de pop ups (popUpmanager)

**Sub Tareas**

- [x] Ajustar las funciones de popUpManager.ts y alert-manager.service.ts, dentro del popUpManager.
- [x] Intentar unificar código para manejar un estándar de popUps

**Criterios de aceptación**

- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
## :triangular_flag_on_post: **Ajustes Pop ups**  :triangular_flag_on_post:

Se ha llevado a cabo una modificación en todo el proyecto, donde se han reemplazado todas las partes que utilizaban el servicio `alertManager` por el estándar de `popUpsManager`, con el objetivo de generar uniformidad en el desarrollo.

Además, se ha agregado la función `showLoadingAlert` al servicio `popUpsManager`. Esta función es la misma que se utilizaba en `alertManager` para mostrar la alerta de carga.

Se han editado los colores de los botones de confirmación para alinearlos con la paleta de colores del proyecto. Se ha señalado que el color verde está en consideración, ya que podría resultar demasiado brillante o intrusivo.

Se realizaron pruebas exhaustivas para asegurar que los pop-ups funcionan correctamente.

También se han corregido algunos errores ortográficos en los pop-ups, con el fin de asegurar que las alertas sean coherentes y comprensibles.

Por último, se ha corregido el comportamiento relacionado con los mensajes de error. Ahora, únicamente se muestran los mensajes de error y no el detalle del error, ya que a los usuarios finales no les interesa visualizar esta información técnica.

![Image](https://github.com/user-attachments/assets/743d5e8c-216c-4071-a2a7-434c555221c6)

![Image](https://github.com/user-attachments/assets/bfdb80e8-dc41-4831-85cb-c293b9cd0c5d)

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 Buen trabajo.
