### ISSUE TITLE
Ajustar botones en componente card de soportes.

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#175]
Se requiere realizar los ajustes necesarios para que los botones se vean bien

**Sub Tareas**

- [x] Ajustar botones de eliminar y comentarios para que compartan estilos con el botón de ver.

**Criterios de aceptación**

- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
## :triangular_flag_on_post: **Botones componente card**  :triangular_flag_on_post:

### Avances

- A la interface de Button se le agrega el campo ```Condicional``` al cual se le pasa un booleano que indica si el boton tiene algun condicional para mostrarse, en caso de que el campo tenga alguna condicion para renderizarse se debe enviar este campo en true, en caso de que no tenga algun condicional no es necesario agregarlo, el siguiente codigo es el que maneja las condiciones desde el componente hijo.

```JavaScript

evaluarCondicional(button: any): boolean{
      if (!button.Condicional){
        return true;
      }

      return ((this.config.mode == this.mode.CD || this.config.mode == this.mode.RC || this.config.mode == this.mode.RO) && this.config.rolUsuario == this.rolUsuario.S);
    }

```
- Se le pasan al componente los botones de Eliminar y Comentarios, se ajusta su estilo y se propone una nueva manera de organizar los botones.

![Image](https://github.com/user-attachments/assets/4f1d8ff6-d7d0-4478-a580-d2657e1dc00e)

### Faltantes

- Falta organizar la manera de manejar las funciones, puesto que al recorrer todos los botones solo se le esta enviando un parametro a todas las funciones, pero hay funciones de un boton que necesitan hasta 4 parametros.
- Falta arreglar el estilo para cuando solo se debe pintar el boton de ver los soportes.

![Image](https://github.com/user-attachments/assets/501d904d-def1-427a-8ee9-85a4ac824c9a)

**Comment by faidercamilo26** [comment]
Aunque ya se aplicaron las funciones a los botones y solo faltaba una parte de estilos, se obta por hacer una refactorizacion para mejorar la manera en como se manejan las funciones que ejecuta cada boton, puesto que ahora como esta implementado el componente padre es el que le pasa la funcion al componente hijo junto con el boton, pero para respetar el principio de responsabilidad unica lo mejor esque cada componente hijo sea el que maneje las funcionalidades de los botones. Por este motivo puede que me demore más realizando esta tarea.

**Comment by faidercamilo26** [comment]
Se finaliza el ajuste de los botones para el modal que gestiona los soportes, estos son todos los cambios:

- Se elimina el campo ```Condicional``` de la interface de los botones, ahora las validaciones de los condicionales se realiza mediante el nombre del button, esto se realiza para poder implementar un condicional a cada boton en caso de ser necesario.
- Se agregan los codnidonales a cada boton para que aparezcan solo cuando son necesarios.
- Se agrega un condicional para que el boton de comentarios no aparezca cuando el estado del cumplido es ```Cargando documentos``` puesto que en este estado inicial ningun soporte tiene mensajes, este boton empieza a aparecer en los demas estados, para que la persona de contratación u el ordenador puedan agregar comentarios o el supervisor pueda revisar los comentarios de los soportes.
- Se edita la interface de los botones para que la Funcion sea opcional, puesto que en este componente se van a manejar las funciones directamente desde el componente que recibe los botones.
- Se crea la función que maneja todas las acciones de los botones,para que dependiendo del boton al que se le de click se ejecute la funcion correspondiente.
- Se ajustan los estilos para que se vean bien visualmente los botones, sin importar si solo se muestran dos o los tres.

### Estado Cargando documentos

![Image](https://github.com/user-attachments/assets/d41a2de3-70b3-4b29-8084-0839413fdacb)

### Estado Pendiente revision contratación y Estado Pendiente revision ordenador

![Image](https://github.com/user-attachments/assets/5acc9339-c38a-48a2-b4ef-7210379e6adc)

### Estado rechazado contratación y Estado rechazada ordenador


![Image](https://github.com/user-attachments/assets/f2b50627-72d6-482b-8f03-34447ad68674)

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 Buen trabajo.
