### ISSUE TITLE
Revisar y ajustar modals

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#177]
Se requiere realizar el ajuste de los modales del sistema.

**Sub Tareas**

- [x] Revisar las configuraciones de medidas minimas y maximas de los modales, así como su tamaño por defecto.
- [ ] Revisar aspectos como color de botones y demás del aspecto general de los modals

**Criterios de aceptación**

- [ ] Issue documentado.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by stevencol** [comment]
Se inicia con actividad, El plan es comenzar por el rol superviso

**Comment by stevencol** [comment]
El primer modal que se detecta con malas proporciones es del modal despues de firmar el documento 
![image](https://github.com/user-attachments/assets/228d1cfa-9f3c-4171-b310-1e09f6ff5fc3)

**Comment by stevencol** [comment]
## No era de la tarea pero se Realiza Ajuste
- En una tarea anterior se había modificado el código para que al momento de generar el soporte también se guardara, pero por alguna razón no se estaba ejecutando, por lo cual se soluciona y de paso se arregla el modal 
![test](https://github.com/user-attachments/assets/65fbdde7-2182-4d43-98ee-d97d3202d381)

**Comment by stevencol** [comment]
Se modifica la posición del botón cerrar 
De: 

![image](https://github.com/user-attachments/assets/3e9ed4ff-bd6b-4604-b389-d7530b0e207d)

A: 
![image](https://github.com/user-attachments/assets/d0b51b29-a42e-4db6-ae86-a5e3ae6fff59)

**Comment by stevencol** [comment]
Modal visualizar soportes en supervisor: 
De:

![image](https://github.com/user-attachments/assets/51b1ee7a-073a-4fa0-b058-99ebbe22af2e)

A:

![image](https://github.com/user-attachments/assets/49c453d6-3446-40f3-ac78-a83f67694088)

**Comment by stevencol** [comment]
Listar documentos Ordenador: 

De; 
![image](https://github.com/user-attachments/assets/f582ffb3-9f9e-402b-9f9c-d15e48699b62)

A: 
![image](https://github.com/user-attachments/assets/fd632719-5f3f-4f62-8915-3a58df268ba4)

**Comment by stevencol** [comment]
Ver documentos ordenador:
De;
![image](https://github.com/user-attachments/assets/62cee801-43e9-4c1c-a9a1-3573d474a6f2)

A:
![image](https://github.com/user-attachments/assets/07dc9ddd-7cf2-4b8d-9ca5-6b2877dd19f3)

**Comment by stevencol** [comment]
Se ajustan espacios: 
![image](https://github.com/user-attachments/assets/75a752d7-50a3-44d7-9b02-288f50053342)

se ajusta tamaño del nombre del archivo: 
![image](https://github.com/user-attachments/assets/73a7aab2-bc7f-4ab9-8916-977a49b0b225)

**Comment by stevencol** [comment]
Se ajusta tamaño al ver el documento en el caso de que no tenga funciones no se muestra el footer 
![image](https://github.com/user-attachments/assets/81ec8c89-a08f-49cc-ad85-0a1de5cd34b9)

![image](https://github.com/user-attachments/assets/73b77bfb-d471-48d6-8882-b98815e0ef5a)

**Comment by stevencol** [comment]
Se agrega modal de carga al consultar las solicitudes del proveedor 
![test](https://github.com/user-attachments/assets/54216d49-53c1-403a-9804-8af0d345efad)

**Comment by JuanCamiloMartinezLopez** [comment]
@stevencol Buen trabajo.
