### ISSUE TITLE
Realizar pruebas funcionales al modulo de revision_cumplido_prov

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#178]
Se requiere realizar las pruebas funcionales del módulo desplegado de revision_cumplido_prov

**Sub Tareas**

- [x] Tomar como base las [anteriores pruebas](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/Es_-S3NLsGtNmaof1KBp4DwBYFzs9_9ZF5dqsJ0bwLQobg?e=RuQVOU) 
- [x] Realizar las pruebas en el cliente desplegado en [pruebas](https://pruebascumplidosprovmf.portaloas.udistrital.edu.co/) 
- [x] Documentar en el formato indicado en la carpeta de pruebas del proyecto.

**Criterios de aceptación**

- [x] Documento de pruebas funcionales.
- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se ha comenzado las pruebas funcionales en ambiente de pruebas

[carpeta de pruebas](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/Es_-S3NLsGtNmaof1KBp4DwBYFzs9_9ZF5dqsJ0bwLQobg?e=22P63G)

**Comment by mantnicot** [comment]
Se han realizado las pruebas que se consideran , se ha actualizado la carpeta con los datos

[carpeta de pruebas ya hechas](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/Es_-S3NLsGtNmaof1KBp4DwBYFzs9_9ZF5dqsJ0bwLQobg?e=22P63G)

**Comment by jcmurilloa** [comment]
Muy buen trabajo @mantnicot!
