### ISSUE TITLE
Reunión pruebas sistema

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#179]
Realizar una reunión para revisar el estado de cumplidos prov  deslegado.

**Sub Tareas**

- [x] Revisar el funcionamiento del sistema.

**Criterios de aceptación**

- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico/SoSM.
- [ ] Artefacto solicitado satisface la necesidad.

**Comment by faidercamilo26** [comment]
Se realiza la reunión en la cual se evidencian inconvenientes con el proyecto desplegado, se verifican cuáles pueden ser los inconvenientes y se trabaja para solucionarlos. Adicional a esto se realiza una actualización de variables de entorno para que las variables usen los endpoints de autenticación, se adjunta link de la [reunión](https://teams.microsoft.com/l/meetup-join/19%3ameeting_MGExOTIyNmMtYTY4OS00ZGI0LWE5YTktYmQ1ZGQwMmU0YjZm%40thread.v2/0?context=%7b%22Tid%22%3a%22d51388ef-6ab0-4363-9f94-d56644a45970%22%2c%22Oid%22%3a%22e79ddc6c-1555-42d8-83fe-5a759905daaf%22%7d) como prueba de esta.

**Comment by stevencol** [comment]
En la reunión se verificó el funcionamiento del sistema, donde surgieron algunos errores en el despliegue. Actualmente, estamos a la espera del equipo técnico para identificar las causas de los inconvenientes en el entorno desplegado para pruebas, ya que en la rama local no se han presentado estos problemas.

**Comment by JuanCamiloMartinezLopez** [comment]
Se solucionan los problemas siendo estos por parte de la infraestructura en aws donde se le pide al ingeniero Jaime que ejecute las validaciones de forma manual.
