### ISSUE TITLE
Actualización documentación  (Descripción técnica y diagnóstico final)

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#180]
Se requiere realizar los ajustes necesarios para actualizar los documentos de [descripción técnica](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/ESD9I23i7eJJj8Lt42W3bc4BEeJHf0kcW5GWS029J9El3w?e=qD1NNT) y [diagnóstico final](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/Ea1TD-vEVChDpyLm_Jx74F4BGnbfenEbJT9lpFXBmSPw1w?e=6uA0N5)

**Sub Tareas**

- [x] Ajustar los documentos indicados con los cambios realizados al módulo (mf, mid y crud) según corresponda.
- [x] Tener en cuenta los cambios de funcionalidad agregados.

**Criterios de aceptación**

- [ ] Documentación actualizada.
- [ ] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by stevencol** [comment]
Se inicia con los ajustes del documento DESCRIPCIÓN TÉCNICA DEL SISTEMA DE REVISION

**Comment by stevencol** [comment]
Se modifica la sección de base de datos consultada y se modifican y agregan nuevas rutas que son utilizadas por el proyecto. Se cargará el archivo para su revisión y resolver ciertas dudas generadas
[Descripcion técnica.docx](https://github.com/user-attachments/files/17301431/Descripcion.tecnica.docx)

**Comment by stevencol** [comment]
Se termina modificaciones de DESCRIPCIÓN TÉCNICA DEL SISTEMA DE REVISION aplicando retroalimentación recibida en Daily

**Comment by stevencol** [comment]
[Descripcion.tecnica.docx](https://github.com/user-attachments/files/17317531/Descripcion.tecnica.docx)

**Comment by stevencol** [comment]
Se actualiza directamente el documento diagnóstico final, teniendo encuenta los cambios

**Comment by JuanCamiloMartinezLopez** [comment]
@stevencol Buen trabajo.
