### ISSUE TITLE
Actualización documentación  (Matriz de acceso y casos de soporte)

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#181]
Se requiere realizar los ajustes necesarios para actualizar los documentos de [matriz de acceso](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EW_9cT2avWdLv_MeRLwqZjIBiQbuYV9o1qWX3BA-z8eI8A?e=PScpZ2) y [casos de soporte](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EeCfvGOMJ55DiMv3ajxEwVQBG6Q3pZgwU8EcfKEiKt26mg?e=ikU8Lt)

**Sub Tareas**

- [x] Ajustar los documentos indicados con los cambios realizados al módulo (mf, mid y crud) según corresponda.
- [x] Tener en cuenta los cambios de funcionalidad agregados.

**Criterios de aceptación**

- [x] Documentación actualizada.
- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
## :triangular_flag_on_post: **Actualización documentación**  :triangular_flag_on_post:

### Matriz de acceso

Se agregaron los datos de acceso a la funcionalidad de los comentarios, indicando las funcionalidades y limitaciones de cada uno de los roles, en resumen, se explica que los ordenadores y el equipo de contratación tienen la posibilidad de crear y visualizar comentarios de cada soporte, en cambio, los supervisores solo tienen permitido visualizar los comentarios de un soporte que hayan sido subidos ya sea por el equipo de contracción o el ordenador correspondiente.

### Casos de soporte

Se han generado dos casos de soporte detallados relacionados con los problemas del sistema de **Revisión Cumplidos Proveedores**. Estos casos abordan los errores comunes que pueden ocurrir y posibles soluciones técnicas para cada uno.

**Error al Agregar Comentarios a un Soporte y No Se Registra:**
   - Se describe el problema cuando los usuarios intentan agregar un comentario a un soporte y este no se registra correctamente.
   - Se analizaron posibles causas como fallos de conexión a la base de datos, errores en la lógica de negocio o validación de campos.
   - Se establecieron procedimientos de resolución incluyendo la revisión de logs, validación de datos y pruebas manuales.

2. **Problemas al Conectarse a Otras APIs para Obtener Información:**
   - Se documentaron los errores al conectar el sistema a APIs externas que proporcionan información relevante, como contratos y datos de proveedores.
   - Entre las causas identificadas están fallos de red, timeouts, errores de autenticación y problemas de mapeo de datos.
   - Se propusieron soluciones como la verificación de la conectividad, ajustes en los tiempos de espera y la validación de las respuestas de las APIs.


[Matriz de acceso](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EW_9cT2avWdLv_MeRLwqZjIBiQbuYV9o1qWX3BA-z8eI8A?e=ALfqQL)
[Casos de soporte](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EeCfvGOMJ55DiMv3ajxEwVQBG6Q3pZgwU8EcfKEiKt26mg?e=nNufr3)

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 Buen trabajo.
