### ISSUE TITLE
Adaptar vista de reversión a la estructura actual del proyecto.

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#182]
Debido a la reestructuración del proyecto mf se requiere adaptar la vista de reversión.

**Sub Tareas**

- [x] Adaptar la vista a la nueva estructura.
- [x] Agregar funcionalidades nuevas (popManager, componente tabla, etc.)

**Criterios de aceptación**

- [x] Vista con funcionalidad desarrollada.
- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
## :triangular_flag_on_post: **Adaptación vista reversión de cumplidos**  :triangular_flag_on_post:

### Trabajo realizado en la issue:
- Se actualiza la rama develop, se aplican los cambios de la rama `feature/VistaCumplidosReversibles` manualmente para evitar que la integración de las ramas causara fallos en la aplicación.
- Se actualiza la manera de utilizar el componente `app-tabla` incluyendo los datos que se le deben pasar para la correcta visualización de los datos de los cumplidos que se pueden revertir por un ordenador.
- Se agrega la funcionalidad para visualizar los soportes del cumplido y para poderlo revertir en caso de ser necesario.

![Image](https://github.com/user-attachments/assets/1d5f6ecb-92b7-44c8-b9ba-b4fb5dab3fa0)

- Se cambia la vista que se tenía cuando no habían cumplidos que se pudieran revertir por parte de un ordenador, antes aparecía un mensaje en rojo indicando que no habían cumplidos con posibilidad de revertir y un botón verde para que al dar click redirigiera al inicio, esto visualmente no era muy atractivo, por eso se cambio, ahora aparece una alerta informativa indicando que no hay cumplidos, y despues de 3 segundos se redirige al usuario a la pagina de inicio.

![Image](https://github.com/user-attachments/assets/542bebce-8de0-4214-8887-5a85b1796985)

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 Buen trabajo.
