### ISSUE TITLE
Adaptar vista de históricos a la estructura actual del proyecto.

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#183]
Debido a la reestructuración del proyecto mf se requiere adaptar la vista de Histórico.

**Sub Tareas**

- [x] Adaptar la vista a la nueva estructura.
- [x] Agregar funcionalidades nuevas (popManager, componente tabla, etc.)

**Criterios de aceptación**

- [x] Vista con funcionalidad desarrollada.
- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by stevencol** [comment]
Se inicia con actividad inicialmente buscado la rama donde se habían elaborado las vistas https://github.com/udistrital/revision_cumplidos_proveedores_mf/tree/feature/issue-135

**Comment by stevencol** [comment]
Se traslada vista

**Comment by stevencol** [comment]
![image](https://github.com/user-attachments/assets/0f6527b9-ff2f-4e46-af06-2e8ba6a9d6b0)

**Comment by stevencol** [comment]
Se adapta tabla al formato implementado en el sistema 
![image](https://github.com/user-attachments/assets/0ea93a96-93eb-4261-a0af-528e62ddd50d)

**Comment by stevencol** [comment]
Se termina la adaptación de las vistas, para lo cual la tabla y la lista de documentos cargados son datos creados únicamente con la finalidad de la creación de las vistas.

**Comment by stevencol** [comment]
![image](https://github.com/user-attachments/assets/b3e136a6-e9f9-4165-b214-ffb3c660f670)


![image](https://github.com/user-attachments/assets/0473ea4e-0d19-4761-8eb8-65f5f33ed38a)

**Comment by JuanCamiloMartinezLopez** [comment]
@stevencol Buen trabajo.
