### ISSUE TITLE
Ajustes finales modulo revision_cumplido_prov - Parte I

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#184]
Se requiere realizar los últimos ajustes resultado de las pruebas funcionales #178 

**Sub Tareas**

- [x] Agregar pop up de carga al proceso de subida de documento. 
- [x] Agregar "sin observación" como valor por defecto para los soportes
- [x] Revisar textos de pop ups, ej:

     - 	pop up previo a enviar a revisión
	 "¿Está seguro de que desea aprobar los soportes?" debería ser 
	 enviar a revisión el cumplido o algo similar.
- [ ] Revisar notificaciones internas.
- [x] Hacer obligatorio el cumplido a satisfacción, y en caso de crear varios, "eliminar" los anteriores.
- [ ] Revisar input documentos (estilo y eliminar documento después de subido).

**Criterios de aceptación**

- [ ] Cambios realizados.
- [ ] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by stevencol** [comment]
Se inicia con la acidad colocando pop up de carga al proceso de subida de documento.

**Comment by stevencol** [comment]
Se implementa; 
1- pop up de carga al proceso de subida de documento.
2- Mensaje de Sin observaciónes en el documento
3: Eliminar documento del input después de subido

**Comment by stevencol** [comment]
![test](https://github.com/user-attachments/assets/2ef60d35-4a7b-4212-980a-089715a9e0a2)

**Comment by stevencol** [comment]
Se remplaza mensaje :
![image](https://github.com/user-attachments/assets/1d14e6d1-14ff-4046-9733-47150fdb3247)

**Comment by stevencol** [comment]
Se ajusta para que al crear el informe de satisfacción se remplaza el anterior si este existe 
![test](https://github.com/user-attachments/assets/835fbad3-2da2-4dc9-bb3e-bb628c6a2253)

**Comment by JuanCamiloMartinezLopez** [comment]
@stevencol Buen trabajo.
