### ISSUE TITLE
Ajustes finales modulo revision_cumplido_prov - Parte II

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#185]
Se requiere realizar los últimos ajustes resultado de las pruebas funcionales https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/issues/178

**Sub Tareas**

- [x] Cambiar nombres incorrectos:
	- configuracion(menus): cambiar nombres como aprobación informe y aprobación pago por nombres mas 
       coherentes.
	- cambiar nombre de informe seguimiento por cumplido a satisfacción.
	- cambiar nombre de aprobacion pago por autorización de giro.
- [x]  Agregar label al text area de comentarios:
	"ingrese un comentario:"
- [x] Mostrar tipo contrato en las tablas (inicial de supervisor, y revision de contratación y ordenador).
- [x] Eliminar la consulta de cambio estado del modal de soportes(supervisor, contratación y ordenador).
- [x] Ajustar la imagen del escudo en la autorización de giro.

**Criterios de aceptación**

- [x] Cambios realizados.
- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
## Ajuste Autorizacion de Giro

Se ajusta el encabezado del documento de autorización giro, antes se estaba utilizando la función general Header() para realizar este encabezado, pero en alguno de los commits se cambió esta parte, se implementa nuevamente la función general para que el header comparta el mismo estilo que el cumplido satisfacción y con esto se soluciona el inconveniente que se tenia con el desbordamiento del escudo.

![Image](https://github.com/user-attachments/assets/f18603aa-5d43-43d6-8ec5-6064f0fac75f)

**Comment by faidercamilo26** [comment]
## Campo tipo de contrato en las tablas

Se agrega el campo de tipo contrato en las tablas correspondientes.

### Tabla inicial supervisor

![Image](https://github.com/user-attachments/assets/805f5576-7092-4828-8b3a-23602fe53cfb)

### Revisión cumplidos contratación

![Image](https://github.com/user-attachments/assets/25d7216f-ff1f-4012-9ebb-0ef62e3f5c96)

### Revisión cumplidos ordenador

![Image](https://github.com/user-attachments/assets/ea8eb361-818e-49a8-b21e-864ba2dc57fe)

**Comment by faidercamilo26** [comment]
## Label Comentarios

Se agrega el label al text area para que sea mas clara su funcionalidad.

![Image](https://github.com/user-attachments/assets/abf85772-cbb0-4f70-9bf8-8004e0039837)

**Comment by faidercamilo26** [comment]
## Cambio Nombres

- Se realiza el cambio de nombre en la base de datos de `informe seguimiento` a `cumplido a satisfacción` .
![Image](https://github.com/user-attachments/assets/f5e6f0f8-d01f-4683-b15d-54ba52b6cfdf)

- Se realiza el cambio de nombre en la base de datos de `autorizacion pago` a `autorizacion giro` .
- Se cambia el menú del equipo de contratación de `Aprobacion Informe` a `Revisión Cumplidos`.
![Image](https://github.com/user-attachments/assets/fdc2ee9f-40e7-4eb8-8493-eafcb5b2f3ef)

- Se cambia el menú del ordenador de `Aprobacion Cumplido` a `Revisión Cumplidos`.

![Image](https://github.com/user-attachments/assets/c103e0fd-debb-4ca4-8f76-92540b817da6)

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 Buen trabajo.
