### ISSUE TITLE
Creación vista evaluacion proveedores - Gestión evaluadores

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#186]
Se requiere realizar las vistas de gestion-evaluadores con base en los [mockups](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EjLBmhGhO-RLlZkurA1CbfoB3ZWXSdbTbAPvAHR4tBV5qA?e=5xs2f5) 

**Sub Tareas**

- [x] Usar [expansion panel](https://v16.material.angular.io/components/expansion/examples) cuando sea requerido 
- [x] Usar form builder para los formularios con los validadores necesarios
- [x] Usar componente generales según se requiera
- [x] Crear vistas en una rama desde develop con la estructura acordada.

**Criterios de aceptación**

- [x] Vistas desarrolladas.
- [ ] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by stevencol** [comment]
Se inicia con la actividad, se comienza analizando el mockup y separando los componentes por cajas.

![Modulo de evaluación proveedores v4-Gestión evaluadores drawio](https://github.com/user-attachments/assets/f22b077e-b01f-4f39-abee-24c5048ba310)

**Comment by stevencol** [comment]
Se inicia con el componente inicial: gestion de evaluadores 
![componete gestion evaluadores](https://github.com/user-attachments/assets/3e6b037e-280d-475f-98b0-b13ed6ec6435)

**Comment by stevencol** [comment]
Se agrega componetne item  a evaluar:
![item a evaluar](https://github.com/user-attachments/assets/5d7091d3-0e87-49af-9e2a-18dae40933f8)

**Comment by stevencol** [comment]
Se agrega funcionalidad a item a evaluar: 
![funcionalidad item a evaluar](https://github.com/user-attachments/assets/23465a16-9136-4520-8ec3-6b84a4bcafb5)

**Comment by stevencol** [comment]
Se modifica competente Ítem a evaluar:


![item a evaluar response](https://github.com/user-attachments/assets/a2cdd565-48e8-41ce-b76d-6889c0020e32)

**Comment by stevencol** [comment]
Se crea componente Ítem a evaluar: 

![Evaluadores](https://github.com/user-attachments/assets/664ec2d9-cbc5-4608-bd88-f39388eee858)

**Comment by JuanCamiloMartinezLopez** [comment]
@stevencol Buen trabajo.
