### ISSUE TITLE
Creación vista evaluacion proveedores - Lista contratos evaluacion

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#187]
Se requiere realizar las vistas de listar-contratos-evaluacion con base en los [mockups](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EjLBmhGhO-RLlZkurA1CbfoB3ZWXSdbTbAPvAHR4tBV5qA?e=5xs2f5) 

**Sub Tareas**

- [x] Usar [expansion panel](https://v16.material.angular.io/components/expansion/examples) cuando sea requerido 
- [x] Usar form builder para los formularios con los validadores necesarios
- [x] Usar componente generales según se requiera
- [x] Crear vistas en una rama desde develop con la estructura acordada.

**Criterios de aceptación**

- [x] Vistas desarrolladas.
- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
## :triangular_flag_on_post: **Vistas iniciales**  :triangular_flag_on_post:

### Vista listar-contratos-evaluación

Se realiza la creación de la vista, se usa el componente general tabla que se ha usado en todo el proyecto para mantener la uniformidad de las tablas, la tabla por defecto ya tiene una manera de mostrar u ocultar una acción mediante una variable booleana, se entiende que a los supervisores les debe aparecer la opción de asignar evaluadores, pero a los evaluadores no les debe aparecer esta acción, todavía falta implementar la función para que se esconda esta acción en los evaluadores, solucionando esto se podría usar la misma vista tanto para supervisores como para evaluadores.


![Image](https://github.com/user-attachments/assets/97b5193c-67ef-46e6-9c76-53f5135de255)

**Comment by faidercamilo26** [comment]
Se centra el titulo y la nota para darle un mejor aspecto a la vista, se separan los componentes con cards para que se pueda notar donde finaliza uno y comienza el otro, se tienen dos posibles diseños para esta parte.

![Image](https://github.com/user-attachments/assets/29418c55-75a7-467c-9a5b-4c9d495e71aa)


![Image](https://github.com/user-attachments/assets/72d7c0fc-365a-443d-9cd7-1c8619172eeb)

**Comment by faidercamilo26** [comment]
Se adapta el color del titulo para que concuerde con el color de todo el proyecto y se hace responsive la vista.

![Image](https://github.com/user-attachments/assets/c69a8038-55f7-4590-a388-e86765bc1f00)

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 Buen trabajo.
