### ISSUE TITLE
Actualizar Mockups módulo evaluación proveedores

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/Cumplidos_y_certificaciones_documentacion#188]
Se requiere realizar la actualización de los mockups relacionados con el módulo de evaluación proveedores, según actualización de requerimientos. 

**Sub Tareas**

- [x] Actualizar el diseño del mockup con base en los requerimientos.
- [x] Presentar el mockup al equipo
- [x] Realizar ajustes según comentarios del equipo
- [x] Presentar al equipo y cliente el mockup definitivo para el desarrollo.

**Criterios de aceptación**

- [x] Mockup aprobado por equipo y cliente.
- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se han actualizado os mockups con base a los comentarios del equipo y del lider tecnico

[Carpeta mockups](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EjLBmhGhO-RLlZkurA1CbfoB3ZWXSdbTbAPvAHR4tBV5qA?e=c1aS0l)

![Image](https://github.com/user-attachments/assets/916dbc65-cc4a-4f5b-b252-e4a634e129cb)
![Image](https://github.com/user-attachments/assets/8eb11ef8-0f0f-4b73-8ed9-c1c3f234ecc4)
![Image](https://github.com/user-attachments/assets/62deb1da-3761-45b9-a286-76f197a59b61)
![Image](https://github.com/user-attachments/assets/d869147d-4dd7-430d-b1f6-ff33eaa77aa8)
![Image](https://github.com/user-attachments/assets/ebf79096-65aa-4f99-9f8c-4a3083c8dc7f)
![Image](https://github.com/user-attachments/assets/b64380aa-523b-4fa8-bbf4-b8fd79f675dc)

**Comment by jcmurilloa** [comment]
Muy buen trabajo @mantnicot, por favor tener en cuenta las sugerencias antes de exponer al cliente para su respectiva aprobación.

**Comment by mantnicot** [comment]
los mockups fueron aprobados por el usuario

[Carpeta mockups](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EkSXz-N7sqdDkIPS9SWb3tgBC1YUxPlVZlCVF7-6SHXh9w?e=RHWf4L)
![Image](https://github.com/user-attachments/assets/2ec54c20-2366-42c8-ac76-05bb27b6249c)

**Comment by jcmurilloa** [comment]
Muy buen trabajo @mantnicot
