### ISSUE TITLE
Concertar, desarrollar y levantar sesión de muestra a usuario y funcionamiento

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/Cumplidos_y_certificaciones_documentacion#189]
Se requiere realizar la concertación, desarrollo y levantamiento del acta de sesión de muestra a usuario y funcionamiento

**Sub Tareas**

- [x] Concertar reunión con el cliente.
- [x] Desarrollar la reunión con el cliente.
- [x] Proyectar acta de la reunión.
- [x] Recolectar las firmas correspondientes.

**Criterios de aceptación**

- [x] Acta revisada por el líder de proyecto.
- [x] Acta firmada por las partes con anexo de historias de usuario o mockup.
- [x] Acta y anexos documentados.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [X] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [X] No tiene bloqueos que impidan su ejecución.
- [X] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se ha agendado la sesión 18/10/2024 a las 11 am

[enlace reunión](https://teams.microsoft.com/l/meetup-join/19%3ameeting_Zjc5MzAzMzEtM2JlZC00OTliLThkYmYtNTA0MjA1ZjgwNTQw%40thread.v2/0?context=%7b%22Tid%22%3a%22d51388ef-6ab0-4363-9f94-d56644a45970%22%2c%22Oid%22%3a%221dd8bdce-0185-41b4-8caa-01da7e5506b2%22%7d)

**Comment by mantnicot** [comment]
Se adjunta el acta de la reunión
[acta sin firmas](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EWXSwQfDhiNBiZ1hmZtSvewBZL1Wph6g8yv9iDslYRAAAA?e=hrB4jz)

**Comment by jcmurilloa** [comment]
Acta revisada y con VoBo para recolección de firmas @mantnicot

**Comment by mantnicot** [comment]
se adjunta el acta firmada 

[acta firmada](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EW0pHimtkplFg12nRqo0qZcBFZVwwvrXNVYKLLPd-XExvA?e=hI3P73)

**Comment by jcmurilloa** [comment]
Excelente trabajo @mantnicot
