### ISSUE TITLE
Concertar reunión exploratoria para el módulo de evaluación

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/Cumplidos_y_certificaciones_documentacion#19]
Se requiere realizar la exploración del módulo existente de evaluación por parte del cliente para la socialización de la lógica del negocio

**Sub Tareas**

- [x] Concertar reunión exploratoria con el cliente
- [x] Desarrollar la reunión exploratoria
- [x] Proyectar acta de la reunión

**Criterios de aceptación**

- [x] Acta revisada por el líder de proyecto
- [x] Acta firmada por las partes

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se agrega el acta ya con las firmas puestas


[Acta firmada](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EY5lqGGpp71NvQnwqvh6guMBXaDRsX_wMIrT38VM9oz2yg?e=4iIzgc)

**Comment by jcmurilloa** [comment]
Gran maratón para conseguir las respectivas firmas @mantnicot Felicitaciones!
