### ISSUE TITLE
Gestión para la creación de manuales de usuario del sistema Cumplidos proveedores

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/Cumplidos_y_certificaciones_documentacion#190]
Se requiere realizar la gestión para la creación de los manuales de usuario para el sistema Cumplidos proveedores

**Sub Tareas**

- [x] Generar contacto con responsable de Manuales en funcionamiento
- [x] Levantar requerimientos de actualización
- [x] Generar el requerimiento de actualización de Manuales
- [x] Revisión de manuales generados

**Criterios de aceptación**

- [x] Solicitud de creación o actualización de Manuales con responsable
- [x] Manuales e instructivos actualizados

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se ha tenido la reunión con viviana 
[enlace reunión](https://teams.microsoft.com/l/meetup-join/19%3ameeting_MDAwOGJlZTgtNzEwOC00MjhlLThiNmMtYjViOGZlMDRmMDAx%40thread.v2/0?context=%7b%22Tid%22%3a%22d51388ef-6ab0-4363-9f94-d56644a45970%22%2c%22Oid%22%3a%221dd8bdce-0185-41b4-8caa-01da7e5506b2%22%7d)

Se establecio en la misma que se entregaran el día 18/10/2024

**Comment by mantnicot** [comment]
Se ha generado los manuales , se hicieron diferentes recomendaciones y se queda a espera del de ordenador
[Carpeta de manuales](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/Eio1agdmFspAl4oy6tIBHQABlxFM5u4sq_luMUF4-0V29A?e=HPoVHA)

**Comment by jcmurilloa** [comment]
Entendido @mantnicot, dejaremos abierta entonces la issue para el instructor de ordenador.

**Comment by mantnicot** [comment]
Se ha subido el ultimo manual y actualizado el resto a la carpeta de manuales 
[Carpeta de manuales](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/Eio1agdmFspAl4oy6tIBHQABlxFM5u4sq_luMUF4-0V29A?e=HPoVHA)

**Comment by jcmurilloa** [comment]
Excelente gestión para los manuales @mantnicot
