### ISSUE TITLE
Revisar issues de sonarqube para revision_cumplido_prov_mid

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#191]
Se requiere realizar la revisión de los issues encontrados por [sonarqube](https://sonarqube.portaloas.udistrital.edu.co/project/issues?id=udistrital%3Arevision_cumplido_prov_mid&resolved=false&severities=MAJOR) 

**Sub Tareas**

- [x] Revisar problemas de code smell
- [x] Revisar problemas de tipo critical y major
- [x] Analizar cuales cambios son necesarios
- [x] de ser posible solucionar los casos sencillos

**Criterios de aceptación**

- [x] Revisión de los issues con su analisis
- [x] issue documentado.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
## :triangular_flag_on_post: **Solución problemas sonarqube**  :triangular_flag_on_post:

### Complejidad de la función
No se realiza este cambio, puesto que se tendría que refactorizar totalmente la función `ObtenerInformacionContratoProveedor()` para poder bajar su complejidad y esto puede ocasionar posibles fallos a largo plazo.

![Image](https://github.com/user-attachments/assets/2f4b9f5a-7c79-4b32-9528-300244685d8c)

### Uso excesivo de la misma descripción de error

Se corrige esta parte, se cambian los mensajes de posibles errores para que el mensaje sea acorde al inconveniente que se pudo haber presentado y de esta manera ya no se esta utilizando tantas veces el mismo mensaje de error.

![Image](https://github.com/user-attachments/assets/5eb8d4b9-0894-4a41-807f-726b0b09cdb6)


### Complejidad de la función

No se realiza este cambio, puesto que se tendría que refactorizar totalmente la función `ObtenerActaInicio()` para poder bajar su complejidad y esto puede ocasionar posibles fallos a largo plazo.


![Image](https://github.com/user-attachments/assets/727b876b-690f-4835-944f-1fa392766ade)


### Uso varias veces del literal `application/json`

No se ha procedido con la corrección de este inconveniente, ya que el literal `application/json` se utiliza en tres funciones diferentes. Esto implicaría la creación de una constante en cada una de las funciones, lo cual no aportaría una mejora significativa en términos de reducción o simplificación del código.

![Image](https://github.com/user-attachments/assets/8415ae3b-cfc2-40a1-b4f4-14faa5fc1260)


### Complejidad de la función

No se realiza este cambio, puesto que se tendría que refactorizar totalmente la función `ValorLetras()` para poder bajar su complejidad y esto puede ocasionar posibles fallos a largo plazo.

![Image](https://github.com/user-attachments/assets/4510a71b-c514-4ae4-8856-2461814260ab)

### Duplicación de código

No se procese a solucionar este inconveniente puesto que me indica que se debe editar el archivo `routers/commentsRouter_controllers.go` que es autogenerado, por lo tanto no se debe editar para que siga el correcto funcionamiento del proyecto.

![Image](https://github.com/user-attachments/assets/faf2aa10-7afd-4d5e-b89e-63214b6d9588)


### Duplicación de código

Se crea la variable  `error_supervisor_contrato := fmt.Errorf("Error al obtener el supervisor del contrato")` y se utiliza en las tres ocasiones que se usa el mismo mensaje de error.

![Image](https://github.com/user-attachments/assets/26b33b60-d7b7-4843-8c7a-c9b926b33f2a)


### Duplicación de código

Se crea la variable `error_json := fmt.Errorf("Error al convertir el json")` y se utiliza en las cuatro ocasiones que se usa el mismo mensaje de error.

![Image](https://github.com/user-attachments/assets/a2dcd091-1944-43fe-b2e0-58038b1348d7)

### Duplicación de código

No se ha procedido con la corrección de este inconveniente, ya que el mensaje de error `"Error al consultar los cumplidos pendientes de revision por el ordenador"` se utiliza en tres funciones diferentes. Esto implicaría la creación de una constante en cada una de las funciones, lo cual no aportaría una mejora significativa en términos de reducción o simplificación del código.

![Image](https://github.com/user-attachments/assets/27fd14a6-89ca-4334-abe3-6f071ebd5236)

**Comment by faidercamilo26** [comment]
### Parámetros de las funciones para crear el cumplido satisfacción

Lo recomendable es tener máximo 7 parámetros en una función, sin embargo, el cumplido satisfacción se crea párrafo por párrafo,  este documento contiene demasiada información dinámica, por eso a cada función se le pasan varios parámetros, para cambiar esto se tendría que realizar una refactorización exhaustiva de la manera en como se crea este documento.

![Image](https://github.com/user-attachments/assets/ca515f66-e5e3-4f6b-bf96-4f40863aa8ab)


### Duplicación de código

No se modifica este código debido a que, aunque existe duplicación en algunas ramas del bloque `case`, el contexto específico de cada una es diferente. En este caso, agrupar el código duplicado en una función o método separado no aportaría una mejora significativa en la claridad o mantenibilidad.

![Image](https://github.com/user-attachments/assets/18eb3c09-76fb-49f5-a4c3-d6b8ac21de3e)

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 Buen trabajo.

**Comment by faidercamilo26** [comment]
Se sube documenta de las pruebas a realizadas a los endpoints del mid para verifica sus respuestas en caso de errores.

[pruebas endpoints.pdf](https://github.com/user-attachments/files/17507655/pruebas.endpoints.pdf)
