### ISSUE TITLE
Revisar issues de sonarqube para revision_cumplido_prov_mf

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#192]
Se requiere realizar la revisión de los issues encontrados por [sonarqube](https://sonarqube.portaloas.udistrital.edu.co/project/issues?id=udistrital%3Arevision_cumplidos_proveedores_mf&resolved=false&types=CODE_SMELL) 

**Sub Tareas**

- [x] Revisar problemas de code smell
- [x] Revisar problemas de tipo critical y major
- [ ] Analizar cuales cambios son necesarios
- [ ] de ser posible solucionar los casos sencillos

**Criterios de aceptación**

- [ ] Revisión de los issues con su análisis
- [ ] issue documentado.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by stevencol** [comment]
Se inicia con actividad iniciando por code smell:

**Comment by stevencol** [comment]
## Code Smell

1. 
![image](https://github.com/user-attachments/assets/6ac6c1ac-b28d-4b6d-9fde-5e1250fe4a2e)

- Código repetido

``` JavaScript
    .mat-mdc-header-row{
        background: #FFEAE6;
        text-align: center;
        vertical-align: middle;
      }

      .mat-mdc-header-row {
        box-shadow: none !important;
        height: 30px !important;
        background-color:#E8DADA;
        font-weight: bold;


      }
```
Se unifica por:

``` JavaScript
     .mat-mdc-header-row {
        background: #E8DADA;
        text-align: center;
        vertical-align: middle;
        box-shadow: none !important;
        height: 30px !important;
        font-weight: bold;
    }
```

**Comment by stevencol** [comment]
2.
![image](https://github.com/user-attachments/assets/da592ed0-1449-4ef0-a5e4-155babcd2898)
![image](https://github.com/user-attachments/assets/934f7c7a-2e3f-4d7e-9186-30cd70542d61)
![image](https://github.com/user-attachments/assets/5ff66839-c760-4ca5-b855-ce095fa2d168)
![image](https://github.com/user-attachments/assets/ba4cd015-9ee8-4474-82d5-6540754789f9)

Codigo comentado en card-soporte.component.html

- Se elimina código

**Comment by stevencol** [comment]
3.
![image](https://github.com/user-attachments/assets/21ff49aa-7a61-4999-90bf-a332950724eb)

Código comentado en modal-soportes-cumplido.component.html 
* Se elimina

**Comment by stevencol** [comment]
4.

![image](https://github.com/user-attachments/assets/66562320-03cc-4362-9211-d5e863b35c90)

*Agregar accesibilidad en el caso de que no se pueda visualizar el Archivo

De 
``` JavaScript

  <div style="height:100vh; width: 60vw; overflow:initial" mat-dialog-content>
    <object [data]="documentData|safeUrl" type="application/pdf" *ngIf="documentLoad">
    </object>
</div>
```


A: 

``` JavaScript

  <div style="height:100vh; width: 60vw; overflow:initial" mat-dialog-content>
    <object [data]="documentData|safeUrl" type="application/pdf" *ngIf="documentLoad">
      <p>Tu navegador no soporta la visualización de PDFs. Puedes descargar el documento <a [href]="documentData | safeUrl" download>aquí</a>.</p>
    </object>
</div>
```

**Comment by stevencol** [comment]
5. Código repetido:

![image](https://github.com/user-attachments/assets/8697d8e5-1ec9-48df-985f-e2f1378108d3)

* Se elimina código repetido
``` JavaScript
.mat-mdc-header-row{
      text-align: center;
      vertical-align: middle;
    }
    .mat-mdc-header-row {
      box-shadow: none !important;
      height: 30px !important;
      background-color:#E8DADA;
      font-weight: bold;


    }
```

a
 * Se elimina código repetido
``` JavaScript
.mat-mdc-header-row {
    text-align: center;
    vertical-align: middle;
    box-shadow: none !important;
    height: 30px !important;
    background-color: #E8DADA;
    font-weight: bold;
}

```

**Comment by stevencol** [comment]
6 . 

![image](https://github.com/user-attachments/assets/c0fb9658-c9e4-4fd4-95c3-2b81d959f110)

Condigo comentado en: listar-contratos.component.html 

- Se elimina codigo

**Comment by stevencol** [comment]
7. Codigo repetido


![image](https://github.com/user-attachments/assets/ec523805-d523-40a9-b6ab-bdc65df8c4e3)

Se unifica  de:

``` JavaScript
    .mat-mdc-header-row {
      box-shadow: none !important;
      height: 30px !important;
      background-color:#E8DADA;


    }

    .mat-mdc-header-row{
      text-align: center;
      vertical-align: middle;
    }
    .mat-mdc-row {
      height:10px !important;

  }
```

a: 


``` JavaScript
.mat-mdc-header-row {
    text-align: center;
    vertical-align: middle;
    box-shadow: none !important;
    height: 30px !important;
    background-color: #E8DADA;
    font-weight: bold;
}
```

**Comment by stevencol** [comment]
8 . Código repetido
![image](https://github.com/user-attachments/assets/07fd5097-5680-48f5-9c86-40f94ba4061c)

- Se unifica

De: 
``` JavaScript
.mat-mdc-header-row{
  background: #FFEAE6;
  text-align: center;
  vertical-align: middle;
}

.mat-mdc-header-row {
  box-shadow: none;
  height: 35px !important;
}
```


a: 
``` JavaScript
.mat-mdc-header-row {
  background: #FFEAE6;
  text-align: center;
  vertical-align: middle;
  box-shadow: none;
  height: 35px !important;
}
```

**Comment by stevencol** [comment]
## Critical

**Comment by stevencol** [comment]
1:
![image](https://github.com/user-attachments/assets/f6a59a34-189f-47c9-9262-b1435e63e432)

Clase de scss mal declarada:
De:

``` JavaScript
 app-soporte-cumplido{
    margin-bottom: 50px;
  }
```


``` JavaScript
 .app-soporte-cumplido{
 margin-bottom: 50px;
  }
```

**Comment by stevencol** [comment]
## Major 

![image](https://github.com/user-attachments/assets/4e4b9990-ac5b-40d9-8dbc-579136c19e8b)

se elimina código duplicado
``` JavaScript
.card-oas {
  width: calc(100vw - 60px);
  border-radius: 10px;
  height: auto;
  margin: 0 auto;
}

```

**Comment by stevencol** [comment]
2  
![image](https://github.com/user-attachments/assets/1c2e5ef7-8478-4666-b870-c3f838931a7a)

Se agrega scope a la tabla : 

``` JavaScript
 <th mat-header-cell *matHeaderCellDef mat-sort-header class="header" scope="col">
            {{column.header}}
          </th>
```

**Comment by stevencol** [comment]
3: 
![image](https://github.com/user-attachments/assets/e3d90418-069b-4ec8-90c2-a28a59b16a50)

Se elimina código repetido

``` JavaScript
.padding2px {
    padding: 3px;
    margin-top: 5px;
  }

```

**Comment by JuanCamiloMartinezLopez** [comment]
@stevencol Buen trabajo.
