### ISSUE TITLE
Ajustar documento Autorización de giro y probar su correcto funcionamiento

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#193]
Se requiere realizar los ajustes pertinentes para el correcto funcionamiento del endpoint para la generación del documento de Autorización de giro 

**Sub Tareas**

- [x] Realizar los cambios de los codigos segun cambiaron en la issue #185
- [x] Probar su correcto funcionamiento con todos los tipos de documentos.

**Criterios de aceptación**

- [x] Ajuste realizado.
- [x] Issue documentado.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by stevencol** [comment]
Se inicia con activad:

Se elimina la lista estática en el código y se utiliza una consulta ya establecida, la cual se define en el servicio que llama a la función de patrocinación de pago, pasando de:

``` JavaScript
func docuementos() (docuementos map[string]string) {
	docuementos = make(map[string]string)
	docuementos["COPS1"] = "Copia de la Orden o Contrato de Prestación de Servicio (para el primer pago"
	docuementos["COPS2"] = "Copia de la Orden de Compra o Suministro (para el primer pago). "
	docuementos["COPS3"] = "Copia de Certificados de Disponibilidad y Reserva Presupuestal. "
	docuementos["COPS4"] = "Acta de inicio (únicamente para el primer pago). "
	docuementos["COPS5"] = "Certificado de cumplido o recibo a satisfacción por parte del supervisor."
	docuementos["FACT6"] = "Factura original. "
	docuementos["COPS"] = "Entrada a almacén de bienes devolutivos. "
	docuementos["ARL"] = "Copia del pago del aporte al Sistema General de Seguridad Social en Salud. "
	docuementos["SSP"] = "Copia del pago del aporte al Sistema General de Seguridad Social en Pensión. "
	docuementos["RUT"] = "Copia del Registro Único Tributario (RUT). "
	docuementos["MMEN"] = "Medio magnético y escrito de la nomina. "
	docuementos["POL"] = "Copia de las pólizas necesarias. "
	docuementos["AL"] = "Acta de liquidación o Acta de Terminación. "
	docuementos["PTA"] = "Pasabordo en tiquetes aéreos. "
	docuementos["RMAAV"] = "Resolución motivada autorizando avance y /o viáticos. "
	docuementos["POLA"] = "Pólizas acordadas en el contrato y en el presupuesto para los anticipos. "

	return docuementos

}
```

a su llamado en el service  ordenarod_cumplido_ordenador, el cual  realiza la consulta lo cual hace que se dinámico: 



``` JavaScript
func docuementos() (documentos map[string]string) {

	var tipo_documento, _ = ObtenerTiposDocumentosCumplido()
	documentos = make(map[string]string)

	for _, documento := range tipo_documento {
		documentos[documento.CodigoAbreviacionTipoDocumento] = documento.Nombre
	}
	return documentos

}
```


Se realizan pruebas para verificar que los documentos sean cargados:

Evaluación, Cuenta bancaria y  entrega de elementos: 

![evalucion cuenta bancaria y entrega de elementos ](https://github.com/user-attachments/assets/01df9c46-5489-4d0b-9509-b5a837357ef1)

Acta de liquidación, acta inicio y Factura :
![acta liquidacion , acta incio factura ](https://github.com/user-attachments/assets/89f420cd-11fc-4413-889a-af17619c6637)

Pólizas y medios magnéticos:

![polizas y medios magneticos](https://github.com/user-attachments/assets/fe6963cd-015f-44fa-83c7-c23bb63e08b9)

Cedula :
![testCedula](https://github.com/user-attachments/assets/920a4024-f68e-44ba-b02c-885f829ce537)

Medio magnético de nomina:
![medio magentico de nomina](https://github.com/user-attachments/assets/f9aa04f1-3791-48f5-b6be-88437af81993)

Tiquete áreo
![tiquete aéreo](https://github.com/user-attachments/assets/b15363ba-0381-47b6-86ba-1083eef4d653)

Viaticos
![viaticos](https://github.com/user-attachments/assets/80b55e06-702d-48a5-ada2-612d65cf0271)

Arl y seguridad social 
![arly sewguridad social](https://github.com/user-attachments/assets/c05f59a2-c61c-4bbc-a49d-0dc7e41f004c)

**Comment by JuanCamiloMartinezLopez** [comment]
@stevencol Buen trabajo.
