### ISSUE TITLE
Ajustar documento Cumplido a satisfacción y probar su correcto funcionamiento

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#195]
Se requiere realizar los ajustes pertinentes para el correcto funcionamiento del endpoint para la generación del documento de cumplido a satisfacción.

**Sub Tareas**

- [] Realizar los cambios para que muestre los valores correctos.
- [] Probar su correcto funcionamiento con todos los tipos de documentos.

**Criterios de aceptación**

- [] Ajuste realizado.
- [] Issue documentado.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
Se revisa la generación del cumplido satisfacción, se verifica que hay datos que no están correctamente, por ejemplo en la vigencia cdp y la crp segun el ejemplo del documento este dato debe ser la fecha completa compuesta de día, mes y año, pero en el documento solo se estaba manejando el año, se cambio esto, en la parte del valor que restaba por pagar aparecía el saldo del contrato pero para este dato se debe restar al saldo el valor que se esta pagando, tambien se ajusta un tema de estilos que no se estaban manejando correctamente en el documento.

![Image](https://github.com/user-attachments/assets/36977933-5f85-4e7f-b416-b8f4005dec6c)

![Image](https://github.com/user-attachments/assets/98e36ecc-4fe6-4046-aaf9-3a3d09d479a2)

![Image](https://github.com/user-attachments/assets/7e37cccb-5a2e-4fca-baf3-292c35dde405)

![Image](https://github.com/user-attachments/assets/b81dbf7e-c52b-4fe8-a1a5-13179fb4582b)

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 Buen trabajo.
