### ISSUE TITLE
Creación vista evaluacion proveedores - formulario evaluacion contrato

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#196]
Se requiere realizar las vistas de form-evaluacion-contrato con base en los [mockups](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EjLBmhGhO-RLlZkurA1CbfoB3ZWXSdbTbAPvAHR4tBV5qA?e=5xs2f5) 

**Sub Tareas**

- [x] Usar [expansion panel](https://v16.material.angular.io/components/expansion/examples) cuando sea requerido 
- [ ] Usar form builder para los formularios con los validadores necesarios
- [x] Usar componente generales según se requiera
- [x] Crear vistas en una rama desde develop con la estructura acordada.

**Criterios de aceptación**

- [x] Vistas desarrolladas.
- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by stevencol** [comment]
Se inicio actividad se crea vista según mockup

**Comment by stevencol** [comment]
Se termina con diseño:

![ev](https://github.com/user-attachments/assets/9c7b69d8-56af-4f1d-9eae-d3f1aec207af)

**Comment by stevencol** [comment]
Se Aplican correcciones indicadas
![finalev](https://github.com/user-attachments/assets/c6a7ebea-5a77-4cfb-bcc2-313c1ec87c5a)

**Comment by JuanCamiloMartinezLopez** [comment]
@stevencol Buen trabajo.
