### ISSUE TITLE
Creación vista evaluacion proveedores - Visualización evaluacion contrato

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#197]
Se requiere realizar las vistas de Visualizar-evaluacion-contrato con base en los [mockups](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EjLBmhGhO-RLlZkurA1CbfoB3ZWXSdbTbAPvAHR4tBV5qA?e=5xs2f5) 

**Sub Tareas**

- [x] Usar [expansion panel](https://v16.material.angular.io/components/expansion/examples) cuando sea requerido 
- [x] Usar form builder para los formularios con los validadores necesarios
- [x] Usar componente generales según se requiera
- [x] Crear vistas en una rama desde develop con la estructura acordada.

**Criterios de aceptación**

- [x] Vistas desarrolladas.
- [x] Issue documentada.
**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
## :triangular_flag_on_post: **Vista evaluación Proveedores**  :triangular_flag_on_post:

- Se ha implementado la vista completa que permite la visualización de las evaluaciones, tanto por parte de un supervisor como de un evaluador.
- Se ha optado por el uso de *expansion panels*, dado que algunos componentes de la vista pueden contener información extensa.

![Image](https://github.com/user-attachments/assets/cf96dbc7-f5ea-4407-ba84-389a5d310a17)

**Comment by JuanCamiloMartinezLopez** [comment]
Buen trabajo, por favor realizar los siguientes ajustes:

- [x] Centrar y agrandar el título para que resalte más
- [x] Agregar color(color primario del sistema)  a los backgrounds de los expansion panels headers para más contraste

**Comment by faidercamilo26** [comment]
- Se agranda, se centra el título de `Ver evaluación`, y se envía a la parte de arriba para que resalte como el titulo central de la vista.
- Se cambian los headers de todos los expansión panel para que concuerden, se les pone un fondo del color primario del proyecto.

![Image](https://github.com/user-attachments/assets/e50a0a05-fc2b-451a-ae02-0806e5145b5c)

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 Buen trabajo.
