### ISSUE TITLE
Generar la investigación relacionada con los soportes de cumplidos y planillas de pago en Cumplidos CPS

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/Cumplidos_y_certificaciones_documentacion#198]
Se requiere realizar la investigación relacionada con los soportes de cumplidos y planillas de pago en Cumplidos CPS

**Sub Tareas**

- [x] Generar contacto con el responsable.
- [x] Adelantar la investigación.
- [x] Alimentar la documentación relacionada.

**Criterios de aceptación**

- [x] Documento con información relacionada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by mantnicot** [comment]
Se ha podido tener una reunión con Diana la persona encargada y nos cuenta que :

- La subida de documento a la parte de drive individual se hace para poder gestionar de forma más rápida la subida indivual de los documentos de los contratista a secopi

![Image](https://github.com/user-attachments/assets/362a79d9-b9f1-48e0-9937-b5a52759b300)

- Los mensaje de whatsapp al celular se hace para poder cumplir con las fechas de subida y no cargar al equipo buscando en el sistema los datos del contratista.

![Image](https://github.com/user-attachments/assets/25e6d77c-45b4-4cf3-a7c9-37f43461b063)

Con base a eso se propuso a Diana posibles mejoras a este proceso para poder agilizarlo :

- Poder generar una notificación por whatsapp a los contratista una vez se apruebe de parte de ordenador
- Desde el sistema poder unificar los cumplidos del mes una fuesen aprobados por el ordenador.
- Poder enviar un pdf de los cumplidos unificados al whatsapp de la persona encargada

Ya con esto se puede plantear un nuevo alcance y mejora para cumplidos cps y así mismo apoyar y generar impacto más grande en la universidad

**Comment by jcmurilloa** [comment]
Buen trabajo @mantnicot, pendiente generar la respectiva documentación.

**Comment by mantnicot** [comment]
Se adjunta el documento 

[documento de analisis base](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EWd30o0ZemtKiwoF4N63cJwBIfwJerPRc6-DTIM6CTs9Rw?e=Roezgb)
