### ISSUE TITLE
Ajustes módulo revisión cumplidos proveedores - Funcionamiento

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#199]
Se requiere realizar los ajustes indicados por funcionamiento en la [presentación](https://udistritaleduco-my.sharepoint.com/:v:/r/personal/caescorciab_udistrital_edu_co/Documents/Grabaciones/Cumplidos%20Proveedores%20-%20Muestra%20Funcionamiento-20241018_110637-Grabaci%C3%B3n%20de%20la%20reuni%C3%B3n.mp4?csf=1&web=1&e=2wlJQY) del día 18 de octubre

**Sub Tareas**

- [x] Cambiar fuente por la fuente indicada por [lineamientos](https://udistritaleduco-my.sharepoint.com/personal/computo_udistrital_edu_co/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fcomputo_udistrital_edu_co%2FDocuments%2FINVERSIÓN%2FPROYECTOS%20DE%20INVERSIÓN%2FGERENCIA%20DE%20PROYECTOS%2FPROYECTOS%20OAS%2FPROYECTO%20SISIFO%20V2%2F2024%2FEJECUCIÓN%2FGestión%20técnica%2FDocumentación%20recopilada%20Sísifo%20v1%2FLineamientos%20aplicativos%20V2%2Epdf&parent=%2Fpersonal%2Fcomputo_udistrital_edu_co%2FDocuments%2FINVERSIÓN%2FPROYECTOS%20DE%20INVERSIÓN%2FGERENCIA%20DE%20PROYECTOS%2FPROYECTOS%20OAS%2FPROYECTO%20SISIFO%20V2%2F2024%2FEJECUCIÓN%2FGestión%20técnica%2FDocumentación%20recopilada%20Sísifo%20v1&ga=1 ).
- [x] Cambiar color de los botones (con color primario)
- [x] Mensaje informativo para el Input soporte,  texto que indique que solo pdf y el máximo del tamaño (5MB).

**Criterios de aceptación**

- [ ] Cambios realizados.
- [ ] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by stevencol** [comment]
- Se Realizan cambios de colores en lo botones.
-  Se pone Mensaje informativo para el Input soporte, texto que indique que solo pdf y el máximo del tamaño (5MB).
- Se valida el tamaño del archivo

**Comment by stevencol** [comment]
Al intentar cambiar la fuente se generaron varios inconvenientes ya el cliente no reconocía la fuente. 

Para que el cliente reconociera la fuente se realizaron siguientes   pasos:
En el html principal  se importa la fuente a usar 
``` html
  <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Raleway:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
```

En el css principal se importa 

``` css
@import url('https://fonts.googleapis.com/css2?family=Raleway:ital,wght@0,100..900;1,100..900&display=swap');
```


Y en el theme-angular-material
``` css
$light-theme: mat.define-light-theme(
  (
    color: (
      primary: mat.define-palette($md-primary, 500),
      accent: mat.define-palette($md-accent, 500),
      warn: mat.define-palette($md-warning, 500),
    ),
    typography: mat.define-typography-config(
      $font-family: "Raleway",
    ),
    density: 0,
  )
);
```

**Comment by stevencol** [comment]
Con la nueva fuente : 
![image](https://github.com/user-attachments/assets/855bea5b-bb89-44cc-b6c1-177df14556d1)

**Comment by JuanCamiloMartinezLopez** [comment]
@stevencol Buen trabajo.
