### ISSUE TITLE
Revisar error en valores - Cumplido a satisfaccion

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#200]
Se requiere revisar la generación correcta del cumplido a satisfacción en el ambiente de pruebas

**Sub Tareas**

- [x] Realizar múltiples pruebas de la generación del documento.
- [x] Si existe un error, identificarlo y solucionarlo.

**Criterios de aceptación**

- [x] Issue documentado.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
## :triangular_flag_on_post: **Solución Problema Valores Cumplidos satisfacción **  :triangular_flag_on_post:

1) Se identifica el error en el microcliente desplegado, se nota que el valor a pagar en el payload esta llegando en null. Lo que ocasiona que por defecto este valor se llene con un 0.
![Image](https://github.com/user-attachments/assets/42c99b0c-f973-4247-9d06-5ccd10002f9a)

2) Una vez identificado el error se evalúa que es lo que lo está causando, vemos que este error está siendo provocado por la instrucción que recupera el campo. En dicha función se esta recuperando el valor del campo y se esta limpiando para quitarle los signos "$" y ",". Sin embargo esto solo funciona cuando hay un solo simbolo, por lo tanto si el valor tiene un solo simboolo "," esta instruccion recupera correctamente el valor, pero cuando tiene más de una "," no puede reemplazar y retorna 0.

```typescript
ValorPagar: Number(
        this.formularioInformeSeguimiento
          .get('valor_cumplido')
          ?.getRawValue().replace('$','').replace(',','') ?? 0
      ),
```
### Ejemplo utilizando el valor $500,000

![Image](https://github.com/user-attachments/assets/a3d29714-8e00-49c3-96ba-0538df7d14f7)


### Ejemplo utilizando el valor $50,000,000

![Image](https://github.com/user-attachments/assets/76cb8e0a-31e9-426a-a02b-733c121a0d57)


## Solución del problema

Teniendo en cuenta el problema encontrado se soluciona este inconveniente reformulando la instruccion que recupera el valor a pagar, y queda de la siguiente manera.

```typescript
ValorPagar: Number((this.formularioInformeSeguimiento.get('valor_cumplido')?.value ?? '0').replace(/[^\d]/g, ''))
``` 

Esta función lo que hace es reemplazar todos los símbolos no numéricos en el valor recuperado y para ello hace uso de una expresión regular.

### Ejemplo utilizando el valor $500

![Image](https://github.com/user-attachments/assets/84c6eea4-860e-4418-9ae8-94aef8956278)

### Ejemplo utilizando el valor $500,000

![Image](https://github.com/user-attachments/assets/aabb267c-e3af-4eba-9768-bd293fef5e17)

### Ejemplo utilizando el valor $50,000,000

![Image](https://github.com/user-attachments/assets/4942f84a-2713-493a-832e-6ea8662983e2)

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 Buen trabajo.
