### ISSUE TITLE
Agregar input de filtrado para la cabeceras de componente tabla

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#201]
Se requiere modificar el componente tabla para permitir tener filtro de en las cabeceras, ej: 
![Image](https://github.com/user-attachments/assets/1be8a812-e79e-4590-96b1-9731d13bdfe9)

**Sub Tareas**

- [x] Revisar la viabilidad de implementación
- [x] Permitir que sea configurable

**Criterios de aceptación**

- [x] Issue comentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
## :triangular_flag_on_post: **Investigación posibilidad de filtros**  :triangular_flag_on_post:

Se evalúa la viabilidad de agregar filtros en las tablas, utilizando inputs en la cabecera de cada una de las columnas. Tras la investigación, se concluye que la implementación es factible, aunque es necesario realizar algunos ajustes en los estilos. Los filtros funcionan correctamente, y se ha desarrollado un código inicial como primer acercamiento. A continuación, se detallan los hallazgos encontrados con este código:

- Al implementar estos filtros, se debe desactivar el ordenamiento, ya que al hacer clic en un input para editar el filtro, también se activa el ordenamiento, lo cual no es óptimo.
- Es necesario corregir los estilos para garantizar que la tabla mantenga una apariencia visual adecuada al incluir los inputs de filtros.
- Se debe evaluar la posibilidad de convertir todas las fechas en la tabla a cadenas de texto (strings), ya que al intentar filtrar un campo de tipo fecha, no se reconocen coincidencias. Alternativamente, se debe buscar la forma de que los filtros funcionen también con fechas, si es posible.
- Es viable aplicar múltiples filtros utilizando distintas columnas.

Por el momento, no se ha realizado la implementación completa de los filtros en la tabla, ya que esta tarea se centraba en investigar la factibilidad de su aplicación. La construcción final, incluyendo los ajustes de estilo, queda fuera del alcance de esta tarea.

![Image](https://github.com/user-attachments/assets/049cdf05-27ab-47af-8c81-c4ea1d20bf26)

**Comment by faidercamilo26** [comment]
Se adecua el componente tabla para que se puedan pasar los filtros dinámicamente a las filas que  que se requiera, de esta manera hay mas libertad para elegir que tablas tienen filtros y que filas exactas, para esto en el la lista se de las columnas se le debe agregar el atributo booleano `filter` si se pone en true, dicha columna tendrá el input de filtro, en caso de que se ponga en false o no se ponga la columna no tendrá el input de filtrado.

##Ejemplo en código con filtros

A continuación se muestra las columnas de la tabla encargada de listar los contratos de un supervisor, se puede evidenciar que las filas numero contrato, tipo contrato, nombre proveedor y dependencias tiene el atributo `filter` en true, por lo tanto estas deben ser las únicas filas que cuenten con la opción de filtrado.

```typescript
displayedColumns: any[] = [
    {def: 'numeroContrato', header: 'NUMERO CONTRATO', filter: true },
    {def: 'vigencia', header: 'VIGENCIA' },
    {def: 'tipoContrato', header: 'TIPO CONTRATO', filter: true },
    {def: 'rp', header: 'RP' },
    {def: 'vigenciaRp', header: 'VIGENCIA RP' },
    {def: 'nombreProveedor', header: 'NOMBRE PROVEEDOR', filter: true },
    {def: 'dependencias', header: 'DEPENDENCIAS', filter: true },
    {
      def: 'acciones',
      header: 'ACCIONES',
      isAction: true,
    }
  ];
```

## Visual del ejemplo

![Image](https://github.com/user-attachments/assets/d90e518b-434f-4aba-963f-137687ebd944)

### Ejemplo código sin filtros

Aqui se muestra la tabla encargada de mostrar las solicitudes de un contrato, vemos que en el código ninguna de las columnas tiene el atributo `filter`, por lo tanto, ninguna fila debería tener la posibilidad de filtrar.

```typescript

displayedColumns: any[] = [
    { def: 'noSolicitud', header: 'N° SOLICITUD' },
    { def: 'numeroContrato', header: 'N° CONTRATO' },
    { def: 'fechaCreacion', header: 'FECHA CREACION' },
    { def: 'periodo', header: 'PERIODO' },
    { def: 'estadoSoliciatud', header: 'ESTADO SOLICITUD' },
    {
      def: 'acciones',
      header: 'ACCIONES',
      isAction: true,
    },
  ];

```

## visual del ejemplo

![Image](https://github.com/user-attachments/assets/28885a9d-3c01-4eb7-81ae-e3d4c80ed28a)

**Comment by faidercamilo26** [comment]
Se agregan los inputs de filtrado para la tabla de contratación.

![Image](https://github.com/user-attachments/assets/fa691227-b47a-41ff-81a7-0e49d6e9c7c6)

**Comment by faidercamilo26** [comment]
Se edita el tamaño de los inputs para que se alcance a visualizar toda la tabla sin necesidad de el scroll.

![Image](https://github.com/user-attachments/assets/a81a196b-42f3-49de-81c5-68715a88b702)

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26  Buen trabajo.
