### ISSUE TITLE
Modificar modelo de base de datos - Evaluación proveedores

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#202]
Se requiere realizar la modificación al [modelo de base de datos](https://udistritaleduco-my.sharepoint.com/my?listurl=%2Fpersonal%2Fcomputo%5Fudistrital%5Fedu%5Fco%2FDocuments&id=%2Fpersonal%2Fcomputo%5Fudistrital%5Fedu%5Fco%2FDocuments%2FINVERSI%C3%93N%2FPROYECTOS%20DE%20INVERSI%C3%93N%2FGERENCIA%20DE%20PROYECTOS%2FPROYECTOS%20OAS%2FPROYECTO%20CUMPLIDOS%20Y%20CERTIFICACIONES%2F2024%2FEjecuci%C3%B3n%2FGesti%C3%B3n%20t%C3%A9cnica%2FCUMPLIDOS%2FProveedores%2FModelos%20de%20base%20de%20datos%2FEvaluaci%C3%B3n%20cumplidos%20proveedores%2Fv5%2Fpropuesta%5Fevaluacion%5Fproveedor%5Fv5%2Epng&remoteItem=%7B%22mp%22%3A%7B%22webAbsoluteUrl%22%3A%22https%3A%2F%2Fudistritaleduco%2Dmy%2Esharepoint%2Ecom%2Fpersonal%2Fjuacmartinezl%5Fudistrital%5Fedu%5Fco%22%2C%22listFullUrl%22%3A%22https%3A%2F%2Fudistritaleduco%2Dmy%2Esharepoint%2Ecom%2Fpersonal%2Fjuacmartinezl%5Fudistrital%5Fedu%5Fco%2FDocuments%22%2C%22rootFolder%22%3A%22%2Fpersonal%2Fjuacmartinezl%5Fudistrital%5Fedu%5Fco%2FDocuments%2FPROYECTOS%20OAS%22%7D%2C%22rsi%22%3A%7B%22listFullUrl%22%3A%22https%3A%2F%2Fudistritaleduco%2Dmy%2Esharepoint%2Ecom%2Fpersonal%2Fcomputo%5Fudistrital%5Fedu%5Fco%2FDocuments%22%2C%22rootFolder%22%3A%22%2Fpersonal%2Fcomputo%5Fudistrital%5Fedu%5Fco%2FDocuments%2FINVERSI%C3%93N%2FPROYECTOS%20DE%20INVERSI%C3%93N%2FGERENCIA%20DE%20PROYECTOS%2FPROYECTOS%20OAS%2FPROYECTO%20CUMPLIDOS%20Y%20CERTIFICACIONES%2F2024%2FEjecuci%C3%B3n%2FGesti%C3%B3n%20t%C3%A9cnica%2FCUMPLIDOS%2FProveedores%2FModelos%20de%20base%20de%20datos%2FEvaluaci%C3%B3n%20cumplidos%20proveedores%2Fv5%22%2C%22webAbsoluteUrl%22%3A%22https%3A%2F%2Fudistritaleduco%2Dmy%2Esharepoint%2Ecom%2Fpersonal%2Fcomputo%5Fudistrital%5Fedu%5Fco%22%7D%7D&parent=%2Fpersonal%2Fcomputo%5Fudistrital%5Fedu%5Fco%2FDocuments%2FINVERSI%C3%93N%2FPROYECTOS%20DE%20INVERSI%C3%93N%2FGERENCIA%20DE%20PROYECTOS%2FPROYECTOS%20OAS%2FPROYECTO%20CUMPLIDOS%20Y%20CERTIFICACIONES%2F2024%2FEjecuci%C3%B3n%2FGesti%C3%B3n%20t%C3%A9cnica%2FCUMPLIDOS%2FProveedores%2FModelos%20de%20base%20de%20datos%2FEvaluaci%C3%B3n%20cumplidos%20proveedores%2Fv5) planteado para el módulo de Evaluación proveedores.

**Sub Tareas**

- [x] Agregar tablas necesarias para guardas los ítems pertenecientes a una evaluación 

- Item: Identificador( alfanumérico), nombre y descripción 

- [x] Agregar tabla para relacionar los ítems a evaluar a un determinado evaluador.
- [x] Seguir lineamientos

**Criterios de aceptación**

- [x] Propuesta de modelo actualizado.
- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
### Cambios realizados en el modelo de base de datos:

#### 1. Nueva Tabla: `item`
Se ha creado una nueva tabla llamada `item` que almacena los ítems que son evaluados en los contratos de los proveedores. Esta tabla contiene los siguientes campos:
- `id`: Identificador único del ítem.
- `identificador`: Identificador de uso interno del ítem.
- `nombre`: Nombre del ítem.
- `descripcion`: Descripción detallada del ítem.
- `activo`: Indica si el ítem está activo.
- `fecha_creacion`: Fecha de creación del ítem.
- `fecha_modificacion`: Fecha de última modificación.

#### 2. Nueva Tabla: `evaluador_item`
Se ha agregado una tabla intermedia `evaluador_item` que permite la relación entre un evaluador y un ítem, con la finalidad de poder asignar distintos ítems a un evaluador dentro de una evaluación.
- `id`: Identificador único.
- `evaluador_id`: Referencia al evaluador.
- `item_id`: Referencia al ítem.
- `activo`: Indica si la relación está activa.
- `fecha_creacion`: Fecha de creación de la relación.
- `fecha_modificacion`: Fecha de última modificación de la relación.

#### 3. Modificación en la tabla `evaluacion_evaluador_item`
La tabla `evaluacion_evaluador_item` ha sido ajustada para incluir una relación más detallada entre los evaluadores y los ítems evaluados en una evaluación. Ahora puede manejar que un evaluador esté evaluando múltiples ítems dentro de una evaluación.
- **Campos adicionales**: `evaluacion_id`, `evaluador_id`, `item_id`, `clasificacion_id`.
- Permite una relación muchos a muchos entre evaluaciones, evaluadores e ítems.


## Modelo de bases de datos antes

![Image](https://github.com/user-attachments/assets/d0f77bb6-66d2-4f41-b0d5-00855a1882d9)

## Modelo de bases de datos ahora

![Image](https://github.com/user-attachments/assets/f0a99798-80d2-419c-a5b6-7617eaff1d24)


Se sube el nuevo modelo a la [carpeta del proyecto](https://udistritaleduco-my.sharepoint.com/shared?id=%2Fpersonal%2Fcomputo%5Fudistrital%5Fedu%5Fco%2FDocuments%2FINVERSI%C3%93N%2FPROYECTOS%20DE%20INVERSI%C3%93N%2FGERENCIA%20DE%20PROYECTOS%2FPROYECTOS%20OAS%2FPROYECTO%20CUMPLIDOS%20Y%20CERTIFICACIONES%2F2024%2FEjecuci%C3%B3n%2FGesti%C3%B3n%20t%C3%A9cnica%2FCUMPLIDOS%2FProveedores%2FModelos%20de%20base%20de%20datos%2FEvaluaci%C3%B3n%20cumplidos%20proveedores%2Fv6&listurl=%2Fpersonal%2Fcomputo%5Fudistrital%5Fedu%5Fco%2FDocuments)

**Comment by faidercamilo26** [comment]
Se realizan las correcciones indicadas en el daily del día viernes para resolver el inconveniente que se tenia al agregar la tabla item al modelo, por el momento se pueden evidenciar que quedan ciclos entre las tablas evaluacion_evaluador, item y evaluacion, los cuales se espera solucionarlos con la ayuda de los DBA.

![Image](https://github.com/user-attachments/assets/f38b5e39-cd83-4b83-9bae-da659d15949c)

**Comment by faidercamilo26** [comment]
Se actualiza nuevamente el modelo para que ahora el resultado_evaluacion se guarde en cada evaluación individual, ahí también se va a almacenar la clasificación, esto para permitir la posibilidad de que un evaluador pueda corregir su evaluación individual,  el valor total de la evaluación se calcularía teniendo en cuenta los resultados de las evaluaciones individuales.

![Image](https://github.com/user-attachments/assets/d470e67c-c943-4a33-b700-c3ffe7f94905)

**Comment by faidercamilo26** [comment]
Se corrige el modelo con las indicaciones del daily del día 30/10.

![Image](https://github.com/user-attachments/assets/844513f9-bdaa-4fa4-abbe-e757610d7953)

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 Buen trabajo.
