### ISSUE TITLE
Unificar ramas - Históricos y Reversion

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#203]
Se requiere realizar la integración de las ramas en las que se desarrollaron las funciones y vistas de Históricos y reversión.

**Sub Tareas**

- [x] Integrar las ramas en una sola rama para facilitar su próxima integración a develop para las ramas del cliente.
- [x] Integrar las funcionalidades del mid a develop.
- [x] Probar el estado actual de los módulos de históricos y reversión
- [ ] Ramas a integrar:

- Cliente:

1.   [udistrital/revision_cumpido_prov_mf/issue-183](https://github.com/udistrital/revision_cumplidos_proveedores_mf/tree/feature/issue-183)
2. [udistrital/revision_cumplidos_proveedores_mf/RefactorizacionReversionCumplidos](https://github.com/udistrital/revision_cumplidos_proveedores_mf/tree/feature/RefactorizacionReversionCumplidos)
- Mid:

1. [udistrital/revision_cumplido_prov_mid/ussue/#138](https://github.com/udistrital/revision_cumplido_prov_mid/tree/ussue/%23138)
2. [udistrital/feature/HistoricoCumplidosProveedores](https://github.com/udistrital/revision_cumplido_prov_mid/tree/feature/HistoricosCumplidosProveedores)
 

**Criterios de aceptación**

- [ ] ramas integradas y con su funcionamiento actual probado.
- [ ] issue comentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by stevencol** [comment]
Se inicia con actividad. La finalidad principal es traer las vistas a la rama

**Comment by stevencol** [comment]
Se tuvieron bastantes errores al unificar ramas. El cliente, aunque no dio error al hacer el merge, no iniciaba el proyecto; parte de la unificación tuvo que hacerse de forma manual. El MID dio bastantes problemas, ya que la rama [udistrital/feature/HistoricoCumplidosProveedores](https://github.com/udistrital/revision_cumplido_prov_mid/tree/feature/HistoricosCumplidosProveedores) está bastante desactualizada en comparación con la versión actual. Se intentó varias veces, pero la mejor manera fue una integración manual.

Las ramas que se crearon se eliminaron y se volvieron a eliminar.

**Comment by JuanCamiloMartinezLopez** [comment]
@stevencol Buen trabajo.
