### ISSUE TITLE
Implementar consulta de ordenes de giro a la funciona de revertir cumplidos proveedores.

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#204]
Se requiere realizar la implementación de consulta por órdenes de giro:

http://busservicios.intranetoas.udistrital.edu.co:8282/wso2eiserver/services/financiera_produccion/ordenes_pago_tercero/{CDP}/{Vigencia CDP}/{Documento proveedor}/{Año}

**Sub Tareas**

- [ ] Probar la petición en varios contratos proveedores para verificar su correcto funcionamiento.
- [x] Implementar en el flujo de filtrado de contratos que pueden revertirse.( si tiene orden de pago para le cumplido correspondiente no se puede revertir)

**Criterios de aceptación**

- [ ] petición probada e implementada.
- [x] Issue comentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by stevencol** [comment]
Se inicia con actividad, realizando  pruebas de contratos  para su posterior integración

**Comment by stevencol** [comment]
Se realizan varias consultas con contratos de proveedores pero ninguna trae información
La búsqueda se realizado de la siguiente manera:

1-  Donde se excluyen Los contratos  que no son de proveedores 
![image](https://github.com/user-attachments/assets/e1e224f3-62b2-42f9-a355-1ab3df7be70f)

2- Con eso sacamos el id del contratista : 

![image](https://github.com/user-attachments/assets/e82d12c3-44d9-4a4e-9c37-f24b9f6e0b60)

Informacion:

![image](https://github.com/user-attachments/assets/fc8cfcca-3d06-4ef5-9c5a-9034692e277f)



 3- Buscamos el cdp y su vigencia 
![image](https://github.com/user-attachments/assets/62a0c9a5-4303-4c87-b9c3-edaf4a88b6ed)

Se realiza consulta 
http://busservicios.intranetoas.udistrital.edu.co:8282/wso2eiserver/services/financiera_produccion/giros_tercero/999/2017/1
![image](https://github.com/user-attachments/assets/8065aec0-7018-46c9-b1c0-26a8d8247961)

y 
http://busservicios.intranetoas.udistrital.edu.co:8282/wso2eiserver/services/financiera_produccion/ordenes_pago_tercero/999/2017/52498415/2017
![image](https://github.com/user-attachments/assets/5561fe01-a4ce-4d64-8cea-94b2842bdf04)


No da resultados

Se prueba con el sigente año y sigue sin resultados 
![image](https://github.com/user-attachments/assets/444f126a-b211-4eda-8f35-0ea061c1dbf3)

se prueban varios contratos: prueban varios contratos: 


Contrato 995
http://busservicios.intranetoas.udistrital.edu.co:8282/wso2eiserver/services/financiera_produccion/giros_tercero/995/2017/1

![image](https://github.com/user-attachments/assets/091c39de-687c-4800-85b9-17f7e9a72323)

http://busservicios.intranetoas.udistrital.edu.co:8282/wso2eiserver/services/financiera_produccion/ordenes_pago_tercero/995/2017/80851495/2017

![image](https://github.com/user-attachments/assets/ea834402-0749-4e5c-992f-f7ea9d85a384)

![image](https://github.com/user-attachments/assets/c046b3d6-159e-4b6a-a197-124017131a02)
![image](https://github.com/user-attachments/assets/1feaa41b-293c-4fe3-b694-54b711c2148e)

**Comment by JuanCamiloMartinezLopez** [comment]
@stevencol Buen trabajo.
