### ISSUE TITLE
Integración y prueba de módulos Históricos y reversión.

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#205]
Se requiere realizar la integración de la funcionalidad del mid (#203 y #204) desarrollada para los módulos de  históricos y reversión a la vistas de estos.

**Sub Tareas**

- [x] Agregar la funcionalidad a las vistas
- [x] Probar su funcionamiento.

**Criterios de aceptación**

- [ ] Modulos de históricos y reversión funcionando.
- [x] Issue comentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [ ] Push en Feature.
- [x] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by stevencol** [comment]
Se inicia con actividad. La finalidad principal es trae las vistas a  la rama develop

**Comment by stevencol** [comment]
Se da unió con la actividad: 

1 - Se adapta tabla a la respuesta que generar el servicio
2 - Se modifica formulario para adaptase a la peticion  
3 - Se crea función para realizar la consulta de los cumplidos según el formulario
- Se avanza en el proceso ya realiza consultar
- 
![image](https://github.com/user-attachments/assets/b643bf06-37ed-4cd1-b658-0536caa81229)

**Comment by stevencol** [comment]
Se termina con el desarrollo:
![finalev](https://github.com/user-attachments/assets/f0f7d5ad-e570-4ec3-abce-00a51f4d6975)

# Nota
-Todos los selects realizan su consulta, excepto el de dependencia, ya que genera un error de CORS, aunque su función ya está desarrollada
-No realiza búsquedas por nombre ya que el en back recibe es un int como valor 
![image](https://github.com/user-attachments/assets/8cfb5263-8d41-4c62-aae0-0aca1eb53e42)

- Se desconoce pero por alguna razón no se aplica paginación a la tabla :
![finalev](https://github.com/user-attachments/assets/54216747-bea3-4f3c-a1b1-f2047d4639c8)

**Comment by stevencol** [comment]
No se puede probar lo de reversión ya que no se cargan las solicitudes para revertir, y se trata de seguir un ciclo completo desde para aprobar un cumplido con el ordenador, pero la solicitud no llega al ordenador.

![image](https://github.com/user-attachments/assets/c642d9b9-24d0-48ed-a4a3-c7f45fec616e)

![image](https://github.com/user-attachments/assets/913f8330-e54a-4c60-a720-7c42ea8bd836)

**Comment by JuanCamiloMartinezLopez** [comment]
@stevencol Buen trabajo.

**Comment by JuanCamiloMartinezLopez** [comment]
Se cierra la issue
