### ISSUE TITLE
Revisión y remisión de documentación cumplidos proveedores ( analista )

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/Cumplidos_y_certificaciones_documentacion#207]
Se requiere revisar los requerimientos de documentación técnica de cumplidos proveedores (revisión, históricos y reversión), contestar con lo existente y generar la necesidad de construcción de lo pendiente, para finalmente remitir a funcionamiento, según la siguiente carpeta:

https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/Epgr_v9BxsJBjnhtEZiWRn0BZKgLLpqi7vFBoEtKc-zY2Q?e=x9ZFpo

**Sub Tareas**

- [x] Establecer documentación pendiente.
- [x] Generar requerimiento de construcción de documentación faltante.
- [x] Enviar a funcionamiento documentación completa para revisión.
- [x] Generar seguimiento a la realimentación.

**Criterios de aceptación**

- [x] Documentación técnica completada.
- [x] Envío de documentación a funcionamiento.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [X] Está refinada y estimada en puntos de historia por el equipo.
- [X] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [X] No tiene bloqueos que impidan su ejecución.
- [X] Las dependencias están identificadas y resueltas.
- [X] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por líder de proyecto.

**Comment by mantnicot** [comment]
Se hizo la revisión de cada documento y se hicieron ciertos mejoras y cambios visuales, ya estan listos para enviar a funcionamiento

**Comment by jcmurilloa** [comment]
Muy buen trabajo, pendiente realimentación de funcionamiento-
