### ISSUE TITLE
Ajustar paginación tabla históricos

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#208]
Se requiere realizar el ajuste de la paginación de la tabla según el error encontrado en la issue #205 

**Sub Tareas**

- [x] Ajustar para el correcto funcionamiento de la tabla.
- [x] Realizar los cambios en la rama [issue/203](https://github.com/udistrital/revision_cumplidos_proveedores_mf/tree/feature/issue%23203)

**Criterios de aceptación**

- [x] tabla ajusta.
- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
## :triangular_flag_on_post: **Ajuste paginación tabla históricos** :triangular_flag_on_post:

Se revisa el la tabla de históricos y se evidencia que posiblemente el error se estaba debiendo a que en el modelo que se esta usando en el componente de `historico-cumplidos` no contiene la estructura correcta que necesita la tabla para recibir las acciones, este era el modelo antes.

```typescript
export interface Cumplido {
    NumeroContrato: string;
    Vigencia: string;
    Rp: string;
    Mes: number;
    FechaCambioEstado: string;
    NombreProveedor: string;
    Dependencia: string;
    Estado: string;
    TipoContrato: string;
    acciones?:[]
    IdCumplido:number
  }
```

y ahora este es el modelo corregido

```typescript
import { Acciones } from "./acciones.model";

export interface Cumplido {
    NumeroContrato: string;
    Vigencia: string;
    Rp: string;
    Mes: number;
    FechaCambioEstado: string;
    NombreProveedor: string;
    Dependencia: string;
    Estado: string;
    TipoContrato: string;
    acciones?: Acciones[];
    IdCumplido:number
  }
```


### Pruebas 

https://github.com/user-attachments/assets/15c36b57-a43d-4d2e-baee-557001376557

**Comment by faidercamilo26** [comment]
Se soluciona el inconveniente que se tenía con la paginación de la tabla, se evidencia que en el componente `FormularioConsultaComponent` se está emitiendo anticipadamente el evento que dispara el método `listarCumplidos()`. Por esto este método estaba pasando una lista vacía al componente `ListadoHistoricosComponent` y este componente le estaba pasando una lista vacía a la tabla.  Después cuando se cargaban los datos que debían ir en la tabla se enviaban y se mostraban pero ya el dataSource de la tabla se había cargado con una lista vacía, por este motivo no se estaba cargando correctamente la tabla y las funcionalidades de esta, estaban fallando.

![Image](https://github.com/user-attachments/assets/0f069a41-17f6-4331-8541-9bb659a42c63)

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 Buen trabajo.
