### ISSUE TITLE
Ajustar función de filtro para el módulo de histórico.

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#209]
Se requiere realizar de la función ObtenerHistoricoCumplidosFiltro del mid

**Sub Tareas**

- [x] Ajustar para filtrar con los valores de año y/o mes entre los valores de fecha inicio y fecha fin de la tabla información pago.
- [x] Cambiar el objeto de retorno, eliminar mes y fecha aprobación, y retornar el periodo de la información de pago (fecha_inicio - fecha_fin).
- [x] Realizar los cambios en la rama [issue/203](https://github.com/udistrital/revision_cumplido_prov_mid/tree/feature/issue%23203)

**Criterios de aceptación**

- [x] Función de filtro ajustada.
- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
## :triangular_flag_on_post: **Ajuste función filtro** :triangular_flag_on_post:

- Se edita el modelo de retorno de la función filtro para que ahora retorne el periodo de la informacion pago y para que deje de retornar el mes y la fecha creación del cumplido.
```go
type CumplidosFiltrados struct {
	IdCumplido      int    `json:"IdCumplido"`
	NumeroContrato  string `json:"NumeroContrato"`
	Vigencia        string `json:"Vigencia"`
	Rp              string `json:"Rp"`
	NombreProveedor string `json:"NombreProveedor"`
	Dependencia     string `json:"Dependencia"`
	Estado          string `json:"Estado"`
	TipoContrato    string `json:"TipoContrato"`
	InformacionPago string `json:"InformacionPago"`
}
```

- Se ajusta la funcionalidad para que ahora los meses y años se usen para filtrar los periodos de pago, esto tiene mas sentido que filtrar por la fecha de creación del cumplido, por lo tanto, ahora si un mes o un año está en el rango de fechas de inicio y fechas de finalización de un pago, este se debe retornar si se cumplen las otras condiciones de los filtros.

![Image](https://github.com/user-attachments/assets/25d6ad3e-bb02-452e-9fea-b6c9d98c6bc5)


![Image](https://github.com/user-attachments/assets/506321ad-c783-4253-ad22-54444feec048)

![Image](https://github.com/user-attachments/assets/e1487eb5-027c-4bb2-a66e-91e98b55c496)


## Faltante

Por el momento aunque la funcionalidad ya esta completamente diseñada falta realizar más pruebas exhaustivas para asegurar que los filtros funcionan correctamente, asi que por el momento no se da por finalizada la issue y el día de hoy se continuara con las pruebas finales, en caso de que todo salga bien se dará por finalizada la issue y se subirá el código, caso contrario se realizaran los ajustes pertinentes.

**Comment by faidercamilo26** [comment]
- **Filtrado de Cumplidos**: Se mejoró la funcionalidad de filtrado, permitiendo que los usuarios envíen múltiples meses y años para filtrar los periodos de pago de un cumplido.
- **Nueva Función `MesesEntreFechas`**: Se agregó una función auxiliar que recibe `fechaInicio` y `fechaFin`, retornando una lista de `MesAnio` con los meses entre dichas fechas. Esto permite realizar validaciones precisas sobre el período de cumplimiento solicitado.
  - Se incluyeron validaciones adicionales para cumplir con los filtros enviados en cuanto a meses y años, mejorando la precisión del filtrado.

## Pruebas

Se realizan pruebas exhaustivas para verificar que este funcionando correctamente la función para filtrar, se le cambia la fecha al cumplido id `49` para que el periodo sea `2025-03-26 - 2026-05-26`, se cabe aclarar que se hacen las pruebas usando el estado `RO` por el cual el cumplido ha pasado dos veces.

### filtrando por año 2025 además de la dependencia y el estado `RO`.

Se evidencia que se retornan los dos históricos, puesto que los dos en el periodo inicial tienen fecha de 2025.

![Image](https://github.com/user-attachments/assets/2171bede-77ef-4ad3-8a6c-2a835e9c8cf5)

### filtrando por año 2025 además de la dependencia y el estado `RO`.

Se evidencia que se retornan los dos históricos, puesto que los dos en el periodo final tienen fecha de 2026.

![Image](https://github.com/user-attachments/assets/0ee10525-fb32-41e4-a74d-97f1162e327c)


### filtrando por año 2025 y mes 2 además de la dependencia y el estado `RO`.

El periodo inicia en el mes 3 del año 2025, por lo tanto al filtrar por el mes 02 del 2025 no se van a retornar el cumplido anterior.

![Image](https://github.com/user-attachments/assets/c7668507-c9bf-4bf2-94f5-e1a1da405ad3)

### filtrando por años 2025, 2026 y mes 2 además de la dependencia y el estado `RO`.

Como el periodo termina el `2026-05-26` la fecha `2026-02` entra en el periodo y por este motivo se retorna el cumplido.

![Image](https://github.com/user-attachments/assets/3dd78405-99ed-4c92-88da-5736c3d51960)


### filtrando por año 2025 y mes 3 además de la dependencia y el estado `RO`.

El periodo inicial inicia en 2025-03 por eso este filtro retorna el cumplido correctamente 

![Image](https://github.com/user-attachments/assets/a260e3cc-1ac3-4d4c-8ba5-49a432e1c9c3)

###

**Comment by faidercamilo26** [comment]
Anteriormente en los filtros aplicados se estaban trayendo todos los estados de un mismo cumplido, lo cual es incorrecto, puesto que para el histórico solo se debía traer el último estado de un cumplido.

### Ejemplo incorrecto anterior

Como se puede notar al filtrar nos trae dos veces el mismo cumplido, puesto que esté cumplido paso en dos ocasiones por el estado `Rechazado ordenador`, lo cual es incorrecto, puesto que  aunque paso dos veces por ese estado solo se debería estar retornando el mismo estado.

![Image](https://github.com/user-attachments/assets/d59209f7-2f23-443b-8485-29c96967a8a7)

### Mismos filtros con el cambio

Podemos notar que aunque se están utilizando los mismos filtros que en el ejemplo anterior en este caso solo está retornando una vez el cumplido id `49` debido a que solo se está teniendo en cuenta el último estado, es decir el estado actual del cumplido y es la manera correcta de retornar los históricos.

![Image](https://github.com/user-attachments/assets/72704ff2-8206-4eb2-a7e7-51249704a19a)

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 Buen trabajo.
