### ISSUE TITLE
Ajustar función de listado de cumplidos reversibles

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#210]
Se requiere realizar de la función ListaCumplidosReversibles del mid

**Sub Tareas**

- [x] Revisar el [error](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/issues/205#issuecomment-2442457445) encontrado en la issue 203 
- [x] Realizar los cambios en la rama [issue/203](https://github.com/udistrital/revision_cumplido_prov_mid/tree/feature/issue%23203)

**Criterios de aceptación**

- [ ] Función de listado de cumplidos revertibles ajustada.
- [ ] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by stevencol** [comment]
Se inicia con actividad, Con la finalidad de detectar la falla del origen

**Comment by stevencol** [comment]
Se realizan pruebas, la cuales dan como resultado la posible causa del error: 
1- Se imprimen la fecha de inicio y fechas fin del ordenador que dan como resultado
![image](https://github.com/user-attachments/assets/f22467a6-ac49-4644-9e29-ccd1148f97d0)

![image](https://github.com/user-attachments/assets/17c1f287-2fee-4a2c-9387-27f98245ec8c)

![image](https://github.com/user-attachments/assets/0978c830-c883-419c-a1b7-88729d09bb2d)

- Por motivos de prueba se evita validación de fachas el cual da como resultado: 

![image](https://github.com/user-attachments/assets/43f6319c-3d1a-46de-9de0-6205ad1b9f65)

**Comment by stevencol** [comment]
Se modifica la consulta, ya que anteriormente había un error en la consulta


``` JavaScript
	if response, err := helpers.GetJsonTest(beego.AppConfig.String("UrlCrudRevisionCumplidosProveedores")+"/cambio_estado_cumplido/?query=DocumentoResponsable:"+documentos+",EstadoCumplidoId.CodigoAbreviacion:AO,Activo:true,FechaModificacion__gte:"+fechaFormateada+"&limit=-1", &respuesta_peticion); err == nil && response == 200 {

```
Esto soluciona el error en la consulta, pero no estaban concatenando los números de documento, por lo que la consulta llegaba vacía y generaba un error.
``` JavaScript
respuesta_peticion["Data"].([]interface{})
```

![image](https://github.com/user-attachments/assets/4706c247-b5b0-400f-86f4-d04278e257f3)

El sistema esperaba la llave [Data], por lo cual se corrige la validación y se modifica la concatenación de los documentos.
por lo que se usa validación 
Pasando de : 
http://pruebasapi2.intranetoas.udistrital.edu.co:8562/v1/cambio_estado_cumplido/?query=DocumentoResponsable:12550145,80746381,12550145,EstadoCumplidoId.CodigoAbreviacion:AO,Activo:true,FechaModificacion__gte:10/15/2024&limit=-1

a 
http://pruebasapi2.intranetoas.udistrital.edu.co:8562/v1/cambio_estado_cumplido/?query=DocumentoResponsable:12550145,80746381,12550145,EstadoCumplidoId.CodigoAbreviacion:AO,Activo:true,FechaModificacion__gte:10/15/2024&limit=-1

y validación
:   

``` JavaScript
if respuesta_peticion["Data"].([]interface{}) != nil && len(data[0].(map[string]interface{})) > 0 {
			helpers.LimpiezaRespuestaRefactor(respuesta_peticion, &cumplidos)
			if len(cumplidos) > 0 {
				for _, cumplido := range cumplidos {
					informacion_contrato_proveedor, err := helpers.ObtenerInformacionContratoProveedor(cumplido.CumplidoProveedorId.NumeroContrato, strconv.Itoa(cumplido.CumplidoProveedorId.VigenciaContrato))
					if err == nil {
						vigencia, _ := strconv.Atoi(informacion_contrato_proveedor[0].Vigencia)
						solicitudes_cumplido := models.SolicituRevisionCumplidoProveedor{
							TipoContrato:              informacion_contrato_proveedor[0].TipoContrato,
							NumeroContrato:            informacion_contrato_proveedor[0].NumeroContratoSuscrito,
							VigenciaContrato:          vigencia,
							Dependencia:               informacion_contrato_proveedor[0].NombreDependencia,
							NombreProveedor:           informacion_contrato_proveedor[0].NombreProveedor,
							Cdp:                       informacion_contrato_proveedor[0].NumeroCdp,
							Rp:                        informacion_contrato_proveedor[0].NumeroRp,
							VigenciaRP:                informacion_contrato_proveedor[0].VigenciaRp,
							CumplidoId:                cumplido.CumplidoProveedorId.Id,
							CodigoAbreviacionCumplido: cumplido.EstadoCumplidoId.CodigoAbreviacion,
							Activo:                    cumplido.Activo,
							FechaCreacion:             cumplido.CumplidoProveedorId.FechaCreacion,
							FechaModificacion:         cumplido.CumplidoProveedorId.FechaModificacion,
						}
						soliciudes_revertibles = append(soliciudes_revertibles, solicitudes_cumplido)
					} else {
						outputError = fmt.Errorf("Error al consultar los cumplidos pendientes de revision por el ordenador")
						return nil, outputError
					}
				}
			} else {
				outputError = fmt.Errorf("No hay cumplidos que se puedan revertir")
				return nil, outputError
			}
		}
```
Evitando asi si la respuesta de data llega nula.

Y Responde : 

![image](https://github.com/user-attachments/assets/9e358605-832c-4229-b102-979a797fa4e0)

Se procede a realizar pruebas desde el cliente.

**Comment by stevencol** [comment]
Después de los ajustes se realizan pruebas y el rechazo funciona correctamente 
![image](https://github.com/user-attachments/assets/36322cdc-795d-48da-867c-92ab48258807)

**Comment by stevencol** [comment]
![finalev](https://github.com/user-attachments/assets/c6273e08-be82-4f75-b2d7-47af84cca160)

**Comment by JuanCamiloMartinezLopez** [comment]
@stevencol Buen trabajo.
