### ISSUE TITLE
Ajustar vista históricos cumplidos proveedores.

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#211]
Se requiere realizar el ajuste de la vista del módulo de históricos de cumplidos proveedores.

**Sub Tareas**

- [x] Cambiar el orden de los select en el formulario, orden propuesto: dependencia, numero contrato, vigencia contrato, proveedor, año, mes y estado.
- [x] Consultar los proveedores y actualizar el select segun las dependencias escogidas:
`POST http://busservicios.intranetoas.udistrital.edu.co:8282/administrativa/proveedores_dependencias
body 
{
    "dependencias": "'DEP626','DEP12'"
}`
- [x] Consultar los contratos y actualizar los selects de numero contrato y vigencia segun las dependencias escogidas:
`POST http://busservicios.intranetoas.udistrital.edu.co:8282/administrativa/contratos_dependencias_total
body 
{
    "dependencias": "'DEP626','DEP12'"
}`
- [x] Modificar la tabla, eliminar columna de mes y fecha_aprobacion, agregar columna de periodo.

**Criterios de aceptación**

- [ ] Cambios realizados.
- [ ] Issue comentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by stevencol** [comment]
Se inicia con la actividad, comenzado por el orden de los Inputs

**Comment by stevencol** [comment]
Se cambia orden de los inputs : 
![image](https://github.com/user-attachments/assets/50cb40d8-7e0c-4e95-9dc9-4534969143c2)


Se crea una función para la consulta de los contratos según la dependencia y, con eso, mostrarlos en el select de proveedor.

``` JavaScript
dependenciaChange(envent: string[]) {
    let body = {
      dependencias: envent.map((dependencia) => `'${dependencia}'`).join(','),
    };

    this.jbpmPostService
      .post('/administrativa/proveedores_dependencias', body)
      .subscribe({
        next: (response: any) => {
          this.listaProveedores = response.dependencias.proveedor.map(
            (dependencia: any) => {
              return {
                Codigo: dependencia.proveedor_id,
                Nombre: dependencia.nombre_proveedor,
              };
            }
          );
        },
      });

    
  }
```

Se está a la espera de que se agreguen los servicios por autenticación, ya que genera CORS origin
![image](https://github.com/user-attachments/assets/b2f81fb8-2f4b-419b-90d2-7fe351dfafd6)

**Comment by stevencol** [comment]
Se soluciona el error de CORS y de código al consultar las dependencias. Ya no está directamente en el código, sino que son consultadas.
![finalev](https://github.com/user-attachments/assets/e15ff761-68c4-436a-a854-817e39e82887)

**Comment by stevencol** [comment]
Se continúa con la función que permite seleccionar el proveedor al seleccionar la dependencia.

![finalev](https://github.com/user-attachments/assets/d462d658-3bc3-4b01-bde6-d76f0a27a531)

**Comment by stevencol** [comment]
Se termina con la edición del formulario: 

![finalev](https://github.com/user-attachments/assets/9dd3a278-dc97-41af-a3b6-c495811ced12)

Al consultar las dependencias, busca los números de contrato.
Al consultar las dependencias, busca los números de los proveedores.
Al seleccionar los contratos, se busca la vigencia.

**Comment by stevencol** [comment]
Se actualiza la tabla pero se esta a la espera que el back responda correctamente el  periodo: 
![image](https://github.com/user-attachments/assets/27fcb4da-83f8-4e6e-96f5-86cc89544d2c)

**Comment by JuanCamiloMartinezLopez** [comment]
@stevencol Buen trabajo.
