### ISSUE TITLE
Implementar firma electrónica para el certificado de DVE

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#212]
Se requiere implementar el servicio de firma electrónica en la generación de certificados de DVE 

**Sub Tareas**

- [x] Implementar firma electrónica en el certificado DVE por parte del jefe de talento humano activo.

**Criterios de aceptación**

- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by stevencol** [comment]
Se inicia con actividad iniciando por la creación del servicio

**Comment by stevencol** [comment]
Al iniciar con la actividad, se evidencia que en la rama master ya se encuentra un servicio de firma electrónica, por lo que se creó una rama a partir de la rama feature/viewCertificacionesDve, donde se encuentra la generación de documentos a la que se desea implementar la firma electrónica y se une con master

**Comment by stevencol** [comment]
También se detecta que ya existe un método para firmar el documento, pero dicho método se encuentra en un componente, por lo que no se puede reutilizar de una manera correcta. Por lo tanto, se creó un servicio para la firma del documento, donde se consulta el documento y se crea la lista de responsables.

**Comment by stevencol** [comment]
Se implementó el servicio ya creado de firma electrónica en CrearCertificacionesDveService.
Donde temporalmente se utilizan datos de prueba, obteniendo el base64 del archivo firmado: 

``` JavaScript
async firmarDocumento(file: any, nombreArchivo: string): Promise<string> {
    let docsAFirmar = [
      {
        IdDocumento: 12,
        nombre: nombreArchivo + ".pdf",
        metadatos: {},
        descripcion: "",
        file: file,
        firmantes: [
          {
            nombre: "solicituDeFirma.NombreResponsable,",
            cargo: "Supervisor",
            tipoId: "CC",
            identificacion: "88194457",
          },
        ],
        representantes: [],
      },
    ];

    try {
      return new Promise((resolve, reject) => {
        this.firmaElectronicaService
          .uploadFilesElectronicSign(docsAFirmar)
          .subscribe({
            next: (response: any) => {
              if ( response &&response.length > 0) {
                resolve(response[0].file);
              } else {
                reject("No se recibió una respuesta válida.");
              }
            },
            error: (error) => {
              reject(error);
            },
          });
      });
    } catch (error) {
      console.log(error);
    }
  }
```
Con esa respuesta se captura. Ya no se descarga el documento directamente, sino que se utiliza su blob y se envía al método anterior de la siguiente manera, el cual envía el PDF en base64 y responde el mismo, pero firmado
``` JavaScript
this.pdf.create().getBlob(async (blob) => {
        let pdfBase64 = await this.firmarDocumento(
          blob,
          informacionCertificacionDve.informacionDve.nombre_docente
        );
        const descarga = document.createElement("a");
        descarga.href = "data:application/pdf;base64," + pdfBase64;
        descarga.download = `${informacionCertificacionDve.informacionDve.nombre_docente}.pdf`;
        descarga.click();
      });
```

**Comment by stevencol** [comment]
Se realiza prueba :

![finalev](https://github.com/user-attachments/assets/d8e9cb1c-ef16-4cb2-83fa-aac255811118)
##  -Se sigue utilizando la consulta con datos falsos

**Comment by stevencol** [comment]
### - Se crea servicio para la consulta de responsable 
``` JavaScript
import { Injectable } from "@angular/core";
import { RequestManager } from "../managers/requestManager";

@Injectable({
    providedIn: 'root',
  })
  

  export class AgoraService{

    constructor(private requestManager:RequestManager){

    }

    get(endpoint: string) {

        this.requestManager.setPath('AGORA_SERVICE');
        return this.requestManager.get(endpoint);
      }

  }
```
### - Se crea método para la consulta del responsable 

``` JavaScript
async  obtenerDatosSuperVisor():Promise<any>{
    try{
 
      return new Promise((resolve, reject)=>{
        this.agoraService.get('supervisor_contrato?query=DependenciaSupervisor:DEP633&sortby=FechaInicio&order=desc').subscribe({
          next:(response:any)=>{
            if(response && response.length>0){

              resolve(response[0])
            }else{
              reject("No se obtuvieron los datos requeridos")
            }
            
          }
        })
      })
    }catch(error){

    }
  }
```


### - Se implementa consulta 
``` JavaScript
async firmarDocumento(file: any, nombreArchivo: string): Promise<string> {

    let data =   await this.obtenerDatosSuperVisor();
    console.log(data)
    let docsAFirmar = [
      {
        IdDocumento: 12,
        nombre: nombreArchivo + ".pdf",
        metadatos: {},
        descripcion: "",
        file: file,
        firmantes: [
          {
            nombre: data.Nombre,
            cargo: data.Cargo,
            tipoId: 'CC',
            identificacion: String(data.Documento),
          },
        ],
        representantes: [],
      },
    ];

    try {
      return new Promise((resolve, reject) => {
        this.firmaElectronicaService
          .uploadFilesElectronicSign(docsAFirmar)
          .subscribe({
            next: (response: any) => {
              if ( response &&response.length > 0) {
                resolve(response[0].file);
              } else {
                reject('No se recibió una respuesta válida.');
              }
            },
            error: (error) => {
              reject(error);
            },
          });
      });
    } catch (error) {
      console.log(error);
    }
  }
```

**Comment by stevencol** [comment]
Con el fin de tener un documento que represente la firma:
se crea un dominio_tipo de documento en la bd udistrita_core schema documento



``` sql
INSERT INTO documento.dominio_tipo_documento (nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion
) 
VALUES (
    'Certificaciones', 
    'Certificaciones', 
    'CERT', 
    true,
    1, 
    NOW(), 
   NOW()
);
```
Y se crea el documento con ese dominio.

``` JavaScript
INSERT INTO documento.tipo_documento (
    nombre, descripcion, codigo_abreviacion, activo, numero_orden, tamano, extension, workspace, tipo_documento_nuxeo, fecha_creacion, fecha_modificacion, dominio_tipo_documento
) 
VALUES (
    'Certificado', 
    'Certificado generado por certificaciones DVE', 
    'CERT-DVE', 
    true, 
    1, 
    5, 
    'pdf', 
    '/desarrollo/workspaces/pruebas', 
    'file', 
    NOW(), 
    NOW(), 
    13
);

```

**Comment by stevencol** [comment]
Se crea e implementa consulta de ID de documento por ID, pero al aplicar y obtener el ID, no es válido para la firma.


-Error al utilizar documento registrado donde se imprime el id tipo de documento  
![image](https://github.com/user-attachments/assets/cdee2a28-d075-4325-b3c7-6a5a321ae52c)

PlayLoad error :

![image](https://github.com/user-attachments/assets/f7a66926-fbad-4af7-b03e-6190b7d2b5bd)



Playload Funcional:
![image](https://github.com/user-attachments/assets/dc506cb3-abd7-492e-b432-7298b6d13116)

**Comment by stevencol** [comment]
La tarea está completada, pero no se puede probar con datos reales, ya que da errores de CORS con la aplicación en local. 
![image](https://github.com/user-attachments/assets/2229b4d6-3b05-42ff-a9e5-873e050e897a)

**Comment by JuanCamiloMartinezLopez** [comment]
> Se crea e implementa consulta de ID de documento por ID, pero al aplicar y obtener el ID, no es válido para la firma.
> 
> -Error al utilizar documento registrado donde se imprime el id tipo de documento ![image](https://github.com/user-attachments/assets/cdee2a28-d075-4325-b3c7-6a5a321ae52c)
> 
> PlayLoad error :
> 
> ![image](https://github.com/user-attachments/assets/f7a66926-fbad-4af7-b03e-6190b7d2b5bd)
> 
> Playload Funcional: ![image](https://github.com/user-attachments/assets/dc506cb3-abd7-492e-b432-7298b6d13116)

Por favor revisar la razon de que se esté respondiendo el id 172 en tipo documento.

**Comment by JuanCamiloMartinezLopez** [comment]
@stevencol Buen trabajo.
