### ISSUE TITLE
Implementar consulta de carga académica para un DVE

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#213]
Se requiere realizar la implementación de consulta de carga académica para DVE 

**Sub Tareas**

- [x] Usar el servicio ofrecido en ODIN con el [Proceso_consumir_servicios_Web (2).pdf](https://github.com/user-attachments/files/17604350/Proceso_consumir_servicios_Web.2.pdf)
- [x] Revisar y ajustar los datos para obtener la información requerida.

**Criterios de aceptación**

- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
## Avances

- Se utiliza el servicio de autenticación y el de carga académica para obtener los datos, en esta parte se tuvo que crear la función auxiliar `sendJsonAutenticacion` puesto que las funciones que se tenían en el proyecto actualmente para realizar las solicitudes `POST` no funcionaban para esta petición, siempre daban un error.
- Para realizar la petición al servicio de carga académica se tiene que enviar el token obtenido por la petición anterior, no había una función en las utilidades que realizara este proceso, por eso se construye la función `sendJsonWithToken` para enviar el token como parámetro de la petición.
- Se crea la función `ObtenerPeriodo()` la cual recibe un periodo en estilo `"2024-III"` y con base en esto retorna el año 2024 y el periodo 3, esta función se utiliza para realizar los filtros por periodos, también se configura correctamente la funcionalidad de filtro por vinculación.

### Filtro sin resultados porque no hay ningún registro de periodos anteriores al 2024-III

![Image](https://github.com/user-attachments/assets/6f2bf8a3-8288-4f99-86a1-304259023db4)

### Filtro con resultados

![Image](https://github.com/user-attachments/assets/43013403-b061-47fd-b646-516f04acb045)

por el momento los datos de horas semanales, numero de semanas, horas semestrales y salario docente no se estan calculando correctamente debido a las limitaciones de los datos que se explican mas adelante en el próximo comentario.

**Comment by faidercamilo26** [comment]
## Limitaciones

- **Numero de horas semanales:** El servicio de carga académica retorna todos los estudiantes de un docente con su horario de clases. teniendo esto en cuenta para calcular el numero  de horas semanales se tendría que recorrer todo el arreglo de retorno y tener en cuenta los campos `ANIO`, `PERIODO`, `ESPACIO`, `ID_GRUPO`, `DIA`, `HORA`. Todos estos datos se deben tener en cuenta puesto que para cada semestre se debe calcular dependiendo de la materia las horas que el docente dicta, sin embargo, como lo que retorna este servicio son todos los estudiantes que tengan la clase con el profesor puede que el mismo horario aparezca infinidad de veces, por eso teniendo en cuenta todos estos datos se evita sumar horas que ya se han sumado anteriormente.

- **Numero de semanas:** El servicio no retorna este dato explícitamente ni algún rango de fechas que permita calcularlo.
- **Horas semestrales:** Para calcular este dato se deben tener los cálculos de las horas semanales y del número de semanas, como no se han podido calcular estos datos, tampoco es posible calcular este.
-  **Salario docente:** El servicio no retorna este valor ni ningún dato que nos pueda servir para calcularlo.
- **Semestres y periodos retornados por el servicio:** Se realizo la prueba de este servicio con tres documentos distintos de docentes y en todos solo retorno las asignaturas del periodo 2024-III es decir el ultimo periodo activo.

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 Buen trabajo.
