### ISSUE TITLE
Ajustes al Modelo base de datos Evaluación Proveedores - Parte II

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#214]
Se requiere realizar el ajuste al modelo de base de datos presentado #202 

**Sub Tareas**

- [x] Cambiar la tabla de item para que sea similar a agora.item_cotizacion de udistrital.
- [x] Quitar documento_responsable por la referencia a agora.informacion_persona_natural.
- [x] Cambiar el nombre de la tabla evaluador por asignacion_evaluador.
- [x] Revisar y ajustar los comentarios sobre las tablas.
- [x] Quitar columna proveedor_id de evaluación.

**Criterios de aceptación**

- [x] Modelo modificado.
- [x] Issue comentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
## :triangular_flag_on_post: **Ajustes modelo de base de datos**  :triangular_flag_on_post:


Se modifica el modelo de la base de datos de acuerdo a los cambios sugeridos por el equipo de DBA, se sube a la carpeta del proyecto la imagen del modelo, el archivo editable de la aplicación pgModeler y el script.

[Carpeta del proyecto.](https://udistritaleduco-my.sharepoint.com/shared?id=%2Fpersonal%2Fcomputo%5Fudistrital%5Fedu%5Fco%2FDocuments%2FINVERSI%C3%93N%2FPROYECTOS%20DE%20INVERSI%C3%93N%2FGERENCIA%20DE%20PROYECTOS%2FPROYECTOS%20OAS%2FPROYECTO%20CUMPLIDOS%20Y%20CERTIFICACIONES%2F2024%2FEjecuci%C3%B3n%2FGesti%C3%B3n%20t%C3%A9cnica%2FCUMPLIDOS%2FProveedores%2FModelos%20de%20base%20de%20datos%2FEvaluaci%C3%B3n%20cumplidos%20proveedores%2Fv8&listurl=%2Fpersonal%2Fcomputo%5Fudistrital%5Fedu%5Fco%2FDocuments)


![Image](https://github.com/user-attachments/assets/1566877f-6ad5-4f3b-b365-3b35f9288413)

**Comment by faidercamilo26** [comment]
Se realiza la corrección del modelo ajustando los últimos detalles dialogados en el daily. Se sube el modelo corregido a la carpeta.![Image](https://github.com/user-attachments/assets/c8d3e0b2-7c2b-44a2-8956-24b876b61c8d)

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 Buen trabajo.
