### ISSUE TITLE
Ajustes resultado pruebas de carga y seguridad - revisión cumplidos proveedores - cliente

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#215]
Se requiere realizar los ajustes resultantes de las [pruebas de carga y seguridad](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/mfavendannom_udistrital_edu_co/EVOEjwB6j2JCq4RCajMYuZoBsNx4WpYGEf7vq6OxQn0J8A?e=cbePcC)

**Sub Tareas**

- [x] Revisar las alertas de dependencias de los repositorios https://github.com/udistrital/revision_cumplidos_proveedores_mf/security/dependabot y https://github.com/udistrital/cumplidos_proveedores/security/dependabot
- [x] revisar el cargue de los archivos de lenguaje en.json y es.json.
- [x] eliminar los mensajes por consola.
- [x] cambiar el icono y nombre del sistema
![Image](https://github.com/user-attachments/assets/18995605-5b8f-4681-a4ea-4b658ea1eb8b)

**Criterios de aceptación**

- [x] Problemas y recomendaciones solucionadas.
- [x] Issue documentadas.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by stevencol** [comment]
Se inicia con actividad, eliminado los mensajes por consola

**Comment by stevencol** [comment]
Se eliminan mensajes de consola, incluidos los comentados.

**Comment by stevencol** [comment]
Se está trabajando en los errores de los archivos de lenguaje en.json y es.json, y se detecta que son generados ya que estos son llamados en la petición apuntando al root y no al microcliente.
![image](https://github.com/user-attachments/assets/d4beb930-9a3f-4927-866f-3d13742c7ce4)

consulta al root:
![image](https://github.com/user-attachments/assets/7c35843b-f27b-46b4-ab6e-200636ffcbe7)

Consulta desde el micro cliente - 

![image](https://github.com/user-attachments/assets/2564b251-946d-4685-b946-06c02aaa9997)

**Comment by stevencol** [comment]
fix: corrección de archivos de lenguaje en.json y es.json

- Se modifica la variable de entorno `apiUrl: 'http://localhost:4202/'` en `environment.development`.
- En `app.module.ts` se agrega la ruta con la variable de entorno.
- En `angular.json` se agrega el enrutamiento a los assets.

app.module.ts:
![image](https://github.com/user-attachments/assets/b8bf29b4-f3a8-41ef-902d-4781fc3d4622)

 angular.json:
![image](https://github.com/user-attachments/assets/65f9ff4d-905e-4274-8b36-17fc03d3fa36)

**Comment by stevencol** [comment]
Nombre cambiado: 
![image](https://github.com/user-attachments/assets/2d738e4e-5a74-48b7-9fe7-59cd2f290871)

**Comment by stevencol** [comment]
Problema de archivos solucionado : 

Ahora:
![finalev](https://github.com/user-attachments/assets/81c2c591-cb4d-4c6a-abb1-8b55bad44915)

Antes: 


![finalev](https://github.com/user-attachments/assets/d12bfceb-f8db-4b32-8bfe-aedbec7d741e)

**Comment by stevencol** [comment]
Se prueba con proyecto construido y funciona

![finalev](https://github.com/user-attachments/assets/b9473a35-d4b1-4097-88d6-67d2e95dbd96)

**Comment by stevencol** [comment]
## Ajuste Dependabot alerts:

1.  
![image](https://github.com/user-attachments/assets/8600241f-56bf-4577-ad2f-b8afa02878ff)


Segun sugerencia se debe remplazar:

![image](https://github.com/user-attachments/assets/f64ac8ce-bbec-4e4d-880f-8fadab396c10)

Se actualiza version de dependendcia : 

![image](https://github.com/user-attachments/assets/5b0e7a18-fb14-4e93-a1c4-fb3bbd8b529e)

![image](https://github.com/user-attachments/assets/17ee9c8d-666e-41c7-8bb0-eef65718add9)

![image](https://github.com/user-attachments/assets/b3463833-2661-4932-ad3b-2a29f3353b29)
![image](https://github.com/user-attachments/assets/ec633f3a-6da3-4b2d-9563-007ee35659f0)

**Comment by stevencol** [comment]
2. Remplazar dependencia 

![image](https://github.com/user-attachments/assets/e83c8546-2e05-4301-bc95-e90c39a30a00)

Por recomendación  de   [bot](https://github.com/udistrital/revision_cumplidos_proveedores_mf/security/dependabot/5) Se actualiza 
![image](https://github.com/user-attachments/assets/b1e801fb-b627-43b4-a0ce-08f1cfdcad11)

**Comment by stevencol** [comment]
3 :

![Uploading image.png…]()


Por recomendación  de   [bot](https://github.com/udistrital/revision_cumplidos_proveedores_mf/security/dependabot/6) Se actualiza 

![image](https://github.com/user-attachments/assets/23b02ddc-fe6b-4442-8d3e-b48874d6f80e)

**Comment by stevencol** [comment]
4. 
![image](https://github.com/user-attachments/assets/2e8b2d67-2753-4f1c-a041-9d2444896cb6)

Por recomendación  de   [bot](https://github.com/udistrital/revision_cumplidos_proveedores_mf/security/dependabot/1) Se actualiza 

![image](https://github.com/user-attachments/assets/13a69154-d86d-4d7c-8bc5-e46ec70ecd49)

# Nota
Aunque se ha actualizado sweetalert2 a la versión 11.6.13, que es la última disponible, la vulnerabilidad relacionada con la funcionalidad oculta sigue apareciendo en los reportes de auditoría.

Fuente :   [Repo](https://github.com/sweetalert2/sweetalert2/releases)

**Comment by stevencol** [comment]
Para solucionar el inconveniente, se crea una rama (feature/issues#215) en el root, la cual contiene un proxy que permite la carga del archivo de traducción desde el microcliente. Es una solución propuesta debido al comportamiento de Single SPA, ya que la carga de archivos se realiza directamente desde el root. Esta solución está en evaluación, ya que posiblemente funcione con un microcliente y, en el futuro, podría ser necesario adaptarla para más microclientes

**Comment by JuanCamiloMartinezLopez** [comment]
@stevencol buen trabajo.
