### ISSUE TITLE
Realizar pruebas funcionales - históricos y reversión proveedores.

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#216]
Se requiere realizar las pruebas funcionales de los módulos de históricos y revisión en cumplidos proovedores

**Sub Tareas**

- [ ] 

**Criterios de aceptación**

- [ ] 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se ha realizado las pruebas en el siguiente documento
[documento de pruebas](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/ETpX_4GnN9pOjRUkcTVshrABZCgyqUCnqJ3stn0m_p4inw?e=efZuJu)

**Comment by jcmurilloa** [comment]
Muy buen trabajo @mantnicot, insumo fundamental para el equipo de desarrollo.
