### ISSUE TITLE
Revisar vista de talento humano - Certificaciones DVE

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#219]
Se requiere realizar la revisión de la vista para talento humano en el módulo de generación de Certificados DVE

**Sub Tareas**

- [x] Revisar e implementar en dado caso la funciona para la generación del certificado DVE.
- [x] Contrastar vista con el mockup e identificar las funciones faltantes.

**Criterios de aceptación**

- [ ] Issue comentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by stevencol** [comment]
Se inicia con la actividad verificando primero la vista y su funcionalidad planteada, donde se comprueba que la funcionalidad planeada ya está en el diseño visual.

Vista planteada:

![Flujo certificaciones DVE-HC-003 drawio](https://github.com/user-attachments/assets/37ab2ab7-c424-4834-94c5-9817428c9bd2)
Vista actual:
![image](https://github.com/user-attachments/assets/8febe30a-fb15-45ae-89e0-8212afd4cc95)

**Comment by stevencol** [comment]
1: Cambiar nombres de componentes ya que el de talento humano se llama formulario.cetificaciones y el de docente esta como formulario_talento-humano

![image](https://github.com/user-attachments/assets/710c2405-bdbf-41ee-8e57-d83a795c67b4)

**Comment by stevencol** [comment]
2 crear método para obtener el rol y mostrar la vista  , ya que originalmente así se establecio

![image](https://github.com/user-attachments/assets/27fcf392-c322-4978-8458-949fa8170c1b)

**Comment by stevencol** [comment]
3. Crear un método que implemente la consulta, el cual a su vez crea el documento según los datos del formulario, teniendo en cuenta que el formulario solo solicita nombre e incluye salario. Si el backend funciona con eso, sería perfecto.

4. Ya el método de creación está elaborado por lo que solo se requeriría que el backend responda.

He corregido los errores ortográficos y mejorado un poco la estructura para mayor claridad.

**Comment by stevencol** [comment]
3. Crear un método que implemente la consulta, el cual a su vez crea el documento según los datos del formulario, teniendo en cuenta que el formulario solo solicita nombre e incluye salario. Si el backend funciona con eso, sería perfecto.

4. Ya el método de creación está elaborado por lo que solo se requeriría que el backend responda.

**Comment by JuanCamiloMartinezLopez** [comment]
@stevencol Buen trabajo.
