### ISSUE TITLE
Concertar, desarrollar y levantar acta de sesión de requerimientos y refinamiento con el cliente sobre ítems de contratación

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/Cumplidos_y_certificaciones_documentacion#220]
Se requiere realizar la concertación, desarrollo y levantamiento del acta de sesión de requerimientos y refinamiento con el cliente sobre ítems de contratación

**Sub Tareas**

- [x] Concertar reunión con el cliente.
- [x] Desarrollar la reunión con el cliente.
- [x] Diligenciamiento y aprobación del formato de historias de usuario o Mockup por parte del cliente (si aplica).
- [x] Proyectar acta de la reunión.
- [x] Recolectar las firmas correspondientes.

**Criterios de aceptación**

- [x] Acta revisada por el líder de proyecto.
- [x] Acta firmada por las partes con anexo de historias de usuario o mockup.
- [x] Acta y anexos documentados.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
se agrega el acta de la reunión

[acta sin firmas](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EfS5dvtupj5AhVvUnVMBVc0BUzgqbkkA4LRc5yjN9g0J8A?e=Gngyff)

**Comment by jcmurilloa** [comment]
Acta revisada y con VoBo para recolección de firmas!

**Comment by mantnicot** [comment]
Se ha recolectado las firmas
[acta firmada](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/ERTQ-xVgpBxKtoSzifvWvO8BII3BvQp1i9BgDF2RBk0KWA?e=ID908x)

**Comment by jcmurilloa** [comment]
Muy buen trabajo @mantnicot!
