### ISSUE TITLE
Ajustes resultado pruebas de carga y seguridad - revisión cumplidos proveedores - mid

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#221]
Se requiere realizar los ajustes resultantes de las [pruebas de carga y seguridad](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/mfavendannom_udistrital_edu_co/EVOEjwB6j2JCq4RCajMYuZoBsNx4WpYGEf7vq6OxQn0J8A?e=cbePcC)

**Sub Tareas**

- [x] Revisar el manejo de cors y librería de auditoría.
- [x] Revisar error al cargar un documento no pdf con extensión pdf (realizar validación completa de tipo de documento)

**Criterios de aceptación**

- [x] Cambio realizado.
- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
## :triangular_flag_on_post: **Ajustes pruebas de carga y seguridad**  :triangular_flag_on_post:

Se realiza la implementación de los cors para que solo se aceptan dominios `*.udistrital.edu.co` y tambien se implementa la libreria  de `auditoria`.

Como se puede evidenciar en la captura, la librería de `auditoria` aparece que está deprecada, sin embargo, en la respuesta de la consola se puede evidenciar que esta sigue funcionando.

![Image](https://github.com/user-attachments/assets/d88693f8-d2f2-4083-9d38-90a783e2bf09)

Al realizar la configuración de los cors al conectar el cliente con el mid nos da un error de cors, sin embargo, este error se soluciona fácilmente agregando la instrucción `http://localhost:4200` a la lista de la variable `AllowedOrigins`. Cabe aclarar que esto solo se debe realizar para realizar pruebas y no se debe subir este cambio a un entorno de producción, puesto que esto ocasionaría que se pudieran realizar consultas desde un entorno local.

![Image](https://github.com/user-attachments/assets/8eeae42c-bd86-481a-a9ec-fb3f9753bf90)

**Comment by faidercamilo26** [comment]
## :triangular_flag_on_post: **Error al cargar documento**  :triangular_flag_on_post:

Anteriormente el sistema solo validaba que el documento que se iba a subir terminara en `.pdf` sin embargo, al renombrar un documento de cualquier extensión con un `.pdf` al final del nombre el cliente recibía el documento pero en el mid se generaba un error, se edito esta parte para que el cliente valide exactamente que el archivo a subir sea un pdf y no otro tipo de documento renombrado.

### Verificación de archivo PDF en Angular

Para asegurar que el archivo cargado es un PDF real (y no solo un archivo renombrado con la extensión `.pdf`), hemos añadido un método de validación basado en la firma binaria del archivo. Los archivos PDF genuinos comienzan con la secuencia de bytes `%PDF`, lo que nos permite verificar su autenticidad.

#### Implementación del Método `isPDF`

```typescript
isPDF(fileBytes: Uint8Array): boolean {
  const pdfSignature = [0x25, 0x50, 0x44, 0x46]; // %PDF en ASCII
  return pdfSignature.every((byte, index) => fileBytes[index] === byte);
}

```

### Ejemplo archivo `.doc` renombrado con `.pdf`

![Image](https://github.com/user-attachments/assets/117c2da1-8609-4769-95f6-98b5d35e986b)

### Ejemplo Archivo pdf real

![Image](https://github.com/user-attachments/assets/55063cd1-3c76-4784-a79a-f34d8e1b9198)

### Ejemplo con archivo extensión `.jpeg`

![Image](https://github.com/user-attachments/assets/aa587bdb-6268-4988-8c3e-64271812a67d)

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 buen trabajo.
