### ISSUE TITLE
Revisar error en modulo de históricos y reversión desplegados en pruebas

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#222]
Se requiere realizar la revisión de los errores al cargar la vista de históricos y de reversión en el cliente desplegado.

**Sub Tareas**

- [x] Revisar errores y solucionarlos.
- [x] Preparar el entorno para la correcta ejecución de las pruebas.

**Criterios de aceptación**

- [ ] Entorno de pruebas funcionando.
- [x] Issue documentada. 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by stevencol** [comment]
Se inicia con actividad, como primer error se evidencia que al seleccionar la dependencia no está consultado las vigencias, los contratos, no realiza la petición cuando se selecciona la dependencia 
![finalev](https://github.com/user-attachments/assets/bf8fafbf-1e3a-47f4-89e1-8ced6fd9587c)

- Se va construir el proyecto en local y verificar su funcionamiento

**Comment by stevencol** [comment]
Se detecta que el error de redireccionamiento es porque en configuración la ruta estaba "historico-cumplidos" y es "historicos-cumplidos

![image](https://github.com/user-attachments/assets/911ccc0c-e099-4a27-a8e0-70011b9e51d4)

Se configura.: 
![image](https://github.com/user-attachments/assets/576c042a-deee-4ce6-89b0-72596e367e91)

**Comment by stevencol** [comment]
Después de los cambios realizados en las variables de entorno, el sistema recobra la funcionalidad para consultar los números de contrato y el nombre del proveedor en vigencia. Sin embargo, al hacer la consulta, el back recibe un tipo numérico, pero se envía un tipo texto.
![finalev](https://github.com/user-attachments/assets/4da0dad7-77e9-42cc-b5e8-defaec5714bd)

Playload: 
``` JavaScript
{
  "Anios": [],
  "Meses": [],
  "Vigencias": [
    "2023"
  ],
  "Proveedores": [],
  "Estados": [],
  "Dependencias": [
    "DEP626"
  ],
  "Contratos": [
    "2035"
  ]
}
```

Response: 
![image](https://github.com/user-attachments/assets/bc7d7d58-ff71-4ba0-9b44-0f71bde7084c)

**Comment by stevencol** [comment]
Se modifican tipo de variables según cambios en el back:   y se soluciona el inconveniente 
Playload
``` Json
{
    "Anios": [],
    "Meses": [],
    "Vigencias": [],
    "Proveedores": [],
    "Estados": [],
    "Dependencias": [
        "DEP626"
    ],
    "Contratos": [
        "2026"
    ]
}
```

response: 
![image](https://github.com/user-attachments/assets/923af4e5-1466-4e28-94bc-78e37f825f63)

**Comment by stevencol** [comment]
Se detectó un pequeño error que causaba que la lista de números de contrato, aunque la consulta se realizaba correctamente, se actualizara sin borrar los datos anteriores, lo que provocaba que la lista siguiera creciendo.
![finalev](https://github.com/user-attachments/assets/83ae6990-7d9b-403a-91f7-5802bf1292ed)

Se actualiza:
![finalev](https://github.com/user-attachments/assets/6a2ebde1-d7c8-4ece-8bf9-f4f3d30282fb)

**Comment by JuanCamiloMartinezLopez** [comment]
@stevencol Buen trabajo.
