### ISSUE TITLE
Propuesta de servicio para consultar los items en ágora de un contrato proveedor

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#223]
Se requiere realizar la propuesta de servicio para consultar los ítems en argo de un contrato proveedor

**Sub Tareas**

- [x] Revisar modelo de argo respecto a las cotización ([video de explicacion](https://udistritaleduco-my.sharepoint.com/:v:/g/personal/juacmartinezl_udistrital_edu_co/EaEWZ-_bs7VJhxbR0J6GS5IBfd0J7lUkue_ZcV7GUvzmbw?e=35dLhX))
- [x] Proponer un consulta de sql que segun la informacion del contrato retorne los items

**Criterios de aceptación**

- [x] Propuesta de servicio.
- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
## :triangular_flag_on_post: **Propuesta servicio para consultar los items de un contrato**  :triangular_flag_on_post:

Se revisa la totalidad del video para tener un mayor entendimiento del funcionamiento de Agora y así poder comprender la estructura ideal para el servicio, se toman capturas de pantalla de algunas consultas relevantes que se pueden servir para construir el servicio.

![Image](https://github.com/user-attachments/assets/59aebcce-c6d3-47dd-96a3-144b917c48d8)

![Image](https://github.com/user-attachments/assets/202b2868-3ae8-4957-8bc3-d81d46926bb6)

![Image](https://github.com/user-attachments/assets/119d789b-9351-4ca7-9efc-86f0f3600ae0)

**Comment by faidercamilo26** [comment]
Según la información brindada se piensa crear un servicio que retorne el número de necesidad de un contrato, por lo tanto, se propone crear el siguiente servicio, el cual recibe un numero de necesidad y retorna todos los `item_cotizacion`  asociados, se entiende que este número de necesidad es único. Adicional se hace la validación de que el resultado cotización sea igual a 1. Lo que indica que la propuesta cotización fue la ganadora. Esto se hace solo como validación extra, puesto que se entiende que si hay un contrato es porque la propuesta fue la ganadora.

```sql

SELECT ic.id, ic.respuesta_cotizacion_proveedor, ic.item_cotizacion_padre_id, ic.valor_unitario, ic.iva, ic.ficha_tecnica 
FROM agora.item_cotizacion ic
join agora.respuesta_cotizacion_proveedor rcp on ic.respuesta_cotizacion_proveedor = rcp.id 
join agora.solicitud_cotizacion sc on rcp.solicitud_cotizacion = sc.id 
join agora.respuesta_cotizacion_solicitante rcs on sc.id = rcs.solicitud_cotizacion 
join agora.resultado_cotizacion rc on rcs.resultado = rc.id 
join agora.item_cotizacion_padre icp on ic.item_cotizacion_padre_id = icp.id 
join agora.objeto_cotizacion oc on icp.objeto_cotizacion_id = oc.id 
where oc.numero_necesidad = ? and rc.id = 1;

```

En el ejemplo se uso la respuesta cotización numero `2928` como ejemplo, por lo tanto se creo la siguiente consulta para obtener el numero de necesidad de esa cotización y probar la propuesta de servicio, sin embargo, esta petición solo sirve en la base de datos de producción, como no tengo acceso a esas bases de datos no puedo realizar la prueba directamente.

```sql

select oc.numero_necesidad
from agora.objeto_cotizacion oc 
join agora.item_cotizacion_padre icp on oc.id = icp.objeto_cotizacion_id
join agora.item_cotizacion ic on icp.id = item_cotizacion_padre_id
where ic.respuesta_cotizacion_proveedor = 2928;

```

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 Buen trabajo.
