### ISSUE TITLE
Construir diagrama modular y de procesos del sistema

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/Cumplidos_y_certificaciones_documentacion#224]
Se requiere realizar la construcción de los diagramas modulares y de procesos del sistema como complemento de la documentación técnica.

**Sub Tareas**

- [x] Revisar la inmersión del requerimiento según los siguientes enlaces: https://udistritaleduco-my.sharepoint.com/:b:/g/personal/caescorciab_udistrital_edu_co/ES7a6FEo7gFIvQXkuLrLJp8BwC2OkgrCL7OTdsrHmTVPfQ?e=lpuvxv, https://udistritaleduco-my.sharepoint.com/:b:/g/personal/caescorciab_udistrital_edu_co/Ef8JZ-s9FXJBkRFKbsLcR2EBWG2yk5hAQ_qt7x0dcUo_sA?e=q9rxnW
- [x] Articular con líder técnico la información necesaria.
- [x] Proyectar los diagramas modulares y de procesos para equipo SoS.

**Criterios de aceptación**

- [x] Diagramas aprobados por equipo SoS
- [x] Diagramas referenciados en carpeta Documentación técnica

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico/SoSM.
- [ ] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
![Image](https://github.com/user-attachments/assets/9879719b-092c-4703-84fc-8c3b59a4c4df)
![Image](https://github.com/user-attachments/assets/52bfa105-bb52-47f4-ae2a-8fb62b366f05)

se han realizado los dos diagramas modulares del sistema 

[Carpeta diagrama modular](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EtVk75bhDexInP_VUhG8JTYBoe0hyg1_J65MF-EQeseZ_g?e=f7FdkL)

**Comment by mantnicot** [comment]
Se realizo los cambios del diagrama modular 
![Image](https://github.com/user-attachments/assets/3034f3ac-e588-43cd-82fd-e5cf663e1797)
y se realizo el diagrama de proceso
![Image](https://github.com/user-attachments/assets/2fa67037-0467-4c8f-8eba-60cba8a24304)

[Carpeta de proceso](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EkvIII0zWJ1Np-dlvhU61v0B71u3PmwPgeqdmQrlEtPKwA?e=SYZSsB)

**Comment by jcmurilloa** [comment]
Excelente trabajo @mantnicot, diseños incluidos en documentación del proyecto para presentar a funcionamiento.
