### ISSUE TITLE
Ajuste de servicio de generación de certificado DVE

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#225]
Se requiere realizar el ajuste de la función de certificados de DVE para consultar información faltante #213.

**Sub Tareas**

- [x] Realizar el mapeo de información de argo y resoluciones( v1 y v2) para completar la información faltante.
- [x] Realizar pruebas de su correcto funcionamiento.

**Criterios de aceptación**

- [x] Servicio ajustado.
- [x] Issue documentado.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
## Avances

Se esta intentando utilizar la información de las vinculaciones de cada docente que se obtienen con la función creada en la [issue 230](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/issues/230) contrastada con la información que retorna el servicio de carga_academica, sin embargo, la información de estas dos partes no coincide, y eso que las vinculaciones se estan retornando de producción.

Se realizan ejemplos con el docente `JOSÉ  VILLADA DIAZ` identificado con la cédula `19188722` .

### Vinculaciones

![Image](https://github.com/user-attachments/assets/12cc1435-bdc2-455e-a111-7674015e7721)

### Servicio carga académica 

Procesando las cargas académicas del docente para obtener las materias distintas da la siguiente información.

![Image](https://github.com/user-attachments/assets/6bdce228-cde9-47da-b9be-948288cded9b)


El inconveniente es que solo nos aparece una vinculación para el docente en el periodo 2024-III pero en el servicio de cargas académicas nos aparecen dos materias distintas del docente para el mismo semestre.

**Comment by faidercamilo26** [comment]
## Cambios

- Se crea la función `VinculacionesDocenteDve()` y su respectivo controlador para poder retornar una lista de vinculaciones de un docente para poder seleccionar una o varias para filtrar los datos. 
- Para filtrar las vinculaciones se debe enviar las vinculaciones de la siguiente manera: `vigencia-periodo-codProyectoCurricular`, puesto que como al combinar las vigencias con el servicio creado no hay algun id en común para referenciarlas.

![Image](https://github.com/user-attachments/assets/3e824932-2aea-4940-a267-7734043f1820)

- Se vincula esta función con la función `InformacionDve()` para contrastar los datos obtenidos en el servicio de vinculacion_academica con las vinculaciones retornadas por la función `VinculacionesDocenteDve()` para poder retornar la informacion completa del docente y las vinculaciones.

![Image](https://github.com/user-attachments/assets/68e92b52-cd8b-4fbe-ac24-cec7a79eca67)

**Comment by faidercamilo26** [comment]
## Inconvenientes 

El Principal inconveniente que se puede notar es que en el servicio que retorna la carga_academica de un docente, retornando todos los estudiantes de la clase, retorna dos distintas materias de distintos proyectos curriculares(`TECNOLOGIA EN SISTEMATIZACION DE DATOS (CICLOS PROPEDEUTICOS)` e `INGENIERIA EN TELEMATICA (CICLOS PROPEDEUTICOS)`), y la petición de vinculaciones retorna una sola vinculación para el periodo `2024-3` la de `TECNOLOGIA EN SISTEMATIZACION DE DATOS (POR CICLOS PROPEDEUTICOS)` la asociación entre estos dos servicios se realiza teniendo en cuenta las coincidencias entre año, periodo y proyecto curricular. Por este motivo cuando se hace la petición solo se retornan las materias de `TECNOLOGIA EN SISTEMATIZACION DE DATOS (POR CICLOS PROPEDEUTICOS)` en este caso `Fundamentos de organización`, pero no se retornan las materias del proyecto curricular `INGENIERIA EN TELEMATICA (CICLOS PROPEDEUTICOS)` que en este caso es `INGENIERÍA ECONÓMICA`.

### Servicio Carga académica

![Image](https://github.com/user-attachments/assets/f0154bc0-339f-4c42-9cf4-c4a95adaf826)

### Petición vinculaciones docente

![Image](https://github.com/user-attachments/assets/9a061ad3-ee46-44f8-9364-06721edba3ff)

### Resultado

![Image](https://github.com/user-attachments/assets/7b2202b9-5a63-4812-aa0c-70fad1e4eda3)

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 Buen trabajo.
