### ISSUE TITLE
Implementar funcionalidad en cliente de certificaciones DVE

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#226]
Se requiere realizar la implementación de funcionalidad a las vistas.

**Sub Tareas**

- [x] Implementar la consulta a los servicios de las issues #225 y #230 
- [x] Implementar la distinción por rol para las vistas.

**Criterios de aceptación**

- [x] vistas con funcionalidades implementadas.
- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by stevencol** [comment]
Se inicia con la actividad. Inicialmente se crea una función para obtener los roles a partir del token, con la finalidad de mostrar el menú según el rol, ya sea talento humano o docente. Si por algún motivo el usuario tiene roles de talento humano (no debería pasar), el menú predominante sea el de talento humano.

**Comment by stevencol** [comment]
Se muestra menú, según rol, en este caso el usuario tiene los dos roles, por lo que predomina el rol de talento humano
![finalev](https://github.com/user-attachments/assets/d473b8f0-28cb-40ff-9244-15175ffbff79)

Metodo utilizado para obtener roles: 

``` JavaScript
  obtenerRoles():string[]{
   return this.userService.getPayload().role
  }

```

**Comment by stevencol** [comment]
Para motivos de pruebas se remplaza temporalmente el método, para que solo retorne el rol de DOCENTE

``` JavaScript

  obtenerRoles():string[]{
   //return this.userService.getPayload().role
   return["DOCENTE"]
  }
```

Funcionalidad: 
![finalev](https://github.com/user-attachments/assets/e51e5693-5199-45e2-8362-0498728079fb)

**Comment by stevencol** [comment]
## No se logra, realizar la actividad se tienen inconvenientes con   CORS
![image](https://github.com/user-attachments/assets/15aafcc5-8bf3-4dc1-9d6c-772e2f655ae2)


Se intenta creando un proxy en el cliente obteniendo el mismo resultado

Forma original: 
``` JavaScript
{
    "/v1": {
      "target": "http://localhost:8080",
      "secure": false
    }
  }
```

Se intenta especificar lo orígenes en el back 
``` JavaScript
func main() {
	if beego.BConfig.RunMode == "dev" {
		beego.BConfig.WebConfig.DirectoryIndex = true
		beego.BConfig.WebConfig.StaticDir["/swagger"] = "swagger"
	}

	beego.InsertFilter("*", beego.BeforeRouter, cors.Allow(&cors.Options{
		AllowOrigins: []string{"*"},
		AllowMethods: []string{"PUT", "PATCH", "GET", "POST", "OPTIONS", "DELETE"},
		AllowHeaders: []string{"Origin", "x-requested-with",
			"content-type",
			"accept",
			"origin",
			"authorization",
			"x-csrftoken",
			"pragma",
			"cache-control"},
		ExposeHeaders:    []string{"Content-Length"},
		AllowCredentials: true,
	}))
	beego.ErrorController(&customerrorv2.CustomErrorController{})
	apistatus.Init()
	beego.Run()
}

```


Se intenta especificar usando ip local

``` JavaScript
func main() {
	if beego.BConfig.RunMode == "dev" {
		beego.BConfig.WebConfig.DirectoryIndex = true
		beego.BConfig.WebConfig.StaticDir["/swagger"] = "swagger"
	}

	beego.InsertFilter("*", beego.BeforeRouter, cors.Allow(&cors.Options{
		AllowOrigins: []string{"http://http://localhost:4200/"},
		AllowMethods: []string{"PUT", "PATCH", "GET", "POST", "OPTIONS", "DELETE"},
		AllowHeaders: []string{"Origin", "x-requested-with",
			"content-type",
			"accept",
			"origin",
			"authorization",
			"x-csrftoken",
			"pragma",
			"cache-control"},
		ExposeHeaders:    []string{"Content-Length"},
		AllowCredentials: true,
	}))
	beego.ErrorController(&customerrorv2.CustomErrorController{})
	apistatus.Init()
	beego.Run()
}
```

Tampoco funciona,

- Se intenta usar otra configuración, de igual manera sigue sin funcionar 


``` JavaScript
func main() {
	
AllowedOrigins := []string{"*"}
	if beego.BConfig.RunMode == "dev" {
		beego.BConfig.WebConfig.DirectoryIndex = true
		beego.BConfig.WebConfig.StaticDir["/swagger"] = "swagger"
	}
	beego.InsertFilter("*", beego.BeforeRouter, cors.Allow(&cors.Options{
		AllowOrigins: AllowedOrigins,
		AllowMethods: []string{"PUT", "PATCH", "GET", "POST", "OPTIONS", "DELETE"},
		AllowHeaders: []string{"Origin", "x-requested-with",
			"content-type",
			"accept",
			"origin",
			"authorization",
			"x-csrftoken"},
		ExposeHeaders:    []string{"Content-Length"},
		AllowCredentials: true,
	}))
	beego.ErrorController(&customerrorv2.CustomErrorController{})
	apistatus.Init()
	beego.Run()
}
```

- Se intenta ejecutando el navegador sin restricciones de seguridad , con el siguete comando 

C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe" --user-data-dir="C:/EdgeDevSession" --disable-web-security --disable-site-isolation-trials

Genera error al realizar la petición
![image](https://github.com/user-attachments/assets/4a7e2839-ee23-4836-9b21-9eab4b764961)

Se detecta que el error posiblemente es por la petición no esta enviando el playload 
![image](https://github.com/user-attachments/assets/1fdf4730-82ea-4d60-907b-fe8c2e46f498)

- Se se usa el requestManager ya establecido el error se mantiene se está imprimiendo la petición,  si se esta ejecutando 

![image](https://github.com/user-attachments/assets/44f38003-827f-4796-ae4f-f0a37915fbf5)


``` JavaScript
post(endpoint, element) {
    return this.http.post<any>(`${this.path}${endpoint}`, element, this.httpOptions).pipe(
      catchError(this.errManager.handleError),
    );
  }
```


- se intenta crear directamente el request desde el componente de la siguiente manera 

``` JavaScript
 constructor(private http: HttpClient,private requestManager:RequestManager,private popUpManager:PopUpManager,private errManager:HttpErrorManager) {}
  private httpHeaders = new HttpHeaders({
    "Content-Type": "application/json",
  });


  get(endpoint: string) {

    this.requestManager.setPath('EVALUACIONMID_SERVICE');
    return this.requestManager.get(endpoint);
  }


 
  post(endpoint, element) {
    return this.http.post<any>(this.urlCertificacionesDve+endpoint, element, {
      headers: this.httpHeaders,
    }).pipe(
      catchError(this.errManager.handleError),
    );
  }

```
Sigues sin funcionar:

**Comment by stevencol** [comment]
Se sigue con la actividad. Como solución, se intentó reinstalar la versión de Node, cosa que no funcionó. Al realizar esto, se presentan inconvenientes al tratar de volver a ejecutar el proyecto, ya que las versiones de la página del repositorio no funcionan. El proyecto se logra ejecutar con las mismas versiones de Angular y Node."

Node:

``` JavaScript
$ node -v
v12.22.12

```

Angular y Angular cli
``` JavaScript
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 7.3.10
Node: 12.22.12
OS: win32 x64
Angular: 7.2.16
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.10
@angular-devkit/build-angular     0.13.10
@angular-devkit/build-optimizer   0.13.10
@angular-devkit/build-webpack     0.13.10
@angular-devkit/core              7.3.10
@angular-devkit/schematics        7.3.10
@angular/cdk                      7.3.7
@angular/cli                      7.3.10
@angular/language-service         7.2.15
@angular/material                 7.3.7
@ngtools/json-schema              1.1.0
@ngtools/webpack                  7.3.10
@schematics/angular               7.3.10
@schematics/update                0.13.10
ng-packagr                        4.7.1
rxjs                              6.6.7
typescript                        3.2.4
webpack                           4.29.0
```

**Comment by stevencol** [comment]
Se modifica el formulario para que coincida con los datos de la petcion a: 

``` JavaScript
  this.formularioCertificacionesDve = this.fg.group({
      numero_documento:[{ value: "", require:true}] ,
      periodo_inicial:[{ value: "", require:true}] ,
      periodo_final: [{ value: "", require:true}] ,
      vinculaciones: [{ value: []}],
      incluir_salario: false,
    });
```

**Comment by stevencol** [comment]
Se agrego validación de periodo:
![finalev](https://github.com/user-attachments/assets/eab1d53d-95c5-4670-9942-04412287893b)

**Comment by stevencol** [comment]
Funcionalidad con rol Docente:
![finalev](https://github.com/user-attachments/assets/938b23e5-0aaf-4419-b92e-3cf6531f7d8a)

Documento Generado sin saldo: 
[docente Sin saldo.pdf](https://github.com/user-attachments/files/17879894/docente.Sin.saldo.pdf)

Documento Generado con saldo: 
[docente con saldo.pdf](https://github.com/user-attachments/files/17879895/docente.con.saldo.pdf)

**Comment by stevencol** [comment]
Funcionalidad Rol Talento Humano:
![finalev](https://github.com/user-attachments/assets/a731fbc9-5b4d-4b5a-87af-47afc7e9acf7)

**Comment by stevencol** [comment]
# Nota:

- La funcionalidad ya se encuentra implementada.
- Para las pruebas, aunque la funcionalidad ya está lista, se está retornando la lista de roles para cambiar de docente a talento humano.
- Se está firmando como documento de prueba con el ID 12, ya que el documento registrado para este caso no es aceptado por el servicio de firma.
- Para la funcionalidad del docente, se está utilizando un documento directo en el código, ya que el obtenido por el token no es válido.
- El documento está a la espera de aprobación.

**Comment by stevencol** [comment]
Se presenta en error constate con el servicio de firma electrónica
 ![image](https://github.com/user-attachments/assets/9aded71e-003f-42fc-ad89-57377b0eff64)

![image](https://github.com/user-attachments/assets/5085097e-7860-43bc-af2c-282a75ce8666)

![image](https://github.com/user-attachments/assets/be5b56b7-ff17-4a4f-86aa-2f587bcc3f75)

![image](https://github.com/user-attachments/assets/9a8d2204-4790-430e-98cb-2862a7d71539)

**Comment by JuanCamiloMartinezLopez** [comment]
@stevencol Bueno trabajo.

**Comment by stevencol** [comment]
Se realizan Ajustes sugeridas 
![image](https://github.com/user-attachments/assets/27a21122-176a-4615-a859-80af074b5c9b)
