### ISSUE TITLE
Actualizar Mockups asignación de ítems administrando la información

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/Cumplidos_y_certificaciones_documentacion#227]
Se requiere realizar la actualización de los mockups relacionados con la asignación de ítems administrando la información. 

**Sub Tareas**

- [x] Actualizar el diseño del mockup con base en los requerimientos.
- [x] Presentar el mockup al equipo
- [x] Realizar ajustes según comentarios del equipo
- [x] Presentar al equipo y cliente el mockup definitivo para el desarrollo.

**Criterios de aceptación**

- [x] Mockup aprobado por equipo y cliente.
- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico/SoSM.
- [ ] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
![Image](https://github.com/user-attachments/assets/1d816189-e48e-4346-a02f-997affef5c5a)
![Image](https://github.com/user-attachments/assets/c2d61aeb-9eeb-4c19-89b1-64a1630a897b)


Se han realizado los cambios en los mockups , agregando modal de los documentos

[Carpeta mockups](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/ErmXv75QvNlNtiJNX1kgYBwB-0z1eA6mDF-NvlD1dIz43Q?e=HDTULa)

**Comment by jcmurilloa** [comment]
Los diseños se ven muy bien @mantnicot, los revisamos al detalle en la próxima sesión para aprobar junto con @JuanCamiloMartinezLopez.

**Comment by mantnicot** [comment]
Con base a los comentarios del equipo de desarrollo se realizaron los cambios 

![Image](https://github.com/user-attachments/assets/ab9347d5-9656-4cff-8d6e-23df6acbc5ea)


![Image](https://github.com/user-attachments/assets/ecac3f73-f2bb-43f9-a76e-9f26f82af12c)


[carpeta de mockups](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EpyGBilgqVJPoxsSyK99bN0BJj3tzP-NSD8x1urAiqfSjQ?e=5OyR4q)

**Comment by jcmurilloa** [comment]
Muy buen trabajo @mantnicot!
