### ISSUE TITLE
Ajustar vista Gestión de evaluadores - Evaluadores Proveedores.

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#228]
Se requiere realizar el ajuste de la vista de gestión de evaluadores teniendo en cuenta los nuevos mockups creados #227 

**Sub Tareas**

- [x] Ajustar vista creada en #186 teniendo en cuenta los cambios del mockup.

**Criterios de aceptación**

- [x] Vista ajustada.
- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by stevencol** [comment]
Se actualiza el formulario de acuerdo con los nuevos mockups proporcionados para mejorar la interfaz de usuario y la funcionalidad.
![finalev](https://github.com/user-attachments/assets/baab9d8a-5701-4521-b35d-762b9c5299db)

**Comment by stevencol** [comment]
-Se modifica la vista a la requerida  del formulario items a  evaluar 
![image](https://github.com/user-attachments/assets/a4ddc7de-a790-46d7-82d8-9504dda745cf)

**Comment by stevencol** [comment]
- Se crea modal para la carga de items 

![image](https://github.com/user-attachments/assets/93a83e15-1a0a-4e4a-9e59-f7fb142c0da2)

**Comment by stevencol** [comment]
- Se crea función para obtener la lista de unidades en utilsService 
``` JavaScript
  async obtenerMedidas():Promise<UnidadMedida[]>{
 
    return new Promise((resolve, reject) => {
      this.administrativaAmazonService.get("/unidad").subscribe({
        next:(response:any)=>{
          const ListaUnidades:UnidadMedida[]=response;
          resolve(ListaUnidades??null)
        },error:(error)=>{
          this.popUpManager.showErrorAlert(
            'No fue posible obtener las medida de unidad.'
          );
        }
      
      })
    })
  
  }
```

**Comment by stevencol** [comment]
- Funcionalidad formulario:


![finalev](https://github.com/user-attachments/assets/a9291192-df15-4626-93d2-44b583c3e4ff)

**Comment by stevencol** [comment]
- Funcionalidad Modal cargar de items; 
![finalev](https://github.com/user-attachments/assets/33762707-6d97-4b65-810b-0670cfd7a8e7)

**Comment by stevencol** [comment]
- Modificación formulario evaluador: 
![image](https://github.com/user-attachments/assets/0b6f9532-6b0a-488c-98aa-61aeca5e2cc9)

**Comment by stevencol** [comment]
- Formulario evaluador 

![finalev](https://github.com/user-attachments/assets/14d2fcfb-ac39-42d3-9789-be2d713da15c)

**Comment by stevencol** [comment]
Se realizan ajustes solicitados: 

![image](https://github.com/user-attachments/assets/cc28a92c-446d-4442-9dc1-bcf90319f11f)

**Comment by JuanCamiloMartinezLopez** [comment]
@stevencol Buen trabajo.
