### ISSUE TITLE
Ajustes pruebas funcionales módulo de historicos y reversion.

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#229]
Se requiere realizar los ajustes necesarios teniendo en cuenta las pruebas funcionales realizadas #216, así como de los errores ya conocidos.

**Sub Tareas**

- [x] Contrastar las pruebas realizadas con los últimos cambios desplegados.
- [x] Revisar errores de ortografía y de redacción.
- [x] Revisar otros errores encontrados en las pruebas.
- [x] Registrar en otras pruebas funcionales las correcciones.

**Criterios de aceptación**

- [ ] Nuevas pruebas funcionales.
- [ ] Errores corregidos. 
- [ ] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by stevencol** [comment]
Se inicia con la actividad, inicialmente verificando los errores y comprobar si estos ya fueron solucionados

**Comment by stevencol** [comment]
Mientras se corrige el problema de acceso, se sigue con corregir los Errores de Ortografía detectados:
- El siguiente error de ortografía se detecta en el mid, y se corrige 
![image](https://github.com/user-attachments/assets/d15b958d-3d23-43ba-b2b5-112baf556626)

Se corrige 
![image](https://github.com/user-attachments/assets/e9431fc5-6489-4de0-a829-c18d3a551c43)

**Comment by stevencol** [comment]
Se detectó un error que generaba 4 páginas en blanco. Este error ocurre cuando existe una lista de documentos muy grande, lo que provoca que los textos se desplacen hacia abajo. Dado que la posición de los textos se determina por coordenadas, cuando el espacio disponible en la página se agota, el sistema intenta ajustar los textos a una nueva página. Al no haber suficiente espacio, se generan páginas en blanco adicionales. 

Se corrige y se prueba funcionalidad:

![finalev](https://github.com/user-attachments/assets/58933582-f929-4da5-a7ef-69384c814876)

**Comment by stevencol** [comment]
Con el fin de mantener una ordenación adecuada, se utiliza la rama para el cliente ussue#228-merge, la cual se usó en el issue #228. Los cambios en el medio se cerraron correctamente en develop

**Comment by stevencol** [comment]
Se vuelven a realizar las pruebas y los errores  detectados  ya no se están generando. [Documento](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EZFHMqw7ZpVFq3QlBvDHOWYBDWc4d6pZ9wqdaFk_tk9Omg?e=Ra7A7R)

**Comment by JuanCamiloMartinezLopez** [comment]
@stevencol Buen trabajo.
