### ISSUE TITLE
Creación de función para la consulta de vinculaciones de DVE

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#230]
Se requiere realizar la creación de un servicio para consulta de vinculaciones de DVE.

**Sub Tareas**

- [x] Hacer uso de argo (contrato_general), así como de resoluciones_crud (revisar inventario de apis) para vinculaciones de 2023 en adelante.
- [x] Revisar la bd udistrital_administrativa, esquema resoluciones_old para la consulta de vinculaciones anteriores a 2023, y proponer la creación de una consulta para obtener la información de vinculaciones antiguas.
- [x] El servicio debe responder la lista de vinculaciones con (número de contrato, vigencia, periodo, tipo de vinculación, etc).

**Criterios de aceptación**

- [x] Servicio creado.
- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
## Propuesta servicio

Se elabora la propuesta de servicio para retornar la información necesaria para las vinculaciones, esta consulta se realizó usando la base de datos `udistrital_administrativa.resoluciones` y se debe proporcionar el número de cédula del docente de vinculación especial. 

```sql
SELECT vd.numero_contrato, vd.vigencia, re.periodo, vd.numero_horas_semanales, vd.numero_semanas,de.descripcion , vd.proyecto_curricular_id  
FROM resoluciones.vinculacion_docente vd 
join resoluciones.resolucion_vinculacion_docente rvd on vd.resolucion_vinculacion_docente_id = rvd.id
join resoluciones.resolucion re on rvd.id = re.id
join resoluciones.dedicacion de on vd.dedicacion_id = de.id  
where vd.persona_id = ? and vd.numero_contrato is not null;
```

![Image](https://github.com/user-attachments/assets/fcb8dee6-f641-4e26-8ced-b3c9e5441ff4)


- Se retorna el campo `proyecto_curricular_id` puesto que con este dato se puede hacer la siguiente petición para obtener el proyecto curricular.

```sql
SELECT *
FROM oikos.dependencia
WHERE id = ?;
```

![Image](https://github.com/user-attachments/assets/284c3491-830d-4e23-a1d3-dc3839ef36ce)

**Comment by faidercamilo26** [comment]
## Vinculaciones 2023 en adelante

Se crea el servicio para retornar las vinculaciones de un docente. Se tenia entendido que la Api de resoluciones solo retornaba vinculaciones de 2023 para adelante, sin embargo, en la construcción del servicio, en las respuestas se puede notar la Api si esta retornando vinculaciones del 2023 para abajo.

![Image](https://github.com/user-attachments/assets/fcba4592-5a10-4246-a099-e25ec0f836d1)

### Inconvenientes

Se puede notar en el ejemplo del gif que se esta retornando la siguiente vinculación que tiene una duración de 40 semanas y 42 horas semanales. Pero un semestre es de máximo 6 meses, lo cual equivale a mas o menos 25 o 26 semanas.

![Image](https://github.com/user-attachments/assets/a5c91ef3-d952-4b51-a3c7-0789c3e320d3)

**Comment by faidercamilo26** [comment]
## Corrección

Se corrige la consulta SQL del servicio para que se retorne la fecha inicio y la fecha fin del contrato de un docente de vinculación especial.

```sql
SELECT vd.numero_contrato, vd.vigencia, vd.fecha_inicio,vd.fecha_inicio + (vd.numero_semanas || ' weeks')::interval as fecha_fin ,re.periodo, vd.numero_horas_semanales, vd.numero_semanas,de.descripcion, vd.proyecto_curricular_id, vd.dedicacion_id  
FROM resoluciones.vinculacion_docente vd 
join resoluciones.resolucion_vinculacion_docente rvd on vd.resolucion_vinculacion_docente_id = rvd.id
join resoluciones.resolucion re on rvd.id = re.id
join resoluciones.dedicacion de on vd.dedicacion_id = de.id
where vd.persona_id = 80426185 and vd.numero_contrato is not null;
```

![Image](https://github.com/user-attachments/assets/9f3f0368-184d-49d4-b891-6365d5e28ce2)

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 Buen trabajo.
