### ISSUE TITLE
Creación api crud base para el módulo de evaluación cumplidos proveedores

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#231]
Se requiere realizar la creación del api crud base para el módulo de evaluacion cumplidos proveedores en golang(beego) partiendo del [modelo](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EtxrSa7d80xMo-m5Sz9ftekBUkcwTfTPo9Sc9AwQEyrRYw?e=Yj6cbd).

**Sub Tareas**

- [x] Clonar el repositorio [evaluacion_cumplido_prov_crud](https://github.com/udistrital/evaluacion_cumplido_prov_crud)
- [x] Creación API REST siguiendo los [lineamientos](https://github.com/udistrital/lineamientos_oas?tab=readme-ov-file#generaci%C3%B3n-api-crud).
- [x] Modificación endpoint de eliminación para realizar la eliminación lógica.

**Criterios de aceptación**

- [x] Issue documentada.
- [x] Proyecto base creado y commit realizado.

**Requerimientos**

- Completar la Issue #214.
- [Aprobación del modelo de datos](https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=62102).

**Especificaciones técnicas**
1. Repositorio de este nuevo microservicio [evaluacion_cumplido_prov_crud](https://github.com/udistrital/evaluacion_cumplido_prov_crud)

**Lineamientos Generales**
Lineamientos que se deben cumplir en cualquier desarrollo.
1. [Lineamiento y Metodología para Branches](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/nombre_branch.md)
2. [Etiquetas en comentarios de Commits](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/etiqueta_commits.md)
3. Seguir los lineamientos para la documentación del README [Contenido README](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/contenido_readme.md)

**Lineamientos Microservicios**
1. Definición de endpoints para APIs REST [Hoja resumen de buenas prácticas](https://udistritaleduco-my.sharepoint.com/:p:/g/personal/computo_udistrital_edu_co/EYwQbkAKVCJCqrmJ7NgnjQ4B8WSd81vxGVx-hqi0WBAcfQ?e=lJZdx8) y [Aclaración y ejemplos de nombres adecuados para endpoints](https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/lineamientos-endpoints.md)
2. Guiarse en la construcción del microservicio basado en los lineamientos de [APIS Beego](https://github.com/udistrital/lineamientos_oas?tab=readme-ov-file#5-apis-beego-mortar_board) si se usa Golang
3. Guiarse de los lineamientos de [ambientes dockerizados](https://github.com/udistrital/lineamientos_oas/blob/master/ambientes_dockerizados/dockerizacion.md)
4. [(health check) validación de estado en APIs](https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/endpoint_validacions.md#health-check-validaci%C3%B3n-de-estado-en-apis)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
## :triangular_flag_on_post: **Api crud evaluaciones proveedores**  :triangular_flag_on_post:

- Se crea el api crud base para la evaluación de proveedores.
- Se realizan las configuraciones iniciales, teniendo en cuenta los lineamientos en el repositorio de la oati.
- Se aplica la configuración de múltiples filtros.
- Se aplica la configuración de eliminación lógica, para que al realizar un `delete` solo se cambie el campo `activo` a `false`.
- Se corre el proyecto para generar el swwager.
- Se agrega y configura el documento `gitignore` para no subir archivos de configuración y el archivo `.env`.

![Image](https://github.com/user-attachments/assets/e16c699b-8a5c-48a7-b9e7-57e37003f9d5)
![Image](https://github.com/user-attachments/assets/08ec3e50-ceff-423d-94a5-b67aa676f660)

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 Buen trabajo.
