### ISSUE TITLE
Implementar servicios - Certificaciones DVE

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#233]
Se requiere realizar la implementación de los servicios para certificados DVE

**Sub Tareas**

- [x] Servicio administrativa_pruebas/vinculacion_docente/{documento_docente} para la consulta de resoluciones antiguo

**Criterios de aceptación**

- [x] Servicios implementados.
- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
## Avances

Se implementa el servicio de vinculación docente para obtener las vinculaciones de un docente anteriores al año 2023, de esta manera se completa el servicio de retornar las vinculaciones de un docente, solo queda faltando implementar el servicio de la carga académica, pero este servicio está en espera de reestructuración así que por el momento no se puede avanzar más con esta issue.

![Image](https://github.com/user-attachments/assets/e538c8c5-10b3-43d6-8e86-61b048f93ddb)

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 buen trabajo.
