### ISSUE TITLE
Probar flujo cumplidos proveedores.

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#235]
Se requiere realizar un video/evidencia para poder ver reflejado el flujo del sistema

**Sub Tareas**

- [ ] 

**Criterios de aceptación**

- [ ] 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se adjunta el video del flujo completo de cumplidos

[flujo cumplido videos](https://udistritaleduco-my.sharepoint.com/:v:/g/personal/computo_udistrital_edu_co/Ee9Dh8NORc5IuWSa-Tz5MFoBq1gzIvednm32lcDgZKjXMg?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=418h2Z)

**Comment by jcmurilloa** [comment]
Muy buen trabajo @mantnicot, nos surgieron un par de dudas sobre una doble aprobación del cumplido antes de llegar la ordenación, espero en el daily nos las puedas aclarar.
