### ISSUE TITLE
Ajustar consulta sql servicio vinculación docente.

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#236]
Se requiere realizar el ajuste al sql del servicio propuesto en #230.

**Sub Tareas**

- [x] Ajustar el servicio para tener en cuenta las fechas de inicio y fin de la vinculación.
- [x] Tener en cuenta el caso de fecha inicio faltante.

**Criterios de aceptación**

- [x] Issue documentada.
- [x] Servicio ajustado.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
## Avance

Se ajusta el servicio sql para retornar siempre las fechas, puesto que en ocasiones la `fecha_inicio` de la tabla `vinculaciones_docente` se retorna en null, por lo tanto, el cálculo de `fecha_fin` tambien se retorna en null, se ajusta el servicio para que si `fecha_inicio` es igual a null se tome la fecha inicio de la tabla `resoluciones` y con esta fecha se calcule la `fecha_fin`.

```sql

SELECT 
    vd.numero_contrato, 
    vd.vigencia, 
    COALESCE(vd.fecha_inicio, re.fecha_creacion) AS fecha_inicio, 
    COALESCE(vd.fecha_inicio, re.fecha_creacion) + (vd.numero_semanas || ' weeks')::interval AS fecha_fin,
    re.periodo, 
    vd.numero_horas_semanales, 
    vd.numero_semanas, 
    de.descripcion, 
    vd.proyecto_curricular_id, 
    vd.dedicacion_id  
FROM resoluciones.vinculacion_docente vd 
JOIN resoluciones.resolucion_vinculacion_docente rvd ON vd.resolucion_vinculacion_docente_id = rvd.id
JOIN resoluciones.resolucion re ON rvd.id = re.id
JOIN resoluciones.dedicacion de ON vd.dedicacion_id = de.id
WHERE vd.persona_id = 79362769 
  AND vd.numero_contrato IS NOT NULL;

```

**Comment by faidercamilo26** [comment]
## Inconveniente

Se puede notar que en las bases de datos de pruebas algunos datos en la tabla de `vinculaciones_docente` y `resolucion` tienen el numero de semanas distintas, por el momento se estan sumando las semanas de la tabla  `vinculaciones_docente`, sin embargo, se espera para probar en la base de datos de producción, para verificar si esto solo ocurre en pruebas.


![Image](https://github.com/user-attachments/assets/cdf78506-5c2a-45b2-a918-c723fff5dfcd)

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 Buen trabajo.
