### ISSUE TITLE
Pruebas funcionales - Certificaciones DVE

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#237]
Se requiere realizar el pruebas funcionales del módulo de certificados DVE

**Sub Tareas**

- [x] Realizar pruebas funcionales con las [HU](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EdGjHQWRybZBr6CyeGAA4SQBpHR47ZcodIgcYxalf03Frg?e=kR7Fks) como base.
- [x] Realizar pruebas en local.
- [x] Utilizar el formato de pruebas funcionales.

**Criterios de aceptación**

- [ ] Pruebas funcionales realizadas.
- [ ] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by stevencol** [comment]
Se inicia creando las pruebas según documento de guía:

Se relizan pruebas para el rol DOCENTE:

[Pruebas.Funcionales-CertificacionesDVE_DOCENTE.xlsx](https://github.com/user-attachments/files/17882023/Pruebas.Funcionales-CertificacionesDVE_DOCENTE.xlsx)

TALENTO_HUMANO

[Pruebas.Funcionales-CertificacionesDVE_Talento-Humano.xlsx](https://github.com/user-attachments/files/17882024/Pruebas.Funcionales-CertificacionesDVE_Talento-Humano.xlsx)

Se cargan al drive:

[OneDrive](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EnfxcC_B9vFCpARoXHlceNEBfOwZEF-2fMPeiI48rlAuhQ?e=GzRg8r)

**Comment by JuanCamiloMartinezLopez** [comment]
@stevencol Buen trabajo.
