### ISSUE TITLE
Ajustar el documento de autorización de giro

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#238]
Se requiere realizar el ajuste del documento de autorización de giro, puesto que la firma se está generando en un página vacía.

**Sub Tareas**

- [x] Agregar una página con la cabecera y pie de página para la firma electrónica.
- [x] Revisar el formato para agregar el listado a la tabla de los documentos subidos bajo el tipo "otros".
- [x] Revisar la correcta generación del documento antes y después de la firma electrónica.

**Criterios de aceptación**

- [x] Documento ajustado.
- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
# :triangular_flag_on_post: **Ajustes autorización de giro**  :triangular_flag_on_post:

## Antes de los cambios

Realizando las pruebas se puede envidenciar que actualmente el documento no respeta el espacio del footer y por eso se crean varias hojas y se sobreescribe texto encima del footer.

### Ejemplo de la manera en que se estaba generando la autorizacion de giro 

#### Pagina 1

En esta pagina se puede notar que en el footer se esta sobreescribiendo la linea horizontal de la firma

![Image](https://github.com/user-attachments/assets/c8a6e4dd-9df4-4207-bbfa-78bc0c28a141)

#### Pagina 2

Se genera una pagina solo con la palabra "Firma"

![Image](https://github.com/user-attachments/assets/2136c8f2-b787-4e0d-9495-ee6ed9ac59c0)

#### Pagina 3

Se genera una pagina solo con la palabra ".Nota"

![Image](https://github.com/user-attachments/assets/9ce92527-7beb-4894-a26c-c130b588a0c3)

#### Pagina 4

Se genera una cuarta pagina con la nota y la firma

![Image](https://github.com/user-attachments/assets/e4cf8caa-3cdf-4ebd-9ea0-9077d54e44fb)


## Cambios realizados

- Se implementan validaciones para verificar que si un texto o parte de la tabla no caben en la hoja se cree una nueva hoja y se agreguen en la nueva pagina.
- Se edita la funcion `GenerarPdfAutorizacionGiro()` que es la encargada de crear el pdf de autorizacion de giro, para que reciva una lista llamada `otros_documentos` que es una lista de strings con el nombre de los archivos que pertenecen a la categoria de `otros`.
- Se edita la funcion `GenerarPdfAutorizacionGiro()` para renderizar los documentos de categoria `otros` para que se pinten despues de la celda `OTROS DOCUMENTOS (DETALLAR)` en la tabla.

![Image](https://github.com/user-attachments/assets/1bc35544-6501-4f0a-8e66-0206f87753aa)

- Se calcua que la firma ocupa verticalmente aproximadamente `56 px` por lo tanto se genera una verificacion, para que si, en la ultima pagina no queda minimo este espacio se genere una nueva pagina para incluir la firma en esa nueva pagina.

![Image](https://github.com/user-attachments/assets/ed62e27a-82de-486e-8967-5b2b9422888c)

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 Buen trabajo.
