### ISSUE TITLE
Investigación y desarrollo de la funcionalidad para carga de ítems a partir de un excel

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#239]
Se requiere realizar la investigación y desarrollo de la funcionalidad que permita cargar un excel con un formato fijo  y procesar los ítems para guardarlos. 

**Sub Tareas**

- [x] Revisar tecnologías y herramientas necesarias para realizar el proceso.
- [x] Revisar las opciones en cual implementar esta función (mid o cliente).
- [x]  Realizar un implementación a modo de prueba.
- [ ] Tomar como ejemplo lo implementado en [arka II](https://github.com/udistrital/arka_mid/blob/develop/helpers/actaRecibido/DecodeXlsx2Json.go)

**Criterios de aceptación**

- [ ] Propuesta de funcionalidad.
- [ ] Propuesta implementada.
- [ ] issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by stevencol** [comment]
Se inicia con actividad analizando  
 [codigo](https://github.com/udistrital/arka_mid/blob/develop/helpers/actaRecibido/DecodeXlsx2Json.go)

**Comment by stevencol** [comment]
Se lee también   [excelize](https://github.com/qax-os/excelize), parece la opción mas fácil para la implementación

**Comment by stevencol** [comment]
se propone excelize , por su aparente facilidad de uso se realizan códigos de prueba para imprimir datos de un excel :

![image](https://github.com/user-attachments/assets/b6173b7a-387c-4b72-a3ea-79c45214be7f)

codigo:

``` JavaScript
func (c *TestController) UploadExcel() {

	file, _, err := c.GetFile("file")
	if err != nil {
		c.Ctx.ResponseWriter.WriteHeader(400)
		c.Ctx.WriteString("Error al obtener el archivo")

		return
	}
	defer file.Close()

	f, err := excelize.OpenReader(file)

	if err != nil {
		fmt.Println("Error al abrir el archivo")
		return
	}

	rows, err := f.GetRows("Hoja1")
	if err != nil {
		fmt.Print("Error al obtenr hoja")
		fmt.Print(err)
		return
	}

	for _, row := range rows {

		for _, col := range row {
			fmt.Print(col, "\t")

		}
	}

}
```

excel:
![image](https://github.com/user-attachments/assets/d7294990-e3a9-4d78-8f80-26beb929a0d7)


Se imprimen celda: 
![image](https://github.com/user-attachments/assets/4186563f-c36e-4812-9f44-9d47ae98dcb6)

Codigo 
``` JavaScript
for i := 1; i < 10; i++ {
		fmt.Println("A" + strconv.Itoa(i))
		cell, err := f.GetCellValue("Hoja1", "A"+strconv.Itoa(i))
		if err != nil {
			fmt.Println("Errro al imprimir  celdas ")
			return
		}
		fmt.Println(cell)
	}


```

**Comment by stevencol** [comment]
Codigo para detener lectura si el campo es vacio:
![image](https://github.com/user-attachments/assets/741ba2d0-1ee0-4120-85f0-ecbe626025fc)

**Comment by stevencol** [comment]
| **Característica**               | **excelize**                                                                 | **tealeg/xlsx**                                              |
|----------------------------------|-----------------------------------------------------------------------------|-------------------------------------------------------------|
| **Formatos soportados**          | `.xlsx`, `.xlsm`, `.ods` (experimental)                                      | `.xlsx`                                                      |
| **Soporte para `.xls`**          | No soportado                                                                | No soportado                                                 |
| **Soporte para `.xlsm` (Macros)**| Sí, puede leer y escribir, pero no puede modificar el código VBA            | No soportado                                                 |
| **Soporte para `.ods`**          | Soporte experimental                                                       | No soportado                                                 |

**Comment by JuanCamiloMartinezLopez** [comment]
@stevencol Buen trabajo..
