### ISSUE TITLE
Definir templates para notificaciones del módulo de evaluación de cumplidos proveedores

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/Cumplidos_y_certificaciones_documentacion#241]
Se requiere realizar la definición de los templates que se van a usar para el envío de notificaciones del módulo de evaluación del sistema cumplidos proveedores.

**Sub Tareas**

- [x] Definir templates a realizar.
- [x] Crear los templates que se van a usar en las notificaciones.
- [x] Documentar los templates creados indicando en que parte del flujo se usarían.

**Criterios de aceptación**

- [x] Templates definidos.
- [x] Templates creados.
- [x] Documentación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by mantnicot** [comment]
Se ha creado un documento de templates para evaluación proveedores 
[documento de templates](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EQxlppJj3nJOhDVYkhuRMjYB3xSl1fJQFKp9y5cuPvW-9A?e=bpGq0N)

**Comment by jcmurilloa** [comment]
De acuerdo a lo revisado en el Daily, se aprueban las tenplates. Buen trabajo @mantnicot
