### ISSUE TITLE
Gestionar la elaboración del manual de usuario para certificaciones DVE

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/Cumplidos_y_certificaciones_documentacion#242]
Se requiere realizar la actualización del manual de usuario para certificaciones DVE 

**Sub Tareas**

- [x] Generar contacto con responsable de Manuales en funcionamiento.
- [x] Levantar requerimientos de elaboración.
- [x] Generar el requerimiento de elaboración de Manuales
- [x] Revisión de manuales generados

**Criterios de aceptación**

- [x] Solicitud de creación o actualización de Manuales con responsable
- [x] Manuales e instructivos actualizados

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se ha agendado la reunión pra el día 29 - 11 - 2024 a las 10:00 am

[enlace reunión](https://teams.microsoft.com/l/meetup-join/19%3ameeting_N2Q2ODg2YzctZDQxMi00NDcxLThjM2QtYjM5YTdkMDZkNzZh%40thread.v2/0?context=%7b%22Tid%22%3a%22d51388ef-6ab0-4363-9f94-d56644a45970%22%2c%22Oid%22%3a%221dd8bdce-0185-41b4-8caa-01da7e5506b2%22%7d)

**Comment by mantnicot** [comment]
Se ha gestionado y revisado los manuales de los usuarios
[carpeta de manuales](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EqVg05oIFRlPioJPGsH8zGsBhDHyFaLGa-WAcmr07YkqxA?e=1nfiiG)

**Comment by jcmurilloa** [comment]
Con el VoBo de @JuanCamiloMartinezLopez daremos por cerrada la issue.

**Comment by JuanCamiloMartinezLopez** [comment]
Se revisa los manuales y se encuentran bien.
