### ISSUE TITLE
Creación de servicio para cargar items de forma masiva

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#243]
Se requiere realizar el servicio en el mid de evalucion_cumplido_prov_mid  para cargar desde un excel los ítems

**Sub Tareas**

- [x] Revisar el formato propuesto #248 
- [x] implementar la librería de la #239 para cargar los items desde le formato indicado y validar cuales cumplen con los limitantes del modelo de base de datos para guardarlos, los que no retornarlos en el servicio.
- [x] Crear un endpoint para realizar un insert masivo de ítems en evalucion_cumplido_prov_crud.

**Criterios de aceptación**

- [ ] Servicio funcionando.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by stevencol** [comment]
Se inicia con actividad , inicialmente  se crea helper  para la lectura del del excel, se va estructurando la manera de que se va a forma el cuerpo 

metodo en el helper para la lectura de archivo:

``` JavaScript
func CargaDataExcel(excel multipart.File) {

	f, err := excelize.OpenReader(excel)

	if err != nil {
		fmt.Errorf("Error al abrir el archivo: %v", err)
	}

	var items []models.ItemEvaluacion

	for i := 2; ; i++ {

		nombre := obtenerCelda(f, 65, i)
		if nombre == "" {
			break
		}

		item := models.ItemEvaluacion{
			Nombre:         obtenerCelda(f, 65, i),
			Cantidad:       parseFloat(obtenerCelda(f, 66, i), 64),
			ValorInitario:  parseFloat(obtenerCelda(f, 67, i), 64),
			Iva:            parseFloat(obtenerCelda(f, 68, i), 64),
			Unidad:         1,
			TipoNecessidad: 1,
			FichaTecnica:   obtenerCelda(f, 71, i),
		}
		items = append(items, item)
		fmt.Printf("%+v\n", item)
		fmt.Printf("%+v\n", items)
		// return nil
	}
}
```

**Comment by stevencol** [comment]
Archivo de prueba: 

![image](https://github.com/user-attachments/assets/cbb12fa3-2b31-4fec-b25f-ff29fff6e7a7)

Lectura desde consola con objeto ya creado y lista de items: 
![image](https://github.com/user-attachments/assets/af58c7a5-34f2-4e58-bc3a-327e5a627bfd)

**Comment by stevencol** [comment]
Se prueba funcionalidad de carga masiva: 

Excel: 
![image](https://github.com/user-attachments/assets/795b730a-091c-429c-ae0e-9a3bb62fd11d)

bd depues de cargar:

![image](https://github.com/user-attachments/assets/40983c3e-6af1-4587-9e68-aafb557a9f74)

Proceso:

![finalev](https://github.com/user-attachments/assets/bd013c5e-48e3-4ae1-9c35-48e3d1e10be5)

Respuesta: 

``` JavaScript
{
    "Success": true,
    "Status": 200,
    "Message": {
        "itemsNoAgregados": [
            {
                "Id": 0,
                "EvaluacionId": {
                    "Id": 1,
                    "ContratoSuscritoId": 0,
                    "VigenciaContrato": 0,
                    "Activo": false,
                    "FechaCreacion": "0001-01-01T00:00:00Z",
                    "FechaModificacion": "0001-01-01T00:00:00Z"
                },
                "Identificador": "2131",
                "Nombre": "Jabon de mesa2",
                "ValorInitario": 1,
                "Iva": 1.44,
                "FichaTecnica": "1132",
                "Unidad": 0,
                "Cantidad": 1,
                "TipoNecessidad": 0,
                "Activo": false,
                "FechaCreacion": "0001-01-01T00:00:00Z",
                "FechaModificacion": "0001-01-01T00:00:00Z"
            }
        ]
    },
    "Data": {
        "Message": "Items insertados exitosamente, se insenrtaron 2 items",
        "Status": "201",
        "Success": true
    }
}
```

**Comment by JuanCamiloMartinezLopez** [comment]
@stevencol Buen trabajo.
