### ISSUE TITLE
Creación de funciona para consulta de evaluadores( info de informacion_persona_natural/agora)

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#244]
Se requiere realizar la propuesta de un consulta sql para consultar personas por documento en informacion_persona_natural

**Sub Tareas**

- [x] implementar en la consulta un [LIKE](https://www.w3schools.com/postgresql/postgresql_like.php) para buscar coincidencias.
- [x] retornar documento y nombre de la persona.

**Criterios de aceptación**

- [x] Propuesta de consulta.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
## :triangular_flag_on_post: **Propuesta servicio para consultar información persona natural**  :triangular_flag_on_post:

Se crea el script SQL para que al ingresar mínimo 3 dígitos del número de documento de una persona se retornen las coincidencias de documento y el nombre de la persona.

```sql
select num_documento_persona, primer_nombre || ' ' || segundo_nombre ||' '|| primer_apellido|| ' ' || segundo_apellido as nombre
FROM agora.informacion_persona_natural
where num_documento_persona like '%num_documento%'

```
![Image](https://github.com/user-attachments/assets/abe3cb69-103a-4518-b065-7283470fc167)

**Comment by JuanCamiloMartinezLopez** [comment]
Se crea el servicio de jbpm 
http://busservicios.intranetoas.udistrital.edu.co:8282/wso2eiserver/services/administrativa_pruebas/personas_documento/{{documento}}

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 Buen trabajo.
