### ISSUE TITLE
Crear funciona para registrar evaluaciones

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#245]
Se requiere realizar la función para guardar los resultados de un evaluador.

**Sub Tareas**

- [x] Implementar una funciona para guardar la información de los resultados (json)

**Criterios de aceptación**

- [x] función creada.
- [x] issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
## :triangular_flag_on_post: **Guardar Resultados individuales**  :triangular_flag_on_post:

## Avances 

Se construye la totalidad de la función `GuardarResultadoEvaluacion()` cuya función es registrar un resultado de evaluación a un proveedor, los datos se le deben enviar con el siguiente modelo: 

```go
type BodyResultadoEvaluacion struct {
	AsignacionEvaluadorId int       `json:"AsignacionEvaluadorId"`
	ClasificacionId       int       `json:"ClasificacionId"`
	ResultadoEvaluacion   Resultado `json:"ResultadoEvaluacion"`
	Observaciones         string    `json:"Observaciones"`
}

type Resultado struct {
	ResultadosIndividuales []struct {
		Categoria string `json:"Categoria"`
		Titulo    string `json:"Titulo"`
		Respuesta struct {
			Pregunta      string `json:"Pregunta"`
			Cumplimiento  bool   `json:"Cumplimiento"`
			ValorAsignado int    `json:"ValorAsignado"`
		} `json:"Respuesta"`
	} `json:"ResultadosIndividuales"`
}
```

La función procesa esta datos y los almacena en la base de datos para persistir los datos. Por el momento esta función solo retorna un mensaje de confirmación indicando que se guardó correctamente el registro y las respuestas y puntajes de cada pregunta.

## Inconvenientes

- Al guardar un registros aunque en el api crud el campo `Activo` tiene un default `true` siempre se registra en false, a menos, que se le pase explícitamente la propiedad en `true`. Aunque este es más problema del api crud se deja registrado en la issue.

## Pruebas del funcionamiento

![Image](https://github.com/user-attachments/assets/b1691379-2684-428c-8003-5976e15b8365)

**Comment by faidercamilo26** [comment]
## Correcciones

Se edita el modelo de respuesta para que la función no retorne todas las respuesta de las preguntas, ahora solo responde con el mensaje `Registro guardado con exito` y un status `201`. En caso de error responde con un status 404 y el mensaje del error.

```json
{
    "Success": true,
    "Status": 201,
    "Message": "Recurso creado con éxito",
    "Data": "Registro guardado con exito"
}
```

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 Buen trabajo.
