### ISSUE TITLE
Implementar cambios y servicios desarrollados en el cliente.

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#246]
Se requiere realizar la implementación de las consultas a los servicios desarrollados y cambios a las vistas.

**Sub Tareas**

- [x] Implementar los servicios:

- #243 
- #244 
- #248

- [x] Ajustes gráficos
- Cambiar "tipo necesidad" por "tipo" en la vista de gestión evaluación.
- Agregar botón para guardar la info de evaluadores en la vista de gestión evaluación.

- [ ] Implementar la consulta de contratos-supervisor del revision_cumplido_prov_mid para listar los contratos por dependencias en la vista de listar evaluaciones.

**Criterios de aceptación**

- [ ] Servicios y cambios realizados.
- [ ] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by stevencol** [comment]
Se inicia con actividad, cambiando  "tipo necesidad" por "tipo" en la vista de gestión evaluación.

**Comment by stevencol** [comment]
Se cambia el texto y adicionalmente, se cambia el input por una listade el tipo de necesidad 
![Animation](https://github.com/user-attachments/assets/f3ace6fb-5e15-4206-a20f-b53afd1bb47e)

**Comment by stevencol** [comment]
Se crea método que implementa búsqueda  de personas  de la ussue [#244 ](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/issues/244), pero genera erro de cors al usar, se creA con la validación para que sea mayor a 3 dígitos para que la consulta se realiza
![Animation](https://github.com/user-attachments/assets/3e7549cc-e2e4-447f-9c8c-1f8eb1d911d0)

error :  

```

Access to fetch at 'https://autenticacion.portaloas.udistrital.edu.co/apioas/administrativa_jbpm/v2/personas_documento/1111' from origin 'http://localhost:4200' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```


![image](https://github.com/user-attachments/assets/2f1bdf4d-ecd0-4f04-91ea-6d30db409d17)



Headers:
![image](https://github.com/user-attachments/assets/f678248c-bc6d-40c8-b6fe-661e43f7d24e)


![image](https://github.com/user-attachments/assets/e73957c2-c03b-47d3-b318-1a9fb1a5e7f8)

**Comment by stevencol** [comment]
El momento de hacer la petición de carga desde el formulario genera error: 


Header:
![image](https://github.com/user-attachments/assets/0b86941c-d24e-4565-aff3-98d45107ca6d)


Payload:
![image](https://github.com/user-attachments/assets/e690779e-90b3-4761-9b46-29e93997e354)

Response:
![image](https://github.com/user-attachments/assets/2743c2d2-8470-4587-a576-c3e667fd32f3)

Flujo: 

![Animation](https://github.com/user-attachments/assets/f8e14d99-d69d-4e91-8bed-46741c0ac4ea)

Después de investigar, se detecta la  causa del error, el cual les generado por la cabecera enviada desde el requestmanager el cual envía la cabezara 'Accept': 'application/json', y  'Authorization': `Bearer ${acces_token}`, , en el request manager hay un método para la carga de archivos el cual envía la cabezara adecuada :;                 'Content-Type': 'multipart/form-data',
 pero no envia el header de Authorization, pro lo cual se crea una version modificada desde el service: 

``` JavaScript
  post_file(endpoint: any, element: any) {
    
    const postOptions = {
      ...this.httpOptions,
       headers: new HttpHeaders({
            'Content-Type': 'multipart/form-data',
        })
   
    }
    return this.http.post<any>(`${environment.EVALUACION_CUMPLIDOS_PROVEEDORES_MID}${endpoint}`, element, postOptions).pipe(
        catchError(this.errManager.handleError),
    );
}
```

El cual se pone a prueba

**Comment by stevencol** [comment]
se modifica servico  y funciona correctamente
 ``` JavaScript
postCargaExcel(endpoint: any, element: any) {
    if (this.acces_token != '') {
      const postOptions = {
        headers: new HttpHeaders({
          'Content-Type': 'multipart/form-data',
          Authorization: `Bearer ${this.acces_token}`,
        }),
      };

      return this.http
        .post<any>(
          `${environment.EVALUACION_CUMPLIDOS_PROVEEDORES_MID}${endpoint}`,
          element,
          postOptions
        )
        .pipe(catchError(this.errManager.handleError));
    }
    return this.http
      .post<any>(
        `${environment.EVALUACION_CUMPLIDOS_PROVEEDORES_MID}${endpoint}`,
        element
      )
      .pipe(catchError(this.errManager.handleError));
  }
```

**Comment by stevencol** [comment]
![Animation](https://github.com/user-attachments/assets/04168b35-acd9-4162-9394-4ed2a860bcde)

**Comment by stevencol** [comment]
Al intentar implementar la consulta de contratos-supervisor del revision_cumplido_prov_mi, no se encuentra la vista, por lo que se procede a buscar la rama de su elaboración y se encuentra en: #187. Se intenta unir con la rama actual de la issue, pero genera inconvenientes, por lo que se copia directamente el componente y se pega en la rama actual, la búsqueda se implementa de manera temporal ya que no permite búsqueda por  contrato, ya que se hace desde el mid y no permite querys

**Comment by stevencol** [comment]
Para la consulta se crea el método : 

``` JavaScript

  consultarContratos():Promise<void> {
    return new Promise((resolve, reject) => {
      
      this.cumplidosProveedoresMidService.get('/supervisor/contratos-supervisor/'+this.documentoSupervisor).subscribe({
        next: (res: any) => {
          if(res.Data && res.Data.contratos.length > 0){
            this.dataSource = res.Data.contratos.map((item: any) => {
              return {
                nombreProveedor: item.NombreProveedor,
                dependencia: item.NombreDependencia,
                tipoContrato: item.TipoContrato,
                contrato: item.NumeroContratoSuscrito,
                vigencia: item.Vigencia,
                acciones: [
                  {
                    icon: 'edit',
                    actionName: 'edit',
                    isActive: true,
                  },
                  {
                    icon: 'visibility',
                    actionName: 'visibility',
                    isActive: true,
                  },
                  {
                    icon: 'accessibility',
                    actionName: 'accessibility',
                    isActive: true,
                  },
                ],
              }
              
            },)
            
            
          }
          resolve()
        },error: (err: any) => {
          this.popUpManager.showErrorAlert("Error al consultar los contratos")
        }
        
      })
    });


  }

```

**Comment by stevencol** [comment]
Funcionamiento:
![Animation](https://github.com/user-attachments/assets/b84b8fd8-920d-4e16-bc75-45b379c9f9da)

**Comment by stevencol** [comment]
Funcionamiento completo cada de ítems: 

![Animation](https://github.com/user-attachments/assets/93284a1b-d2ba-4736-9397-64b6f64af5b5)

**Comment by stevencol** [comment]
## Nota por el momento no se puede obtener el link de la evaluación, por lo que se la consulta se hace con el id 1:

**Comment by JuanCamiloMartinezLopez** [comment]
@stevencol Buen trabajo.
