### ISSUE TITLE
Investigar la generación de pdf con excelize y gofpdf

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#247]
Se requiere revisar el uso de excelize y gofpdf para generar pdf.

**Sub Tareas**

- [x] Revisar la implementación en [sga](https://github.com/udistrital/sga_trabajo_docente_mid/blob/develop/services/reportes.go) 
- [x] realizar un ejemplo sencillo de su funcionamiento.

**Criterios de aceptación**

- [x] Issue comentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
## :triangular_flag_on_post: **Excelize**  :triangular_flag_on_post:

- Se inicia revisando rápidamente la manera en que se usa esta librería en el proyecto de SGA. Solo fue un primer acercamiento rápido para al leer la documentación ir contrastando con la manera que esta en el código. 
- Se revisa la documentación de go acerca de esta librería en el siguiente [link](https://pkg.go.dev/github.com/xuri/excelize/v2#readme-introduction)

![Image](https://github.com/user-attachments/assets/524af157-9de9-4142-bf36-633e7d9d8dfc)
![Image](https://github.com/user-attachments/assets/745b6c61-9f0d-4cd3-882d-20834a659827)

**Comment by faidercamilo26** [comment]
Se realiza un código de prueba con excelize creando un documento de excel utilizando únicamente el código de la librería, luego se utiliza la libreria `gopdf` para crear un archivo pdf y por último la librería `xlsx2pdf` que fue desarrollada por la Oati con la función de convertir de excel a pdf.

### *Codigo completo de prueba*

```go
package main

import (
	"fmt"

	"github.com/phpdave11/gofpdf"
	"github.com/udistrital/utils_oas/xlsx2pdf"
	"github.com/xuri/excelize/v2"
)

func main() {

	f := excelize.NewFile()
	sheetname := "Transcript"

	// Se cambia el nombre de la hoja
	f.SetSheetName("Sheet1", sheetname)

	//Se crean los datos de la hoja, en este caso va a ser una tabla de calificaciones
	data := [][]interface{}{
		{"Student Exam Score"},
		{"Type: Midterm Exam", nil, nil, nil, "Core Curriculum", nil, nil, "Science"},
		{"Number", "ID", "Name", "Class", "Language Arts", "Mathematics", "History", "Chemistry", "Biology", "Physics", "Total"},
		{"1", "001", "John Doe", "JSS 1", 70, 80, 90, 85, 75, 80},
		{"2", "002", "Jane Doe", "JSS 1", 75, 85, 95, 80, 70, 85},
		{"3", "003", "James Doe", "JSS 1", 80, 90, 100, 75, 65, 90},
		{"4", "004", "Janet Doe", "JSS 1", 85, 95, 105, 70, 60, 95},
		{"5", "005", "Jude Doe", "JSS 1", 90, 100, 110, 65, 55, 100},
		{"6", "006", "Jade Doe", "JSS 1", 95, 105, 115, 60, 50, 105},
		{"7", "007", "Jade Doe", "JSS 1", 100, 110, 120, 55, 45, 110},
	}

	// Se recorre la tabla y se insertan los datos en la hoja
	for i, row := range data {
		startCell, err := excelize.JoinCellName("A", i+1)
		if err != nil {
			fmt.Println(err)
			return
		}

		if err := f.SetSheetRow(sheetname, startCell, &row); err != nil {
			fmt.Println(err)
			return
		}
	}

	// Se inserta la formula de suma en las celdas K4:K10
	formulaType, ref := excelize.STCellFormulaTypeShared, "K4:K10"
	if err := f.SetCellFormula(sheetname, "K4", "=SUM(E4:J4)",
		excelize.FormulaOpts{Ref: &ref, Type: &formulaType}); err != nil {
		fmt.Println(err)
		return
	}

	// Se combinan las celdas de la primera y segunda fila
	mergeCellRanges := [][]string{{"A1", "K1"}, {"A2", "D2"}, {"E2", "G2"}, {"H2", "J2"}}
	for _, mergeCellRange := range mergeCellRanges {
		if err := f.MergeCell(sheetname, mergeCellRange[0], mergeCellRange[1]); err != nil {
			fmt.Println(err)
			return
		}
	}

	// Se establece el estilo de las celdas de la primera fila
	style1, err := f.NewStyle(&excelize.Style{
		Alignment: &excelize.Alignment{Horizontal: "center", Vertical: "center"},
		Fill:      excelize.Fill{Type: "pattern", Color: []string{"#DFEBF6"}, Pattern: 1},
	})

	if err != nil {
		fmt.Println(err)
		return
	}

	if err := f.SetCellStyle(sheetname, "A1", "A1", style1); err != nil {
		fmt.Println(err)
		return
	}

	// Se establece el estilo de las celdas de la segunda fila
	style2, err := f.NewStyle(&excelize.Style{
		Alignment: &excelize.Alignment{Horizontal: "center", Vertical: "center"},
	})

	if err != nil {
		fmt.Println(err)
		return
	}

	for _, cell := range []string{"A2", "E2", "H2"} {
		if err := f.SetCellStyle(sheetname, cell, cell, style2); err != nil {
			fmt.Println(err)
			return
		}
	}

	// Se establece el ancho de las columnas
	if err := f.SetColWidth(sheetname, "D", "K", 14); err != nil {
		fmt.Println(err)
		return
	}

	//Crear formato de tabla para la tabla

	table := &excelize.Table{
		Name:              "table",
		Range:             "A3:K10",
		StyleName:         "TableStyleMedium9",
		ShowColumnStripes: true,
	}

	if err := f.AddTable(sheetname, table); err != nil {
		fmt.Println(err)
		return
	}

	f.AddChart(sheetname, "A12", &excelize.Chart{
		Type: excelize.Col,
		Series: []excelize.ChartSeries{
			{
				Name:       "Transcript!$A$2",
				Categories: "Transcript!$C$4:$C$10",
				Values:     "Transcript!$K$4:$K$10",
			},
		},
	})

	if err := f.SaveAs("ejemplo.xlsx"); err != nil {
		fmt.Println(err)
		return
	}

	template, err := excelize.OpenFile("PTD.xlsx")
	if err != nil {
		fmt.Println(err)
		return
	}

	pdf := gofpdf.New("P", "mm", "A4", "")

	ExcelPdf := xlsx2pdf.Excel2PDF{
		Excel:    template,
		Pdf:      pdf,
		Sheets:   make(map[string]xlsx2pdf.SheetInfo),
		WFx:      2.02,
		HFx:      2.925,
		FontDims: xlsx2pdf.FontDims{Size: 0.85},
		Header:   func() {},
		Footer:   func() {},
		CustomSize: xlsx2pdf.PageFormat{
			Orientation: "L",
			Wd:          225.9,
			Ht:          230,
		},
	}

	ExcelPdf.Header = func() {
		if ExcelPdf.PageCount == 1 {
			pdf.SetFontSize(9)
			pdf.SetFontStyle("")
			lm, _, _, _ := pdf.GetMargins()
			//pw, _ := pdf.GetPageSize()
			x, y := pdf.GetXY()
			pdf.SetXY(lm, 8)
			pdf.BeginLayer(ExcelPdf.Layers.Imgs)
			pdf.ImageOptions("logoud.jpeg", lm+1.5, 12, 50, 0, false, gofpdf.ImageOptions{ImageType: "JPEG", ReadDpi: true}, 0, "")
			//pdf.ImageOptions("logosigud.jpeg", (pw/5)-rm-60, 12, 60, 0, false, gofpdf.ImageOptions{ImageType: "JPEG", ReadDpi: true}, 0, "")
			pdf.EndLayer()
			pdf.SetXY(x, y)
		}
	}

	maxpages := ExcelPdf.EstimateMaxPages()
	ExcelPdf.Footer = func() {
		pdf.SetFontSize(9)
		pdf.SetFontStyle("")
		pagenum := pdf.PageNo()
		lm, _, rm, bm := pdf.GetMargins()
		pw, ph := pdf.GetPageSize()
		x, y := pdf.GetXY()
		pdf.SetXY(lm, ph-bm)
		w := (pw - lm - rm) / 3
		pdf.BeginLayer(ExcelPdf.Layers.Txts)
		pdf.CellFormat(w, 9, pdf.UnicodeTranslatorFromDescriptor("")("Oficina Asesora de Tecnologías e Información"), "", 0, "LT", false, 0, "")
		pdf.CellFormat(w, 9, pdf.UnicodeTranslatorFromDescriptor("")(fmt.Sprintf("Página %d de %d", pagenum, maxpages)), "", 0, "CT", false, 0, "")
		pdf.CellFormat(w, 9, pdf.UnicodeTranslatorFromDescriptor("")("Fecha de generación: "), "", 0, "RT", false, 0, "")
		pdf.EndLayer()
		pdf.SetXY(x, y)
	}

	ExcelPdf.ConvertSheets()

	if err != nil {
		fmt.Println(err)
		return
	}
	if err := pdf.OutputFileAndClose("prueba.pdf"); err != nil {
		fmt.Println(err)
		return
	}

}

```

### Resultados

- Se puede crear correctamente el excel el cual se ve la siguiente forma.

![Image](https://github.com/user-attachments/assets/d213179d-2165-46e9-b165-2b5f0c4ecd82)

- Se presenta un problema al utilizar la libreria de `xlsx2pdf` para convertir ese excel de pruebas a un pdf, puesto que la función `EstimateMaxPages()` es la encargada de calcular el numero de paginas que tiene el excel para realizar la correspondiente conversión a pdf, sin embargo, esta función no esta calculando correctamente las paginas del excel de pruebas y retorna el siguiente error.

![Image](https://github.com/user-attachments/assets/0a074510-8604-408e-a79d-a02cbf855156)

Se investiga acerca de este error, se revisa la función y se trata de soluciona el problema pero no fue posible, sin embargo, se descarga el archivo `PTD.xlsx` del proyecto `sga` y con este si se puede realizar la conversión sin ningún problema.

![Image](https://github.com/user-attachments/assets/653fbd5d-846c-4f30-8c93-58ada9919cf8)


- Para este documento que se mostró anteriormente se realizó la conversión de excel a pdf, se creo un header y un footer con la librería `xlsx2pdf` para realizar pruebas y entender un poco mejor su funcionamiento.

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 Buen trabajo.
