### ISSUE TITLE
Crear formato plantilla de excel para los items - Evaluación proveedores.

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#248]
Se requiere realizar la propuesta de plantilla de excel para los ítems.

**Sub Tareas**

- [x] Propuesta de plantilla con una hoja de explicación, y una hoja para ingresar la información.
- [x] Implementar limitantes para las casillas según el modelo de la base de datos, tabla item.
- [ ] Agregar casillas tipo select para los datos necesarios (tipo necesidad y unidad)

**Criterios de aceptación**

- [ ] Propuesta de plantilla.
- [ ] issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by stevencol** [comment]
Se inicio con actividad investigando, como crear las reglas de validación, se logran algunas validaciones, pero no deja combinar, se realiza el siguiente formato
![image](https://github.com/user-attachments/assets/5f9e1b67-7e28-4a1c-b01e-ea20d042cc0b)

**Comment by stevencol** [comment]
![image](https://github.com/user-attachments/assets/4e77848b-40fb-4ba1-aa03-9dd2f675eab3)

**Comment by stevencol** [comment]
![finalev](https://github.com/user-attachments/assets/4f3cc6fb-e2fb-43fe-bae2-d9364870ed3f)

**Comment by stevencol** [comment]
Se carga el archivo 

[Formato.xlsx](https://github.com/user-attachments/files/17935480/Formato.xlsx)

**Comment by stevencol** [comment]
Se realizan ajuste sugeridos y se carga en [oneDrive](https://udistritaleduco-my.sharepoint.com/personal/computo_udistrital_edu_co/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fcomputo%5Fudistrital%5Fedu%5Fco%2FDocuments%2FINVERSI%C3%93N%2FPROYECTOS%20DE%20INVERSI%C3%93N%2FGERENCIA%20DE%20PROYECTOS%2FPROYECTOS%20OAS%2FPROYECTO%20CUMPLIDOS%20Y%20CERTIFICACIONES%2F2024%2FEjecuci%C3%B3n%2FGesti%C3%B3n%20t%C3%A9cnica%2FCUMPLIDOS%2FProveedores&ct=1732729879396&or=Teams%2DHL&ga=1)

**Comment by JuanCamiloMartinezLopez** [comment]
@stevencol Buen trabajo.
