### ISSUE TITLE
Crear un a funciona para insertar/actualizar los evaluadores registrados en una evaluación

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#249]
Se requiere realizar la función para guardar los evaluadores (documento, cargo, ítems a evaluar y porcentaje)

**Sub Tareas**

- [x] Implementar una funciona para guardar la información de los evaluadores, el servicio debe permitir guardar varios al tiempo, asi como actualizar o insertar la informacion de estos.

**Criterios de aceptación**

- [x] función creada.
- [x] issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
## *Avances*

- *Implementación ReadorUpdate:* Se crea en en el modelo de asignacion_evaluacion la funcion `ReadOrUpdateAsignacionEvaluador()` la cual es la encargada de validar si un objeto ya existe en la base de datos basándose en si la `personaId` y la `evaluacionId` son las mismas a un registro existente en la base de datos, si estos es así, se actualiza el registro, en caso de que no haya encontrado un registro con estas coincidencias se crea este registro.

```go
func ReadOrUpdateAsignacionEvaluador(m *AsignacionEvaluador) (created bool, err error) {
	o := orm.NewOrm()

	var existing AsignacionEvaluador
	err = o.QueryTable(new(AsignacionEvaluador)).
		Filter("PersonaId", m.PersonaId).
		Filter("EvaluacionId__Id", m.EvaluacionId.Id).
		Filter("Activo", true).
		One(&existing)

	if err == orm.ErrNoRows {
		m.Activo = true
		if _, err = o.Insert(m); err == nil {
			created = true
			return created, nil
		}
	} else if err == nil {
		m.Id = existing.Id
		m.FechaCreacion = existing.FechaCreacion
		if _, err = o.Update(m); err == nil {
			created = false
			return created, nil
		}
	}

	return false, err
}

```

Se crea su respectivo controlador retornando un `201` si el registro se creo por primera vez o un `200` si el registro se actualizó con éxito.

```go
func (c *AsignacionEvaluadorController) ReadOrUpdate() {
	var v models.AsignacionEvaluador

	if err := json.Unmarshal(c.Ctx.Input.RequestBody, &v); err != nil {
		logs.Error(err)
		c.Data["mesaage"] = "Error service ReadOrUpdate: Invalid request body"
		c.Abort("400")
		return
	}

	if created, err := models.ReadOrUpdateAsignacionEvaluador(&v); err == nil {
		if created {
			c.Ctx.Output.SetStatus(201)
			c.Data["json"] = map[string]interface{}{"Success": true, "Status": "201", "Message": "Record created successfully", "Data": v}
		} else {
			c.Ctx.Output.SetStatus(200)
			c.Data["json"] = map[string]interface{}{"Success": true, "Status": "200", "Message": "Record updated successfully", "Data": v}
		}
	} else {
		logs.Error(err)
		c.Data["mesaage"] = "Error service ReadOrUpdate: Could not process the request"
		c.Abort("400")
	}
	c.ServeJSON()
}
```

**Comment by faidercamilo26** [comment]
## *Avances*

- Se cambia el nombre de la función `ReadOrUpdateAsignacionEvaluador` a `CreateorUpdateAsignacionEvaluador` nombre que es mas diciente acerca de la funcionalidad de la función y el controlador se cambia de `ReadOrUpdate` a `CreateOrUpdate`.
- Para probar que el crud este realizando las inserciones o actualizaciones correctamente se implementan las siguientes funciones en el cliente:
1. **`guardarEvaluadorIndividual`:**
   - Esta función es responsable de realizar una solicitud HTTP `POST` para guardar un único evaluador en el backend.
   - Se utiliza el servicio `evaluacionCumplidoProvCrudService` para gestionar la solicitud.
   - Manejo de errores: Si ocurre un error, se captura y se registra en la consola con detalles específicos (`error.response` o `error.message`).

   **Ejemplo de código:**
   ```typescript
   guardarEvaluadorIndividual = async (data: AsignacionEvaluador): Promise<void> => {
       try {
           const response = await this.evaluacionCumplidoProvCrudService.post('/asignacion_evaluador', data).toPromise();
           console.log(`Respuesta del servidor: ${response}`);
       } catch (error: any) {
           console.error(`Error: ${error.response?.data?.message || error.message}`);
       }
   };
2. **`guardarEvaluadores`:**
- Esta función procesa un conjunto de evaluadores a la vez, utilizando la función `guardarEvaluadorIndividual` para enviar cada registro.
- Para mejorar la eficiencia, se implementó el uso de `Promise.allSettled`: 
- - Ejecuta todas las solicitudes en paralelo.
- - Asegura que incluso si una solicitud falla, las demás continúan ejecutándose.
**Ejemplo de código:**

```typescript
async guardarEvaluadores() {
    const datosPrueba: AsignacionEvaluador[] = [
        { PersonaId: 12345678, EvaluacionId: { Id: 1 }, Cargo: 'Cargo', PorcentajeEvaluacion: 0.25 },
        { PersonaId: 111111, EvaluacionId: { Id: 1 }, Cargo: 'Supervisor', PorcentajeEvaluacion: 0.30 },
        { PersonaId: 12345678, EvaluacionId: { Id: 1 }, Cargo: 'Supervisor', PorcentajeEvaluacion: 0.10 },
        { PersonaId: 111111, EvaluacionId: { Id: 1 }, Cargo: 'Sin asignar', PorcentajeEvaluacion: 0.35 },
    ];

    const resultados = await Promise.allSettled(
        datosPrueba.map((data) => this.guardarEvaluadorIndividual(data))
    );

    resultados.forEach((resultado, index) => {
        if (resultado.status === "fulfilled") {
            console.log(`Solicitud ${index + 1} completada con éxito.`);
        } else {
            console.error(`Solicitud ${index + 1} falló:`, resultado.reason);
        }
    });
};
```

Por el momento a estas funciones solo les hace falta un manejo de errores mas robusto, haciendo unas pequeñas modificaciones se pueden usar en el código final para almacenar los evaluadores.

**Comment by faidercamilo26** [comment]
#### Descripción Avance:
Se crea la función `guardarItemsEvaluador`, la cual se encarga de manejar la asignación de ítems a un evaluador en la base de datos. Primero, verifica si los ítems ya existen para el evaluador asignado. Si un ítem no está presente en la nueva lista proporcionada (`ItemsAEvaluar`), lo elimina. Posteriormente, agrega todos los ítems nuevos que aún no estén asignados.

#### Flujo de la función:
1. Consulta los ítems actuales asignados al evaluador mediante una solicitud `GET`.
2. Si encuentra ítems existentes:
   - Itera sobre ellos para verificar si aún deben estar asignados utilizando la función `itemInLista`.
   - Si no deben estar asignados, los elimina mediante una solicitud `DELETE`.
3. Recorre la lista de nuevos ítems (`ItemsAEvaluar`) y asigna los ítems mediante solicitudes `POST`.
4. Si ocurre un error en cualquier parte del proceso, muestra un mensaje de error en un pop-up y registra el error en la consola.

#### Consideraciones:
- La función espera que `ItemsAEvaluar` sea un array no vacío antes de realizar las operaciones.
- Usa una función auxiliar, `itemInLista`, para verificar si un ítem ya está presente en la lista.
- Implementa suscripciones para manejar respuestas y errores de las solicitudes HTTP.

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 Buen trabajo.
