### ISSUE TITLE
Investigar sobre la estimación del uso de cumplidos proveedores para los usuarios de la Universidad

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/Cumplidos_y_certificaciones_documentacion#250]
Se requiere realizar la investigación relacionada con la estimación del uso de cumplidos proveedores para los usuarios de la Universidad

**Sub Tareas**

- [x] Generar contacto con el responsable.
- [x] Adelantar la investigación.
- [x] Alimentar la documentación relacionada.

**Criterios de aceptación**

- [x] Documento con información relacionada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by mantnicot** [comment]
Se ha realizado el contacto con la oficina de contratación para obtener datos de la cantidad de peticiones , usuarios de cumplidos proveedores , pero por información de ellos no se encuentra ese tipo de datos más haya de los casos prácticos de ellos.

Despues de la sesión con el equipo se determino la opción de consultar AGORA para obtener la información y darle solución al requerimiento.

**Comment by mantnicot** [comment]
se ha creado una documento de estimación para el sistema cumplidos proveedores

[documento de estimación](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EbibAC2zTh5NnwQYBZp0uF4B9-jvg7XeT1jgi5NFE5Ru_A?e=aamQQw)

**Comment by mantnicot** [comment]
se actualizo el documento con un excel suministrado por el lider tecnico 
[Excel de datos por meses de los contratos](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/caescorciab_udistrital_edu_co/EXm2YHz9ZuFGmQ8sEfoR1VMB-xRsDQaOZykaqQxLva2HeQ?e=yDzEaW)

[documento de estimación](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EbibAC2zTh5NnwQYBZp0uF4B9-jvg7XeT1jgi5NFE5Ru_A?e=aamQQw)

**Comment by jcmurilloa** [comment]
Muy buen trabajo @mantnicot
