### ISSUE TITLE
Crear helper para calcular resultado de la evaluación

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#255]
Se requiere crear helper para calcular resultado de las evaluaciones

**Sub Tareas**

- [x] El helper debe tener en cuenta los resultados individuales y porcentaje para pregunta a pregunta calcular la mayoría entre las opciones, en caso de empate la opción ganadora es la escogida por el supervisor.
- [x] retornar un json similar al guardado en resultado junto con la información de evaluadores.

**Criterios de aceptación**

- [x] Helper creado y funcionando.
- [x] Issue documentado.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
## Avances en la implementación de la funcionalidad para obtener el resultado final de la evaluación

### Funcionalidades implementadas:

1. **Validación del estado de la evaluación:**
   - Se verifica que la evaluación esté en el estado "Aprobado por evaluadores" (`EstadoEvaluacionId.CodigoAbreviacion:AE`).
   - Se maneja un mensaje de error adecuado si la evaluación no cumple esta condición.

2. **Obtención de evaluadores asignados a la evaluación:**
   - Se consulta la asignación de evaluadores activos asociados al `evaluacion_id`.
   - Se limpian y procesan los datos obtenidos mediante la función `helpers.LimpiezaRespuestaRefactor`.

3. **Procesamiento de los resultados de evaluación por evaluador:**
   - Se realiza una consulta para obtener los resultados individuales de cada evaluador con base en su ID de asignación.
   - Los resultados de evaluación se deserializan de JSON al modelo `models.Resultado`.
   - Se procesan las respuestas individuales para calcular:
     - Porcentaje acumulado por pregunta y cumplimiento.
     - Valores asignados por pregunta y cumplimiento.

### Faltantes
- Por el momento falta recuperar el nombre del evaluador para retornarlo.
- Falta guardar las respuestas del supervisor puesto que todavía el modelo no esta actualizado con la tabla `Rol`.

**Comment by faidercamilo26** [comment]
## Detalle de las pruebas realizadas 

Se crea la evaluacion con id 1 y esta se le asignan a 3 evaluadores:
    - *Evaluador 1:*
   ```go
   {
            "Id": 2,
            "EvaluacionId": {
                "Id": 1,
                "ContratoSuscritoId": 1158,
                "VigenciaContrato": 2024,
                "Activo": true,
                "DocumentoId": 1000520869,
                "FechaCreacion": "2024-12-04T19:00:00-05:00",
                "FechaModificacion": "2024-12-04T19:00:00-05:00"
            },
            "PersonaId": 1000520869,
            "Cargo": "Cooridinador representante ante el CILUD \nde los Laboratorios de la Facultad de Ingenieria.",
            "PorcentajeEvaluacion": 0.4,
            "RolAsignacionEvaluadorId": {
                "Id": 1,
                "Nombre": "Supervisor",
                "Descripcion": "El supervisor de la evaluación.",
                "CodigoAbreviacion": "SP",
                "Activo": true
            },
            "Activo": true,
            "FechaCreacion": "2024-12-04T19:00:00-05:00",
            "FechaModificacion": "2024-12-04T19:00:00-05:00"
        },
   ```

   -*Evaluador 2:*

   ```go
   {
            "Id": 3,
            "EvaluacionId": {
                "Id": 1,
                "ContratoSuscritoId": 1158,
                "VigenciaContrato": 2024,
                "Activo": true,
                "DocumentoId": 1000520869,
                "FechaCreacion": "2024-12-04T19:00:00-05:00",
                "FechaModificacion": "2024-12-04T19:00:00-05:00"
            },
            "PersonaId": 14265904,
            "Cargo": "Coordinador representante ante el CILUD \nde los Laboratoris de laFacultad Tecnologica",
            "PorcentajeEvaluacion": 0.35,
            "RolAsignacionEvaluadorId": {
                "Id": 2,
                "Nombre": "Evaluador",
                "Descripcion": "Evaluador de la evaluación.",
                "CodigoAbreviacion": "EV",
                "Activo": true
            },
            "Activo": true,
            "FechaCreacion": "2024-12-04T19:00:00-05:00",
            "FechaModificacion": "2024-12-04T19:00:00-05:00"
        }

  ```
   -*Evaluador 3:*

   ```go
{
            "Id": 4,
            "EvaluacionId": {
                "Id": 1,
                "ContratoSuscritoId": 1158,
                "VigenciaContrato": 2024,
                "Activo": true,
                "DocumentoId": 1000520869,
                "FechaCreacion": "2024-12-04T19:00:00-05:00",
                "FechaModificacion": "2024-12-04T19:00:00-05:00"
            },
            "PersonaId": 1111193324,
            "Cargo": "Coordinador representante ante el CILUD \nde los Laboratoris de laFacultad Tecnologica",
            "PorcentajeEvaluacion": 0.25,
            "RolAsignacionEvaluadorId": {
                "Id": 2,
                "Nombre": "Evaluador",
                "Descripcion": "Evaluador de la evaluación.",
                "CodigoAbreviacion": "EV",
                "Activo": true
            },
            "Activo": true,
            "FechaCreacion": "2024-12-04T19:00:00-05:00",
            "FechaModificacion": "2024-12-04T19:00:00-05:00"
        }
   ```

**Comment by faidercamilo26** [comment]
Se crean los siguientes resultados de evaluación para cada evaluador:

- ## *Evaluador 1:*

![Image](https://github.com/user-attachments/assets/9c0f1beb-6dd6-4c9d-8a99-aa08b0f02260)

- ## *Evaluador 2:*

![Image](https://github.com/user-attachments/assets/08932410-81bc-4ab3-850d-a493eedd8a98)

- ## *Evaluador 3:*

![Image](https://github.com/user-attachments/assets/8076571a-0706-4de0-be6c-0511090d3922)

**Comment by faidercamilo26** [comment]
## Resultado obtenido

```Json
"Data": {
        "Evaluadores": [
            {
                "Nombre": "FAIDER CAMILO TRUJILLO OLAYA",
                "Cargo": "Cooridinador representante ante el CILUD \nde los Laboratorios de la Facultad de Ingenieria.",
                "Items": "1, 2, 3, 4, 5"
            },
            {
                "Nombre": "HUMBERTO  SUANCHA MEJIA",
                "Cargo": "Coordinador representante ante el CILUD \nde los Laboratoris de laFacultad Tecnologica",
                "Items": "6, 7, 8"
            },
            {
                "Nombre": "NATALIA  PEREZ FERNANDEZ",
                "Cargo": "Coordinador representante ante el CILUD \nde los Laboratoris de laFacultad Tecnologica",
                "Items": "9, 10"
            }
        ],
        "Resultados": [
            {
                "Categoria": "POS CONTRACTUAL",
                "Titulo": "SERVICIO POS VENTA",
                "Pregunta": "¿El proveedor cumple con los compromisos pactados dentro del contrato u orden de servicio o compra? (aplicación de garantías, mantenimiento, cambios, reparaciones, capacitaciones, entre otras)",
                "Cumplimiento": "No",
                "ValorAsignado": 0
            },
            {
                "Categoria": "GESTIÓN",
                "Titulo": "PROCEDIMIENTOS",
                "Pregunta": "¿El contrato es suscrito en el tiempo pactado, entrega las pólizas a tiempo y las facturas son radicadas en el tiempo indicado con las condiciones y soportes requeridos para su trámite contractual?",
                "Cumplimiento": "Malo",
                "ValorAsignado": 0
            },
            {
                "Categoria": "GESTIÓN",
                "Titulo": "GARANTÍA",
                "Pregunta": "¿Se requirió hacer uso de la garantía del producto o servicio?",
                "Cumplimiento": "No",
                "ValorAsignado": 15
            },
            {
                "Categoria": "GESTIÓN",
                "Titulo": "GARANTÍA",
                "Pregunta": " ¿El proveedor cumplió a satisfacción con la garantía pactada?",
                "Cumplimiento": "No",
                "ValorAsignado": 0
            },
            {
                "Categoria": "CUMPLIMIENTO",
                "Titulo": "TIEMPOS DE ENTREGA",
                "Pregunta": "¿Se cumplieron los tiempos de entrega de bienes o la prestación del servicios ofertados por el proveedor?",
                "Cumplimiento": "Si",
                "ValorAsignado": 12
            },
            {
                "Categoria": "CUMPLIMIENTO",
                "Titulo": "CANTIDADES",
                "Pregunta": "¿Se entregan las cantidades solicitadas?",
                "Cumplimiento": "No",
                "ValorAsignado": 0
            },
            {
                "Categoria": "CALIDAD",
                "Titulo": "CONFORMIDAD",
                "Pregunta": "¿El bien o servicio cumplió con las especificaciones y requisitos pactados en el momento de entrega?",
                "Cumplimiento": "Si",
                "ValorAsignado": 20
            },
            {
                "Categoria": "CALIDAD",
                "Titulo": "FUNCIONALIDAD ADICIONAL",
                "Pregunta": "¿El producto comprado o el servicio prestado proporcionó más herramientas o funciones de las solicitadas originalmente?",
                "Cumplimiento": "No",
                "ValorAsignado": 0
            },
            {
                "Categoria": "POS CONTRACTUAL",
                "Titulo": "RECLAMACIONES",
                "Pregunta": "¿Se han presentado reclamaciones al proveedor en calidad o gestión?",
                "Cumplimiento": "No",
                "ValorAsignado": 12
            },
            {
                "Categoria": "POS CONTRACTUAL",
                "Titulo": "RECLAMACIONES",
                "Pregunta": "¿El proveedor soluciona oportunamente las no conformidades de calidad y gestión de los bienes o servicios recibidos?",
                "Cumplimiento": "No",
                "ValorAsignado": 0
            }
        ]

```

**Comment by faidercamilo26** [comment]
## Explicacion resultado

## **Contexto**
- **Pesos por evaluador**:
  - Primer evaluador: **40%**
  - Segundo evaluador: **35%**
  - Tercer evaluador: **25%**

- **Mecanismo de decisión**:
  1. Para cada pregunta, se suman los pesos de los evaluadores que seleccionaron una misma opción.
  2. La opción con el mayor porcentaje acumulado se considera la respuesta ganadora.
  3. En caso de empate, se utiliza la respuesta del **supervisor**.

---

## **Resultados por pregunta**

### **Pregunta 1: ¿Se cumplieron los tiempos de entrega de bienes o la prestación del servicios ofertados por el proveedor?**
- **Respuestas**:
  - Evaluador 1: "Sí" (40%)
  - Evaluador 2: "No" (35%)
  - Evaluador 3: "Sí" (25%)
- **Cálculo**:
  - "Sí": `40% + 25% = 65%`
  - "No": `35%`
- **Resultado final**: **"Sí"** (65%, mayor porcentaje).

### **Pregunta 2: ¿Se entregan las cantidades solicitadas?**
- **Respuestas**:
  - Evaluador 1: "Sí" (40%)
  - Evaluador 2: "No" (35%)
  - Evaluador 3: "No" (25%)
- **Cálculo**:
  - "Sí": `40%`
  - "No": `35% + 25% = 60%`
- **Resultado final**: **"No"** (60%, mayor porcentaje).

### **Pregunta 3: ¿El bien o servicio cumplió con las especificaciones y requisitos pactados en el momento de entrega?**
- **Respuestas**:
  - Evaluador 1: "Sí" (40%)
  - Evaluador 2: "Sí" (35%)
  - Evaluador 3: "No" (25%)
- **Cálculo**:
  - "Sí": `40% + 35% = 75%`
  - "No": `25%`
- **Resultado final**: **"Sí"** (75%, mayor porcentaje).

### **Pregunta 4: ¿El producto comprado o el servicio prestado proporcionó más herramientas o funciones de las solicitadas originalmente?**
- **Respuestas**:
  - Evaluador 1: "No" (40%)
  - Evaluador 2: "Sí" (35%)
  - Evaluador 3: "No" (25%)
- **Cálculo**:
  - "Sí": `35%`
  - "No": `40% + 25% = 65%`
- **Resultado final**: **"No"** (65%, mayor porcentaje).

### **Pregunta 5: ¿Se han presentado reclamaciones al proveedor en calidad o gestión?**
- **Respuestas**:
  - Evaluador 1: "No" (40%)
  - Evaluador 2: "Sí" (35%)
  - Evaluador 3: "No" (25%)
- **Cálculo**:
  - "Sí": `35%`
  - "No": `40% + 25% = 65%`
- **Resultado final**: **"No"** (65%, mayor porcentaje).

### **Pregunta 6: ¿El proveedor soluciona oportunamente las no conformidades de calidad y gestión de los bienes o servicios recibidos?**
- **Respuestas**:
  - Evaluador 1: "No" (40%)
  - Evaluador 2: "Sí" (35%)
  - Evaluador 3: "No" (25%)
- **Cálculo**:
  - "Sí": `35%`
  - "No": `40% + 25% = 65%`
- **Resultado final**: **"No"** (65%, mayor porcentaje).

### **Pregunta 7: ¿El proveedor cumple con los compromisos pactados dentro del contrato u orden de servicio o compra?**
- **Respuestas**:
  - Evaluador 1: "No" (40%)
  - Evaluador 2: "No" (35%)
  - Evaluador 3: "Sí" (25%)
- **Cálculo**:
  - "Sí": `25%`
  - "No": `40% + 35% = 75%`
- **Resultado final**: **"No"** (75%, mayor porcentaje).

### **Pregunta 8: ¿El contrato es suscrito en el tiempo pactado, entrega las pólizas a tiempo y las facturas son radicadas en el tiempo indicado?**
- **Respuestas**:
  - Evaluador 1: "Malo" (40%)
  - Evaluador 2: "Bueno" (35%)
  - Evaluador 3: "Excelente" (25%)
- **Cálculo**:
  - "Malo": `40%`
  - "Bueno": `35%`
  - "Excelente": `25%`
- **Resultado final**: **"Malo"** (40%, mayor porcentaje).

### **Pregunta 9: ¿Se requirió hacer uso de la garantía del producto o servicio?**
- **Respuestas**:
  - Evaluador 1: "No" (40%)
  - Evaluador 2: "Sí" (35%)
  - Evaluador 3: "No" (25%)
- **Cálculo**:
  - "Sí": `35%`
  - "No": `40% + 25% = 65%`
- **Resultado final**: **"No"** (65%, mayor porcentaje).

### **Pregunta 10: ¿El proveedor cumplió a satisfacción con la garantía pactada?**
- **Respuestas**:
  - Evaluador 1: "No" (40%)
  - Evaluador 2: "Sí" (35%)
  - Evaluador 3: "No" (25%)
- **Cálculo**:
  - "Sí": `35%`
  - "No": `40% + 25% = 65%`
- **Resultado final**: **"No"** (65%, mayor porcentaje).

---

## **Resumen de resultados**

| **Pregunta** | **Resultado final** |
|--------------|----------------------|
| Pregunta 1   | "Sí"                |
| Pregunta 2   | "No"                |
| Pregunta 3   | "Sí"                |
| Pregunta 4   | "No"                |
| Pregunta 5   | "No"                |
| Pregunta 6   | "No"                |
| Pregunta 7   | "No"                |
| Pregunta 8   | "Malo"              |
| Pregunta 9   | "No"                |
| Pregunta 10  | "No"                |

**Comment by faidercamilo26** [comment]
## *Prueba 2*

Para esta prueba se crean 2 evaluadores cada uno con un porcentaje de 50% cada uno.

- *Evaluador 1:*

```json
{
            "Id": 5,
            "EvaluacionId": {
                "Id": 2,
                "ContratoSuscritoId": 1982,
                "VigenciaContrato": 2024,
                "Activo": true,
                "DocumentoId": 0,
                "FechaCreacion": "2024-12-08T19:03:10.677282-05:00",
                "FechaModificacion": "2024-12-08T19:03:10.677292-05:00"
            },
            "PersonaId": 79722274,
            "Cargo": "Supervisor de laboratorios de la facultad de ingenieria",
            "PorcentajeEvaluacion": 0.5,
            "RolAsignacionEvaluadorId": {
                "Id": 1,
                "Nombre": "Supervisor",
                "Descripcion": "El supervisor de la evaluación.",
                "CodigoAbreviacion": "SP",
                "Activo": true
            },
            "Activo": true,
            "FechaCreacion": "2024-12-08T19:09:49.065999-05:00",
            "FechaModificacion": "2024-12-08T19:09:49.066005-05:00"
        }
```

- *Evaluador 2:*

```json
{
            "Id": 6,
            "EvaluacionId": {
                "Id": 2,
                "ContratoSuscritoId": 1982,
                "VigenciaContrato": 2024,
                "Activo": true,
                "DocumentoId": 0,
                "FechaCreacion": "2024-12-08T19:03:10.677282-05:00",
                "FechaModificacion": "2024-12-08T19:03:10.677292-05:00"
            },
            "PersonaId": 79777053,
            "Cargo": "Responsable encargado de la oficina asesora de sistemas",
            "PorcentajeEvaluacion": 0.5,
            "RolAsignacionEvaluadorId": {
                "Id": 2,
                "Nombre": "Evaluador",
                "Descripcion": "Evaluador de la evaluación.",
                "CodigoAbreviacion": "EV",
                "Activo": true
            },
            "Activo": false,
            "FechaCreacion": "2024-12-08T19:10:51.299721-05:00",
            "FechaModificacion": "2024-12-08T19:11:17.438764-05:00"
        }
```

**Comment by faidercamilo26** [comment]
## *Resultados Evaluación*
-----

*Evaluador 1:*

![Image](https://github.com/user-attachments/assets/3e3f5ca4-06c6-4099-a0a7-399468f2bff5)

*Evaluador 2:*

![Image](https://github.com/user-attachments/assets/c6ed9ce6-05b9-4beb-bc56-e539f5b3f2f9)

**Comment by faidercamilo26** [comment]
## Resultado

-----

![Image](https://github.com/user-attachments/assets/01976cff-c7a7-4bda-8355-f99817f7791e)

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 Buen trabajo.
