### ISSUE TITLE
Generar servicio para crear el documento de evaluación de proveedores

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#256]
Se requiere realizar el controlador para generar el documento resultado de la evaluación. 

**Sub Tareas**

- [x] Utilizar el helper #255 y lo investigado en la issue #247 para crear el documento con excelize y gofpdf
- [x] El servicio debe retornar el base 64  tomando como base el [documento](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/ETPCsHJ-GlFAuGCRSNJ6NLABQRe6fCT0UkhAsWFS15PJcg?e=TWAicE).

**Criterios de aceptación**

- [x] Servicio creado.
- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
## Avances Realizados

### 1. **Estructura Base de la Función Principal**
Se creó la función `GenerarDocumentoEvaluacion` para manejar todo el proceso de generación del documento Excel:
- **Entrada:** Recibe el `evaluacion_id` como identificador único de la evaluación a procesar.
- **Salida:** Genera un archivo Excel y lo guarda en la carpeta `static/documento/`.

### 2. **Obtención de Información**
Se implementó la función `ObtenerInformacionDocumento` para recuperar la información necesaria desde diferentes fuentes:
- **Evaluación:** Se consultan los datos de evaluación activos.
- **Contrato General:** Se obtiene el contrato suscrito asociado a la evaluación.
- **Dependencia del Supervisor:** Se identifican las dependencias del supervisor que supervisa el contrato.
- **Proveedor:** Se consulta la información del proveedor evaluado.

### 3. **Procesamiento del Archivo Excel**
- **Plantilla Base:** La funcionalidad utiliza una plantilla ubicada en la ruta `static/plantilla/Formato_aprobado_de_evaluación proveedores.xlsx`.
- **Llenado de Información Inicial:**
  - Fecha de generación en la celda `I6`.
  - Nombre del proveedor en la celda `D8`.
  - Dependencia del supervisor en la celda `D6`.
  - Objeto del contrato en la celda `D9`.

### 4. **Preparación de Estilos (Pendiente de Ajustes)**
- Se incorporó un esquema para aplicar estilos personalizados a las celdas:
  - Centrado horizontal y vertical.
  - Habilitación de ajuste de texto (`WrapText`).
  - Eliminar el uso de texto en negrita.

**Nota:** Por el momento, los estilos están comentados, pero su implementación se encuentra lista para habilitar.

---

## Tareas Pendientes

1. **Soporte para Múltiples Evaluadores:**
   - Ajustar la plantilla para duplicar las columnas de evaluación por cada evaluador.
   - Asegurar que las respuestas finales se coloquen correctamente en las celdas correspondientes.

2. **Estilo Avanzado de Celdas:**
   - Configurar correctamente el ajuste de texto (`WrapText`) para evitar cortes verticales.
   - Centrar el contenido de las celdas tanto horizontal como verticalmente.

3. **Validación de Resultados Finales:**
   - Verificar que los resultados de cada evaluador se reflejen adecuadamente en el archivo Excel.

---

## Próximos Pasos
- Completar el llenado dinámico de la información de evaluadores.
- Implementar lógica para insertar nuevas columnas sin sobreescribir datos existentes.
- Finalizar y probar el archivo generado con datos de prueba reales.

---

**Comment by faidercamilo26** [comment]
## Finalización 👍 

- Se crea el servicio para para que se llene dinámicamente los datos de la evaluación en la plantilla de Excel aprobada, utilizando la librería excelize. Se puede notar que este servicio llena todos los datos dinámicamente, dependiendo del número de evaluadores se crean las celdas correspondientes y por cada uno se llenan los datos pertinentes.

![Image](https://github.com/user-attachments/assets/168687bd-849b-4487-9284-44f7fc419681)

![Image](https://github.com/user-attachments/assets/bade65b5-a47d-4a5c-bf30-8da34435f8f0)

## Inconvenientes ❌ 

- Al llenar los datos dinámicamente desde excel, se usa la librería `xlsx2pdf`  diseñada por la oas para convertir el excel a pdf, sin embargo, esta librería realiza la conversión incorrectamente, se prueban varias configuraciones y se prueban maneras de realizar la conversión pero no fue posible, aunque se estudio el código de la librería.

### Ejemplo conversión librería

![Image](https://github.com/user-attachments/assets/106ceee2-7602-4f0f-933e-558a502e7221)

![Image](https://github.com/user-attachments/assets/7ed5e75b-bf3b-4a45-a7d5-47136be36588)

Aparte de estas dos paginas se generan 8 paginas más en blanco.

### Ejemplo de como se ve el pdf cuando se le da `imprimir` en el visor de pdf.

![Image](https://github.com/user-attachments/assets/6992f707-22d6-4cac-aadb-4d944173c482)

**Comment by faidercamilo26** [comment]
Segun lo hablado en el daily del día de hoy se edita la plantilla de excel para eliminar las filas ocultas y las formulas porque se puede ver que la librería no las esta tomando correctamente, sin embargo aunque se edita la plantilla el error de conversión persiste, se puede notar que este error se debe a que la librería `xlsx2pdf` no esta reconociendo el estilo de las celdas, ya en la plantilla se eliminó el exceso de celdas  lo cual redujo el tiempo de conversión del documento y lo que estaba generando muchas más hojas de las necesarias que no se estan utilizando pero el problema persiste, al parecer esta librería no esta adecuada para recibir y procesar estilos complejos de excel. Esto se puede confirmar porque se intento convertir la plantilla vacía y los estilos seguían apareciendo en negro.

![Image](https://github.com/user-attachments/assets/121fe204-834e-416c-b887-e7396e32411f)

![Image](https://github.com/user-attachments/assets/04008e0c-8501-434c-8f4e-928e47c62cbe)


Tambien se intento crear un código para convertir a pdf obteniendo los datos de cada celda, sin embargo, este codigo falla y no obtiene bien los estilos.

```go
func ExcelToPDFWithStyles(inputFile, outputFile string) error {
	// Abrir el archivo Excel
	excel, err := excelize.OpenFile(inputFile)
	if err != nil {
		return fmt.Errorf("Error al abrir el archivo Excel: %v", err)
	}

	// Crear un nuevo PDF
	pdf := gofpdf.New("P", "mm", "A4", "")
	pdf.SetFont("Arial", "", 10)

	for _, sheet := range excel.GetSheetList() {
		// Crear una nueva página para cada hoja
		pdf.AddPage()
		pdf.SetFont("Arial", "B", 12)
		pdf.Cell(190, 10, fmt.Sprintf("Hoja: %s", sheet))
		pdf.Ln(12)

		// Obtener las filas de la hoja
		rows, err := excel.GetRows(sheet)
		if err != nil {
			return fmt.Errorf("Error al leer filas de la hoja %s: %v", sheet, err)
		}

		// Ajustar el ancho y alto de las celdas
		pageWidth := 190.0 // Ancho total de la página
		colWidths := pageWidth / float64(len(rows[0]))
		rowHeight := 8.0

		// Procesar celdas combinadas
		mergedCells, err := excel.GetMergeCells(sheet)
		if err != nil {
			return fmt.Errorf("Error al obtener celdas combinadas: %v", err)
		}
		mergedRanges := map[string]string{}
		for _, merged := range mergedCells {
			mergedRanges[merged.GetStartAxis()] = merged.GetEndAxis()
		}

		// Procesar cada fila
		for rIdx, row := range rows {
			for cIdx, cellValue := range row {
				cellName, _ := excelize.CoordinatesToCellName(cIdx+1, rIdx+1)
				styleID, _ := excel.GetCellStyle(sheet, cellName)

				// Obtener estilos
				style, err := excel.GetStyle(styleID)
				if err != nil {
					return fmt.Errorf("Error al obtener estilo de celda: %v", err)
				}

				// Procesar colores
				fillColor := "255 255 255" // Blanco por defecto
				if len(style.Fill.Color) > 0 {
					fillColor = style.Fill.Color[0]
				}
				r, g, b := parseHexColor(fillColor)

				// Dibujar la celda
				pdf.SetFillColor(r, g, b)
				pdf.SetTextColor(0, 0, 0) // Negro por defecto
				pdf.SetDrawColor(0, 0, 0)

				if _, isMerged := mergedRanges[cellName]; isMerged {
					// Si la celda es parte de un rango combinado, saltar para evitar duplicados
					continue
				}

				// Ajustar texto
				text := cellValue
				if len(text) > 50 {
					text = fmt.Sprintf("%s...", text[:50])
				}

				// Dibujar la celda con texto y bordes
				pdf.CellFormat(colWidths, rowHeight, text, "1", 0, "C", true, 0, "")
			}
			pdf.Ln(rowHeight) // Mover a la siguiente fila
		}
	}

	// Guardar el archivo PDF
	if err := pdf.OutputFileAndClose(outputFile); err != nil {
		return fmt.Errorf("Error al guardar el archivo PDF: %v", err)
	}

	return nil
}

func parseHexColor(hexColor string) (int, int, int) {
	hexColor = strings.TrimPrefix(hexColor, "#")
	if len(hexColor) == 6 {
		var r, g, b int
		fmt.Sscanf(hexColor, "%02x%02x%02x", &r, &g, &b)
		return r, g, b
	}
	return 255, 255, 255
}
```

**Comment by faidercamilo26** [comment]
### Avances

1) Se eliminan todos los formatos de colores del pdf de la plantilla y las formulas,puesto que se puede notar que esto era lo que estaba evitando que el documento se convirtiera, sien embaro esto produce el siguiente error

```error
2024/12/10 10:33:11.038 [E] [panic.go:838]  Panic:  runtime error: invalid memory address or nil pointer dereference
goroutine 24 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/udistrital/utils_oas/errorhandler.HandlePanic(0xc0008900e0)
        /home/faidercamilo/go/pkg/mod/github.com/udistrital/utils_oas@v0.0.0-20240829190820-0bdc14dd8544/errorhandler/errorHandler.go:36 +0x7e
panic({0xff2be0, 0xc00082b040})
        /usr/local/go/src/runtime/panic.go:838 +0x207
github.com/udistrital/evaluacion_cumplido_prov_mid/services.GenerarDocumentoEvaluacion.func1()
        /home/faidercamilo/go/src/github.com/udistrital/evaluacion_cumplido_prov_mid/services/documento_evaluacion.go:26 +0x95
panic({0x100ff60, 0x1d0b870})
        /usr/local/go/src/runtime/panic.go:838 +0x207
github.com/udistrital/utils_oas/xlsx2pdf.(*Excel2PDF).GetCellColor(0xc000156960?, 0xc000a52c82?)
        /home/faidercamilo/go/pkg/mod/github.com/udistrital/utils_oas@v0.0.0-20240829190820-0bdc14dd8544/xlsx2pdf/xlsx2pdf.go:189 +0x57
github.com/udistrital/utils_oas/xlsx2pdf.(*Excel2PDF).ConvertSheets(0xc0008a3480)
        /home/faidercamilo/go/pkg/mod/github.com/udistrital/utils_oas@v0.0.0-20240829190820-0bdc14dd8544/xlsx2pdf/xlsx2pdf.go:509 +0x76c
github.com/udistrital/evaluacion_cumplido_prov_mid/services.GenerarDocumentoEvaluacion(0xc0003b2023?)
        /home/faidercamilo/go/src/github.com/udistrital/evaluacion_cumplido_prov_mid/services/documento_evaluacion.go:139 +0xba5
github.com/udistrital/evaluacion_cumplido_prov_mid/controllers.(*DocumentoEvaluacionController).GenerarDocumentoEvaluacion(0xc0008900e0)
        /home/faidercamilo/go/src/github.com/udistrital/evaluacion_cumplido_prov_mid/controllers/generar_documento_evaluacion.go:33 +0xaa
github.com/astaxie/beego.(*Controller).HandlerFunc(0xc0008900e0?, {0xc0001bcc64?, 0xf79f3a?})
        /home/faidercamilo/go/pkg/mod/github.com/astaxie/beego@v1.12.3/controller.go:218 +0x3e
github.com/astaxie/beego.(*ControllerRegister).ServeHTTP(0xc000142000, {0x14f9d78, 0xc000890000}, 0xc0000ac700)
        /home/faidercamilo/go/pkg/mod/github.com/astaxie/beego@v1.12.3/router.go:893 +0x1999
net/http.serverHandler.ServeHTTP({0xc00086d1a0?}, {0x14f9d78, 0xc000890000}, 0xc0000ac700)
        /usr/local/go/src/net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc000266820, {0x14fabd0, 0xc00086cf90})
        /usr/local/go/src/net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:3071 +0x4db
2024/12/10 10:33:11.038 [D] [server.go:2916]  |            ::1| 500 | 2.867622229s|   match| GET      /v1/resultado-final-evaluacion/2   r:/v1/resultado-final-evaluacion/:evaluacion_id
```

2) Se evidencia que este error se esta produciendo por el método `GetCellColor()` de la librería `xlsx2pdf` por eso se edita momentaneamente ese metodo por el siguiente:

```go
func (Xlsx2Pdf *Excel2PDF) GetCellColor(styleID int) (color colorRGB, fill bool) {
	// Validar que el índice styleID sea válido
	if styleID < 0 || styleID >= len(Xlsx2Pdf.Excel.Styles.CellXfs.Xf) {
		return colorRGB{R: 0, G: 0, B: 0}, false
	}

	style := Xlsx2Pdf.Excel.Styles.CellXfs.Xf[styleID]

	// Validar que FillID no sea nil
	if style.FillID == nil {
		return colorRGB{R: 0, G: 0, B: 0}, false
	}

	fillID := *style.FillID

	// Validar que fillID esté dentro del rango
	if fillID < 0 || fillID >= len(Xlsx2Pdf.Excel.Styles.Fills.Fill) {
		return colorRGB{R: 0, G: 0, B: 0}, false
	}

	// Obtener el objeto Fill correspondiente
	fillObj := Xlsx2Pdf.Excel.Styles.Fills.Fill[fillID]

	// Validar que PatternFill exista
	if fillObj.PatternFill == nil || fillObj.PatternFill.FgColor == nil {
		return colorRGB{R: 0, G: 0, B: 0}, false
	}

	// Obtener el color de primer plano (Foreground Color)
	fgColor := fillObj.PatternFill.FgColor

	// Convertir el color hexadecimal a RGB
	if fgColor.RGB != "" {
		color.R, color.G, color.B = ColorHex2RGB(fgColor.RGB)
		return color, true
	}

	// Si no hay un color válido, devolver color blanco
	return colorRGB{R: 0, G: 0, B: 0}, false
}
```

3) Esto colabora con la conversión, sin embargo, todavía hay fallas con la conversión que no se han podido solucionar.

## *Primera prueba*

-------

### *Excel*

![Image](https://github.com/user-attachments/assets/987fbe79-7878-4a9a-84dc-478c2782e6da)

![Image](https://github.com/user-attachments/assets/de5adf8e-bbd5-4051-b0ee-da0fac7cb3bf)

### *Pdf*

![Image](https://github.com/user-attachments/assets/1a347c06-7ccb-473e-a596-887ea73ecaec)

![Image](https://github.com/user-attachments/assets/24afba8a-c94c-4c0c-98b4-42c863ba3a29)

## *Segunda Prueba*

------

### *Excel*

![Image](https://github.com/user-attachments/assets/0641a7eb-1806-4e04-b8af-183f59b31bb5)

![Image](https://github.com/user-attachments/assets/0b8aed8c-4fed-489e-8064-ac7ef41ec1ac)

## *Pdf*

![Image](https://github.com/user-attachments/assets/904405c1-4c8f-4f4a-a4b6-8c0e7fff6e19)

![Image](https://github.com/user-attachments/assets/a8e40d55-f520-4d27-9720-91639753e70f)

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 Buen trabajo.
