### ISSUE TITLE
Investigar sobre la estimación del uso de certificaciones DVE para los usuarios de la Universidad

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/Cumplidos_y_certificaciones_documentacion#261]
Se requiere realizar la investigación relacionada con la estimación del uso de certificaciones DVE para los usuarios de la Universidad

**Sub Tareas**

- [x] Generar contacto con el responsable.
- [x] Adelantar la investigación.
- [x] Alimentar la documentación relacionada.

**Criterios de aceptación**

- [x] Documento con información relacionada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by mantnicot** [comment]
Se ha intentado gestionar con el cliente , pero no se ha podido concretar por la falta de comunicaicón

![Image](https://github.com/user-attachments/assets/a501804f-df47-4f35-bb68-ffa446096fb6)

**Comment by jcmurilloa** [comment]
Seguiremos de esta manera intentando el contacto con el cliente.

**Comment by mantnicot** [comment]
Como se ha agendado una reunión para el días 16/12/2024 , se levantara la información directamente en la reunión

[documento de base](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EdFIrqASwNtNpOh9b4PY5IUBAQynEypNJprzB10g2MrX7A?e=z0dg5r)

[Enlace de sesión](https://teams.microsoft.com/l/meetup-join/19%3ameeting_OTA2ODQzZGItYzcwNS00ZGY2LTk2MzQtNjU1OWJmZDU2MWE4%40thread.v2/0?context=%7b%22Tid%22%3a%22d51388ef-6ab0-4363-9f94-d56644a45970%22%2c%22Oid%22%3a%22b989c328-89fa-4486-abfe-df75fdd723ba%22%7d)

**Comment by jcmurilloa** [comment]
Muy buen trabajo @mantnicot, información valiosa para la implementación del sistema
