### ISSUE TITLE
Agregar funcionalidad desarrollada a la vista de listar evaluaciones.

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#263]
Se requiere realizar la implementación de funcionalidad a la vista de listar evaluaciones.

**Sub Tareas**

- [x] Implementar el [servicio](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/issues/253) para consultar las asignaciones y contratos a crear evaluaciones.
- [x] Agregar botones de acciones (ver evaluación, evaluar, gestionar evaluacion) de forma dinámica según si existe evaluación, estado de esta, rol , etc.
- [x] Si se es supervisor y no se tiene evaluación en un contrato activo, el botón gestión evaluación debe realizar la creación de esta (POST evaluación).
- [x] utilizar observable para compartir información entre vistas.

**Criterios de aceptación**

- [ ] Funcionalidad implementada.
- [ ] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by stevencol** [comment]
Se inicia con actividad, se realiza consulta de asignaciones  disponibles para asignar
![image](https://github.com/user-attachments/assets/a49ec982-4848-4c6e-9989-45635e8df34b)

Al implementar la consulta , se detecta que no se esta retornando el nombre de la dependencia por lo que se procede a medicar el mis para agregar esa consulta

**Comment by stevencol** [comment]
Se modifica mid para relziar la consulta del nomre de le dependencia:

**Comment by stevencol** [comment]
Se modifica mid, para realizar la consulta del nombre de la dependencia 

![image](https://github.com/user-attachments/assets/50f1108b-8858-4429-ac30-651b961fdaa8)

**Comment by stevencol** [comment]
Se muestra botones  según si hay asignaciones : 
![image](https://github.com/user-attachments/assets/8cb3b128-3a3d-46fe-bf75-99ea179e6683)

**Comment by stevencol** [comment]
- Se crea una función que genera un observable para suscribirse a la vista redirigida. con la finalidad de que sea reutilizada 

``` JavaScript
async  redirigirVista(element: any, vista: string): Promise<void> {
    return new Promise( async (resolve) => {

      const evaluacion =  await this.consultarEvaluacionCreada(element.contrato, element.vigencia);
      await this.evaluacionCumplidosCrud.setEvaluacion(evaluacion); 
       this.router.navigate([vista]);
       resolve();
     });

  }
```

y se crea vista para implmentar  funcionalidad



``` JavaScript
  async realizarEvaluacion(element:any) : Promise<void>{
  return await this.redirigirVista(element, 'evaluacion-contrato')
  }

  async verEvaluacion(element:any) : Promise<void>{
  return await this.redirigirVista(element, 'visualizar-evaluacion-contrato');
  }


  async gestionarEvaluacion(element: any): Promise<void> {
    return await this.redirigirVista(element, 'gestion-evaluadores');
  }


```

**Comment by stevencol** [comment]
Se crea método para consultar evaluación creada:

``` JavaScript
  async consultarEvaluacionCreada(
    contratoId: number,
    vigenciaContrato: number
  ): Promise<Evaluacion | null> {
    return new Promise((resolve, reject) => {
      this.evaluacionCumplidosCrud
        .get(
          `/evaluacion/?query=ContratoSuscritoId:${contratoId},VigenciaContrato:${vigenciaContrato}&limit=1`
        )
        .subscribe({
          next: (res: any) => {
            if (res.Data && res.Data.length > 0) {
              const evaluacion: Evaluacion = res.Data[0];
              resolve(evaluacion);
            } else {
              resolve(null);
            }
          },
          error: (error: any) => {
            this.popUpManager.showErrorAlert(
              'Error al consultar la evaluación'
            );
          },
        });
    });
  }
```

**Comment by stevencol** [comment]
se crea función que crea evaluación, verificando que no exista ya uno creado para el contrato y la vigencia , si no existe lo crea y redirige a la vista ,  si ya existe  redirige , en ambos casos se crea el observable , para obtener la evaluación 

``` JavaScript
async crearEvaluacion(element: any) {
    const solicitudCrearEvaluacion = {
      ContratoSuscritoId: Number(element.contrato),
      VigenciaContrato: Number(element.vigencia),
    };

    var evaluacion=  await this.consultarEvaluacionCreada(element.contrato, element.vigencia);


    if(evaluacion && evaluacion!=null){
      this.evaluacionCumplidosCrud.setEvaluacion(evaluacion); 
      this.router.navigate(['evaluacion-contrato']);
      return Promise.resolve(evaluacion)
     
    }else{
      return new Promise((resolve, reject) => {
        this.evaluacionCumplidosCrud
          .post('/evaluacion', solicitudCrearEvaluacion)
          .subscribe({
            next: (res: any) => {
              this.evaluacionCumplidosCrud.setEvaluacion(res.Data); 
              this.router.navigate(['evaluacion-contrato']);
              resolve(res.Data)
            },
            complete: () => {
              this.popUpManager.showSuccessAlert(
                'Evaluación creada correctamente'
              );
            },
            error: (error: any) => {
              this.popUpManager.showErrorAlert('Error al crear la evaluación');
            },
          });
      });
    }
  }
```

**Comment by JuanCamiloMartinezLopez** [comment]
@stevencol Buen trabajo.
