### ISSUE TITLE
Modificar y agregar funcionalidad desarrollada a la vista de visualización evaluación.

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#264]
Se requiere realizar modificaciones a la vista e implementar funcionalidad desarrollada.

**Sub Tareas**

- [x] Modificar la sección de items para manejar una tabla, como en la vista de gestión.
- [x] Tener en cuenta el rol en la evaluación para decidir qué secciones mostrar, el supervisor debe poder ver la información de los evaluadores registrados (estado de la asignación,  porcentaje de evaluacion, cargo, items etc)
- [x] Implementar el servicio #266.
- [x] Agregar botones según estados y roles:
- Firmar: botón para firmar cuando la evaluación se encuentre en estado: PRE
- Cargar evaluación en un cumplido: botón para cargar el soporte de evaluación a un cumplido en el estado de AEV para el rol de supervisor.

**Criterios de aceptación**

- [x] Vista modificada y funcionalidad del mid implementada.
- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
## *Avances*

-----

A la vista de visualizar evaluación se le agregan las siguientes funcionalidades:

- *Información general:* Se implementa el servicio para consultar y mostrar dinámicamente la información general de una evaluación.
- *Items evaluados:* Se reciben los datos de los items evaluados y se pintan utilizando el componente general tabla.
- *Observaciones:* Por cada evaluador que nos retorna el servicio del mid se leen sus observaciones y en caso de no estar vacías se muestran en la sección de observaciones.
- *Evaluadores:* Se ajusta esta sección para ahora mostrar tambien el porcentaje de evaluación, por el momento esta sección se muestra sin importar el rol, ya que si es un evaluador solo van a aparecer sus datos y en caso de ser supervisor aparecerán los datos de todos los evaluadores incluyéndolo a el, sin embargo, esto esta sujeto a cambios, puesto que de ser necesario se puede mostrar esta sección solo para el supervisor de la evaluación.

**Comment by faidercamilo26** [comment]
## *Prueba supervisor*

-----

![Image](https://github.com/user-attachments/assets/0efa2dc4-83bc-42f3-8359-232a3215d35f)

**Comment by faidercamilo26** [comment]
## *Prueba Evaluador*

![Image](https://github.com/user-attachments/assets/2b6f053a-6a01-452e-9da6-db8f473cc2cf)

**Comment by faidercamilo26** [comment]
## **Pendientes**

----

1. **Agregar validaciones y lógica según roles:**
   - Mostrar u ocultar secciones según el rol del usuario (supervisor, evaluador).
2. **Implementar los botones dinámicamente:**
   - Habilitar el botón de firmar en estado `PRE`.
   - Habilitar el botón de cargar evaluación en estado `AEV` para supervisores.

**Comment by faidercamilo26** [comment]
## *Finalización*

- Se agrega la sección de resultado evaluación.
- Se agrega la configuración para que aparezcan los botones de firmar y subir evaluación dependiendo del estado de la evaluación y el rol.

**Comment by faidercamilo26** [comment]
## *Ejemplo 1*

--------

### *Rol: Supervisor; Estado Evaluación: Aprobado evaluadores*

![Image](https://github.com/user-attachments/assets/51108ad2-9ff9-4069-8dfb-8d604ac818c9)

**Comment by faidercamilo26** [comment]
## *Ejemplo 2*

--------

### *Rol: Evaluador; Estado Evaluación: Pendiente Revisión Evaluadores*

![Image](https://github.com/user-attachments/assets/558f00b0-f65c-45de-8f13-813a5d168617)

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 Buen trabajo.
