### ISSUE TITLE
Resolver conflictos modulo de evaluacion - microcliente

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#267]
Se requiere realizar los ajustes necesarios para solucionar los errores en el despliegue del micro cliente de la rama develop

**Sub Tareas**

- [x] Revisar [consola](https://hubci.portaloas.udistrital.edu.co/udistrital/revision_cumplidos_proveedores_mf/123/1/3) de errores en el build.
- [x] Validar el correcto funcionamiento de las vistas de evaluación y del micro cliente en general.

**Criterios de aceptación**

- [x] microcliente en develop estable.
- [x] issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
Se evidencia que el inconveniente se debía a que el componente `EvaluadoresComponent` se encontraba mal importado en el documento `app.module.ts` lo que hacia que fallaran todos los componentes internos que usaba este modulo.

![Image](https://github.com/user-attachments/assets/9673bc55-f6f1-453e-b4f1-7944fb7097e1)

**Comment by faidercamilo26** [comment]
## *Resolucion conflictos*

- Se evidencia que aún persistía un conflicto, puesto que habían dos componentes llamados `EvaluadoresComponent` por este motivo en el documento `app-module.ts` solo se estaba importando uno de los dos componentes y el otro estaba fallando, se le cambia el nombre a uno de los dos componentes y se resuelve dicho inconveniente.

**Comment by faidercamilo26** [comment]
## *Gestión Evaluadores*

------

![Image](https://github.com/user-attachments/assets/3645a71c-5fab-46a4-8190-fddba3ed8c24)

**Comment by faidercamilo26** [comment]
## *Evaluación Contrato*

-----

![Image](https://github.com/user-attachments/assets/30c3291b-221a-443c-9ee0-a7c5fa84e7c9)

**Comment by faidercamilo26** [comment]
## *Listar Contratos Evaluar*

-------

![Image](https://github.com/user-attachments/assets/42f6cba3-071e-4fa5-a4b5-f342ce2c8e6a)

**Comment by faidercamilo26** [comment]
## *Visualizar Evaluación Contrato*

------

![Image](https://github.com/user-attachments/assets/031f8da8-a63c-4aa2-bc4c-9e15a5efadd0)

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 Buen trabajo.
