### ISSUE TITLE
Investigación alternativa a gofpdf y excelize

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#268]
Se requiere realizar una investigación sobre otro paquete que permita solucionar los inconvenientes encontrados en la issue #256 

**Sub Tareas**

- [x] Investigar y documentar alternativas a gofpdf para convertir el excel generado por excelize a pdf.
- [x] Realizar pruebas sencillas de las alternativas.

**Criterios de aceptación**

- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
## *Finalización*

Se realiza la investigación sobre las posibles herramientas o librerías que se pueden utilizar, en la investigacion aparecen los siguientes resultados: 
   - libreria `"github.com/tealeg/xlsx"`
 Se realiza el siguiente código de prueba pero esta librería no lee bien los estilos avanzados de excel por eso, al intentar convertir la platilla sin estilos solo genera hojas en blanco

```go
excelFilePath := "static/plantilla/plantilla.xlsx"
	//pdfFilePath := fmt.Sprintf("static/documento/evaluacion_%s.pdf", informacion_evaluacion.EmpresaProveedor)

	xlFile, err := xlsx.OpenFile(excelFilePath)
	if err != nil {
		outputError = fmt.Errorf("No se pudo abrir el archivo Excel: %v", err)
	}

	pdf := gofpdf.New("P", "mm", "A4", "")

	pdf.SetFont("Arial", "", 12)

	x := 50.0
	y := 50.0
	cellWidth := 100.0
	cellHeight := 20.0

	// Iterar por cada hoja en el archivo Excel
	for _, sheet := range xlFile.Sheets {
		// Escribir el nombre de la hoja
		sheetName := "GC-PR-006-FR-028"
		pdf.SetY(y)
		pdf.SetX(x)
		pdf.CellFormat(cellWidth, cellHeight, fmt.Sprintf("Hoja: %s", sheetName), "", 0, "L", false, 0, "")
		y += cellHeight

		// Iterar por las filas de la hoja
		for _, row := range sheet.Rows {
			pdf.SetX(x) // Resetear posición X al inicio de cada fila
			for _, cell := range row.Cells {
				// Leer el valor de la celda
				text := cell.String()

				// Escribir el contenido de la celda en el PDF
				pdf.CellFormat(cellWidth, cellHeight, text, "", 0, "L", false, 0, "")

				// Mover posición X a la derecha
				pdf.SetX(pdf.GetX() + cellWidth)
			}
			// Mover posición Y hacia abajo para la siguiente fila
			y += cellHeight
			pdf.SetY(y)
		}

		// Salto de página después de cada hoja
		pdf.AddPage()
		y = 50.0 // Reiniciar posición Y
	}
```

![Image](https://github.com/user-attachments/assets/ede784b6-19d3-4595-9106-30c6754ebd1f)

   - *Aspose.Cells for Go*
Esta opción mas que una librería es un API de un tercero, por eso no se considera esta opción, puesto que se dependería de un api de terceros, que si falla en algun momento tumbaría el sistema.
- *ConvertAPI*
Como su nombre lo explica es un api para convertir entre formatos pero tiene el mismo inconveniente que la opcion anterior.
- *Stackoverflow*
Tambien se busca en el portal de ayuda Stackoverflow pero no aparece ninguna alternativa.

![Image](https://github.com/user-attachments/assets/cd66adec-99bc-407d-ada0-c5955199b558)

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 Buen trabajo.
