### ISSUE TITLE
Crear las transacciones para el CRUD - Evaluación Proveedores. 

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#270]
Se requiere realizar la creación de transacciones que faciliten la creación de evaluacion, asignaciones etc

**Sub Tareas**

- [x] Crear una transacción para la creación de una asignación_evaluador, con su rol (evaluador o supervisor), y con el asignacion_evaluacion_estado inicial.
- [x] Crear una transacción para la creación de una evaluación con su estado inicial.

**Criterios de aceptación**

- [x] Transacciones realizadas.
- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
## Finalización

-------

- Se crea la transacción para crear una nueva evaluación con su estado inicial `Gestión`.

### *Estructura para crear la transacción*

```go
type SolicitudEvaluacion struct {
	ContratoSuscritoId int
	VigenciaContrato   int
}
```
- Se crea la transacción para crear una nueva asignación evaluador con su estado inicial `Evaluación Asignada` y también se tiene en cuenta el Rol del evaluador.

### *Estructura para crear la transacción*

```go
type SolicitudAsignacionEvaluador struct {
	EvaluacionId           int
	PersonaId              string
	Cargo                  string
	PorcentajeEvaluacion   float64
	RolAsignacionEvaluador string
}
```

**Comment by faidercamilo26** [comment]
## *Prueba transacción Evaluación*

---------
### *Evaluación Creada*

![Image](https://github.com/user-attachments/assets/325faec8-1bca-4a90-acf9-2718f2bdd404)

### *Estado Evaluación*

![Image](https://github.com/user-attachments/assets/4e398670-c02f-4a8c-8191-7103bcc24ad6)

**Comment by faidercamilo26** [comment]
## *Prueba transacción Asignación Evaluador*

---------
### *Asignación Evaluador Creada*

```json
{
    "Data": {
        "Id": 10,
        "EvaluacionId": {
            "Id": 9,
            "ContratoSuscritoId": 0,
            "VigenciaContrato": 0,
            "Activo": false,
            "DocumentoId": 0,
            "FechaCreacion": "0001-01-01T00:00:00Z",
            "FechaModificacion": "0001-01-01T00:00:00Z"
        },
        "PersonaId": "79777053",
        "Cargo": "Supervisor Contrato y evaluación",
        "PorcentajeEvaluacion": 0.5,
        "RolAsignacionEvaluadorId": {
            "Id": 2,
            "Nombre": "",
            "Descripcion": "",
            "CodigoAbreviacion": "",
            "Activo": false
        },
        "Activo": true,
        "FechaCreacion": "2024-12-16T16:35:49.781450597-05:00",
        "FechaModificacion": "2024-12-16T16:35:49.781452451-05:00"
    },
    "Message": "Request created successfully",
    "Status": "201",
    "Success": true
}
```

### *Rol evaluador con id 2*

![Image](https://github.com/user-attachments/assets/7c56fa14-98fd-4be2-a1db-741aa377c1a8)


### *Cambio estado asignación evaluador*

```json
{
    "Data": [
        {
            "Id": 1,
            "EstadoAsignacionEvaluadorId": {
                "Id": 1,
                "Nombre": "",
                "CodigoAbreviacion": "",
                "Descripcion": "",
                "Activo": false
            },
            "AsignacionEvaluadorId": {
                "Id": 10,
                "EvaluacionId": null,
                "PersonaId": "",
                "Cargo": "",
                "PorcentajeEvaluacion": 0,
                "RolAsignacionEvaluadorId": null,
                "Activo": false,
                "FechaCreacion": "0001-01-01T00:00:00Z",
                "FechaModificacion": "0001-01-01T00:00:00Z"
            },
            "Activo": true,
            "FechaCreacion": "2024-12-16T11:35:49.787665-05:00",
            "FechaModificacion": "2024-12-16T11:35:49.787667-05:00"
        }
    ],
    "Message": "Request successful",
    "Status": "200",
    "Success": true
}
```

### *estado asignación evaluador 1*

```json
{
    "Data": [
        {
            "Id": 1,
            "Nombre": "Evaluación Asignada",
            "CodigoAbreviacion": "EAG",
            "Descripcion": "Estado que indica que la evaluación fue asignada al evaluador o supervisor.",
            "Activo": true
        }
    ],
    "Message": "Request successful",
    "Status": "200",
    "Success": true
}
```

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 Buen trabajo.
