### ISSUE TITLE
Integración completa de la funcionalidad modulo de evaluacion.

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#274]
Se requiere realizar la implementación y ajustes necesarios para la funcionalidades y vistas desarrolladas.

**Sub Tareas**

- [x] Implementar las transacciones creadas en las issues #270 para la vista de gestión y lista de contratos en los respectivos servicios.
- [x] Probar la integración entre las vistas con observables.

**Criterios de aceptación**

- [x] Funcionalidad ajustadas.
- [x] Vistas correctamente integradas.
- [x] issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
## *Avances*

----

Se agrega la funcionalidad completa de la vista `listar-contratos-evaluar` con las siguientes particularidades:

- Apenas se carga la vista se llenan en la tabla los datos de los contratos en los que ya tiene asignada una evaluación sea como evaluador o supervisor y también los contratos a los que les puede crear una evaluación.
- Para cada contrato aparecen los botones de acción, con las siguientes características:
   - *Botón de realizar evaluación:* Este botón va a aparecer tanto para los supervisores de la evaluación como para los 
     evaluadores. Si ya se realizó la evaluación le va a aparecer un popUp indicando que la evaluación ya fue realizada y dándole la opción de visualizar la evaluación. En caso de que no haya realizado la evaluación lo redirige a la vista 
     `evaluacion-contrato`.

      ![Image](https://github.com/user-attachments/assets/11cba8d6-a059-4759-896f-9272858b2153)
   - *Botón de visualizar evaluación:* Esta opción aparece para todos los evaluadores sin importar si ya realizaron o no la 
       evaluación, en caso de que todavía no la haya realizado, le aparecerá al user una alerta para indicándole que no se ha realizado la evaluación y preguntándole si desea realizarla en el momento.

        ![Image](https://github.com/user-attachments/assets/27ca2f05-b9b9-4249-a5bb-2d1cc941f772)
    -*Botón de gestionar evaluación:* Este botón solo aparece para los contratos que estan en estado `GNT` y que el evaluador tiene rol de supervisor. También aparece cuando el contrato no tiene evaluación creada.

      Si el contrato no tiene una evaluación creada se crea utilizando la transacción y se redirige a la vista `gestion-evaluación`
      En caso de que el contrato ya tenga una evaluación creada se redirige a la vista `gestion-evaluación` y en esa vista se carga la información actual de la evaluación.

**Comment by faidercamilo26** [comment]
## *Finalización:*

Se termina de integrar las funcionalidades con las vistas correspondientes, teniendo en cuenta las siguientes particularidades:

- En esta vista se visualizan las asignaciones de un evaluador, si el evaluador tiene el rol `EV` y la evaluación esta en estado `GNT` lo que quiere decir que el supervisor la esta gestionando no aparecen los botones de realizar evaluación ni el de visualizarla, puesto que en este estado no se puede realizar la evaluación y tampoco hay evaluación a visualizar. 
- Cuando el rol es `SP` y aparece la opción de gestionar la evaluación, si esta no se ha creado, le aparece un popUp al supervisor para que seleccione si quiere crear la evaluación.

 ![Image](https://github.com/user-attachments/assets/40773f4f-76ec-4276-843c-c199d4e52591)

![Image](https://github.com/user-attachments/assets/a9b1a1ad-2d33-4554-b3f8-caa9bdd9bc54)


- Al ingresar al dar click item del lápiz se ingresa a la opción de realizar la evaluación, funcionalidad que se esta trabajando desde la issue #277 
- Al darle click a la opción del ojo, si no se ha realizado la evaluación aparecerá un popUp indicando que no se ha realizado la evaluación y da la opción de realizarla, en caso de que ya se haya realizado redirige a la vista de visualizar la evaluación.

![Image](https://github.com/user-attachments/assets/e000869f-3ff1-4a02-8e63-1876039228f3)

- Las vista de gestionar evaluación esta totalmente funcional, permitiendo agregar items a una evaluación, agregar evaluadores, y agregar items a un evaluador.
- La vista de visualizar evaluadores tambien tiene toda la funcionalidad la cual se implemento desde la issue #264 

![Image](https://github.com/user-attachments/assets/9fc48914-3878-4e95-b17a-3b020c973220)
![Image](https://github.com/user-attachments/assets/f4820d7e-dc26-4fdb-add7-cb1229408a80)
![Image](https://github.com/user-attachments/assets/44337466-8ef9-41d8-9a57-052d75590cc8)

**Comment by faidercamilo26** [comment]
## *Importante*

Se agrego persistencia a todo el modulo guardando la evaluación y la asignación evaluador que se esté trabajando en el momento en el session storage para que sea posible actualizar la pagina sin problemas y sin importar la vista en la que se encuentre se mantengan los datos.

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 Buen trabajo.
