### ISSUE TITLE
Realizar pruebas funcionales módulo de evaluación.

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#275]
Se requiere realizar pruebas funcionales del módulo de evaluación proveedores.

**Sub Tareas**

- [x] Realizar pruebas en el formato indicado.

**Criterios de aceptación**

- [x] Pruebas funcionales desarrolladas.
- [x] issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
## *Avances*

Para probar todo el flujo se realiza el merge de lo realizado en la issue #277 y en la #274. Sin embargo, estas dos ramas presentan varios conflictos los cuales se estan analizando para no eliminar codigo funcional para ninguna de las dos ramas.

![Image](https://github.com/user-attachments/assets/26f9cecb-4d2c-49ea-897f-66354001a73a)

**Comment by faidercamilo26** [comment]
## *Finalización*

------

Se realizaron las pruebas funcionales del modulo de evaluación proveedores y arrojo los siguientes resultados.

 | Hallazgo | Encontrado por  | Dependencia | Fecha        | Módulo                 | Formulario/Sección                   | Contexto                                                                                                                                                                                   | Ruta de ingreso                                                                                                          | PRUEBAS EN LOCAL | AMBIENTE DE PRUEBAS | Comportamiento esperado                                                                                                                                                                                                                                                             | Comportamiento actual                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    | Observaciones Adicionales |
| -------- | --------------- | ----------- | ------------ | ---------------------- | ------------------------------------ | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | ------------------------------------------------------------------------------------------------------------------------ | ---------------- | ------------------- | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | ------------------------- |
| 1        | Faider Trujillo | OAS         | diciembre 26 | Evaluación Proveedores | pages/listar-contratos-evaluar       | El evaluador puede ingresar a la vista correspondiente a visualizar las asignacones de evaluaciones que tiene activas y que pueda empezar a realizar o gestionar en caso de un supervisor. | [http://localhost:4200/pages/listar-contratos-evaluar](http://localhost:4200/pages/listar-contratos-evaluar)             | OK               |                     | <br><br>El sistema debe mostrar todas las asignaciones que tiene un evaluador disponibles para comenzar a evaluar o gestionar, las asignaciones en las cuales el supervisor no ha terminado la gestion no deberian aparecer. Tampoco deberian aparecer dos veces un mismo contrato. | <br><br>El sistema muestra todas las asignaciones sin importar si el supervisor ya termino de gestionar y configurar la evaluación. Aparecen asignaciones en las cuales no se pueden ni ver ni realizar ni ver la evaluación. Tambien hay contratos que aparecen dos veces.                                                                                                                                                                                                                                              |                           |
| 2        | Faider Trujillo | OAS         | diciembre 26 | Evaluación Proveedores | pages/listar-contratos-evaluar       | El evaluador puede realizar la evaluación en caso de no haberla realizado anteriormente.                                                                                                   | [http://localhost:4200/pages/listar-contratos-evaluar](http://localhost:4200/pages/listar-contratos-evaluar)             | OK               |                     | Si el usuario no ha realizado la evaluación el sistema lo debe dirigir a la vista para realizarla.                                                                                                                                                                                  | Si el usuario no ha realizado la evaluación el sistema lo redirige a la vista para realizarla.                                                                                                                                                                                                                                                                                                                                                                                                                           |                           |
| 3        | Faider Trujillo | OAS         | diciembre 26 | Evaluación Proveedores | pages/listar-contratos-evaluar       | El evaluador puede realizar la evaluación en caso de no haberla realizado anteriormente, en caso de haberla realizado anteriormente no debe permitirle realizarla nuevamente.              | [http://localhost:4200/pages/listar-contratos-evaluar](http://localhost:4200/pages/listar-contratos-evaluar)             | OK               |                     | Si el usuario ya realizo la evaluación el sistema debe indicarle que ya la realizo y darle la opcion de visualizar su evaluación.                                                                                                                                                   | Si el usuario ya realizo la evaluación el sistema le indica que ya la realizo y le brinda la opción de visualizar su evaluación.                                                                                                                                                                                                                                                                                                                                                                                         |                           |
| 4        | Faider Trujillo | OAS         | diciembre 26 | Evaluación Proveedores | pages/listar-contratos-evaluar       | El Evaluador puede ver la evaluación en caso de que ya la haya realizado.                                                                                                                  | [http://localhost:4200/pages/listar-contratos-evaluar](http://localhost:4200/pages/listar-contratos-evaluar)             | OK               |                     | Al seleccionar la opción de visualizar evaluación, si el evaluador ya la realizo debe redirigirlo a la vista de visualizar evaluacion.                                                                                                                                              | Al seleccionar la opción de visualizar evaluación, si el evaluador ya la realizolo redirige a la vista de visualizar evaluacion.                                                                                                                                                                                                                                                                                                                                                                                         |                           |
| 5        | Faider Trujillo | OAS         | diciembre 26 | Evaluación Proveedores | pages/listar-contratos-evaluar       | El Evaluador puede ver la evaluación en caso de que ya la haya realizado. En caso de que no la haya realizado no debe dejarlo visualizar una evaluación inexistente.                       | [http://localhost:4200/pages/listar-contratos-evaluar](http://localhost:4200/pages/listar-contratos-evaluar)             | OK               |                     | Al seleccionar la opción de visualizar evaluación, si el evaluador no la ha realizado debe indicarlo que esta no se ha realizado y darle la opción de realizarla.                                                                                                                   | Al seleccionar la opción de visualizar evaluación, si el evaluador no la ha realizado el sistema le indica que esta no se ha realizado y le brinda la opción de realizarla.                                                                                                                                                                                                                                                                                                                                              |                           |
| 6        | Faider Trujillo | OAS         | diciembre 26 | Evaluación Proveedores | pages/listar-contratos-evaluar       | Si el evaluador es un supervisor y ya ha creado la evaluación de un contrato el sistema debe dirigirlo a gestionar la evaluación y cargar los datos del avance de esta.                    | [http://localhost:4200/pages/listar-contratos-evaluar](http://localhost:4200/pages/listar-contratos-evaluar)             | OK               |                     | Al seleccionar la opción de gestionar la evaluación, si esta ya se creo debe redirigirlo a la vista de gestion.                                                                                                                                                                     | Al seleccionar la opción de gestionar la evaluación, si esta ya se creo el sistema lo redirige a la vista de gestion.                                                                                                                                                                                                                                                                                                                                                                                                    |                           |
| 7        | Faider Trujillo | OAS         | diciembre 26 | Evaluación Proveedores | pages/listar-contratos-evaluar       | El evaluador puede gestionar una evaluación, asi esta no se haya creado.                                                                                                                   | [http://localhost:4200/pages/evaluacion-contrato](http://localhost:4200/pages/evaluacion-contrato)                       | OK               |                     | Si el supervisor selecciona la opción de gestionar evaluación y el contrato no tiene una evaluación creada el sistema le debe retornar una alerta indicandole que no hay una evaluacion creada y darle la opción de crearla.                                                        | Si el supervisor selecciona la opción de gestionar evaluación y el contrato no tiene una evaluación creada el sistema le retorna una alerta indicandole que no hay una evaluacion creada y le brinda la opción de crearla.                                                                                                                                                                                                                                                                                               |                           |
| 8        | Faider Trujillo | OAS         | diciembre 26 | Evaluación Proveedores | pages/evaluacion-contrato            | El evaluador puede ingresar a realizar la evaluacion correspondiente.                                                                                                                      | [http://localhost:4200/pages/listar-contratos-evaluar](http://localhost:4200/pages/listar-contratos-evaluar)             | OK               |                     | Cuando no se ha realizado la evaluación el evaluador puede ingresar a realizar la evaluación                                                                                                                                                                                        | Cuando no se ha realizado la evaluación el evaluador puede ingresar a realizar la evaluación                                                                                                                                                                                                                                                                                                                                                                                                                             |                           |
| 9        | Faider Trujillo | OAS         | diciembre 26 | Evaluación Proveedores | pages/evaluacion-contrato            | El evaludor al realizar la evaluacion debe poder ir viendo el valor asignado a cada pregunta.                                                                                              | [http://localhost:4200/pages/listar-contratos-evaluar](http://localhost:4200/pages/listar-contratos-evaluar)             | OK               |                     | Cuando el evaluador selecciona una opcion en una pregunta el valor asignado debe actualizarce para que el evaluador pueda ir viendo estos valores y se pase el body al mid para procesar la evaluación.                                                                             | El sistema permite seleccionar las distintas opciones en cada pregunta, sin embargo, no se actualizan los valores y al intentar enviar los datos al mid para guardar hay un error y no se realiza la peticion.                                                                                                                                                                                                                                                                                                           |                           |
| 10       | Faider Trujillo | OAS         | diciembre 26 | Evaluación Proveedores | pages/visualizar-evaluacion-contrato | Al visualizar la evaluación dependiendo del rol de la asignacion y el estado de la evaluación el ealuador tiene varias opciones.                                                           | [http://localhost:4200/pages/visualizar-evaluacion-contrato](http://localhost:4200/pages/visualizar-evaluacion-contrato) | OK               |                     | Cuando la evaluación esta en estado: evaluación en proceso solo le aparece la opcion de regresar a la vista anterior.                                                                                                                                                               | Cuando la evaluación esta en estado: evaluación en proceso solo le aparece la opcion de regresar a la vista anterior.                                                                                                                                                                                                                                                                                                                                                                                                    |                           |
| 11       | Faider Trujillo | OAS         | diciembre 26 | Evaluación Proveedores | pages/visualizar-evaluacion-contrato | Al visualizar la evaluación dependiendo del rol de la asignacion y el estado de la evaluación el ealuador tiene varias opciones.                                                           | [http://localhost:4200/pages/visualizar-evaluacion-contrato](http://localhost:4200/pages/visualizar-evaluacion-contrato) | OK               |                     | Cuando la evaluación esta en estado: pendiente revision evaluadores le aparece la opcion de regresar a la pantalla anterior, firmar y de descargar la evaluación.                                                                                                                   | Cuando la evaluación esta en estado: pendiente revision evaluadores le aparece la opcion de regresar a la pantalla anterior, firmar y de descargar la evaluación.                                                                                                                                                                                                                                                                                                                                                        |                           |
| 12       | Faider Trujillo | OAS         | diciembre 26 | Evaluación Proveedores | pages/evaluacion-contrato            | Al visualizar la evaluación dependiendo del rol de la asignacion y el estado de la evaluación el ealuador tiene varias opciones.                                                           | [http://localhost:4200/pages/visualizar-evaluacion-contrato](http://localhost:4200/pages/visualizar-evaluacion-contrato) | OK               |                     | Cuando el evaluador no es un supervisor y la evaluación esta en estado aprobado evaluadores le va a aparecer la opción de descargar evaluación y regresar a la vista anterior.                                                                                                      | Cuando el evaluador no es un supervisor y la evaluación esta en estado aprobado evaluadores le va a aparecer la opción de descargar evaluación y regresar a la vista anterior.                                                                                                                                                                                                                                                                                                                                           |                           |
| 13       | Faider Trujillo | OAS         | diciembre 26 | Evaluación Proveedores | pages/evaluacion-contrato            | Al visualizar la evaluación dependiendo del rol de la asignacion y el estado de la evaluación el ealuador tiene varias opciones.                                                           | [http://localhost:4200/pages/visualizar-evaluacion-contrato](http://localhost:4200/pages/visualizar-evaluacion-contrato) | OK               |                     | Cuando el evaluador es un supervisor y la evaluación esta en estado aprobado evaluadores le va a aparecer la opción de descargar evaluación, cargar la evaluación a un cumplido y regresar a la vista anterior.                                                                     | Cuando el evaluador es un supervisor y la evaluación esta en estado aprobado evaluadores le va a aparecer la opción de descargar evaluación, cargar la evaluación a un cumplido y regresar a la vista anterior.                                                                                                                                                                                                                                                                                                          |                           |
| 14       | Faider Trujillo | OAS         | diciembre 26 | Evaluación Proveedores | pages/gestion-evaluadores            | El supervisor al gestionar la evaluación puede agregar items individualmente, cargarlos desde un excel, agregar evaluadores a una evaluacion y asignar items a cada evaluador.             | [http://localhost:4200/pages/gestion-evaluadores](http://localhost:4200/pages/gestion-evaluadores)                       | OK               |                     | El supervisor puede agregar uno por uno los items a evaluar en la evaluación.                                                                                                                                                                                                       | El supervisor puede agregar uno por uno los items a evaluar en la evaluación.                                                                                                                                                                                                                                                                                                                                                                                                                                            |                           |
| 15       | Faider Trujillo | OAS         | diciembre 26 | Evaluación Proveedores | pages/gestion-evaluadores            | El supervisor al gestionar la evaluación puede agregar items individualmente, cargarlos desde un excel, agregar evaluadores a una evaluacion y asignar items a cada evaluador.             | [http://localhost:4200/pages/gestion-evaluadores](http://localhost:4200/pages/gestion-evaluadores)                       | OK               |                     | El supervisor puede descargar la plantilla para subir varios items desde un excel                                                                                                                                                                                                   | al darle en el boton de descargar plantilla no sucede nada.                                                                                                                                                                                                                                                                                                                                                                                                                                                              |                           |
| 16       | Faider Trujillo | OAS         | diciembre 26 | Evaluación Proveedores | pages/gestion-evaluadores            | El supervisor al gestionar la evaluación puede agregar items individualmente, cargarlos desde un excel, agregar evaluadores a una evaluacion y asignar items a cada evaluador.             | [http://localhost:4200/pages/gestion-evaluadores](http://localhost:4200/pages/gestion-evaluadores)                       | OK               |                     | El supervisor puede agregar varios items masivamente desde un excel, usando una plantilla prediseñada.                                                                                                                                                                              | Si ya hay items guardados en la tabla, al guardar items masivamente mediante el excel la tabla se desborda y no se maneja la paginacion, aparecen items que no se cargaron en el excel, y al eliminar el primero de esos items se eliminan los demas y se arregla la tabla. En algunos items no se guardando correctamente el tipo de necesidad y estos items no se estan guardando en base de datos. En el excel se guardaron 19 items mas el que se agrego manualmente deberian haber 20 pero aparecen 96 en la tabla. |                           |
| 17       | Faider Trujillo | OAS         | diciembre 26 | Evaluación Proveedores | pages/gestion-evaluadores            | El supervisor al gestionar la evaluación puede agregar items individualmente, cargarlos desde un excel, agregar evaluadores a una evaluacion y asignar items a cada evaluador.             | [http://localhost:4200/pages/gestion-evaluadores](http://localhost:4200/pages/gestion-evaluadores)                       | OK               |                     | El supervisor puede agregar, editar o eliminar evaluadores y asignarles items que estan asignados a la evaluación.                                                                                                                                                                  | El supervisor puede agregar, editar o eliminar evaluadores y asignarles items que estan asignados a la evaluación.                                                                                                                                                                                                                                                                                                                                                                                                       |                           |

**Comment by faidercamilo26** [comment]
# 🛑 Pruebas Funcionales Fallidas

| **ID** | **Nombre**          | **Dependencia** | **Fecha**       | **Modulo**               | **Vista**                           | **Descripción**                                                                                                                                                        | **URL**                                                   | **Resultado** | **Esperado**                                                                                                                                                             | **Real**                                                                                                                                                                  |
|--------|----------------------|-----------------|-----------------|--------------------------|-------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------|---------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 1      | Faider Trujillo      | OAS             | diciembre 26    | Evaluación Proveedores  | pages/listar-contratos-evaluar     | El evaluador puede ingresar a la vista correspondiente para visualizar las asignaciones de evaluaciones activas y comenzar a gestionarlas en caso de ser supervisor. | [http://localhost:4200/pages/listar-contratos-evaluar](http://localhost:4200/pages/listar-contratos-evaluar) | ❌            | El sistema debe mostrar todas las asignaciones disponibles para el evaluador. No deberían aparecer asignaciones no gestionadas ni duplicadas.                          | El sistema muestra todas las asignaciones sin importar si el supervisor terminó la gestión. Aparecen asignaciones que no permiten evaluación y contratos duplicados.     |
| 9      | Faider Trujillo      | OAS             | diciembre 26    | Evaluación Proveedores  | pages/evaluacion-contrato          | El evaluador, al realizar la evaluación, debe poder ir viendo el valor asignado a cada pregunta.                                                                    | [http://localhost:4200/pages/listar-contratos-evaluar](http://localhost:4200/pages/listar-contratos-evaluar) | ❌            | Cuando el evaluador selecciona una opción en una pregunta, el valor asignado debe actualizarse y el body debe enviarse al MID para procesar la evaluación.              | El sistema permite seleccionar opciones en cada pregunta, pero no actualiza los valores, y al intentar enviar los datos al MID para guardar, no se realiza la petición.  |
| 15     | Faider Trujillo      | OAS             | diciembre 26    | Evaluación Proveedores  | pages/gestion-evaluadores          | El supervisor, al gestionar la evaluación, puede agregar ítems individualmente, cargarlos desde un Excel, agregar evaluadores a una evaluación y asignar ítems.     | [http://localhost:4200/pages/gestion-evaluadores](http://localhost:4200/pages/gestion-evaluadores)         | ❌            | El supervisor puede descargar la plantilla para subir varios ítems desde un Excel.                                                                                     | Al darle al botón de descargar plantilla, no sucede nada.                                                                                                               |
| 16     | Faider Trujillo      | OAS             | diciembre 26    | Evaluación Proveedores  | pages/gestion-evaluadores          | El supervisor, al gestionar la evaluación, puede agregar ítems individualmente, cargarlos desde un Excel, agregar evaluadores a una evaluación y asignar ítems.     | [http://localhost:4200/pages/gestion-evaluadores](http://localhost:4200/pages/gestion-evaluadores)         | ❌            | El supervisor puede agregar varios ítems masivamente desde un Excel, usando una plantilla prediseñada.                                                                | Si hay ítems guardados en la tabla, al guardar masivamente desde el Excel, la tabla se desborda, no se maneja la paginación, y aparecen ítems no cargados en el Excel.   |

**Comment by faidercamilo26** [comment]
Se suben las [pruebas funcionales](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EUJHI0QyCR1NkZyzV6sGXOwBCQlX7MwtcTm8N4dKhNPxAw?e=WaWLyq) a la carpeta del proyecto.

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 Buen trabajo.
