### ISSUE TITLE
Agregar funcionalidad desarrollada a la vista de evaluacion contrato proveedor

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#277]
Se requiere realizar la implementación del servicio para guardar la evaluación de un evaluador asignado a la vista desarrollada #196

**Sub Tareas**

- [x] Validar los estados de la asignación y evaluación para permitir enviar el resultado.

**Criterios de aceptación**

- [x] Vista con funcionalidad implementada.
- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by JuanCamiloMartinezLopez** [comment]
@stevencol por favor realizar documentación.

**Comment by stevencol** [comment]
Se da inicio con la actividad , modificando la estructura del el arreglo de pregunta para que concuerde con la petición al guardar la evaluación,  , de igual manera como el formulario  es  dinámico se modifica su estructura  para que la respuesta pueda ser asignada 

- El formulario queda de la siguiente manera 
``` JavaScript
 constructor(private fb: FormBuilder,private popUpManager: PopUpManager) {

    
    const controls = this.listaPreguntas.flatMap(item =>
      item.preguntas.map((pregunta) => this.fb.group({
        Categoria: item.elemento, 
        Titulo: pregunta.titulo, 
        Respuesta:  this.fb.group({  
          Pregunta: pregunta.pregunta,
          Cumplimiento: ['' ,Validators.required], 
          ValorAsignado: pregunta.valorAsignado
        })
      }))
    );
  
  
    
    this.evaluacion = this.fb.group({
      respuestas: this.fb.array(controls),  
      observaciones: ['', [Validators.required]],
    });
  
    
    const respuestas = this.evaluacion.get('respuestas') as FormArray;
    respuestas.valueChanges.subscribe(() => {
      this.porcentaje = this.sumarPorcentajes();
    });
  }
```
 + Ajustándose a la petición creada en el mid 

- El valor de "Cumplimiento" se optiene con el metodo :
``` JavaScript

    getCumplimiento(index: number): FormControl {
      const respuestas = this.evaluacion.get('respuestas') as FormArray;
      
      const respuestaGroup = respuestas.at(index).get('Respuesta') as FormGroup;
      const cumplimiento = respuestaGroup.get('Cumplimiento') as FormControl;
    
      if (cumplimiento) {
        return cumplimiento;
      } else {
        throw new Error('El campo "Cumplimiento" no es un FormControl');
      }
    }
  
```

y en el html -

``` Html

 <mat-form-field class="mat-form-field">
                            <mat-select [formControl]="getCumplimiento(i)" placeholder="Seleccione una opción">
                              <mat-option value="" disabled>Seleccione una opción</mat-option>
                              <mat-option value="Si">Si</mat-option>
                              <mat-option value="No">No</mat-option>
                            </mat-select>
                          </mat-form-field>
```

**Comment by stevencol** [comment]
Se ha se seguido con la funcionalidad , pero a  ser un formulario dinámico , se  tiene inconvenientes al asignar el index a cada pregunta ya que al generar cada  mat-accordion  genera nuevos índex , por lo que hace imposible su asignacion
![Animation](https://github.com/user-attachments/assets/607e3d7f-80f3-4be3-bd63-ebbe14678cb8)

**Comment by stevencol** [comment]
Se logra avanzar en la actividad :

![Animation](https://github.com/user-attachments/assets/1deff14e-a353-4edd-a541-6b05837268ee)

**Comment by stevencol** [comment]
![Animation](https://github.com/user-attachments/assets/ae201e39-37fd-4e80-9662-100592f7ccd1)

**Comment by JuanCamiloMartinezLopez** [comment]
@stevencol Buen trabajo.
