### ISSUE TITLE
Realizar cambios solicitados al modulo de revisión cumplido proveedores.

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#278]
Se requiere realizar los cambios solicitados al módulo de revisión cumplidos proveedores 

**Sub Tareas**

- [x] Cambiar la fuente para que sea la misma que en cumplidos CPS (Helvetica Neue).
- [x] Modificar valores mostrados en select del proveedor (ej: "nit - (nombre_proveedor)")

**Criterios de aceptación**

- [x] Cambios realizados.
- [x] issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by stevencol** [comment]
- Se inicia con activida cambiando la fuente a  la solicitada:
-

**Comment by stevencol** [comment]
- Se inicia con la actividad cambiando la fuente a la solicitada:

La fuente alteró los textos donde se usaba `font-weight: bold;` de la siguiente manera: 
![image](https://github.com/user-attachments/assets/446fce6b-e2d1-4cbc-a0b1-c0cbb5d45962)

Por lo que se deshabilitó en todos los textos posibles.

Después de deshabilitar queda de la siguiente en manera:  

![image](https://github.com/user-attachments/assets/a1f5dde9-8039-444b-91fa-824634c3af28)

**Comment by stevencol** [comment]
Se realizan ajustes faltantes , y se modifica el tamaño del select del proveedor con al finalidad de que el texto sea mas legible 

![image](https://github.com/user-attachments/assets/af7423b4-6554-455c-8943-d5431f09f3fe)

**Comment by JuanCamiloMartinezLopez** [comment]
@stevencol Buen trabajo.
