### ISSUE TITLE
Crear funcionalidad en cliente para crear el documento de evaluación proveedores con pdfmake - Parte I

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#279]
Se requiere realizar una función para generar el documento de evaluación en pdfmaker en el cliente de cumplidos proveedores.

**Sub Tareas**

- [x] Construir el [documento de evaluación](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EdZe7TCjtdZGil8LR_wBVqwB5IMNVcVaLGPKiI1nTnaXHQ?e=eRmpVw) con pdfmaker teniendo como ejemplo el [informe de gestión](https://github.com/udistrital/cumplidos_cliente/blob/develop/app/scripts/controllers/seguimientoycontrol/tecnico/informe_gestion_y_certificado_cumplimiento.js) desarrollado en cumplidos CPS.

**Criterios de aceptación**

- [x] Documento generado.
- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by mantnicot** [comment]
La falta de documentación no solo afecta la trazabilidad y el seguimiento, sino que además compromete la calidad y la eficiencia del equipo. Esto es inaceptable pues estamos comprometidos en la buena evidencia del trabajo. Toda tarea debe contar con sus avances y detalles claramente registrados; de lo contrario, no se considerará como completa o avanzada.

Favor seguir con la buena documentación que te resalta y se admira y no dejarte atrasar @stevencol

**Comment by stevencol** [comment]
Se Da inicio con actividad, iniciando creando el header: 
![image](https://github.com/user-attachments/assets/700c2de9-5d92-432d-a527-dfe451e6322e)

Se, cambia la posición del documento 

![image](https://github.com/user-attachments/assets/dbb8d5be-6a41-4dc7-9bb8-77031118be5c)


Se acomodan las imagenes:

![image](https://github.com/user-attachments/assets/69ff7279-c6e7-4e1f-ac15-34d455dcb0f4)

Se sigue avanzando con la creación del documento:

**Comment by stevencol** [comment]
![image](https://github.com/user-attachments/assets/be0f11dc-18a1-4e34-89d0-3ec7e928bb08)


![image](https://github.com/user-attachments/assets/99dcd5a0-ac6e-488c-a82f-5020d0e89e00)

![image](https://github.com/user-attachments/assets/a257430e-49aa-40fd-880f-3c1a8c0ceb15)

![image](https://github.com/user-attachments/assets/6c8fc021-9c6c-4e99-a4a2-991af0e9d694)

![image](https://github.com/user-attachments/assets/8d4c9ea5-9cfc-42a5-9f8f-b8d7a3b2f292)

![image](https://github.com/user-attachments/assets/ee569f36-908a-4ff1-a99e-85f0a18bd08b)

![image](https://github.com/user-attachments/assets/fa80eeac-19a5-4d9b-bb27-3916be3e199a)

![image](https://github.com/user-attachments/assets/af52ed64-cd00-43bb-a709-0082fdfb445a)

![image](https://github.com/user-attachments/assets/6bb1310a-48b5-46ee-a9b8-38b6586339b4)

![image](https://github.com/user-attachments/assets/49a395ef-186d-4650-9562-24e401b0d059)

![image](https://github.com/user-attachments/assets/bbf33fe6-462f-4e89-994b-1a16c84f3d17)


![image](https://github.com/user-attachments/assets/387a5a0c-5436-434a-a001-d9c6351d6665)

![image](https://github.com/user-attachments/assets/a982859d-ca69-4eea-a3b9-f41dd458923c)

Ultimo avance : 

![image](https://github.com/user-attachments/assets/3c12014e-42f5-4b7c-a90b-5a6bc85ffcc0)

**Comment by stevencol** [comment]
Se  avanza con la creación del documento 
![Animation](https://github.com/user-attachments/assets/4002ef3f-dd04-4e1f-99e0-46c46f807a85)

**Comment by stevencol** [comment]
Se finaliza el documento quedando : 

![image](https://github.com/user-attachments/assets/cbf05b16-1bc4-404c-95f1-45a731824fbb)


Documento guia:
![image](https://github.com/user-attachments/assets/e4307064-8956-41dc-9fde-80529037e115)

**Comment by JuanCamiloMartinezLopez** [comment]
@stevencol Buen trabajo.
