### ISSUE TITLE
Actualización manuales e instructivos módulo históricos

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/Cumplidos_y_certificaciones_documentacion#28]
Se requiere realizar la actualización manuales e instructivos módulo históricos

**Sub Tareas**

- [x] Generar contacto con responsable de Manuales en funcionamiento
- [x] Levantar requerimientos de actualización
- [ ] Generar el requerimiento de actualización de Manuales
- [ ] Revisión de manuales generados

**Criterios de aceptación**

- [ ] Solicitud de creación o actualización de Manuales con responsable
- [ ] Manuales e instructivos actualizados

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico/SoSM.
- [ ] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se ha creado la reunión para la muestra del modulo para la creación de manuales , para el día 04/06/2024 02:00 pm 
[Enlace reunión](https://teams.microsoft.com/l/meetup-join/19%3ameeting_ZmNjYTZmYTItMjNkMC00MjZkLWEyNzYtMzkzZDk4ZTgzNmIy%40thread.v2/0?context=%7b%22Tid%22%3a%22d51388ef-6ab0-4363-9f94-d56644a45970%22%2c%22Oid%22%3a%221dd8bdce-0185-41b4-8caa-01da7e5506b2%22%7d)

**Comment by mantnicot** [comment]
Se han generado el manual de histórico de cumplidos

[Carpeta de manuales](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EpzDk5FVx6ROos2lr0y_flIBEnMervks4lUHE7rG0M8OtA?e=pvLI5w)

**Comment by jcmurilloa** [comment]
Excelente trabajo @mantnicot
