### ISSUE TITLE
Agregar tabla de items - vista evaluacion

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#280]
Se requiere agregar una tabla de ítems para la vista de evaluación.

**Sub Tareas**

- [x] Agregar una tabla con los ítems asignados a la evaluación.

**Criterios de aceptación**

- [x] Tabla con ítems de la asignación 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by stevencol** [comment]
- Se crea Método para la consulta de asignacion_evaluador_item:


``` JavaScript
 async consularItems(): Promise<Item[]> {
    return new Promise((resolve, reject) => {
      this.evaluacionCumplidosCrud
        .get(`/asignacion_evaluador_item?query=AsignacionEvaluadorId.Id:${41}`)
        .subscribe({
          next: (asignacion: any) => {
            this.listaItems = asignacion.Data.map((itemId: any) => {
              return {
                Id: itemId.ItemId.Id,
                EvaluacionId:  itemId.ItemId.EvaluacionId,
                Identificador: itemId.ItemId.Identificador,
                Nombre: itemId.ItemId.Nombre,
                ValorUnitario: itemId.ItemId.ValorUnitario,
                Iva: itemId.ItemId.Iva,
                FichaTecnica: itemId.ItemId.FichaTecnica,
                Unidad: itemId.ItemId.Unidad,
                Cantidad: itemId.ItemId.Cantidad,
                TipoNecesidad: this.obtenerTipoNecesisdad(itemId.ItemId.TipoNecesidad),
                Activo: itemId.ItemId.Activo,
                FechaCreacion: itemId.ItemId.FechaCreacion,
                FechaModificacion: itemId.ItemId.FechaModificacion,
              };
            });
            resolve(this.listaItems);
          },
        });
    });
  }

```
- Se crea método para Asignar   Tipo de Necesidad


``` JavaScript
  obtenerTipoNecesidad(tipoNecesidad: number): string {

    if (tipoNecesidad === 1) {
      return 'BIEN';
    } 
     if (tipoNecesidad === 2) {
      return 'SERVICIO';
    } 
    if (tipoNecesidad === 3) {
      return 'BIENES Y SERVICIOS';
    }
      return 'No definido';
    }
```

**Comment by stevencol** [comment]
Previsualizacion: 
![image](https://github.com/user-attachments/assets/b0e31ad1-0051-461c-8ae6-6e83848fe55c)

*La columna Ficha técnica se propone eliminación

**Comment by JuanCamiloMartinezLopez** [comment]
@stevencol Buen trabajo.
