### ISSUE TITLE
Implementar input filter en los select de la vista de históricos cumplidos proveedores.

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#284]
Se requiere implementar un input para poder filtrar entre las opciones en los selects del formulario de histórico cumplidos proveedores. 

**Sub Tareas**

- [x] implementar el input de filtro en todos los selects del formulario.

**Criterios de aceptación**

- [x] issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
# *Avances*
----------

Se investiga como se pueden agraegar inputs a los componentes `mat-select` de angular material, sin embargo, no se encuentra informacion sobre esto, por lo tanto lo que se decide hacer es agregar el input como primera opcion siempre, utilizando el siguiente codigo dentro de este componente 
```html
<div>
                      <input
                        matInput
                        placeholder="Filtrar dependencias"
                        [formControl]="filtroDependenciasControl"
                        (input)="applyDependenciasFilter()"
                      />
                    </div>
```

Se construyo la función applyDependenciasFilter() para reaccionar a cada cambio que ocurra en el input de filtrado(esto por el momento solo se esta probando con el input de dependencias). Tambien se crea el método `onDependenciasOpen()` para limpiar los filtros cada vez que se abra el select.

```typescript
applyDependenciasFilter(): void {
    this.filtroDependenciasControl.valueChanges.subscribe(value => {
      this.dependenciasFiltradas = this.listaDependencias.filter(dependencia =>
        dependencia.Nombre.toLowerCase().includes(value?.toLowerCase() || '')
      );
    });
  }


onDependenciasOpen(): void {
    this.filtroDependenciasControl.setValue('');
  }
```

Apenas se inicia la aplicación se asignan todos los datos de la dependencia a la lista `dependenciasFiltradas` y cada vez que se va escribiendo en el input se debería recibir este texto e ir actualizando la lista de las dependencias con el siguiente código.

```typescript
this.filtroDependenciasControl.valueChanges.subscribe(() => {
      this.applyDependenciasFilter();
    });
```
## *Inconvenientes*

Sin embargo, no esta funcionando de la manera que se espera, cuando se escribe texto aveces busca bien las coincidencias pero lo único que hace es sombrar el resultado en vez de ir filtrando la lista y en otras ocasiones ni siquiera toma bien las coincidencias.

**Comment by faidercamilo26** [comment]
# Finalización

-------

Segun la información brindada en el daily se busca la manera de implementar los inputs de filtrado para todos los inputs de la vista de históricos, se logra terminar la tarea con las siguientes caracteristicas:

- No es posible agregar la manera de escribir dentro de la cajita del select, por lo tanto lo que se hace, es que en cada select el primer campo sea el input para filtrar.
- Cuando se filtra cualquier en cualquiera de los inputs la lista del select se reduce solamente al dato o datos que cumplan con los filtros, por lo tanto, si anteriormente se habia seleccionado un dato que no cumpla con el nuevo filtro este se eliminara de la selección porque no pertenece a la lista actual. Para solucionar este inconveniente lo que se hace es no reducir la lista solamente a los datos que coincidan con el filtro, sino que siempre se van a mostrar todos los datos pero en primer lugar los datos que coincidan con el filtro que se esta buscando.

![Image](https://github.com/user-attachments/assets/c8d3be22-a317-49cf-843b-4034cc50e694)

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 Buen trabajo.
