### ISSUE TITLE
Implementar cambios al formato de certificaciones DVE

### ISSUE THREAD

**Issue by mantnicot** [udistrital/Cumplidos_y_certificaciones_documentacion#285]
Se requiere realizar la implementación de camnios al formato de certificaciones DVE

**Sub Tareas**

- [x] Revisión de requerimientos expuestas en las sesiones.
- [x] Actualizar la documentación con base a requerimientos.

**Criterios de aceptación**

- [x] Formatos actualizados y documentados.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by mantnicot** [comment]
Se actualizan los formatos de certificaciones DVE con los cambios de la columna , el orden descendente de fechas , la firma electrónica 

[Carpeta de documentos](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EvGgnV9ZzVJBvNKOo9uvOQMBXiOk6EeTr9cVIa0cqqNJAw?e=iA4fOj)

**Comment by jcmurilloa** [comment]
Muy buen trabajo @mantnicot
