### ISSUE TITLE
Realizar ajuste de error de carga de ítems

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#288]
Se requiere realizar el ajuste de la vista de gestión evaluación, la sección  de carga y visualización de items

**Sub Tareas**

- [x] Revisar las pruebas funcionales realizadas, [error 16](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/issues/275#issuecomment-2563372709)
- [x] Ajustar el servicio en el crud, mid y cliente para que la carga masiva funcione de forma correcta.

**Criterios de aceptación**

- [x] Vista funcionando.
- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
# *Finalización*

----

## *Errores mid*
Se puede evidenciar que parte del error se esta dando por los siguientes inconvenientes que tiene la función de cargar los items desde el mid:
- El método `CargaDataExcel()` solo estaba recibiendo el documento de excel pero no el id de la evaluación, en el código se tenia quemado el id de evaluación `1` y como este código tenía varias pruebas se cargaban todos esos ítems al hacer la petición.
- El metodo `ObternerUnidadMedida()` se supone que recibía el nombre de la unidad que se traia desde el documento y buscaba el id de esta, sin embargo este código estaba incompleto y no hacia nada.
### *Código anterior*
```go
func ObternerUnidadMedida(unidad string) (idUnidad *int, outputError error) {
	defer func() {
		if err := recover(); err != nil {
			outputError = fmt.Errorf("%v", err)
			panic(outputError.Error())
		}
	}()

	var unidadMedida []models.UnidadMedida

	if response, err := helpers.GetJsonWSO2Test(beego.AppConfig.String("UrlAdministrativaAmazonApi")+"/unidad", &unidadMedida); err == nil && response == 200 {
	}
	return nil, outputError
}
```
### *Código corregido*
```go
func ObternerUnidadMedida(unidad string) (idUnidad int, outputError error) {
	defer func() {
		if err := recover(); err != nil {
			outputError = fmt.Errorf("%v", err)
			panic(outputError.Error())
		}
	}()

	var unidadMedida []models.UnidadMedida

	if response, err := helpers.GetJsonWSO2Test(beego.AppConfig.String("UrlAdministrativaAmazonApi")+"/unidad", &unidadMedida); err != nil && response != 200 {
		outputError = fmt.Errorf("Error al obtener las unidades de medida")
		return 0, outputError
	}

	for _, unidadMedidaItem := range unidadMedida {
		if strings.ToLower(unidadMedidaItem.Unidad) == strings.ToLower(unidad) {
			return unidadMedidaItem.Id, nil
		}
	}
	return 0, outputError
}
```

- El método `obtenerTipoNecesidad()` está recuperando de forma incorrecta el tipo de necesidad, puesto que la comparación estaba mal hecha. Puesta que las palabras no son exactas a como se estan comparando y además lo recomendable es convertir las cadenas ya sea a mayúsculas o minúsculas para evitar errores por mayúsculas o minúsculas.

### *Código anterior*
```go
func obtenerTipoNecesidad(tipoNecesidad string) (idTipoNecesidad int) {
	if tipoNecesidad == "BIEN" {
		return 1
	}
	if tipoNecesidad == "SERVICIO" {
		return 2
	}
	if tipoNecesidad == "BIENES Y SERVICIOS" {
		return 3
	}
	return 0
}
```

### *Código corregido*
```go
func obtenerTipoNecesidad(tipoNecesidad string) (idTipoNecesidad int) {
	fmt.Println("Tipo necesidad: ", tipoNecesidad)
	if strings.ToLower(tipoNecesidad) == "bien" {
		fmt.Println("Bien")
		return 1
	}
	if strings.ToLower(tipoNecesidad) == "servicio" {
		fmt.Println("Servicio")
		return 2
	}
	if strings.ToLower(tipoNecesidad) == "bien/servicio" {
		fmt.Println("Bien y servicio")
		return 3
	}
	return 0
}
```

**Comment by faidercamilo26** [comment]
## *Errores cliente*

- Los únicos errores que presentaba el cliente es que en el componente `modal-cargar-items` no se estaba recuperando el la evaluación actual, tampoco, se le estaba pasando este dato al mid.
- Al igual que en el mid, se tenia quemado el id de evaluación 1.

**Comment by faidercamilo26** [comment]
# *Pruebas*

-------

*Evaluación Id:* 22
*Items de la evaluación antes de la prueba*


![Image](https://github.com/user-attachments/assets/3ea505b4-ac7f-407f-8cde-41f72e6413ab)


![Image](https://github.com/user-attachments/assets/0c305ce4-16c6-4681-857a-e735d324ed11)

*Items plantilla*

![Image](https://github.com/user-attachments/assets/900b9da8-39a9-4430-8a90-c59870406d5d)


*Prueba cargar items*

![Image](https://github.com/user-attachments/assets/41849461-74c8-4a3e-8571-e6340dea2661)

**Comment by faidercamilo26** [comment]
Se realiza una prueba final subiendo 14 items para validar que la paginación y el componente tabla no se este rompiendo y se puede apreciar que funciona correctamente.

![Image](https://github.com/user-attachments/assets/cf5e6e64-9fa8-4c8b-ac33-92868b4e4e6a)

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 Buen trabajo.
