### ISSUE TITLE
Concertar, desarrollar y levantar acta de sesión de muestra con cliente y funcionamiento

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/Cumplidos_y_certificaciones_documentacion#30]
Se requiere realizar la concertación, desarrollo y levantamiento acta acta de sesión de muestra con cliente y funcionamiento

**Sub Tareas**

- [x] Concertar reunión de requerimientos con el cliente y funcionamiento
- [x] Desarrollar la reunión exploratoria
- [x] Proyectar acta de la reunión

**Criterios de aceptación**

- [x] Acta revisada por el líder de proyecto
- [ ] Acta firmada por las partes con anexo de historias de usuario

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico/SoSM.
- [ ] Artefacto solicitado satisface la necesidad.

**Comment by jcmurilloa** [comment]
El acta cumple con lo requerido, pendiente colgar enlace de grabación en la issue.

**Comment by mantnicot** [comment]
Se adjunta el acta con las firmas correspondientes

[Acta firmada](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EY1wD61pvbVDgsqNzGRz-ZUB9iRSTi9Ls0YFT6RYJN6BaA?e=4uoqqk)

**Comment by jcmurilloa** [comment]
“El compromiso individual con un esfuerzo colectivo es lo que hace que un equipo, una empresa o una sociedad funcionen”. Vince Lombardi
