### ISSUE TITLE
Proyectar y socializar formato de historias de usuario con cliente y equipo

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/Cumplidos_y_certificaciones_documentacion#31]
Se requiere realizar la proyección y socialización del formato de historias de usuario con cliente y equipo

**Sub Tareas**

- [x] Proyección del formato de historias de usuario
- [x] Socialización del formato de historias de usuario con el cliente
- [x] Socialización del formato aprobado por el cliente con el equipo
- [x] Refinamiento y aprobación del formato por parte del equipo SoS

**Criterios de aceptación**

- [x] Formato de historia de usuario aprobado por los interesados
- [x] Formato de historia de usuario documentado

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se adjunto el acta firmada


[Acta firmada](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/ER9GcKf4hEdBi5a5rTb7KIMBTV1iR31WSGMHGR3HXimpMg?e=a9M5kV)

**Comment by jcmurilloa** [comment]
Por fin se logró la firma, buen trabajo!
