### ISSUE TITLE
Creación de vista para DVE

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#34]
Se requiere crear la vista del módulo de certificados DVE según el https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/issues/15 para los usuarios docente.

**Sub Tareas**

- [x] Desarrollar la vista según el mockup

**Criterios de aceptación**

- [ ] Issue documentada.
- [ ] Vista desarrollada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by stevencol** [comment]
corrige la ortografía :El error de permisos queda corregido, pero se genera un nuevo error, con el linting. con componentes creados y ya existentes.

![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/51761184/a3bc8287-cbd7-4dd3-b970-31dcf587ce78)
