### ISSUE TITLE
Revisar y solucionar problemas de las pruebas funcionales

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#35]
Se requiere realizar una revisión de los problemas encontrados en las [pruebas funcionales](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/issues/25)

**Sub Tareas**

- [x] Revisar los problemas encontrados en las pruebas funcionales.
- [x] Ajustar los servicios o el cliente para dar solución a los problemas.

**Criterios de aceptación**

- [ ] Pruebas funcionales exitosas.
- [ ] Problemas solucionados.
- [ ] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
Se solucionan todos los inconvenientes que se reportaron en las Pruebas funcionales, la mayoría ya se habían resuelto en la issue referenciada en la parte de arriba, principalmente en este caso se crea la función isDisableButton() para deshabilitar el botón de buscar cuando en la entrada de número de contratos o número de documentos se ingresa un valor invalido, cabe aclarar que un valor invalido es es principalmente cuando se finaliza con una "," en vez de poner otro número.

```JavaScript

self.isDisableButton = function() {
          if ((self.filtro.noContratos && self.filtro.noContratos.slice(-1) === ",") || (self.filtro.documentos && self.filtro.documentos.slice(-1) === ",")) {
            self.desabilitarBotonBusqueda = true;
          } else {
            self.desabilitarBotonBusqueda = false;
          }
        };

```

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 Buen trabajo

**Comment by faidercamilo26** [comment]
Se realizan unas actualizaciones en el documento y se sube a la carpeta del proyecto la versión 2 del documento de pruebas.

https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EaOq5Ok6m2lDvcb3usldmikB0lGttCKoPstgt7-Jt53b7g?e=8ToqCP
