### ISSUE TITLE
Agregar rol general para el módulo de históricos CPS

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#38]
Se requiere realizar los cambios requeridos para tener un rol de consulta general en el módulo de históricos CPS, este rol podrá revisar todas las dependencias nuevas y antiguas, así como ver los documentos y descargarlos.

**Sub Tareas**

- [ ] Realizar los cambios necesarios en los servicios del mid para este nuevo rol.
- [ ] Realizar los cambios necesarios en el cliente para el nuevo rol.
- [ ] Realizar registro del nuevo rol en el sistema de [configuraciones](https://pruebasconfiguracion.portaloas.udistrital.edu.co/).

**Criterios de aceptación**

- [ ] Módulo de históricos CPS funcional para el nuevo rol.
- [ ] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by stevencol** [comment]
Se inicia actividad

**Comment by stevencol** [comment]
Como parte inicial se crea método en el helper :

```go
func GetDependenciasRolGeneral() (dependenciasList []models.DependenciaSimple, errorOutput interface{}) {
	
	defer func() {

		if err := recover(); err != nil {
			errorOutput = map[string]interface{}{
				"Success": true,
				"Status":  502,
				"Message": "Error al consultar las dependencias:  para el rol general" ,
				"Error":   err,
			}
			panic(errorOutput)
		}
	}()
	println(beego.AppConfig.String("UrlcrudAgora")+"/dependencia_SIC/?limit=-1");
	var respuesta []interface{}
	if response, err := getJsonWSO2Test(beego.AppConfig.String("UrlcrudAgora")+"/dependencia_SIC/?limit=-1", &respuesta); (err == nil) && (response == 200) {
	
						for _, list := range respuesta {

							depMap := list.(map[string]interface{})
							dependencia := models.DependenciaSimple{

								Codigo: depMap["ESFCODIGODEP"].(string),
								Nombre: depMap["ESFDEPENCARGADA"].(string),
							}
							dependenciasList = append(dependenciasList, dependencia)
						}
				
		
	} else {
		
		return nil, errorOutput
	}
	if dependenciasList != nil {
		return dependenciasList, nil
	}

	return nil, nil
}

}
```
Con la finalidad de traer todas las dependencias 

y se implementa en el controlador 
``` go
// @Title GetDependenciasGeneral
// @Description get all  dependencies 
// @Success 200 {object} map[string]interface{} "Success"
// @Failure 404 {object} map[string]interface{} "Error"
// @router /dependenciasgen/
func (c *HistoricoCumplidos) GetDependenciasGeneral() {

	defer func() {
		if err := recover(); err != nil {
			logs.Error(err)
			localError := err.(map[string]interface{})
			c.Data["message"] = beego.AppConfig.String("appname") + "/dependencias/" + "/" + localError["funcion"].(string)
			c.Data["data"] = localError["err"]
			if status, ok := localError["status"]; ok {
				c.Abort(status.(string))
			} else {
				c.Abort("404")
			}
		}
	}()
	dependencias, err := helpers.GetDependenciasRolGeneral()

	if err != nil {
		panic(c.Data)
	} else if dependencias == nil {
		c.Data["json"] = map[string]interface{}{"Succes": true, "Status:": 204, "Message": "No hay datos en general", "Data": dependencias}
	} else {
		c.Data["json"] = map[string]interface{}{"Succes": true, "Status:": 200, "Message": "Consulta completa", "Data": dependencias}
	}
	c.ServeJSON()

}


```

**Comment by stevencol** [comment]
Se implementó una nueva consulta en el cliente, reemplazando el método anterior que consultaba por documento. Ahora, primero se realizará la consulta por rol para pruebas. Se utilizó el rol **"SUPERVISOR"** para estas pruebas, el cual será reemplazado por un rol más general que traerá todas las dependencias. En caso de que el usuario no tenga el rol específico, la consulta se realizará por documento.
![test](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/51761184/2662366c-5e7d-4886-856d-ac1f0804592c)

***Código nuevo***
```JavaScript
 self.getDependecias  = function(){
        
        let roles= self.playLoad.role;
       
        if(roles!=null && roles.includes("SUPERVISOR")){
        cumplidosMidRequest
          .get("historicos/dependencias_generales/")
          .then(function(response){
       self.dependencias= response.data.Data; 
          return self.dependencias;
          })
          .catch(function(error){
            console.error("Error al obtener dependencias:", error);
          });
        }
        else{
          cumplidosMidRequest
          .get("historicos/dependencias/" + self.playLoad.documento, "")
          .then(function (response) {
            let Ordenador = response.data.Data["Dependencias Ordenador"] || [];
            let Supervisor = response.data.Data["Dependencias Supervisor"] || [];
           self.dependencias=  Ordenador.concat(Supervisor);
            for (var i = 0; i < self.dependencias.length; i++) {
              self.dependenciaString += "'" + self.dependencias[i].Codigo + "'"; //
              if (i < self.dependencias.length - 1) {
                self.dependenciaString += ",";
              }
            }
            refreshSelectPicker();
          })
          .catch(function (error) {
            console.error("Error al obtener dependencias:", error);
          });
        }
        
      }
      self.getDependecias();

```
***Codigo anterior:***
```JavaScript
 self.dependencias = cumplidosMidRequest
        .get("historicos/dependencias/" + self.playLoad.documento, "")
        .then(function (response) {
          let Ordenador = response.data.Data["Dependencias Ordenador"] || [];
          let Supervisor = response.data.Data["Dependencias Supervisor"] || [];
          self.dependencias = Ordenador.concat(Supervisor);

          for (var i = 0; i < self.dependencias.length; i++) {
            self.dependenciaString += "'" + self.dependencias[i].Codigo + "'"; //
            if (i < self.dependencias.length - 1) {
              self.dependenciaString += ",";
            }
          }
          refreshSelectPicker();
        })
        .catch(function (error) {
          console.error("Error al obtener dependencias:", error);
        });
```
***Esta rama incluye últimos Cambios realizados en feature/correciones***

**Comment by JuanCamiloMartinezLopez** [comment]
@stevencol buen trabajo, se queda a la espera de la definición del nuevo rol con las indicaciones y/o lineamientos de funcionamiento

**Comment by JuanCamiloMartinezLopez** [comment]
Se crea el rol "CONTROL_INTERNO" para la revisión general en el modulo de históricos CPS, se le asigna al usuario pruebascps para revisión

**Comment by stevencol** [comment]
Se crea rol y se asginan los persmiso 
![image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/51761184/3e3a1795-3e7b-4b35-ae93-2bee24b11f44)

![image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/51761184/ddb9089a-a815-42c6-a1ce-687bc4e04618)

**Comment by JuanCamiloMartinezLopez** [comment]
@stevencol Buen trabajo
