### ISSUE TITLE
Reunión para la revisión del sistema de evaluaciones

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#39]
Se requiere realizar una reunión con el antiguo desarrollador del sistema evaluaciones para entender las peculiaridades del sistema y resolver las dudas encontradas

**Sub Tareas**

- [x] Presentar las dudas en la reunión.

**Criterios de aceptación**

- [x] Asistencia a la reunión.
- [x] Comentarios con las dudas y respuestas 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by stevencol** [comment]
Se realiza reunión, se logra saber el funcionamiento de TSLint y cómo solucionar el error que impedía realizar push.

**Comment by faidercamilo26** [comment]
En la reunión se pudieron aclarar dudas que se tenia sobre la estructura, tambien se pudonotar que los inconvenientes presentados en la [issue#33](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/issues/33) se debían principalmente a la versión, se utilizó la versión 14.0.0 para solucionarlos por recomendación de Ludwing.

**Comment by JuanCamiloMartinezLopez** [comment]
Link de la reunion 
https://udistritaleduco-my.sharepoint.com/:v:/g/personal/juacmartinezl_udistrital_edu_co/EeEWiFLH9opJpcwnVFZga0YBcR4Y6XShy81E196cL7Vr9Q?e=sCVnoA
