### ISSUE TITLE
Analisis y diseño de funcionalidades para el módulo de certificaciones DVE

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#40]
Se requiere realizar un análisis de los requerimientos, así como el diseño de posibles funciones en el mid para el módulo de certificados DVE

**Sub Tareas**

- [x] Revisar la lógica del negocio
- [x] Proponer las diferentes funciones requeridas en el mid para completar el módulo (inputs, outputs,etc)

**Criterios de aceptación**

- [x] Propuesta.
- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 por favor documentar

**Comment by faidercamilo26** [comment]
Se realiza la revisión de la grabación del dayli del día 29 de mayo donde se explicaron los mockups y las funcionales que se deben desarrollar, todo esto para tener una mejor claridad de las funcionalidades y así poder definir con mayor precisión las posibles funcionalidades a desarrollar en el mid.

**Comment by faidercamilo26** [comment]
Se realiza la propuesta de las funciones que se pueden desarrollar en el mid teniendo en cuenta los requerimientos funcionales, al no tener una clara visión de la manera en que estan conformadas las tablas de la base de datos se generan funciones generales. Puede que salgan mas funciones debido a que puede que una sola tabla no retorne toda la informacion que es necesaria en las funciones que se propusieron.

[Propuesta análisis de requerimientos.pdf](https://github.com/user-attachments/files/15783467/Propuesta.analisis.de.requerimientos.pdf)

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 Buen trabajo.
