### ISSUE TITLE
Investigar y actualizar el flujo de evaluacion de orden de compra

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/Cumplidos_y_certificaciones_documentacion#41]
Se requiere realizar la Investigación y actualización del flujo de evaluacion de orden de compra

**Sub Tareas**

- [x] Repasar diagrama de flujo actual del sistema
- [x] Generar las modificaciones según requerimientos del cliente
- [ ] Socializar con el equipo SOS el flujo actualizado

**Criterios de aceptación**

- [ ] Diagrama de flujo actualizado y socializado

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico/SoSM.
- [ ] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se ha creado el flujo de cumplidos pues es todo el proceso de evaluación en un documento que crea el supervisor para el flujo de cumplidos



![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/85162258/01b32de5-ad8c-4c57-8ec2-9f4816ff76b2)

[Carpeta del flujo](https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/EZymXxsJO4FBqu_qd_WiF6UBuwBVIU64DgjTb-L0qr8_jA?e=UheyNC)

**Comment by jcmurilloa** [comment]
Muy buen trabajo"
