### ISSUE TITLE
Creación de vista para talento humano (II)

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#42]
Continuar con el desarrollo de la vista de talento humano https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/issues/33

**Sub Tareas**

- [x] Continuar con el desarrollo de la vista para talento humano

**Criterios de aceptación**

- [x] Vista desarrollada
- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
Con la decisión tomada por el equipo de desarrollo se utiliza el mismo modulo para las vistas de las descargas de certificaciones, tanto para docentes como para el personal de talento humano, por lo tanto solo se crea el nuevo formulario donde ya se esta desarrollando la vista.



![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/126271909/f0c3f4e0-8300-4cb2-8737-6ba7c60c70b4)

**Comment by faidercamilo26** [comment]
Se crea la vista correspondiente para descargar certificados de profesores de vinculación especial, esta vista va a esta habilitada solo para el personal o los que tengan el rol de talento humano, se crea esta vista sin ninguna funcionalidad.



![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/126271909/c916f4c9-4dc0-4883-9693-2fc09a572f07)

**Comment by faidercamilo26** [comment]
Se realiza la corrección en la vista para una mejor visualización.



![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/126271909/5f845d10-0fc7-4fff-9d2b-89637e2db535)

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 Buen trabajo.
