### ISSUE TITLE
Diseñar el mockup de la vista del modulo evaluación órdenes de compra

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/Cumplidos_y_certificaciones_documentacion#44]
Se requiere diseñar el mockup para la vista del módulo de evaluación órdenes de compra. 

**Sub Tareas**

- [x] Diseñar mockup con base en los requerimientos.
- [x] Presentar el mockup al cliente.
- [x] Realizar ajustes según comentarios del cliente.
- [x] Presentar al equipo el mockup definitivo para el desarrollo.

**Criterios de aceptación**

- [x] Mockup aprobado por cliente y equipo.
- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se han creado los mockups de diseño base para el modulo de evaluaciones proveedores




![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/85162258/278f803c-ae60-4ef3-95dc-6e1a0b2114c8)
![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/85162258/1cbcca79-d6af-4a81-a51d-a766bab4330a)
![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/85162258/07da1628-8b7e-4a72-8b47-0d810f0458c8)
![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/85162258/70100297-fc7a-4523-8f03-d3e67bc3d008)
![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/85162258/41e6cde1-5f0f-4572-aa40-5dc9d45cb692)

[Carpeta de mockups](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/El9eSkxgawJDqkNhgaJ1UfUBYm9cB_X_XqQQORThw58aDQ?e=6EmwX0)

**Comment by jcmurilloa** [comment]
Muy buen trabajo @mantnicot, Se revisará en el Backlog del día martes 18 de junio de 2024.

**Comment by mantnicot** [comment]
Se han actualizado los mockups con los comentarios del equipo



![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/85162258/558c1e7f-bd7f-4303-9e98-36fbe7921624)
![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/85162258/7f42c00f-661d-44da-8e1f-2c14b320e46e)
![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/85162258/f2d57e81-3861-4af6-8a5b-70bbb3c4372c)
![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/85162258/6ea96342-3fef-465e-b91d-8d35bfa897f2)
![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/85162258/026d10ba-6ec3-49d5-8778-ba118c5bf458)

[Carpeta de mockups v2 ](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/ElpTHJ29lRZLqfm0eLSP7ocBIC7lR2_P23n329LiH7EVbA?e=UFRoFI)

**Comment by jcmurilloa** [comment]
Excelente trabajo @mantnicot!
