### ISSUE TITLE
Desarrollar funciones helper y controlador para las certificaciones DVE

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#45]
Se requiere realizar las funciones helper y el controlador según la [propuesta](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/issues/40) 

**Sub Tareas**

- [x] Crear helper ***intensidadHorariaDve*** (responder informacion de pruebas mientras se tiene el endpoint de consulta de condor)
- [x] Crear helper ***InformacionDocenteDVE***, consultando argo y agora para la información de contrato e información básica. 
- [x] Crear Controlador ***InformacionCertificacionDve*** con metodo post que reciba la información de los filtros segun los mockups y retorne la información necesaria para el certificado.

**Criterios de aceptación**

- [x] Helpers y controlador creados según lo indicado.
- [x] issue documentado.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
Se crean los helpers intensidadHorariaDve e InformacionDocenteDVE, hace falta información para poder realizar las consultas correspondientes y que los helpers queden totalmente funcionales, se crea adicionalmente la función InformacionCertificacionDve() que es la encargada de utilizar los helpers anteriores para retornar toda la información necesaria para crear el certificado de los docentes de vinculación especial. Se crea el controlador PostInformacionCertificacionDve() sin embargo, al hacer la petición Post no se estan retornando los datos de pruebas.



![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/126271909/ce48cc68-976d-4a65-bdf5-dfc277035341)

**Comment by faidercamilo26** [comment]
Se crean los modelos de respuesta para retornar la información de los certificados en el archivo informacion_certificacion_dve.go. Se crea el modelo InformacionDVE para retornar la información personal de un docente, el modelo IntensidadHorariaDVE para retornar toda la información de la intensidad horaria de cada una de las vinculaciones de un docente y por ultimo el modelo InformacionCertificacionDve para unir toda esta informacion, este es el modelo que se retorna en el controlador.

```golang

type InformacionCertificacionDve struct {
	InformacionDve    InformacionDVE         `json:"informacion_dve"`
	IntensidadHoraria []IntensidadHorariaDVE `json:"intensidad_horaria"`
}

type InformacionDVE struct {
	Activo             string `json:"activo"`
	NombreDocente      string `json:"nombre_docente"`
	NumeroDocumento    string `json:"numero_documento"`
	NivelAcademico     string `json:"nivel_academico"`
	Facultad           string `json:"facultad"`
	ProyectoCurricular string `json:"proyecto_curricular"`
}

type IntensidadHorariaDVE struct {
	Ano              string `json:"ano"`
	Periodo          string `json:"periodo"`
	NombreAsignatura string `json:"nombre_asignatura"`
	HorasSemana      string `json:"horas_semanales"`
	NumeroSemanas    string `json:"numero_semanas"`
	HorasSemestrales string `json:"horas_semestrales"`
	SalarioDocente   string `json:"salario_docente"`
}

```

**Comment by faidercamilo26** [comment]
Se realiza la modificación correspondiente del helper InformacionDocenteDVE para que realice las búsquedas correspondientes y no retorne datos de prueba, sin embargo, los datos de facultad y proyecto curricular se deben consultar a JBPM para traer los nombres, dados los códigos que ya vienen  del endpoint de resoluciones, sin embargo, he tenido problemas al realizar las peticiones, puesto que el endpoint posiblemente por errores en su implementación no esta retornando la información se espera para consultar con líder de desarrollo y poder finalizar la issue.




![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/126271909/84e4bc74-7936-494c-be69-9fab6fbcdc73)





![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/126271909/e3c19825-6399-4927-af26-604be06b9445)

**Comment by faidercamilo26** [comment]
Con el fin de retornar mas informacion que pueda ser relevante para la certificación se realizan modificaciones en el modelo de InformacionDVE, el cual queda de la siguiente manera 

```golang
type InformacionDVE struct {
	Activo             bool   `json:"activo"`
	NombreDocente      string `json:"nombre_docente"`
	NumeroDocumento    string `json:"numero_documento"`
	NivelAcademico     string `json:"nivel_academico"`
	Facultad           string `json:"facultad"`
	ProyectoCurricular string `json:"proyecto_curricular"`
	Categoria          string `json:"categoria"`
	Dedicacion         string `json:"dedicacion"`
}
```

Se completa el código y las peticiones para retornar toda la información del docente 



![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/126271909/a7339006-945f-45ad-bbdf-59b00d0947a5)

Ya solo quedan faltando los datos del enpoint para validar y retornar correctamente la información de la intensidad horaria de cada una de las vinculaciones del docente de vinculación especial.

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 buen trabajo
