### ISSUE TITLE
Verificar el cumplimiento de lista de chequeo para despliegue

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/Cumplidos_y_certificaciones_documentacion#46]
Se requiere realizar la verificación del cumplimiento de lista de chequeo para despliegue

**Sub Tareas**

- [x] Manuales e instructivos actualizados
- [x] Documento técnico
- [x] Diagnóstico final
- [x] Casos posibles de soporte
- [x] Matriz de acceso

**Criterios de aceptación**

- [ ] Documentación enviada a funcionamiento
- [ ] VoBo funcionamiento

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico/SoSM.
- [ ] Artefacto solicitado satisface la necesidad.

**Comment by JuanCamiloMartinezLopez** [comment]
### Manual de usuario

Se adjunta link del manual de usuario https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EQIm1TKwHNRLgLLPAv_XQ5MBRvPdNAKLsuuPWnQZqn4iIQ?e=cDjEgO 

### Descripción técnica
 
Se adjunta link de la descripción técnica https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EXn9P5yhwA1Kq3cc1rM-b4UBpSgMYE45cnuKQMvOSywzrg?e=NE8vmE

**Comment by JuanCamiloMartinezLopez** [comment]
### Documentos para el despliegue 

Se crea la siguiente carpeta para todos los documentos para el despliegue
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/Eo8tqC5GQnNKhI18i9nX0goBz1JCokLP5ujjCsv9yx5W8A?e=TIU5Qh
