### ISSUE TITLE
Concertar, desarrollar y levantar acta de sesión de muestra con cliente

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/Cumplidos_y_certificaciones_documentacion#47]
Se requiere realizar la concertación, desarrollo y levantamiento acta acta de sesión de muestra con cliente

**Sub Tareas**

- [x] Concertar reunión de requerimientos con el cliente
- [x] Desarrollar la reunión exposición del módulo evaluacioes
- [x] Proyectar acta de la reunión

**Criterios de aceptación**

- [x] Acta revisada por el líder de proyecto
- [ ] Acta firmada por las partes con anexo de historias de usuario

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico/SoSM.
- [ ] Artefacto solicitado satisface la necesidad

**Comment by mantnicot** [comment]
Se ha agendado la reunión para 12/06/2024 a las 11 am

[enlace reunión](https://teams.microsoft.com/l/meetup-join/19%3ameeting_MDZmNTBmZTMtNmE5YS00MjcyLWE3ZTgtOTkzMWU2ODQ5NDU1%40thread.v2/0?context=%7b%22Tid%22%3a%22d51388ef-6ab0-4363-9f94-d56644a45970%22%2c%22Oid%22%3a%22b989c328-89fa-4486-abfe-df75fdd723ba%22%7d)

**Comment by mantnicot** [comment]
Se ha cancelado la reunión por cuestiones de agenda del cliente , se esta buscando re agendar

**Comment by mantnicot** [comment]
Se ha podido reagendar para 12/06/2024 a las 2 pm

**Comment by mantnicot** [comment]
Se ha creado el acta , se queda a espera de firmas

[Acta sin firmas](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/Ebj8NVrHI3RAsLHvpeHyk3MBlft-J6BJY1B78K1lxbx-Tw?e=mLmIHY)

**Comment by mantnicot** [comment]
Se adjunta el acta firmada

[Acta firmada](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EVEBah_MJfhAmyJPIkKkvtABwSfqnU8BLGQwNQWzQyk0ZQ?e=WN0z89)

**Comment by jcmurilloa** [comment]
Excelente trabajo @mantnicot!
