### ISSUE TITLE
Preparacion de documentacion para el despliegue del módulo de históricos de Cumplidos CPS

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#50]
Se requiere realizar la preparación de los documentos necesarios para la salida a producción del módulo de históricos.

**Sub Tareas**

- [x] Agregar al documento de [descripción técnica](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EXn9P5yhwA1Kq3cc1rM-b4UBpSgMYE45cnuKQMvOSywzrg?e=fOFOFo) una portada para mejorar la presentacion.
- [x] Crear el documento de diagnóstico final tomando como [ejemplo](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EVF3zMw-OhpGk9YLvOjM1CkBXthstTWHwOR9UVnt6-6Ieg?e=FWqdxo).
- [x] Crear documento de posibles casos de soporte, con formato propio.
- [x] Crear documento de matriz de acceso, indicando roles y funciones, así como sus limitaciones.

**Criterios de aceptación**

- [x] Documentos realizados y en la [carpeta](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/Eo8tqC5GQnNKhI18i9nX0goBz1JCokLP5ujjCsv9yx5W8A?e=erqhyX) del proyecto.
- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
Se crea el documento de [diagnóstico final](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EYP8_pcOejZMsuC64_ghchkBaklEWluOmVT5fKTNwgbL1w?e=YliwsL) y se agrega a la carpeta del proyecto.

**Comment by faidercamilo26** [comment]
Se crea el documento de [posibles casos de soporte](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EaaGE3OIA69DsxTgkGyxiW8BCsKig6zgQZ7R3_ys80aqvA?e=X9aGGf) y se agrega a la carpeta del proyecto.

**Comment by faidercamilo26** [comment]
Se crea el documento de la[ matriz de acceso](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EbbVZAjhFfBOvKGcluRJBhsBp2jFHf28P1Khl3Thmvmu8w?e=mHINTd) y se agrega a la carpeta del proyecto.

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 buen trabajo.
