### ISSUE TITLE
Carga de información en la tabla cambio dependencia

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#51]
Se requiere generar un script para llenar la [tabla](https://github.com/udistrital/oikos_api/issues/60#issuecomment-2125241158) con datos de producción, continuando con la tarea https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/issues/20

**Sub Tareas**

- [x] Generar script para insertar los datos de cambios de dependencia.

**Criterios de aceptación**

- [ ] Script listo para la ejecución. 
- [ ] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by stevencol** [comment]
Se realiza la consultar con datos de producción según tabla de Excel  pero los nombre nos son iguales o no estan
![image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/51761184/1e3355d5-6202-49a2-87be-ec63f0032078)

🟡 No hay coincidencias
🔴  Múltiples Ids
🟢 Hay coincidencias pero no se llaman igual que en el documento

**Comment by stevencol** [comment]
***Script temporal***
___________________

``` Sql
INSERT INTO cambio_dependencia (id_dependencia_nueva, id_dependencia_antigua,fecha_creacion , fecha_modificacion, activo) VALUES
('254', '122', NOW(),NOW(),true),
('249', '12' ,NOW(),NOW(),true),
('265', '45', NOW(),NOW(),true),
('269', '99',NOW(),NOW(),true ); 
```

*Temporal  
1: no están todos los datos de las dependencias están actualizados por lo que se utilizan las que están al día
2: Algunas dependencias no se han creado
3: el campo vigencia, activo  desconozco su valor

**Comment by JuanCamiloMartinezLopez** [comment]
@stevencol Buen trabajo
