### ISSUE TITLE
Consultar titan para obtener el último pago realizado a un DVE

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#52]
Se requiere realizar la consulta del último pago realizado del último contrato del docente para la información del certificado DVE.

**Sub Tareas**

- [x] Consultar el [crud ](https://autenticacion.portaloas.udistrital.edu.co/store/apis/info?name=titan_api_crud&version=v2&provider=admin&tenant=carbon.super)y/o [mid](https://autenticacion.portaloas.udistrital.edu.co/store/apis/info?name=titan_api_mid&version=v2&provider=admin&tenant=carbon.super)de titan para obtener la información del pago realizado.
- [x] Agregar al modelo de respuesta del controlador PostInformacionCertificacionDve el valor del ultimo pago.
- [x] Realizar la(s) consulta(s) en un helper.

**Criterios de aceptación**

- [x] Controlador funcionando con el valor del último pago.
- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
Se actualiza el modelo InformacionContratoDVE para incluir la informacion del ultimo salario, asi que queda de la siguiente manera:

```golang
type InformacionDVE struct {
	Activo             bool   `json:"activo"`
	NombreDocente      string `json:"nombre_docente"`
	NumeroDocumento    string `json:"numero_documento"`
	NivelAcademico     string `json:"nivel_academico"`
	Facultad           string `json:"facultad"`
	ProyectoCurricular string `json:"proyecto_curricular"`
	Categoria          string `json:"categoria"`
	Dedicacion         string `json:"dedicacion"`
	UltimoPago         string `json:"ultimo_pago_dve"`
}
```
Se crea la función auxiliar ObtenerAnoMes() para poder extraer el año y el mes de la fecha de inicio del contrato, dicha función se utiliza en el helper ObtenerUltimoSalarioDve() el cual es el encargado de hacer las consultas al crud y al mid de titan para obtener el último salario del docente, dicho helper ya esta casi finalizado, sin embargo, tengo algunas dudas sobre el valor de salario que se debe retornar, por ese motivo el helper no se ha finalizado totalmente.

```golang
func ObtenerAnoMes(fecha time.Time) (ano string, mes string, outputError map[string]interface{}) {
	defer func() {
		if err := recover(); err != nil {
			outputError = map[string]interface{}{
				"Succes":  false,
				"Status":  502,
				"Message": "Error al obtener el año y el mes",
				"Funcion": "ObtenerAnoMes",
			}
			panic(outputError)
		}
	}()

	ano = strconv.Itoa(fecha.Year())
	mes = strconv.Itoa(int(fecha.Month()))

	return ano, mes, nil
}

func ObtenerUltimoSalarioDve(numeroDocumentoDve string) (ultimoSalario string, outputError map[string]interface{}) {
	defer func() {
		if err := recover(); err != nil {
			outputError = map[string]interface{}{
				"Succes":  false,
				"Status":  502,
				"Message": "Error al obtener el ultimo salario del docente",
				"Funcion": "ObtenerUltimoSalaraDve",
			}
			panic(outputError)
		}
	}()

	var respuesta_peticion map[string]interface{}
	var detalle_preliquidacion []models.DetallePreliquidacion
	var fecha time.Time
	var nomina string
	if response, err := getJsonTest(beego.AppConfig.String("UrlCrudTitan")+"/detalle_preliquidacion/?query=ContratoPreliquidacionId.ContratoId.Documento:"+numeroDocumentoDve, &respuesta_peticion); err == nil && response == 200 {
		if len(respuesta_peticion) > 0 {
			LimpiezaRespuestaRefactor(respuesta_peticion, &detalle_preliquidacion)
			for _, detalle := range detalle_preliquidacion {
				if fecha.IsZero() {
					fecha = detalle.ContratoPreliquidacionId.ContratoId.FechaInicio
					nomina = strconv.Itoa(detalle.ContratoPreliquidacionId.PreliquidacionId.NominaId)
				} else {
					if fecha.Before(detalle.ContratoPreliquidacionId.ContratoId.FechaInicio) {
						fecha = detalle.ContratoPreliquidacionId.ContratoId.FechaInicio
						nomina = strconv.Itoa(detalle.ContratoPreliquidacionId.PreliquidacionId.NominaId)
					} else {
						fecha = fecha
						nomina = nomina
					}
				}
			}
			ano, mes, errorAnoMes := ObtenerAnoMes(fecha)
			if errorAnoMes != nil {
				return ultimoSalario, errorAnoMes
			} else {
				var respuesta_detalle map[string]interface{}
				var detalle []models.Detalle

				if response, err := getJsonTest(beego.AppConfig.String("UrlMidTitan")+"/detalle_preliquidacion/obtener_detalle_DVE/"+ano+"/"+mes+"/"+numeroDocumentoDve+"/"+nomina, &respuesta_detalle); err == nil && response == 200 {
					if len(respuesta_detalle) > 0 {
						LimpiezaRespuestaRefactor(respuesta_detalle, &detalle)
						fmt.Println("detalle", detalle)
					}
				}
			}
		} else {
			return ultimoSalario, map[string]interface{}{
				"Succes":  false,
				"Status":  404,
				"Message": "No se encontro el salario del docente",
				"Funcion": "ObtenerUltimoSalaraDve",
			}
		}
	}
	return "ultimoSalario", nil
}
```

**Comment by faidercamilo26** [comment]
Se termina la creación del helper para que retorne la información del último salario del docente de vinculación especial.



![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/126271909/d038936a-8c23-4ca6-9ef6-6018338eb916)

**Comment by faidercamilo26** [comment]
Se realiza una modificación al helper  ObtenerUltimoSalarioDve para que ahora el salario se retorne con formato de pesos y sea mas legible la respuesta.

```golang
func ObtenerUltimoSalarioDve(numeroDocumentoDve string) (ultimoSalario string, outputError map[string]interface{}) {
	defer func() {
		if err := recover(); err != nil {
			outputError = map[string]interface{}{
				"Succes":  false,
				"Status":  502,
				"Message": "Error al obtener el ultimo salario del docente",
				"Funcion": "ObtenerUltimoSalaraDve",
			}
			panic(outputError)
		}
	}()
	ultimoSalario = "$"
	var respuesta_peticion map[string]interface{}
	var detalle_preliquidacion []models.DetallePreliquidacion
	var fecha time.Time
	var nomina string

	if response, err := getJsonTest(beego.AppConfig.String("UrlCrudTitan")+"/detalle_preliquidacion/?query=ContratoPreliquidacionId.ContratoId.Documento:"+numeroDocumentoDve, &respuesta_peticion); err == nil && response == 200 {
		if len(respuesta_peticion) > 0 {
			LimpiezaRespuestaRefactor(respuesta_peticion, &detalle_preliquidacion)
			for _, detalle := range detalle_preliquidacion {
				if fecha.IsZero() {
					fecha = detalle.ContratoPreliquidacionId.ContratoId.FechaInicio
					nomina = strconv.Itoa(detalle.ContratoPreliquidacionId.PreliquidacionId.NominaId)
				} else {
					if fecha.Before(detalle.ContratoPreliquidacionId.ContratoId.FechaInicio) {
						fecha = detalle.ContratoPreliquidacionId.ContratoId.FechaInicio
						nomina = strconv.Itoa(detalle.ContratoPreliquidacionId.PreliquidacionId.NominaId)
					} else {
						fecha = fecha
						nomina = nomina
					}
				}
			}
			ano, mes, errorAnoMes := ObtenerAnoMes(fecha)
			if errorAnoMes != nil {
				return ultimoSalario, errorAnoMes
			} else {
				var respuesta_detalle map[string]interface{}
				var detalles []models.Detalle
				if response, err := getJsonTest(beego.AppConfig.String("UrlMidTitan")+"/detalle_preliquidacion/obtener_detalle_DVE/"+ano+"/"+mes+"/"+numeroDocumentoDve+"/"+nomina, &respuesta_detalle); err == nil && response == 200 {
					if len(respuesta_detalle) > 0 {
						LimpiezaRespuestaRefactor(respuesta_detalle, &detalles)
						for _, detalle := range detalles {
							for _, det := range detalle.Detalle {
								if det.ConceptoNominaId.Id == 152 {
									ultimoSalario = FormatMoney(int(det.ValorCalculado), 0)
									return ultimoSalario, nil
								} else {
									continue
								}
							}
						}
					}
				}
			}
		} else {
			return "ultimoSalario", map[string]interface{}{
				"Succes":  false,
				"Status":  404,
				"Message": "No se encontro el salario del docente",
				"Funcion": "ObtenerUltimoSalaraDve",
			}
		}
	}
	return ultimoSalario, nil
}

```



![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/126271909/be068fd7-e9e6-40cf-974a-addc1780cda6)




![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/126271909/3b479f3b-5c11-46a3-8043-ac83944c39ac)

**Comment by faidercamilo26** [comment]
Se evidencia que al hacer la consulta al api de titán con el número de documento del docente hay algunos docentes que no tienen contratos y por eso no es posible retornar la informacion del ultimo salario, para esos casos se retorna en el Json un mensaje indicando esta situación, con esto se finaliza totalmente la implementación de retornar el ultimo salario de un docente.




![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/126271909/dc4e0ca8-9973-43e6-ad6c-1738f3de68a4)


![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/126271909/7778398c-9932-4f83-8c35-7d094bcaa645)

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 buen trabajo
