### ISSUE TITLE
Revisión y familiarización con la tecnologia de micro clientes

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#54]
Se requiere realizar la revisión de los lineamientos y ejemplos sobre la implementación de micro clientes.

**Material de apoyo**
- [Microclientes](https://github.com/udistrital/lineamientos_oas?tab=readme-ov-file#microclientes)
- [sga_cliente_root](https://github.com/udistrital/sga_cliente_root)
- [División del Cliente en Microfrontends PT1](https://github.com/udistrital/planeacion_cliente/issues/892)
- [División del Cliente en Microfrontends PT2](https://github.com/udistrital/planeacion_cliente/issues/910)
- [Single-spa docs](https://single-spa.js.org/docs/getting-started-overview)

**Sub Tareas**

- [x] Revisar material de apoyo de micro clientes 
- [x] Realizar un ejemplo pequeño.

**Criterios de aceptación**

- [x] Issue documentada

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
Se revisa la documentación que se encuentra en el repositorio sobre microclientes, se revisa la grabación de la capacitación que contiene la [teoría de microclientes](https://udistritaleduco-my.sharepoint.com/:v:/r/personal/computo_udistrital_edu_co/Documents/Grabaciones/Capacitaci%C3%B3n%20de%20desarrollo%20Arquitectura-20240417_101133-Grabaci%C3%B3n%20de%20la%20reuni%C3%B3n.mp4?csf=1&web=1&e=WSybum&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D) tambien la capacitacion de la [practica de microclientes](https://udistritaleduco-my.sharepoint.com/:v:/r/personal/ndmunozc_udistrital_edu_co/Documents/Grabaciones/Otras-OATI/Capacitaci%C3%B3n%20de%20desarrollo%20Arquitectura-20240418_081506-Meeting%20Recording.mp4?csf=1&web=1&e=qJKBdZ&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D), se inica el proyecto de microclientes de practica, por el momento se han creado el root y el core.



![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/126271909/42f5a927-1319-416f-a47f-a72a22565ccc)

**Comment by stevencol** [comment]
Se inicia la familiarización con lo requerido, en los cuales se han presentado múltiples errores, tanto con la versión de Angular como de Node. Se intenta con la última versión. Las dificultades continúan, pero se sigue con la familiarización.

![image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/51761184/b5f92315-aa2d-4635-bcba-783afe84fcef)

![image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/51761184/1f56af4d-413b-49d8-92ea-f6d3fbe5983d)

**Comment by stevencol** [comment]
En la familiarización de micro clientes , se uso Angular 16 ya que las versiones mas reciente angular maneja estándalone , por lo que  se practico en esa versión., se logran navegar en lo componentes  directamente desde root 
![image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/51761184/e3a0f406-d8b0-42b1-a64d-ffecbae768ce)
![image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/51761184/c506ed82-6c18-45a0-be47-d0794ad06d05)

**Comment by faidercamilo26** [comment]
Con el fin de poder experimentar como funcionan los microclientes se crea el core y el mf1 de la siguiente manera:

**core:**

![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/126271909/210f6e5d-1a5c-400f-b8b4-d9dd68459c71)

**mf1:**


![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/126271909/a22f0b7b-28c6-4636-8917-7c7d3367ccf0)

Por separado funcionan perfecto pero antes de definir las jerarquías correspondientes vemos que al montar los dos microclientes al tiempo se monta uno sobre el otro, puesto que por el momento los microclientes son hermanos y no saben cuando llamar uno u el otro.


![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/126271909/86ffedbd-8d35-4ff9-bc22-c52989fa2ae3)

Se realiza el ajuste de rutas para que por defecto se muestre la barra del core y tambien para que se pueda mostrar el componente mf1 sin superponerse al core.



![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/126271909/49461fd8-bb35-44f2-a844-85a924b8019a)



![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/126271909/07dc7272-d1d7-411e-9bb7-606756a7a3f7)

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 @stevencol Buen trabajo equipo.
