### ISSUE TITLE
Concertación, desarrollo y levantamiento del acta de sesión de requerimientos y/o refinamiento con el cliente

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/Cumplidos_y_certificaciones_documentacion#55]
Se requiere realizar la concertación, desarrollo y levantamiento del acta de sesión de requerimientos y/o refinamiento con el cliente

**Sub Tareas**

- [x] Concertar reunión con el cliente.
- [x] Desarrollar la reunión con el cliente.
- [x] Diligenciamiento y aprobación del formato de historias de usuario o Mockup por parte del cliente (si aplica).
- [x] Proyectar acta de la reunión.
- [x] Recolectar las firmas correspondientes.

**Criterios de aceptación**

- [x] Acta revisada por el líder de proyecto.
- [x] Acta firmada por las partes con anexo de historias de usuario o mockup.
- [x] Acta y anexos documentados.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se ha podido agendar la reunión para el día 20/06/2024 a las 2:30 pm

**Comment by mantnicot** [comment]
Se ha creado el acta correspondiente

[Acta sin firmas](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/ESYVv9rn-U5LpUoi5JI8vu8BmaXgI5f1bhPTnyxHmy-lfQ?e=ImlZR6)

**Comment by jcmurilloa** [comment]
Información bastante valiosa @mantnicot, se revisarán flujos y formatos en el review del 24/06

**Comment by mantnicot** [comment]
Se ha agregado la firma de los asistentes 


[Acta con firma](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/ETF_Z7CE1ctFhpo8cCTIp1IBlqXEkO3sE5eSW0Nw14RyNg?e=TOfC05)

**Comment by jcmurilloa** [comment]
Algunas firmas complicadas pero lo lograste @mantnicot. Muy buen trabajo!
