### ISSUE TITLE
Revisión y familiarización con la tecnologia de microservicios

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#56]
Se requiere realizar la revisión de los lineamientos y ejemplos sobre la implementación de micro servicios.

**Material de apoyo**
- [Lineamientos microservicios](https://github.com/udistrital/arquitectura_docs/tree/master/aplicaciones#micro-servicios-que-son)
- [Lineamientos de arquitectura](https://github.com/udistrital/arquitectura_docs/tree/master/aplicaciones#lineamientos-generales-de-arquitectura)
- [División del sistema en Microservicios](https://github.com/udistrital/planeacion_cliente/issues/803)
- [Ejemplo de creacion de microservicio sisifo](https://github.com/udistrital/sisifo_documentacion/issues/45)

**Sub Tareas**

- [x] Revisar micro servicios de la OATI como ejemplos de organización.
- [x] Revisar los procesos de otros equipos para el proceso de diseño y creación de microservicios

**Criterios de aceptación**

- [x] Issue documentada. 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
Se inicia la tarea leyendo la documentación contenida en el repositorio de github acerca de los microservicios.

**Comment by faidercamilo26** [comment]
## :triangular_flag_on_post: **Ejemplo SISGPLAN**  :triangular_flag_on_post:

Se revisa la issue que contiene la documentación acerca de la división del sistema SISGPLAN en microservicios, se puede evidenciar   le estructura anterior del sistema, se puede ver claramente que era un monolito compuesto de simplemente la api_mid, api crud y la base de datos.


![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/126271909/1dc002db-390a-468e-a96d-a3f6e80a13a0)




Se revisa el [documento](https://app.diagrams.net/#G1h9gerErueRXNr2StkfX3srKsRQG05m2J#%7B%22pageId%22%3A%221y2TeRVVFiUTmYUZVGZP%22%7D) en la seccion de Propuesta - detalla (V2) que es la propuesta final con los microservicios.



![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/126271909/055afe5f-519b-4bc0-b082-1b987c42995f)

**Comment by faidercamilo26** [comment]
## :triangular_flag_on_post: **Ejemplo sisifo v2**  :triangular_flag_on_post:

Se revisa la documentación contenida en la issue de ejemplo sobre la implementación del microservicio de gestión de usuarios y roles para Sísifo v2 para verificar la forma en la cual se construyo este microservicio, se indaga esta api en el repositorio de apis para tener en cuenta los endpoints generados en este microservicio.



![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/126271909/1340f442-0c47-4a2a-89f4-e2ce3f1563e1)

**Comment by stevencol** [comment]
Se realiza la lectura de documentación sobre la teoría de microservicios y sus características principales. Se propone que el nuevo módulo se desarrolle usando Java - Spring Boot, ya que es el lenguaje y framework que mejor manejo. Se desarrolla una aplicación sencilla usando Java - Spring Boot, donde se consulta la API [api.intranetoas.udistrital.edu.co:8104/v1/dependencia_SIC/?limit=-1](url) y se obtiene el resultado desde esta aplicación, para lo cual se crea el DTO Dependencias pra reprensentar las respuesta.

``` Java
package com.example.demo;

import java.sql.Date;

import com.fasterxml.jackson.annotation.JsonProperty;

public class Dependencias {
	
	@JsonProperty("ESFIDESPACIO")
	 private String esfidespacio;
	@JsonProperty("ESFCODIGODEP")
	    private String esfcodigodep;
	@JsonProperty("ESFDEPENCARGADA")
	    private String esfdepencargada;
	@JsonProperty("ESFESTADO")
	    private String esfestado;
	@JsonProperty("Ciudad")
	    private String ciudad;
	@JsonProperty("Localidad")
	    private String localidad;
	@JsonProperty("Barrio")
	    private String barrio;
	@JsonProperty("Direccion")
	    private String direccion;
	@JsonProperty("EstadoRegistro")
	    private boolean estadoregistro;
	@JsonProperty("FechaRegistro")
	    private String fecharegistro;
	@JsonProperty("Id")
	    private int id;
	public String getEsfidespacio() {
		return esfidespacio;
	}
	public void setEsfidespacio(String esfidespacio) {
		this.esfidespacio = esfidespacio;
	}
	public String getEsfcodigodep() {
		return esfcodigodep;
	}
	public void setEsfcodigodep(String esfcodigodep) {
		this.esfcodigodep = esfcodigodep;
	}
	public String getEsfdepencargada() {
		return esfdepencargada;
	}
	public void setEsfdepencargada(String esfdepencargada) {
		this.esfdepencargada = esfdepencargada;
	}
	public String getEsfestado() {
		return esfestado;
	}
	public void setEsfestado(String esfestado) {
		this.esfestado = esfestado;
	}
	public String getCiudad() {
		return ciudad;
	}
	public void setCiudad(String ciudad) {
		this.ciudad = ciudad;
	}
	public String getLocalidad() {
		return localidad;
	}
	public void setLocalidad(String localidad) {
		this.localidad = localidad;
	}
	public String getBarrio() {
		return Barrio;
	}
	public void setBarrio(String barrio) {
		Barrio = barrio;
	}
	public String getDireccion() {
		return direccion;
	}
	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}
	public boolean isEstadoregistro() {
		return estadoregistro;
	}
	public void setEstadoregistro(boolean estadoregistro) {
		this.estadoregistro = estadoregistro;
	}
	public String getFecharegistro() {
		return fecharegistro;
	}
	public void setFecharegistro(String fecharegistro) {
		this.fecharegistro = fecharegistro;
	}
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}

	
     
}

```
***Controlador***
``` Java
package com.example.demo;

import java.util.Collection;
import java.util.Collections;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.HttpStatusCode;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.client.RestTemplate;

@RestController
public class DependenciaController {
	
	@Autowired
	private RestTemplate restTemplate;
	
	@GetMapping("/getDependencies")
	public ResponseEntity<Map<String, Object>> getMethodName() {

		Dependencias[] dep = restTemplate.getForObject("http://api.intranetoas.udistrital.edu.co:8104/v1/dependencia_SIC/?limit=-1", Dependencias[].class);

		Map< String, Object> response = Collections.singletonMap("resposne", dep);
		return ResponseEntity.status(HttpStatus.OK).body(response);
	}
	

}

```

Respuesta con java: 
![image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/51761184/c9c259e0-0796-418f-8e9f-71b47e58fce6)



Repuesta Original 
![image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/51761184/1be0d46b-76f9-4055-a9aa-fa1c1416fa77)

**Comment by faidercamilo26** [comment]
## :triangular_flag_on_post: **Propuesta nuevas tecnologías**  :triangular_flag_on_post:


Como propuesta personal, para implementar nuevas tecnologías se propone utilizar el framework de Django con el lenguaje de programación Python.

**Comment by JuanCamiloMartinezLopez** [comment]
@stevencol @faidercamilo26 buen trabajo.
