### ISSUE TITLE
Actualización diagrama de flujo de cumplidos proveedores

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/Cumplidos_y_certificaciones_documentacion#57]
Se requiere realizar la actualización del diagrama de flujo de la cumplidos proveedores según reunión con el cliente

**Sub Tareas**

- [x] Repasar diagrama de flujo actual del sistema
- [x] Generar las modificaciones según requerimientos del cliente
- [x] Presentar al equipos SoS diagrama actualizado
- [x] Aprobar con el cliente diagrama actualizado

**Criterios de aceptación**

- [x] Diagrama de flujo actualizado

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se ha realizado el flujo de cumplidos proveedores

![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/85162258/495ed324-8fa0-493c-93d0-e84c754d033c)

[Flujo en carpeta](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EoFgYvar8bBCozbnPXgXbE0Be_pvhs858qnLvWff9iSmfQ?e=h8kYCc)

**Comment by jcmurilloa** [comment]
Se generan observaciones en la revisión, para lograr la refinación del flujo para el sistema. Muy buen trabajo equipo SoS
