### ISSUE TITLE
Diseñar el mockup para el sistema de cumplidos proveedores

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/Cumplidos_y_certificaciones_documentacion#58]
Se requiere iniiciar con el diseño del mockup para el sistema de cumplidos proveedores. 

**Sub Tareas**

- [x] Diseñar mockup inicial con base en los requerimientos.
- [x] Presentar el mockup al equipo SoS.
- [x] Realizar ajustes según comentarios del equipo SoS.
- [x] Presentar al equipo el mockup definitivo para presentar al cliente.

**Criterios de aceptación**

- [x] Mockup aprobado por equipo SoS.
- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se han creado la primera versión de mock ups para el cliente de cumplidos proveedores



![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/85162258/ffa78c33-d8b6-49fe-a438-dc3addac6dc2)
![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/85162258/2b9a0ed7-9f24-4e55-b635-a30449857cee)
![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/85162258/f3f0e216-c4de-4834-9476-f0b4a151e84e)
![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/85162258/8a594e32-b643-400a-ada5-88171edcce33)
![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/85162258/7936590e-88d0-42ae-b86d-25de966ac72f)
![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/85162258/7a0881e2-ccdd-4e71-bd7f-ba545271edbf)
![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/85162258/044a6c7c-abaf-4220-8849-a8a34f7b808d)
![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/85162258/bc3af397-6d4e-4a30-9e8b-840666918c38)
![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/85162258/ffcc8f09-f41a-4e37-97e5-85fa5e28d7cc)


[Carpeta Mockups](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EvYIVjutZzdDgQubf_sG-8ABOfaDR1rjCwHxOk2opHr6NQ?e=xY5lHd)

**Comment by jcmurilloa** [comment]
Excelente trabajo @mantnicot, pendiente revisar con el equipo de desarrollo!

**Comment by mantnicot** [comment]
Se ha realizado los cambios dados por el lider tecnico




![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/85162258/3a7385f0-c186-47fe-8c14-efef2cd8aa4e)
![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/85162258/d3a84c67-e8eb-46c5-a2b7-c2249a21bedc)
![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/85162258/78a2a4ec-99c2-4596-8414-4939cda661c6)
![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/85162258/40ae8534-1cb0-424c-8e83-4d52188a6287)
![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/85162258/65877801-49d8-4f5b-9684-3af85c6984c5)
![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/85162258/7e668395-8213-4b55-b618-09e43508a328)
![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/85162258/de9a5048-48e4-4860-88bc-f064e3c7b016)
![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/85162258/1963eb0c-7938-4de8-af12-c2a0e8156d7e)
![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/85162258/5f261cdc-9073-4e35-a733-d786ed824222)
![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/85162258/34f40900-760c-45d4-8bc5-6ad6382db8d2)

[Carpeta de mockups](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EpPG010MZgZNt1EeOb09bj4BxV9736N7tmPfXXVqvTMntA?e=CIoesX)

**Comment by jcmurilloa** [comment]
Muy buen diseño @mantnicot, pendiente solo presentar al cliente!

**Comment by mantnicot** [comment]
Se ha actualizado los mockups con base a lo dicho por el cliente , y con el cambio , quedan aprobados


![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/85162258/4452eccf-71d6-49f5-872d-1594cceba854)
![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/85162258/0bf8abcf-68d8-479e-b1bb-bf2795551aa1)
![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/85162258/fc6cfa71-5c4d-497a-a4fc-fcd0d12b5003)
![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/85162258/da655b17-b5e8-4089-abca-d77f5be3acbb)
![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/85162258/80e90bfc-2a6a-4790-ba60-0daf09c33d1a)
![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/85162258/060ab797-8b13-43fe-bed2-343e73230b83)
![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/85162258/a629a510-6bed-4851-9153-61dc5dd33ecb)
![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/85162258/1f3a46c4-452d-4b97-b21d-db47fac3329e)
![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/85162258/782bdfc5-529a-4cdc-812c-6eaf89e10c34)
![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/85162258/1fac8c0b-ce8c-4819-9dec-44579145e528)


[Carpeta de los mockups](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EsH0nFt6q05Psqv1mZrS_oEBP5H5_G-GZAT3e29-LIPsrQ?e=PHO1Kz)

**Comment by mantnicot** [comment]
Se han actualizado los mockups con base a lo dicho por el equipo de desarrollo 




![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/85162258/67e8684e-82b5-4cab-a639-cfa789e2fa24)
![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/85162258/76b895a5-3816-4b43-971a-0535ca1f8c39)
![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/85162258/4660d513-5fd3-42a3-a79b-4c57520f5814)
![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/85162258/8e290435-7834-47ec-953a-bbbf9225dcc5)
![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/85162258/f47b7135-554f-4647-8227-186865ed74c2)
![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/85162258/3c88a944-aa3c-4e76-a3fd-b5c0aff5ae2a)
![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/85162258/2f9bbbd4-31d0-4e83-af39-135eb9aada6e)
![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/85162258/e91153b9-26ed-4049-b675-f8de7c5b721a)
![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/85162258/950b6841-3b77-4da9-ba08-746f6ad46b42)
![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/85162258/748626d0-6dd6-43aa-b0e6-c3738eb4843f)


[Carpeta mockups ](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EvvCdYONpSNBlhO4Xplr_nsBaRV-YazS1hn0ue4bIY-xIA?e=iSax3g)

**Comment by jcmurilloa** [comment]
Mockups refinados con equipo y cliente, muy buen trabajo @mantnicot
