### ISSUE TITLE
Revisión y análisis - Cumplidos proveedores

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#59]
Se requiere realizar una [reunión](https://teams.microsoft.com/l/meetup-join/19%3ameeting_ZTBiMWRhYWMtNzQyMy00ZTdlLWJmOWQtM2EzNjA2NDkzZmVm%40thread.v2/0?context=%7b%22Tid%22%3a%22d51388ef-6ab0-4363-9f94-d56644a45970%22%2c%22Oid%22%3a%22e79ddc6c-1555-42d8-83fe-5a759905daaf%22%7d) para dar a conocer el [flujo](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/issues/57) y las peculiaridades de Cumplidos proveedores.

**Sub Tareas**

- [x] Revisar flujo y proceso actual para la revisión de los cumplidos para los proveedores.
- [x] Comparar el proceso de cumplidos CPS y cumplidos proveedores.

**Criterios de aceptación**

- [x] Grabación de la reunión.
- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by JuanCamiloMartinezLopez** [comment]
Se realiza la presentacion y explicacion del flujo de cumplidos proveedores
https://udistritaleduco-my.sharepoint.com/:v:/g/personal/juacmartinezl_udistrital_edu_co/EcVaFFoW5TNCsiD3f2BSvtQBOp8GiQQrfT9vne078wBqPw?e=en17k4

**Comment by stevencol** [comment]
Se asistió a reunión donde se vio el flujo del nuevo módulo Cumplido Proveedores, el cual va a ser para personas jurídicas (**Empresas**). Se discutió qué tipo de contratos se manejan, el tipo de cumplido y las formas de pago. También se revisó el flujo de pago y se dejó en claro que, si es el último pago, se deberá realizar una evaluación al proveedor.
[Reunion](https://udistritaleduco-my.sharepoint.com/personal/juacmartinezl_udistrital_edu_co/_layouts/15/stream.aspx?id=%2Fpersonal%2Fjuacmartinezl%5Fudistrital%5Fedu%5Fco%2FDocuments%2FGrabaciones%2FRevisi%C3%B3n%20y%20an%C3%A1lisis%20%2D%20Cumplidos%20Proveedores%2D20240624%5F090149%2DGrabaci%C3%B3n%20de%20la%20reuni%C3%B3n%2Emp4&referrer=StreamWebApp%2EWeb&referrerScenario=AddressBarCopied%2Eview%2E293592ba%2D74be%2D4c5a%2D95d4%2Da9d7d03cee2b)

**Comment by faidercamilo26** [comment]
Se asiste a la reunión para definir ciertos lineamientos acerca del nuevo desarrollo que va a realizar el equipo, que es el de Cumplidos Proveedores: En la reunión se abordaron varios temas como por ejemplo, como debe funcionar el módulo, qué características tiene, que roles intervienen en este nuevo módulo, entre otros, se inicia un borrador base de Propuesta del módulo, el cual se ura editando con el tiempo para completarlo.

[Reunion](https://teams.microsoft.com/l/meetup-join/19%3ameeting_ZTBiMWRhYWMtNzQyMy00ZTdlLWJmOWQtM2EzNjA2NDkzZmVm%40thread.v2/0?context=%7b%22Tid%22%3a%22d51388ef-6ab0-4363-9f94-d56644a45970%22%2c%22Oid%22%3a%22e79ddc6c-1555-42d8-83fe-5a759905daaf%22%7d)

**Comment by JuanCamiloMartinezLopez** [comment]
@stevencol @faidercamilo26 buen trabajo
