### ISSUE TITLE
Terminar el documento de propuesta de módulos para cumplidos proveedores

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#60]
Se requiere terminar el documento presentado de propuesta para cumplidos proveedores, dando formato y añadiendo las funciones detalladas que tendría cada módulo.

**Sub Tareas**

- [x] Editar el [documento base](https://udistritaleduco-my.sharepoint.com/:x:/r/personal/computo_udistrital_edu_co/Documents/INVERSI%C3%93N/PROYECTOS%20DE%20INVERSI%C3%93N/GERENCIA%20DE%20PROYECTOS/PROYECTOS%20OAS/PROYECTO%20CUMPLIDOS%20Y%20CERTIFICACIONES/2024/Ejecuci%C3%B3n/Gesti%C3%B3n%20t%C3%A9cnica/CUMPLIDOS/Proveedores/Propuesta%20de%20modulos%20Cumplidos%20Proveedores.xlsx?d=w51bf7abee057405cac5cf1b9a4e0dfde&csf=1&web=1&e=Y3Vlfe)
- [x] Agregar las funciones diferenciadas para cada módulo.

**Criterios de aceptación**

- [x] Documento terminado.
- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
## :triangular_flag_on_post: **Propuesta de módulos Cumplidos Proveedores**  :triangular_flag_on_post:

Se edita y se completa totalmente la versión 1 del documento base de la Propuesta de módulos Cumplidos Proveedores, se adjunta el documento y quedo a la espera de la reunión y realizar las correcciones pertinentes en caso de ser necesario. 

[Propuesta de módulos cumplidos proveedores](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/Eb56v1FX4FxArFzxuaTg394BKrOuSRI5cT1DQxOh_-QJIQ?e=orQ7JM)

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 Buen trabajo
