### ISSUE TITLE
Crear y presentar una propuesta de modelo de bases de datos para el módulo de revisión  cumplidos

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#61]
Se requiere realizar una propuesta de modelo de base de datos que cumpla lo [lineamientos](https://github.com/udistrital/lineamientos_oas/blob/master/modelo_de_datos/estandar.md) y mantenga en persistencia el [flujo](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/issues/57) indicado para el modulo de revision de cumplidos.

**Sub Tareas**

- [ ] Generar un modelo propuesta (Herramienta recomendada pgModeler)
- [ ] tomar cumplidos CPS como ejemplo.

**Criterios de aceptación**

- [ ] Propuesta de modelo.
- [ ] Issue documentada

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by stevencol** [comment]
# ***Inicia actividad***

Se inicia con la creación y propuesta del modelo de bases de datos para el módulo de cumplidos proveedores. Inicialmente se desarrolla en PlantUML para facilitar su visualización y comprensión. Posteriormente, se procederá a realizar la implementación en pgModeler. Se requiere aún organizar más la lógica del negocio y definir adecuadamente las cardinalidades entre las entidades. 
![diagrama2_provedores](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/51761184/9f71d6ae-51ba-44be-9718-893b1f1f63f6)
*****los nombres, de las tablas cambian según los lineamientos : Ejemplo: DocumentoPago = documento_pago****

**Comment by JuanCamiloMartinezLopez** [comment]
### Ajustes e indicaciones

@stevencol Se hacen algunas correcciones y sugerencias para la presentación de un nuevo modelo. 

- Intentar no generar duplicidad de datos que ya se almacenan en otras db, mantener los datos requeridos para el dominio del negocio.
- Utilizar apis como https://github.com/udistrital/documentos_crud y https://github.com/udistrital/parametros_crud para datos paramétricos fuera del modelo de negocio o datos generales.
- Nombrar esquemas y tablas de forma descriptiva y referente a la funcionalidad.
- Intentar minimizar la cantidad de tablas, algunas son parte de datos de otras tablas (ej: aprobación pago) 
- Utilizar de ejemplo el modelo de [cumplidos cps](https://github.com/udistrital/cumplidos_crud/tree/develop/models)

**Comment by stevencol** [comment]
Se propone: 
![image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/51761184/9fbc8426-e255-4016-9699-3963bcb5f170)

P: Vigencia se obtiene de numero de contrato? 

- documento_pago.documento_id ➡️ relacion con tabla documentos crud
-  cambio_estado.documento_id ➡️ relacion con tabla documentos crud

**Comment by stevencol** [comment]
Nueva Propuesta : 
![image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/51761184/537bc324-4c9b-4235-bbd1-b14a8649ebb6)



- Se propone no dejar el ultimo estado en soporte_proveedor ya que tiene relación con cambio estado y   para obtener el ultimo estado . se consultaría el que este activo

**Comment by stevencol** [comment]
Se realizan ajustes para cumplir con lineamientos: 
![image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/51761184/7aa40f3f-83e8-407c-9b58-5d0bcdd37220)
- En la tabla comentario soporte se agrega cambio_estado_id  con el fin de obtener los detalles del responble quien deja los comentarios y  su cargo 
- en S¿oporte_pago  documento id hace referencia al id de documento en documentos crud

**Comment by stevencol** [comment]
Se agregan comentarios y correcciones menores: 

![image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/51761184/77b7d309-ec23-4f68-ac8b-a78e89d4007c)

**Comment by JuanCamiloMartinezLopez** [comment]
@stevencol Buen trabajo
