### ISSUE TITLE
Crear y presentar una propuesta de modelo de bases de datos para el módulo de evaluación cumplidos Proveedores

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#62]
Se requiere realizar una propuesta de modelo de base de datos que cumpla lo [lineamientos](https://github.com/udistrital/lineamientos_oas/blob/master/modelo_de_datos/estandar.md) y mantenga en persistencia el [flujo](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/issues/57) indicado para el evaluación cumplidos Proveedores.

**Sub Tareas**

- [x] Generar un modelo propuesta (Herramienta recomendada pgModeler para el caso relacional)
- [x] Revisar los crud de https://github.com/udistrital/evaluaciones_mongo_crud y https://github.com/udistrital/evaluacion_crud para tomar como ejemplo sus modelos
- [x] Evaluar un modelo de base de datos no relacional frente al relacional (pros y contras para este caso en concreto)

**Criterios de aceptación**

- [x] Propuesta de modelo.
- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
Se inicia la tarea, se lee principalmente los lineamientos para generar el modelo de datos acorde a los estándares definidos por la Oati, adicionalmente como no tengo mucho conocimiento de bases de datos no relacionales se realiza la investigación correspondiente acerca de este tipo de bases de datos principalmente de mongoDb que es la utilizada en la oficina, se investiga en varias fuentes, principalemente en un video de [youtube](https://www.youtube.com/watch?v=cT1HAaPqI-c) y en la documentacion oficial de [mongoDb](https://www.mongodb.com/docs/manual/introduction/)

**Comment by faidercamilo26** [comment]
Se clonan y se analizan los proyectos para analizar como se construyo su modelo de datos y así hacer una comparativa más acertada sobre que pro y contras puede tener el utilizar una base de datos relacional o una no relacional para el módulo de Evaluación proveedores.



![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/126271909/c5a592e4-ced9-443d-96e8-e79219414452)



![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/126271909/1ad8c9f5-bc6d-4918-ba40-e8ad6ddd1e46)

**Comment by faidercamilo26** [comment]
Se crea la primera propuesta de modelo de datos en la herramienta Pgmodeler para ser revisada.





![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/126271909/ff34c2ba-2cc1-44a1-b3e8-6d5cc0940172)

**Comment by faidercamilo26** [comment]
## :triangular_flag_on_post: **Corrección modelo propuesto**  :triangular_flag_on_post:

Se corrige el modelo presentado anteriormente y se adjunta la imagen de la nueva propuesta.

![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/126271909/334e83c9-7a56-44cb-b245-d8684e7bcc5d)



## :triangular_flag_on_post: **Explicación tablas modelo**  :triangular_flag_on_post:
### **tipo_item:** 
Tabla paramétrica encargada de crear los tipos de items que se encuentran en el módulo de evaluación, por ejemplo, labels, inputs o selects.

### **item:** 
Tabla que representa cada uno de los items del módulo.

### **seccion:** 
Tabla paramétrica  donde se guardan cada una de las secciones y subsecciones del módulo, por ejemplo, está la sección Calidad la cual no tiene una sección padre.

### **opcion:** 
Tabla que representa las opciones y el valor que tiene cada item de pregunta. 

### **opcion_item:** 
Como un item puede tener muchas opciones y las opciones pueden estar en un solo item se crea esta tabla de rompimiento para la relación muchos a muchos de las tablas item y opcion.

### **clasificacion:** 
Tabla paramétrica que guarda los límites para que una calificación sea excelente, buena o mala.

### **evaluacion:** 
Tabla para guardar los datos de una evaluación.

### **evaluador:** 
Tabla para guardar los evaluadores de los proveedores con los ítems a evaluar y su respectivo porcentaje de evaluación.

### **evaluacion_evaluador:** 
Tabla de rompimiento de la relación muchos a muchos entre evaluador y evaluación.

### **resultado_evaluacion:** 
Tabla que almacena los resultados totales de una evaluación a un proveedor y támbien su clasificación.


## :triangular_flag_on_post: **Preguntas**  :triangular_flag_on_post:

¿El valor asignado está predefinido para cada respuesta o lo decide el evaluador?
¿Es necesario almacenar el valor obtenido en cada una de las secciones padres?
¿En evaluador es mejor guardar el número de documento o directamente el persona_id?

**Comment by faidercamilo26** [comment]
## :triangular_flag_on_post: **Ajuste Modelo**  :triangular_flag_on_post:

Se ajusta el modelo para tener en cuentas las correcciones solicitadas, se divide el modelo en dos esquemas, uno que es el de la funcionalidad de evaluación proveedores y otro que es la estructura del modulo.



![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/126271909/4105c0b0-b3bd-4518-ac05-2936f870706d)

**Comment by faidercamilo26** [comment]
Se corrige el formato de las fechas para que estén de acuerdo a los lineamientos y se colocan notas instructivas de las tablas para su mayor entendimiento.



![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/126271909/ea61ae2e-564f-468c-b444-83b6afa0a1c1)





![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/126271909/48588e78-9a2c-4234-b6c7-273c3d3dc456)

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 Buen trabajo
