### ISSUE TITLE
Crear y refinar la parametrización de datos para el sistema cumplidos proveedores

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/Cumplidos_y_certificaciones_documentacion#63]
Se requiere realizar la creación y refinación la parametrización de datos para el sistema cumplidos proveedores

**Sub Tareas**

- [x] Construir el documento de parametrización de datos.
- [x] Refinar el documento con el equipo el documento.

**Criterios de aceptación**

- [x] Documento de parametrizaciín de datos definido

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se ha creado el documento de parametrización

[Documento parametrización](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EYq5JZKl4EhGgVNGZIpzpQcB1tC2KAO9QVGezgiIcOnixw?e=OWTzQs)

**Comment by jcmurilloa** [comment]
Buen trabajo @mantnicot, esta parametrización es ejemplo para desarrollar en los demás proyectos!
