### ISSUE TITLE
Construcción del acta de entregables módulos vista históricos CPS

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/Cumplidos_y_certificaciones_documentacion#64]
Se requiere construir el acta de entregables módulos vista históricos CPS teniendo en cuenta el formato https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EamQ7nH-CklEqAxb2h93NykBEKyZ5Ftyz6gppB-DI-OkMQ?e=7q3DzU

**Sub Tareas**

- [x] Proyectar acta de entregable
- [x] Presentar acta a líder de proyecto
- [x] Presentar a responsable de funcionamiento para aprobación
- [x] Recopilar las firmas respectivas

**Criterios de aceptación**

- [x] Acta firmada por las partes

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por líder de proyecto.

**Comment by JuanCamiloMartinezLopez** [comment]
Se comienza la realización del formato para el despliegue con funcionamiento

**Comment by JuanCamiloMartinezLopez** [comment]
Se crea la [acta de entregables](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EWDohW5nY2pMkRGJhLFVN9MBPUHZrF512nMLqOyoEIbxDg?e=dggZ3c)

**Comment by jcmurilloa** [comment]
Por favor @JuanCamiloMartinezLopez tener en cuenta los comentarios realizados en el daily de hoy y complementar previo a enviar a funcionamiento para firmas.

**Comment by JuanCamiloMartinezLopez** [comment]
Se realizan los ajustes al acta de entregables

**Comment by jcmurilloa** [comment]
Pendiente definición de usuario de cliente de control interno, con el ánimo de incluir en el acta y recolección de firmas.

**Comment by JuanCamiloMartinezLopez** [comment]
Se envíen los links para firma de los responsables, se espera a la firma de estos.

**Comment by jcmurilloa** [comment]
Muy buena información, se compartirá posteriormente informe consolidado y presentación para reunión de seguimiento.
