### ISSUE TITLE
Ajustes de pruebas de carga y seguridad del módulo de históricos cumplidos CPS - Parte I

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#65]
Se requiere realizar los siguientes ajustes resultantes de las pruebas de carga y seguridad: 

1. Agregar validación de dominio al CORS del [mid](https://github.com/udistrital/cumplidos_mid) y [crud](https://github.com/udistrital/cumplido_crud) tomado como ejemplo [resoluciones](https://github.com/udistrital/resoluciones_crud_v2/blob/develop/main.go)
2. Ajustar el controlador de solicitudes_pagos del mid para validar casos en que no se reciben valores como vigencia y dependencia.
3. Revisar y resolver los [casos](https://sonarqube.portaloas.udistrital.edu.co/project/issues?id=udistrital%3Acumplidos_cliente&resolved=false) de code smell

**Sub Tareas**

- [x] Realizar ajustes indicados.
- [x] Realizar los correspondientes pr a develop.

**Criterios de aceptación**

- [x] Ajustes realizados.
- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
## :triangular_flag_on_post: **Correcciones**  :triangular_flag_on_post:

1. Se realizan las modificaciones al archivo main.go para solucionar los errores de cors que se estaban generando.
2. Se ajusta el controlador SolicitudesPagoMensualController para manejar los casos de error cuando en los filtros se ingrese un dato de tipo incorrecto o no se ingrese alguna dependencia.


![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/126271909/191ff225-8ce1-4e6f-96c0-bcfe3dca7a02)



![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/126271909/4bb558ee-78ae-4633-80ad-18d71c32c91b)

3. Se resuelven los casos segun el code smell.

**Comment by faidercamilo26** [comment]
Se modifica el cuerpo de la respuesta en los casos que se ingrese un tipo de dato incorrecto en los filtros, para que este de acuerdo a la manera que se han venido trabajando este tipo de respuesta.



![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/126271909/c2c02911-ee42-4083-9d04-76a744c7c51a)

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 Buen trabajo
