### ISSUE TITLE
Ajustes de pruebas de carga y seguridad del módulo de históricos cumplidos CPS - Parte II

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#66]
Se requiere realizar los siguientes ajustes resultantes de las pruebas de carga y seguridad:

1. Investigar e implementar (de ser posible totalmente) guards para prevenir el routing directo sin el rol/permisos en el cliente de cumplidos CPS.
2. Eliminar variables, servicios y referencia de nuxeo, la única conexión a nuxeo es por el gestor_documental. 

**Sub Tareas**

- [x] Realizar ajustes indicados.
- [x] Realizar los correspondientes pr a develop.

**Criterios de aceptación**

- [x] Ajustes realizados.
- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by stevencol** [comment]
Se inicio con la actividad, No se pudo aplicar a todas las rutas como se deseaba debido a la falta de certeza sobre los roles con permisos en otras rutas, ya que algunos usuarios no tienen roles asignados.

Token perosnal: 
![image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/51761184/02af8ba9-b4df-4d0a-bd72-fe6b683a20a3)
}
Token Pruebas:
![image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/51761184/18d5db79-d7c8-4afc-8ae2-cd0c9e6136cf)

**Comment by stevencol** [comment]
Se eliminaron variables de entorno de nuxeo. en  environment, environment_test y environment_prod

**Comment by stevencol** [comment]
Para la protección de rutas se propone , crear servico para obtener lo roles del token y así dar acceso las rutas;

### Service
``` JavaScript
angular.module('contractualClienteApp').factory('RoleCheckService', ['$location', '$q', 'token_service', function($location, $q, token_service) {
    var RoleCheckService = {};

    RoleCheckService.checkRole = function(roles) {
        var deferred = $q.defer();

        var playLoad = token_service.getPayload();

        var userRoles = playLoad.role;

        if(!playLoad || !playLoad.role){

            $location.path("/");
            deferred.reject();
            return deferred.promise;
        }

        var hasPermission = roles.some(function(role) {
            return userRoles.includes(role);
        });

        console.log("Has Permission:", hasPermission);

        if (hasPermission) {
            deferred.resolve();
        } else {
            $location.path('/');
            deferred.reject();
        }

        return deferred.promise;
    };

    return RoleCheckService;
}]);

```

## App
``` JavaScript
 .when("/seguimientoycontrol/tecnico/historico_pagos", {
          templateUrl: "views/seguimientoycontrol/tecnico/historico_cumplidos.html",
          controller: "HistoricoCumplidosCtrl",
          controllerAs: "HistoricoCumplidos",
          
          resolve: {
              checkRole: ['RoleCheckService', function(RoleCheckService) {
                  return RoleCheckService.checkRole([
                      "ORDENADOR_DEL_GASTO",
                      "SUPERVISOR",
                      "CONTROL_INTERNO"
                  ]);
              }]
          }
      }
```
- Esta opción es funcional pero no permite que la aplicación sea escalable, ya que lo roles van directamente en el código  por lo que si se quiere modificar el rol o los permisos , se tendera que modificar el código

**Comment by stevencol** [comment]
# Propuesta 2

### Servicio

``` JavaScript
angular.module('contractualClienteApp')
  .factory('NavigationService', ['$rootScope', function($rootScope) {
    var internalNavigation = false;

 
    $rootScope.$on('$routeChangeSuccess', function(event, current, previous) {
      internalNavigation = true; 
    });

    console.log("Se ejecutoEl service");


    function checkNavigation() {
      return internalNavigation;
    }

    return {
      checkNavigation: checkNavigation
    };
  }]);
```

### implementacion
``` JavaScript
  .when("/seguimientoycontrol/tecnico/historico_pagos", {
          templateUrl:
            "views/seguimientoycontrol/tecnico/historico_cumplidos.html",
          controller: "HistoricoCumplidosCtrl",
          controllerAs: "HistoricoCumplidos",
          resolve: {
            checkNavigation: ['NavigationService', '$location', function(NavigationService, $location) {
              if (!NavigationService.checkNavigation()) {
                $location.path('/');
              }
            }]
          }
       
        })
```

- Esta opción protege correctamente el ingreso directo por URL, siempre y cuando no se pegue la url, ya que si se hace de esa manera si permite el ingreso, ya que AngularJS no puede detectar si se ingresó por navegación o por URL.

**Comment by stevencol** [comment]
feat: Eliminación de variables de Nuxeo en environment.js y environment_test.js

Se eliminaron las variables de Nuxeo en los archivos environment.js y environment_test.js.

**Comment by JuanCamiloMartinezLopez** [comment]
@stevencol Buen trabajo.
