### ISSUE TITLE
Concertar, Desarrollar y levantar el acta de sesión de requerimientos y/o refinamiento con el cliente

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/Cumplidos_y_certificaciones_documentacion#67]
Se requiere realizar la concertación, desarrollo y levantamiento del acta de sesión de requerimientos y/o refinamiento con el cliente del mockup del sistema cumplidos proveedores

**Sub Tareas**

- [x] Concertar reunión con el cliente.
- [x] Desarrollar la reunión con el cliente.
- [x] Diligenciamiento y aprobación del Mockup por parte del cliente (si aplica).
- [x] Proyectar acta de la reunión.
- [x] Recolectar las firmas correspondientes.

**Criterios de aceptación**

- [x] Acta revisada por el líder de proyecto.
- [x] Acta firmada por las partes con anexo de historias de usuario o mockup.
- [x] Acta y anexos documentados.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se adjunta el acta de la reunión del día 02/07/2024 a las 2 pm 


[Acta sin firma](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/ERvs5R1LoupKgqUNykFt1X4BCtLE5DQgL81u6xP7oYY80g?e=Ktd1Gx)

**Comment by mantnicot** [comment]
Se adjunta el acta con las respectiva firmas de los asistentes

[Acta firmada](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EX1QECDtgnhAvYhSgseOakUB3UtR9aKG5EQw6-HB8OYbmQ?e=giUupC)

**Comment by jcmurilloa** [comment]
Buen trabajo @mantnicot, recuerda comentar en la issue, la respectiva grabación cuando sea el caso.
