### ISSUE TITLE
Actualización diagrama de flujo del sistema cumplidos proveedores

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/Cumplidos_y_certificaciones_documentacion#68]
Se requiere realizar la actualización del diagrama de flujo del sistema de cumplidos proveedores

**Sub Tareas**

- [x] Repasar diagrama de flujo general del sistema
- [x] Generar las modificaciones según requerimientos
- [x] Presentar al equipos SoS diagrama actualizado
- [x] Aprobar con el cliente diagrama actualizado

**Criterios de aceptación**

- [x] Diagrama de flujo del sistema actualizado

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se ha creado el flujo del sistema 

![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/85162258/f69b1eb8-2f34-4daf-b303-fefe3af6eade)




[Flujo sistema proveedores](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/Es-t3KXtAEVLr5EiIDF2RvkBaY3jlH73Da_-VD3dA_Uaqg?e=148Mgs)

**Comment by jcmurilloa** [comment]
Muy buen trabajo @mantnicot, lo repasaremos junto con @JuanCamiloMartinezLopez en la póxima SoS.

**Comment by jcmurilloa** [comment]
Por favor tener en cuenta las sugerencias realizadas en la sesión SoS y presentar nuevamente.

**Comment by mantnicot** [comment]
Se ha realizado los cambios de parte del equipo



![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/85162258/d149384a-8d72-43e3-94e3-a1c37bf9cd2e)

[Carpeta flujo](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EjP3As9CHI5PknizyT2eZIUBQYR4P5K4IFxL-GCpiX4CpQ?e=vb0CWb)

**Comment by jcmurilloa** [comment]
Este diseño con los estados se ve super @mantnicot, pendiente exponer al cliente.

**Comment by jcmurilloa** [comment]
Tener en cuenta los comentarios realizados en la sesión SoS.

**Comment by mantnicot** [comment]
Se han realizado los cambios dados por el equipo 




![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/85162258/cfbbbe0a-8767-4a33-97ff-4398c56749b1)

[Carpeta flujo](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/Em29HURH7bFNpoQV1ScIs40Br1ebS4LerYD11kmKjAWy9Q?e=HZPi69)

**Comment by jcmurilloa** [comment]
Acogidas las sugerencias, el diagrama esta listo para ser compartido con el cliente y generar su aprobación. Buen trabajo @mantnicot

**Comment by mantnicot** [comment]
Se ha generado aprobación de parte del cliente

![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/85162258/bf4c5c89-1d4c-4492-8c56-d5d6a0204c5d)

**Comment by jcmurilloa** [comment]
Excelente trabajo @mantnicot.
