### ISSUE TITLE
Crear y configurar proyecto root para el sistema de cumplidos proveedores

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#69]
Se requiere realizar la creación del proyecto root, así como su configuración según los [lineamientos](https://github.com/udistrital/lineamientos_oas/blob/master/single_spa/root_config.md) 

**Sub Tareas**

- [x] Clonar el [repositorio](https://github.com/udistrital/cumplidos_proveedores_root_mf) y crear la rama develop.
- [x] Crear el root según los lineamientos.
- [x] Agregar configuraciones base, tomar como ejemplo el [sga_root](https://github.com/udistrital/sga_cliente_root)
- [x] Agregar la información necesaria al README.

**Criterios de aceptación**

- [x] commit(s) del proyecto root creado y configurado en develop
- [x] Issue documentada con los pasos realizados.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
## :triangular_flag_on_post: **Creación Root**  :triangular_flag_on_post:


1. Se crea la rama develop y se espera para que el lider la configure como la rama por defecto.

2. Se realiza la creación del root con las configuraciones base que están en los lineamientos, falta implementar los assets y la paleta de colores, se tienen algunas dudas sobre estos temas y por eso se consulta con líder para poderlas aclarar y finalizar totalmente la issue.

3. Se actualiza la información del archivo readme.

**Comment by faidercamilo26** [comment]
Se realizan las configuraciones de los assets en el root pero aparece un error, se está trabajando para solucionarlo.



![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/126271909/d111aea1-563e-42c3-9ec4-0aef03da2fc6)

**Comment by faidercamilo26** [comment]
Se resuelve el inconveniente y se finaliza la creación del root correctamente con todas las configuraciones iniciales, se monta el core para verificar que el root esté funcionando correctamente y en efecto funciona bien.



![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/126271909/086d4297-cab4-47b3-ad42-48d9a24a0ffc)



![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/126271909/384d3cfb-ebf7-4316-82a9-b077297c8783)



![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/126271909/209c2c4d-16a1-4c1d-bd1b-ca252a910912)

**Comment by faidercamilo26** [comment]
Se soluciona el problema de diseño con el core para que se vea bien estéticamente y el Layout quede en la parte inferior.



![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/126271909/67cc375b-b4c0-4cf3-bb2c-8359464f5850)

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 Buen trabajo
