### ISSUE TITLE
Crear y configurar micro cliente para el módulo de revisión de cumplidos proveedores

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#70]
Se requiere realizar la creacion y configuracion del micro cliente para el módulo de revisión de cumplidos proveedores siguiendo los [lineamientos](https://github.com/udistrital/lineamientos_oas/blob/master/single_spa/parcel.md).

**Sub Tareas**

- [x] Clonar el [repositorio](https://github.com/udistrital/revision_cumplidos_proveedores_mf) y crear la rama develop.
- [x] Crear el parcel según los lineamientos.
- [x] Agregar configuraciones base, tomar como ejemplo el [sga_cliente_admisiones_mf](https://github.com/udistrital/sga_cliente_admisiones_mf)
- [x] Agregar la información necesaria al README.

**Criterios de aceptación**

- [x] commit(s) del micro cliente base creado y configurado en develop
- [x] Issue documentada con los pasos realizados.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by stevencol** [comment]
#### Seda inicio a la actividad ✅

**Comment by stevencol** [comment]
#### Creación de Rama develop
--------------------------------
- Se crea rama develop

#### Creación de parcel
-------------------------
- Se crea parcel  utilizando Node.js 18 y Angular 16.
- se agrega configuraron inicial el cual incluye: cambio de nombre del componente principal, creación de environments

**Comment by JuanCamiloMartinezLopez** [comment]
@stevencol Buen trabajo
