### ISSUE TITLE
Desarrollar vista para la creación de cumplidos - supervisor - parte I

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#71]
Se requiere realizar la interfaz base para la creación de los cumplidos por parte de un supervisor siguiendo el [mockup](https://udistritaleduco-my.sharepoint.com/personal/juacmartinezl_udistrital_edu_co/_layouts/15/onedrive.aspx?listurl=%2Fpersonal%2Fcomputo%5Fudistrital%5Fedu%5Fco%2FDocuments&id=%2Fpersonal%2Fcomputo%5Fudistrital%5Fedu%5Fco%2FDocuments%2FINVERSI%C3%93N%2FPROYECTOS%20DE%20INVERSI%C3%93N%2FGERENCIA%20DE%20PROYECTOS%2FPROYECTOS%20OAS%2FPROYECTO%20CUMPLIDOS%20Y%20CERTIFICACIONES%2F2024%2FEjecuci%C3%B3n%2FAnalista%20de%20requerimientos%2FCUMPLIDOS%2FCumplidos%20Proovedores%2FMockups%2Fv4%2FCliente%20cumplidos%20proveedores%20v4%20%2DCUMPLIDO%20PROVEEDORES%20CLIENTE%20v1%20vista%20carga%20de%20soportes%20%2Edrawio%2Epng&parent=%2Fpersonal%2Fcomputo%5Fudistrital%5Fedu%5Fco%2FDocuments%2FINVERSI%C3%93N%2FPROYECTOS%20DE%20INVERSI%C3%93N%2FGERENCIA%20DE%20PROYECTOS%2FPROYECTOS%20OAS%2FPROYECTO%20CUMPLIDOS%20Y%20CERTIFICACIONES%2F2024%2FEjecuci%C3%B3n%2FAnalista%20de%20requerimientos%2FCUMPLIDOS%2FCumplidos%20Proovedores%2FMockups%2Fv4) presentado.

**Sub Tareas**

- [ ] Realizar el desarrollo en el [mf](https://github.com/udistrital/revision_cumplidos_proveedores_mf/tree/develop) 
- [ ] Crear la estructura base de las tablas usando angular material.
- [ ] Agregar los modales intentado crear un componente para estos.

**Criterios de aceptación**

- [ ] Commits con vista base desarrollada.
- [ ] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by stevencol** [comment]
-Se inicia con la instalación de Angular Material en la rama develop

**Comment by JuanCamiloMartinezLopez** [comment]
@stevencol Por favor comentar el issue con los avances, problemas y limitaciones en el desarrollo

**Comment by stevencol** [comment]
@JuanCamiloMartinezLopez  Disculpa  comente en la issue equivocada:

Se avanza en desarrollo , se tiene dificúltateles en el diseño, los incono en el segmento Acciones no cargan, el ancho y altura de la tabla no se logran ajustar,
![image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/51761184/4aa28c8c-53e3-4f23-887a-7d9c6ffc9e9e)


se esta importando : 
@import url("https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,300,0,0"); 
para los iconos pero no se reconoce

**Comment by stevencol** [comment]
se sigue avanzando en la actividad, se me presentan inconvenientes al separar los elementos  label , inputs y buttons 
![image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/51761184/43f808b4-cc82-45e5-861c-f460ba74ab16)

**Comment by stevencol** [comment]
Se termina con la maquetación de la vista 
![test](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/51761184/067125e5-ba7f-467e-a364-2d7af35336b2)

**Comment by JuanCamiloMartinezLopez** [comment]
@stevencol  buen trabajo
