### ISSUE TITLE
Desarrollar vista para la creación de cumplidos - supervisor - parte II

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#72]
Se requiere realizar la interfaz base para la creación de los cumplidos por parte de un supervisor siguiendo el [mockup](https://udistritaleduco-my.sharepoint.com/:i:/g/personal/computo_udistrital_edu_co/EeZqkMTCam9Bt5z58c4r-uwBOAsPKJM2XvQdb1ttlp3qag?e=iYsHFk) presentado.

**Sub Tareas**

- [x] Realizar el desarrollo en el [mf](https://github.com/udistrital/revision_cumplidos_proveedores_mf/tree/develop) 
- [x] Crear un componente de visualización de archivos reutilizable.
- [x] Permitir diferentes funcionalidades del componente de visualización según el estado( ej: eliminar, ver, etc)

**Criterios de aceptación**

- [x] Commits con vista base desarrollada.
- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
Se inicia con la actividad

**Comment by faidercamilo26** [comment]
Se revisa la documentación de [angular material](https://material.angular.io/components/menu/overview), también se revisa la forma que se implementa la carga de documentos en el sistema de cumplidos CPS

**Comment by faidercamilo26** [comment]
Se avanza con la implementación de la vista para cargar archivos, sin embargo, me aparece un error cuando intento instalar angular material.



![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/126271909/4affce35-86f6-486d-8ee6-97c4d759d487)

**Comment by faidercamilo26** [comment]
Se tuvieron inconvenientes principalmente con la importación de los estilos definidos por la oati, sin embargo, se desarrolla una primera vista del cliente solicitado y se espera finalizar la construcción el día de hoy.

 

![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/126271909/d729f1a6-9917-4812-b7ce-820993179fb0)

**Comment by faidercamilo26** [comment]
Se finaliza la creación completa de la vista de carga y visualización de los documentos de un cumplido, se tienen dudas con unos estilos, por lo tanto, se espera al daily para hacer la respectiva consulta y poder realizar el commit correspondiente con el código final.



![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/126271909/74a2fdf9-1045-4a3e-92b4-d1510a23244c)

**Comment by faidercamilo26** [comment]
## :triangular_flag_on_post: **Vista para subir documentos de un cumplido**  :triangular_flag_on_post:


Se realizan las correcciones comentadas en el daily, se redondean los campos donde se visualizan las observaciones,se disminuyen los espacios que hay entre los componentes de visualización de cada uno de los documentos, se intenta marcar mas los bordes de estos componentes, sin embargo, no se encuentra una propiedad adecuada que haga que los estilos concuerden con los que ya se estan manejando en la vista.



![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/126271909/ab1714e0-b529-4290-9fa6-eec74a44eb60)




![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/126271909/e77df5b5-7e18-4140-bad3-5c9bef45f719)




![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/126271909/37f4526e-7a79-4853-8c8e-3d52c2289982)

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 Buen trabajo
