### ISSUE TITLE
Ajustar modelo de revisión de cumplidos proveedores

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#73]
Se requiere realizar los ajustes indicados por los DBA al modelo [propuesto v1](https://udistritaleduco-my.sharepoint.com/:i:/r/personal/computo_udistrital_edu_co/Documents/INVERSI%C3%93N/PROYECTOS%20DE%20INVERSI%C3%93N/GERENCIA%20DE%20PROYECTOS/PROYECTOS%20OAS/PROYECTO%20CUMPLIDOS%20Y%20CERTIFICACIONES/2024/Ejecuci%C3%B3n/Gesti%C3%B3n%20t%C3%A9cnica/CUMPLIDOS/Proveedores/Modelos%20de%20base%20de%20datos/Revisi%C3%B3n%20cumplidos%20proveedores/propuesta%20revision%20cumplidos%20v1.png?csf=1&web=1&e=csuEqa).

**Sub Tareas**

- [x] Eliminar columnas de fecha_creacion y fecha_modificación de las tablas paramétricas.
- [x] Validar tipos de datos para fechas que sean timestamp como lineamiento genérico.
- [x] Subir el nuevo modelo a la [carpeta del proyecto](https://udistritaleduco-my.sharepoint.com/:f:/r/personal/computo_udistrital_edu_co/Documents/INVERSI%C3%93N/PROYECTOS%20DE%20INVERSI%C3%93N/GERENCIA%20DE%20PROYECTOS/PROYECTOS%20OAS/PROYECTO%20CUMPLIDOS%20Y%20CERTIFICACIONES/2024/Ejecuci%C3%B3n/Gesti%C3%B3n%20t%C3%A9cnica/CUMPLIDOS/Proveedores/Modelos%20de%20base%20de%20datos/Revisi%C3%B3n%20cumplidos%20proveedores?csf=1&web=1&e=en0gkr)

**Criterios de aceptación**

- [ ] Issue documentada.
- [ ] Modelo ajustado. 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by jcmurilloa** [comment]
El día de ayer cerró el sprint y la issue se encuentra a la fecha sin comentarios. Recuerden que es fundamental generar acciones en este aparatado @JuanCamiloMartinezLopez @stevencol

**Comment by stevencol** [comment]
Se inicia con el Issue.

**Comment by stevencol** [comment]
Se realizan modificaciones indicadas

![propuesta revision cumplidos v2](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/51761184/57dd0603-517e-403a-b709-ad51056e5b20)

**Comment by JuanCamiloMartinezLopez** [comment]
@stevencol Buen trabajo
