### ISSUE TITLE
Ajustar modelo de evaluación y estructura de evaluación de cumplidos proveedores

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#74]
Se requiere realizar los ajustes indicados por los DBA al modelo [propuesto v1](https://udistritaleduco-my.sharepoint.com/:f:/r/personal/computo_udistrital_edu_co/Documents/INVERSI%C3%93N/PROYECTOS%20DE%20INVERSI%C3%93N/GERENCIA%20DE%20PROYECTOS/PROYECTOS%20OAS/PROYECTO%20CUMPLIDOS%20Y%20CERTIFICACIONES/2024/Ejecuci%C3%B3n/Gesti%C3%B3n%20t%C3%A9cnica/CUMPLIDOS/Proveedores/Modelos%20de%20base%20de%20datos/Evaluaci%C3%B3n%20cumplidos%20proveedores?csf=1&web=1&e=UVF8ec).

**Sub Tareas**

- [x] Eliminar columnas de fecha_creacion y fecha_modificación de las tablas paramétricas.
- [x] Validar tipos de datos para fechas que sean timestamp como lineamiento genérico.
- [x] Modelar una propuesta de manejo de estados para las evaluaciones teniendo en cuenta múltiples evaluadores.
- [x] Subir el nuevo modelo a la [carpeta del proyecto](https://udistritaleduco-my.sharepoint.com/:f:/r/personal/computo_udistrital_edu_co/Documents/INVERSI%C3%93N/PROYECTOS%20DE%20INVERSI%C3%93N/GERENCIA%20DE%20PROYECTOS/PROYECTOS%20OAS/PROYECTO%20CUMPLIDOS%20Y%20CERTIFICACIONES/2024/Ejecuci%C3%B3n/Gesti%C3%B3n%20t%C3%A9cnica/CUMPLIDOS/Proveedores/Modelos%20de%20base%20de%20datos/Revisi%C3%B3n%20cumplidos%20proveedores?csf=1&web=1&e=en0gkr)

**Criterios de aceptación**

- [x] Issue documentada.
- [x] Modelo ajustado. 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by jcmurilloa** [comment]
El día de ayer cerró el sprint y la issue se encuentra a la fecha sin comentarios. Recuerden que es fundamental generar acciones en este aparatado @JuanCamiloMartinezLopez @faidercamilo26

**Comment by faidercamilo26** [comment]
Se realizan las correcciones comentadas por los dba, se agregan a la [carpeta del proyecto](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/Et2j7RxhiPZGqoiEKsLSP84BDKsvhch5k9ghwaaJc5bnSw?e=JNBp4w) y se dejan las imágenes de los modelos  acá también.



![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/126271909/d3e487c4-4df1-4845-b34a-9ee51758673c)




![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/126271909/e0f45e0b-cfce-44a3-b472-d69f85baad2a)

**Comment by faidercamilo26** [comment]
Se realizan los ajustes comentados en el daily del día de hoy y se adjuntan los modelos corregidos, en la carpeta del proyecto no me permite crear la carpeta de la v3 de los modelos por eso solo se adjuntan los modelos en la issue.



![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/126271909/134f5784-a473-49d7-b2ab-417d6bda0d4e)




![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/126271909/6c11b068-205c-4d21-aa5d-4df204c75151)

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 Buen trabajo
