### ISSUE TITLE
Concertar, Desarrollar y levantar el acta de sesión de requerimientos y/o refinamiento para servicio Cóndor

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/Cumplidos_y_certificaciones_documentacion#75]
Se requiere realizar la concertación, desarrollo y levantamiento de requerimientos para servicio Cóndor

**Sub Tareas**

- [x] Concertar reunión exploratoria con el cliente
- [x] Desarrollar la reunión exploratoria
- [x] Proyectar acta de la reunión

**Criterios de aceptación**

- [x] Acta revisada por el líder de proyecto
- [x] Acta firmada por las partes

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se ha podido contactar con Jairo la persona que nos puede guiar para obtener esa informaciòn sobre el servicio

**Comment by mantnicot** [comment]
Se ha podido agendar la reunión a las 10:00 am el día 9/07/2024 

[Link reunion](https://teams.microsoft.com/l/meetup-join/19%3ameeting_OTc3NjA0MWMtMjQ4Yy00N2VlLTkyM2ItMTRkOTQ5Y2E2ZmZk%40thread.v2/0?context=%7b%22Tid%22%3a%22d51388ef-6ab0-4363-9f94-d56644a45970%22%2c%22Oid%22%3a%221dd8bdce-0185-41b4-8caa-01da7e5506b2%22%7d)

**Comment by mantnicot** [comment]
Se ha realizado la reunión donde se toco el tema del servicio de carga de los docentes, Jairo explico que ahorita están desarrollando un modulo de servicio por el cual se manejaría ese proceso , actualmente solo se puede acceder desde la vpn en entorno local , por lo cual toca esperar a que se realice el despliegue , mientras tanto se generan los compromisos: 

- Crear la solicitud en tuleap para que información se requiere traer
- Desplegar el modulo para poder obtener el servicio

**Comment by jcmurilloa** [comment]
Gracias @mantnicot por los comentarios y compromisos derivados de la reunión. De esta manera por favor @JuanCamiloMartinezLopez realizar commit en esta issue con el radicado de Tuleap.

**Comment by JuanCamiloMartinezLopez** [comment]
Se crea el [kb](https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=62307) en tuleap según lo indicado en la reunion

**Comment by jcmurilloa** [comment]
Estaremos atentos a la respuesta brindadapor parte del responsable, con el fin de proyectar el siguiente paso.

**Comment by mantnicot** [comment]
Se ha podido realizar un contacto con la persona a cargo y se esta gestionando la información via whatsapp , en caso de que el meido no funcione , se buscara a futuro tener una reunión.

**Comment by jcmurilloa** [comment]
@mantnicot Por favor generar un contacto nuevamente con el responsable pendiente de la firma, en caso de no obtener respuesta favorable, por favor contactarme internamente para gestión con patrocinador del proyecto.

**Comment by jcmurilloa** [comment]
No se brinda respuesta a la fecha por parte del área encargada por medio de Tuleap. Se estará atento a la respuesta a la solicitud por parte del responsable, y con base a este trámite, se programarán las issues correspondientes.

**Comment by mantnicot** [comment]
Se ha dado una actualización de parte de Jairo, se espera poder confirmar la respuesta en tuleap



![Image](https://github.com/user-attachments/assets/f426af73-304b-42ba-922b-412d6b85afc2)
