### ISSUE TITLE
Concertar, desarrollar y levantar el acta de sesión de entrega de vista histórico con funcionamiento y cliente

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/Cumplidos_y_certificaciones_documentacion#76]
Se requiere realizar la concertación, desarrollo y levantamiento del acta de sesión de entrega de vista histórico con funcionamiento y cliente
**Sub Tareas**

- [x] Concertar reunión con el cliente y funcionamiento
- [x] Desarrollar la reunión con el cliente y funcionamiento
- [x] Proyectar acta de la reunión con el cliente y funcionamiento

**Criterios de aceptación**

- [x] Acta revisada por el líder de proyecto
- [ ] Acta firmada por las partes

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico/SoSM.
- [ ] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se ha podido concretar la reunión con control interno a las 11:00 am 09/07/2024 

[link reunión](https://teams.microsoft.com/l/meetup-join/19%3ameeting_YmYzZTdkODgtY2Q1MS00OGJjLWFlOWQtYjZiZTQ0OWU4M2Mx%40thread.v2/0?context=%7b%22Tid%22%3a%22d51388ef-6ab0-4363-9f94-d56644a45970%22%2c%22Oid%22%3a%22b989c328-89fa-4486-abfe-df75fdd723ba%22%7d)

**Comment by mantnicot** [comment]
Se ha creado el acta correspondiente sin firmas

[Acta a espera de firmas ](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EU-POAypftVLuEyH4ovLNcIBJVEzzVQVw2ScEJtI0fL5PQ?e=RNiYZk)

**Comment by jcmurilloa** [comment]
@mantnicot en el punto de comentarios y conclusiones no se refleja la participación de la oficina de control interno. Se sugiere describir que el cliente aceptó el módulo según la muestra de la reunión, pues es era el objetivo del encuentro. Por favor realizar los cambios sugeridos antes de enviar a recolección de firmas.

**Comment by jcmurilloa** [comment]
@mantnicot Por favor generar un contacto nuevamente con el responsable pendiente de la firma, en caso de no obtener respuesta favorable, por favor contactarme internamente para gestión con patrocinador del proyecto.

**Comment by jcmurilloa** [comment]
El funcionario encargado de la firma restante, no tiene intención de firmar sin antes cumplir con un requerimiento que no hace parte de la competencia del proyecto. De esta manera se procede a cerrar el issue con el estado del documento actual.
