### ISSUE TITLE
Desarrollar vista para la creación del informe de seguimiento proveedores

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#77]
Se requiere realizar la interfaz base para la creación del informe de seguimiento proveedores por parte de un supervisor siguiendo el [mockup](https://udistritaleduco-my.sharepoint.com/:i:/g/personal/computo_udistrital_edu_co/ESuYSJn_hzlIkWUgnfKx1g4BCGB6dT5q09Vi6whMX7F5Kg?e=HGfI5O) presentado.

**Sub Tareas**

- [x] Realizar el desarrollo en el [mf](https://github.com/udistrital/revision_cumplidos_proveedores_mf/tree/develop) 
- [x] Crear la estructura de formulario base.

**Criterios de aceptación**

- [x] Commits con vista base desarrollada.
- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
## :triangular_flag_on_post: **Vista creación informe de seguimiento**  :triangular_flag_on_post:

Se inicia con la creacion de la vista solicitada.

**Comment by faidercamilo26** [comment]
Se divide la vista en 3 componentes con el fin de construirla lo más modular posible, se realiza la creación del primer componente que va a ser el contenedor de los otros dos y se avanza un poco con la implementación del segundo componente.




![Image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/126271909/68a47db9-026a-4f88-8d30-042656866fbd)

**Comment by faidercamilo26** [comment]
Se finaliza con la tarea de la creación de la vista para la generación de los informes de gestión de los proveedores, se tiene una duda acerca del estilo de colores que se esta usando en el microcliente, puesto que la gama de colores actual con los inputs es azul, cuando una parte del formulario esta incorrecto el color es amarillo, lo que no esta de acuerdo con los colores que se deberían estar manejando en el proyecto de cumplidos proveedores.



![Image](https://github.com/user-attachments/assets/6c79c261-c7f2-4bde-ba43-66cd25efe037)

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 Buen trabajo
