### ISSUE TITLE
Desarrollar vista para la revisión por parte de contratacion

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#78]
Se requiere realizar la interfaz base para la revision de los cumplidos por parte de la oficina de contratacion siguiendo el [mockup](https://udistritaleduco-my.sharepoint.com/:i:/g/personal/computo_udistrital_edu_co/EdcvkiBL38VHg4dJtgzZDgUBqgY9T_aoKcsvlz6OzVlkug?e=4ot6np) presentado.

**Sub Tareas**

- [ ] Realizar el desarrollo en el [mf](https://github.com/udistrital/revision_cumplidos_proveedores_mf/tree/develop) 
- [ ] Crear la estructura base de la tabla usando angular material.
- [ ] Agregar los modales o consumir  el o los componentes necesarios.

**Criterios de aceptación**

- [ ] Commits con vista base desarrollada.
- [ ] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by stevencol** [comment]
Se inicia con la activa, en conjunto con  #udistrital/Cumplidos_y_certificaciones_documentacion#79 , ya que son muy similares

**Comment by stevencol** [comment]
Se termina con la creación  de  las vistas para  Contratación:  
![test](https://github.com/user-attachments/assets/fab00084-f823-4e7a-91bd-d121623cf638)

**Comment by JuanCamiloMartinezLopez** [comment]
@stevencol Buen trabajo
