### ISSUE TITLE
Desarrollar vista para la revisión por parte de un ordenador

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#79]
Se requiere realizar la interfaz base para la revision de los cumplidos por parte de un ordenador siguiendo el [mockup](https://udistritaleduco-my.sharepoint.com/:i:/g/personal/computo_udistrital_edu_co/EVhPFHCnDo5OqHJOUO99H_sBiMxI9CYizS3fk_JFvGZCuA?e=0WfSay) presentado.

**Sub Tareas**

- [ ] Realizar el desarrollo en el [mf](https://github.com/udistrital/revision_cumplidos_proveedores_mf/tree/develop) 
- [ ] Crear la estructura base de la tabla usando angular material.
- [ ] Agregar los modales o consumir  el o los componentes necesarios.

**Criterios de aceptación**

- [ ] Commits con vista base desarrollada.
- [ ] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by stevencol** [comment]
Se avanza en desarrollo , se tiene dificúltateles en el diseño, los incono en el segmento Acciones no cargan, el ancho y altura de la tabla no se logran ajustar,
![image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/51761184/4aa28c8c-53e3-4f23-887a-7d9c6ffc9e9e)


se esta importando : 
@import url("https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,300,0,0"); 
para los iconos pero no se reconoce

**Comment by stevencol** [comment]
Se inicia con Issue:

**Comment by stevencol** [comment]
Avance: 
*los bordes se usan como guía del posicionamiento de los div 
![image](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/51761184/8756ac93-88e3-44f1-8621-f6046ba8bedd)

**Comment by stevencol** [comment]
- Se Termia vista para la revisión por parte de un ordenador, 
* La vista Carga soportes no está relacionada
![test](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/assets/51761184/8b1778d3-d432-480b-86bf-5293a0be6f9a)

**Comment by JuanCamiloMartinezLopez** [comment]
@stevencol Buen trabajo
