### ISSUE TITLE
Creación api crud base para el módulo de revisión cumplidos proveedores

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#80]
Se requiere realizar la creación del api crud base para el módulo de revisión cumplidos proveedores en golang(beego) partiendo del [modelo](https://udistritaleduco-my.sharepoint.com/:i:/g/personal/computo_udistrital_edu_co/ETR13APeEt9Cku_p9ETMLHsBX3gWlmA8MXTQynx2_YrZbw?e=HJTHmM).

**Sub Tareas**

- [x] Clonar el repositorio [revision_cumplidos_proveedores_crud](https://github.com/udistrital/revision_cumplidos_proveedores_crud)
- [x] Creación API REST siguiendo los [lineamientos](https://github.com/udistrital/lineamientos_oas?tab=readme-ov-file#generaci%C3%B3n-api-crud).
- [x] Modificación endpoint de eliminación para realizar la eliminación lógica.

**Criterios de aceptación**

- [x] Issue documentada.
- [x] Proyecto base creado y commit realizado.

**Requerimientos**

- Completar la Issue #73.
- [Aprobación del modelo de datos](https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=62102&group_id=177).

**Especificaciones técnicas**
1. Repositorio de este nuevo microservicio [revision_cumplidos_proveedores_crud](https://github.com/udistrital/revision_cumplidos_proveedores_crud).

**Lineamientos Generales**
Lineamientos que se deben cumplir en cualquier desarrollo.
1. [Lineamiento y Metodología para Branches](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/nombre_branch.md)
2. [Etiquetas en comentarios de Commits](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/etiqueta_commits.md)
3. Seguir los lineamientos para la documentación del README [Contenido README](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/contenido_readme.md)

**Lineamientos Microservicios**
1. Definición de endpoints para APIs REST [Hoja resumen de buenas prácticas](https://udistritaleduco-my.sharepoint.com/:p:/g/personal/computo_udistrital_edu_co/EYwQbkAKVCJCqrmJ7NgnjQ4B8WSd81vxGVx-hqi0WBAcfQ?e=lJZdx8) y [Aclaración y ejemplos de nombres adecuados para endpoints](https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/lineamientos-endpoints.md)
2. Guiarse en la construcción del microservicio basado en los lineamientos de [APIS Beego](https://github.com/udistrital/lineamientos_oas?tab=readme-ov-file#5-apis-beego-mortar_board) si se usa Golang
3. Guiarse de los lineamientos de [ambientes dockerizados](https://github.com/udistrital/lineamientos_oas/blob/master/ambientes_dockerizados/dockerizacion.md)
4. [(health check) validación de estado en APIs](https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/endpoint_validacions.md#health-check-validaci%C3%B3n-de-estado-en-apis)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
Se pretende iniciar con el desarrollo del api_crud, sin embargo, al abrir el programa pg admin para hacer la respectiva ejecución del script me aparece un error, el cual está al parecer relacionado con posibles errores de acceso a carpetas de componentes que la aplicación necesita para funcionar, se está realizando la búsqueda en internet para resolver esta situación.



![Image](https://github.com/user-attachments/assets/6e689be5-e706-4958-927a-b71b3feb25ef)

**Comment by faidercamilo26** [comment]
## :triangular_flag_on_post: **Api crud revisión cumplidos proveedores**  :triangular_flag_on_post:

Al buscar soluciones para el inconveniente anteriormente mencionado solo se encuentran soluciones para el sistema operativo windows, por lo tanto, se desinstala totalmente la aplicación pg admin y se realiza su instalación desde cero y funciona. Se crea el api crud para el módulo de revisión cumplidos proveedores, se siguen todos los lineamientos definidos por la oati y se realizan las configuraciones base, solo queda faltando la modificación endpoint de eliminación para realizar la eliminación lógica, puesto que no tengo entero conocimiento de como se genera este proceso.



![Image](https://github.com/user-attachments/assets/d622a0ea-ca3f-429c-b752-96ddb52264e6)

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 Para el soft delete, dentro de las funciones cambiar la función Delete del orm por un update cambiando el valor de activo,  ej:

```golang
func DeleteCambioEstadoCumplido(id int) (err error) {
	o := orm.NewOrm()
	v := CambioEstadoCumplido{Id: id}
	// ascertain id exists in the database
	if err = o.Read(&v); err == nil {
		var num int64
                v.Activo = false
		if num, err = o.Update(v); err == nil {
			fmt.Println("Number of records deleted in database:", num)
		}
	}
	return
}
```
tambien porfa agregar el filtro por múltiples valores, ejemplo a continuación: 

```golang
func GetAllInforme(query map[string]string, fields []string, sortby []string, order []string,
	offset int64, limit int64) (ml []interface{}, err error) {
	o := orm.NewOrm()
	qs := o.QueryTable(new(Informe))
	// query k=v
	for k, v := range query {
		// rewrite dot-notation to Object__Attribute
		k = strings.Replace(k, ".", "__", -1)
		if strings.Contains(k, "isnull") {
			qs = qs.Filter(k, (v == "true" || v == "1"))
		} else if strings.HasSuffix(k, "in") {
			arr := strings.Split(v, "|")
			qs = qs.Filter(k, arr)
		} else {
			qs = qs.Filter(k, v)
		}
	}
```

**Comment by faidercamilo26** [comment]
Se agregan a todos los modelos la modificación  correspondiente para realizar la eliminación lógica y se agrega filtro múltiples valores.

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 Buen trabajo
