### ISSUE TITLE
Creación api mid base para el módulo de revisión cumplidos proveedores

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#81]
Se requiere realizar la creación del api mid base para el módulo de revisión cumplidos proveedores en golang(beego).

**Sub Tareas**

- [x] Clonar el repositorio [revision_cumplidos_proveedores_mid](https://github.com/udistrital/revision_cumplidos_proveedores_mid)
- [x] Creación API REST siguiendo los [lineamientos](https://github.com/udistrital/lineamientos_oas?tab=readme-ov-file#generaci%C3%B3n-api-mid).

**Criterios de aceptación**

- [x] Issue documentada.
- [x] Proyecto base creado y commit realizado.

**Requerimientos**

No aplica

**Especificaciones técnicas**
1. Repositorio de este nuevo microservicio [revision_cumplidos_proveedores_mid](https://github.com/udistrital/revision_cumplidos_proveedores_mid).

**Lineamientos Generales**
Lineamientos que se deben cumplir en cualquier desarrollo.
1. [Lineamiento y Metodología para Branches](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/nombre_branch.md)
2. [Etiquetas en comentarios de Commits](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/etiqueta_commits.md)
3. Seguir los lineamientos para la documentación del README [Contenido README](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/contenido_readme.md)

**Lineamientos Microservicios**
1. Definición de endpoints para APIs REST [Hoja resumen de buenas prácticas](https://udistritaleduco-my.sharepoint.com/:p:/g/personal/computo_udistrital_edu_co/EYwQbkAKVCJCqrmJ7NgnjQ4B8WSd81vxGVx-hqi0WBAcfQ?e=lJZdx8) y [Aclaración y ejemplos de nombres adecuados para endpoints](https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/lineamientos-endpoints.md)
2. Guiarse en la construcción del microservicio basado en los lineamientos de [APIS Beego](https://github.com/udistrital/lineamientos_oas?tab=readme-ov-file#5-apis-beego-mortar_board) si se usa Golang
3. Guiarse de los lineamientos de [ambientes dockerizados](https://github.com/udistrital/lineamientos_oas/blob/master/ambientes_dockerizados/dockerizacion.md)
4. [(health check) validación de estado en APIs](https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/endpoint_validacions.md#health-check-validaci%C3%B3n-de-estado-en-apis)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by stevencol** [comment]
-Se inicia con Issue  , clonado repositorio

**Comment by stevencol** [comment]
Se realiza creacion del api mid:

*Se uso go versión : 1.18*

***se usaron las siguioens librerias:***
- apistatus "github.com/udistrital/utils_oas/apiStatusLib"
- "github.com/udistrital/utils_oas/customerrorv2"
- auditoria "github.com/udistrital/auditoria"

**Comment by stevencol** [comment]
🔴EL archivo README Esta en fase inicial, se ira completando a medida que el desarrollo avanza

**Comment by JuanCamiloMartinezLopez** [comment]
@stevencol Buen trabajo
