### ISSUE TITLE
Despliegue en producción modulo de históricos - Cumplidos CPS

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#82]
Se requiere realizar el despliegue en producción del módulo de históricos de cumplidos CPS 

**Sub Tareas**

- [x] Desplegar y verificar correcto funcionamiento Cliente.
- [x] Desplegar y verificar correcto funcionamiento Mid.
- [x] Desplegar y verificar correcto funcionamiento Crud.
- [x] Validar menús y roles.

**Criterios de aceptación**

- [x] Despliegue correcto y sistema funcional en producción.
- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
Se lleva a cabo la reunio para el despliegue del modulo de históricos de solicitudes de pagos, se comienza con los respectivos PR a develo, luego a release y por último a master del crud, mid y cliente respectivamente, se crean nuevamente los roles en el sistema de configuraciones y se actualizan las variables de entorno en tuleap, al realizar el despliegue de los componentes de la aplicación se presenta una falla en el sistema de configuraciones, el cual se analizó durante la sesión para su correcta identificación.

**Comment by stevencol** [comment]
Se realizan los siguientes pull request ;

**Cumplidos crud**
De devlop a release  ->https://github.com/udistrital/cumplidos_crud/pull/40
de release a master -> https://github.com/udistrital/cumplidos_crud/pull/41

**Cumplidos mid**
De devlop a release  ->https://github.com/udistrital/cumplidos_mid/pull/144
de release a master -> https://github.com/udistrital/cumplidos_mid/pull/145

**Cumplidos Cliente** 
De devlop a release  ->https://github.com/udistrital/cumplidos_cliente/pull/378
de release a master -> https://github.com/udistrital/cumplidos_cliente/pull/379

**Comment by JuanCamiloMartinezLopez** [comment]
Se realiza la actualizacion de variables de entorno en cumplidos_mid prod mediante el siguiente [kb](https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=62349)

**Comment by JuanCamiloMartinezLopez** [comment]
Se crean los roles de SUPERVISOR, ORDENADOR_DEL_GASTO y CONTRATISTA en configuración en producción, y se asignan los menús para cada rol
