### ISSUE TITLE
Propuesta de controladores para revision_cumplidos_proveedores_mid

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#83]
Se requiere realizar la propuesta de controladores y endpoints para el mid de revisión de cumplidos proveedores, teniendo en cuenta los procesos, roles, datos de entrada y datos de salida, etc.

**Sub Tareas**

- [x] Crear una propuesta de endpoints y controladores
- [x] Indicar que tarea realizaría cada uno.
- [x] proponer helpers que generales (ej: consulta acta de inicio).

**Criterios de aceptación**

- [x] Propuesta realizada.
- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
Se realiza una primera versión de la propuesta que se tiene para los controladores y se adjunta en la carpeta del proyecto para su revisión y los correspondientes comentarios, en caso de ser necesarios.

[Propuesta Controladores Cumplidos Proveedores](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EaEFwZmY5V5Gs5kBhUN0SXwBjgcHGSa3SXkDZ0dqRyZw2g?e=qC7kwZ)

**Comment by faidercamilo26** [comment]
## :triangular_flag_on_post: **Propuesta Controladores Cumplidos Proveedores**  :triangular_flag_on_post:

Se agrega el controlador de listar los documentos que se pueden subir en el cumplido  y se adjunta la propuesta a la issue para que quede en la traza de la issue.


| Número | Carpeta                    | Controlador                                                                                                                                                                                                                   | Entrada                                                                                                                                                 | Salida                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          | Metodo HTTP                     | Endpoint                                                                                                                                                                     | Descripción                                                                                                                                                                                  | Notas                                                           |
| ------ | -------------------------- | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------- | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | --------------------------------------------------------------- |
| 1      | controladores_supervisor   | ContratosSupervisorController                                                                                                                                                                                                 | documento_supervisor                                                                                                                                    | {<br>    "dependencias_supervisor":,<br>    "contratos": [<br>        {<br>            "tipo_contrato",<br>            "numero_contrato",<br>            "vigencia",<br>            "rp",<br>            "vigencia_rp",<br>            "nombre_proovedor",<br>            "dependencia",<br>            "cdp",<br>            "crp"<br>        },<br>    ]<br>}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 | GET                             | /supervisor/contratos-proveedor/{documento-supervisor}                                                                                                                       | Controlador que recibe el número de documento de un supervisor y retorna las dependencias a las que esta vinculado y la informacion de los contratos de los proveedores que tiene asociados. |                                                                 |
| 2      | controladores_supervisor   | SolicitudContratoController                                                                                                                                                                                                   | numero_contrato                                                                                                                                         | <br>{<br>    "id",<br>    "numero_contrato",<br>    "fecha_creacion",<br>    "periodo_pago",<br>    "estado_solicitud",<br>}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    | GET                             | /supervisor/solicitudes-contrato/{numero_contrato}                                                                                                                           | Controlador encargado de retornar el listado de solicitudes de pago de un proveedor, se buscan estas solicitudes con el número de contrato del proveedor.                                    |                                                                 |
| 3      | controladores_supervisor   | InformeSeguimientoController                                                                                                                                                                                                  | numero_contrato                                                                                                                                         | <br>{<br>        "total_contrato",<br>        "saldo"<br>    }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | GET                             | /supervisor/balance-financiero-contrato/{numero_contrato}                                                                                                                    | Controlador que se encarga de retornar el total y el saldo de un contrato.                                                                                                                   |                                                                 |
| 4      | controladores_supervisor   | <br>{<br>    "tipo_pago",<br>    "periodo_inicio",<br>    "periodo_fin",<br>    "tipo_soporte_pagar",<br>    "numero_cuenta_factura",<br>    "valor_pagar",<br>    "tipo_cuenta",<br>    "numero_cuenta",<br>    "banco"<br>} | {<br>    "status":,<br>    "message",<br>    "data",<br>    "succes"<br>}                                                                               | POST                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | /supervisor/informe-seguimiento | Controlador encargado de recibir todos los datos necesarios que el supervisor debe ingresar en el formulario para con estos, generar el informe de seguimiento del proveedor |                                                                                                                                                                                              |
| 5      | controladores_supervisor   | ListarTipoDocumentosCumplidoController                                                                                                                                                                                        |                                                                                                                                                         | {<br>    "status":,<br>    "message",<br>    "data": documentos [<br>       <br>    ],<br>    "succes"<br>}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | GET                             | /supervisor/listar-tipo-documentos                                                                                                                                           | Controlador encargado de listar el tipo de documentos que se pueden subir en la solicitud de pago.                                                                                           |                                                                 |
| 6      | controladores_contratacion | RevisionCumplidoContratacionController                                                                                                                                                                                        |                                                                                                                                                         | {<br>    "contratos": [<br>        {<br>            "tipo_contrato",<br>            "numero_contrato",<br>            "vigencia",<br>            "rp",<br>            "vigencia_rp",<br>            "nombre_proovedor",<br>            "dependencia",<br>            "cdp",<br>            "crp"<br>        },<br>    ]<br>}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    | GET                             | /contratacion/solicitudes-pago/                                                                                                                                              | Controlador encargado de retornar la informacion de las solicitudes a cargo de una persona de contratacion para realizar la aprobación o rechazo de las solicitudes de pago.                 |                                                                 |
| 7      | controladores_ordenador    | RevisionCumplidoOrdenadorController                                                                                                                                                                                           | documento_persona_ordenador                                                                                                                             | <br>{<br>    "contratos": [<br>        {<br>            "tipo_contrato",<br>            "numero_contrato",<br>            "vigencia",<br>            "rp",<br>            "vigencia_rp",<br>            "nombre_proovedor",<br>            "dependencia",<br>            "cdp",<br>            "crp"<br>        },<br>    ]<br>}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                | GET                             | /ordenador/solicitudes-pago/{documento_persona_ordenador}                                                                                                                    | Controlador encargado de retornar la informacion de los contratos a cargo de un ordenador para realizar la aprobación o rechazo de las solicitudes de pago.                                  |                                                                 |
| 8      | controladores_ordenador    | RevisionCumplidoOrdenadorController                                                                                                                                                                                           | solicitud_pago_id                                                                                                                                       | <br>{<br>    "Message",<br>    "succes",<br>    "status",<br>    "estados_pago": [<br>        {<br>           <br>        }<br>    ]<br>}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | POST                            | /ordenador/revertir-solicitud-pago/{id_solicitud_pago}                                                                                                                       | Controlador encargado de revertir el estado de un cumplido aprobado por parte de un ordenador, en caso, de que lo considere necesario.                                                       |                                                                 |
| 9      | controladores_ordenador    | RevisionCumplidoOrdenadorController                                                                                                                                                                                           | solicitud_pago_id                                                                                                                                       | {<br>    "status":,<br>    "message",<br>    "data": certificado aprobacion pago firmado,<br>    "succes"<br>}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | POST                            | /ordenador/certificado-aprobacion-pago                                                                                                                                       | Conrolador encargado de retornar el certificado firmado de aprobacion pago.                                                                                                                  |                                                                 |
| 10     | controladores_soporte      | SoportesCumplidoController                                                                                                                                                                                                    | {<br>    "solicitud_pago_id"<br>    "item",<br>    "observaciones",<br>    "nombre_archivo",<br>    "archivo"<br>}                                      | {<br>    "status":,<br>    "message",<br>    "data",<br>    "succes"<br>}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | POST                            | /solicitud-pago/soportes                                                                                                                                                     | Controlador que se encarga de la subida de un soporte a una solicitud de pago.                                                                                                               | Falta decidir si se sube el documento en el mid o en el cliente |
| 11     | controladores_soporte      | SoportesCumplidoController                                                                                                                                                                                                    | solicitud_pago_id                                                                                                                                       | [<br>  {<br>    "Archivo": {<br>      "file": "string"<br>    },<br>    "Documento": {<br>      "Activo": true,<br>      "Descripcion": "string",<br>      "Enlace": "string",<br>      "FechaCreacion": "string",<br>      "FechaModificacion": "string",<br>      "Id": 0,<br>      "Metadatos": "string",<br>      "Nombre": "string",<br>      "TipoDocumento": {<br>        "Activo": true,<br>        "CodigoAbreviacion": "string",<br>        "Descripcion": "string",<br>        "DominioTipoDocumento": {<br>          "Activo": true,<br>          "CodigoAbreviacion": "string",<br>          "Descripcion": "string",<br>          "FechaCreacion": "string",<br>          "FechaModificacion": "string",<br>          "Id": 0,<br>          "Nombre": "string",<br>          "NumeroOrden": 0<br>        },<br>        "Extension": "string",<br>        "FechaCreacion": "string",<br>        "FechaModificacion": "string",<br>        "Id": 0,<br>        "Nombre": "string",<br>        "NumeroOrden": 0,<br>        "Tamano": 0,<br>        "TipoDocumentoNuxeo": "string",<br>        "Workspace": "string"<br>      }<br>    }<br>  }<br>] | GET                             | /solicitud-pago/soportes/{id_solicitud_pago}                                                                                                                                 | Controlador que se encarga de retornar el Json con los soportes subidos en una solicitud de pago.                                                                                            |                                                                 |
| 12     | controladores_soporte      | SoportesCumplidoController                                                                                                                                                                                                    | id_soporte                                                                                                                                              | {<br>    "status":,<br>    "message",<br>    "data",<br>    "succes"<br>}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | DELETE                          | /solicitud-pago/soportes/{id_soporte}                                                                                                                                        | Controlador encargado de eliminar un soporte de una solicitud de pago.                                                                                                                       |                                                                 |
| 13     | controladores_soporte      | SoportesCumplidoController                                                                                                                                                                                                    | {<br>    "soporte_id",<br>    "cambio_estado_id"<br>    "comentario"<br>}                                                                               | {<br>    "status":,<br>    "message",<br>    "data",<br>    "succes"<br>}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | POST                            | /soporte/comentario                                                                                                                                                          | Controlador encargado de adjuntar un comentario a un soporte de pago.                                                                                                                        |                                                                 |
| 14     | controladores_soporte      | SoportesCumplidoController                                                                                                                                                                                                    | id_solicitud_pago                                                                                                                                       | <br>{<br>    "Message",<br>    "succes",<br>    "status",<br>    "data": {<br>        "nombre":,<br>        "file":<br>    }<br>}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               | GET                             | /solicitud-pago/soportes-comprimido/{id_solicitud_pago}                                                                                                                      | Controlador encargado de descargar un comprimido con todos los soportes asociados a una solicitud de pago                                                                                    |                                                                 |
| 15     | controladores_estados_pago | EstadoSoporteController                                                                                                                                                                                                       | <br>{<br>    "cumplido_proveedor_id",<br>    "solicitud_pago_id",<br>    "responsable_id",<br>    "cargo_responsable",<br>    "estado_cumplido_id"<br>} | {<br>    "status":,<br>    "message",<br>    "data",<br>    "succes"<br>}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | POST                            | /solicitud-pago/cambio-estado                                                                                                                                                | Controlador encargado de cambiar el estado de una solicitud de pago, el estado puede ser aprobado o rechazado.                                                                               |                                                                 |


## :triangular_flag_on_post: **Propuesta Helpers Generales Cumplidos Proveedores**  :triangular_flag_on_post:



| Número | Helper                        | Entradas                                                                                  | Salidas                                                                                                                                  | Descripción                                                                                  |
| ------ | ----------------------------- | ----------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------- |
| 1      | InformacionContratos()        | numero_contrato                                                                           | <br>• tipo_contrato<br>• numero_contrato<br>• vigencia<br>• rp<br>• vigencia_rp<br>• nombre_proovedor<br>• dependencia<br>• cdp<br>• crp | Helper que retorna la informacion completa de un contrato.                                   |
| 2      | CambioEstadoSolicitudPago()   | • estado_solicitud_pago<br>• solicitud_pago_id<br>• responsable_id<br>• cargo_responsable | • estado_solicitud_pago<br>• cumplido_proveedor_id<br>• responsable_id<br>• cargo_responsable<br>                                        | Helper que retorna un cambio de estado en una solicitud de pago.                             |
| 3      | ConsultarGestorDocumental()   | id_solicitud_pago                                                                         | • Listado de documentos encriptados.                                                                                                     | Helper que retorna todos los soportes vinculados a una solicitud de pago.                    |
| 4      | AgregarObservacionSoporte()   | • id_soporte<br>• comentario                                                              | • Informacion soporte con el comentario asinado.                                                                                         | Helper  que asocia un comentario a un soporte subido en el cumplido                          |
| 5      | OpcionTipoDocumentoCumplido() |                                                                                           | • Listado de opciones de archivos para subir en un cumplido.                                                                             | Helper que retorna un listado de los posibles documentos que se pueden subir en un cumplido. |

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 Buen trabajo
