### ISSUE TITLE
Definicion de información de sistemas externos

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#85]
Se requiere realizar la definición de la información requerida para el funcionamiento de cumplidos proveedores que se deba consultar de sistemas externos, data como puede ser información del contrato(argo), información del valores pagados/adeudados(sicapital), etc.

**Sub Tareas**

- [x] Según el flujo y procesos realizados en el módulo de revisión de cumplidos, definir la información requerida y su posible fuente de consulta.
- [x] Determinar los servicios que se requieren solicitar para la información no disponible.

**Criterios de aceptación**

- [x] Definición de información y sus fuentes.
- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by stevencol** [comment]
Se inicia con Issue

**Comment by stevencol** [comment]
1.
- información necesaria:   Numero cdp/Vigencia del Contrato/contratos
- cómo se obtiene:  con documento y contrato : http://busservicios.intranetoas.udistrital.edu.co:8282/wso2eiserver/services/administrativa_produccion/contratos_contratista/{documento}
- Datos que se reciben: 
vigencia
numero_contrato
fecha_inicio
fecha_fin
cdp
2. 
- información necesaria:  InformacionProveedor
- cómo se obtiene: http://api.intranetoas.udistrital.edu.co:8104/v1/informacion_proveedor/?query=id:{documento}

- Datos que se reciben: 
-id
-tipo persona
-Numero Documento
-IdCiudadContacto
-Direccion
-Correo
-Web
-NomAsesor
-TelAsesor
-Descripcion
-PuntajeEvaluacion
-ClasificacionEvaluacion
-TipoCuentaBancaria
-NumCuentaBancaria
-IdEntidadBancaria
-FechaRegistro
-FechaUltimaModificacion
-NomProveedor
-Anexorut
-Anexorup
-RegimenContributivo

3. 
- información necesaria:  Información ordenador:

- Como se obtiene: 
http://pruebasapi.intranetoas.udistrital.edu.co:8104/v1/supervisor_contrato?query=DependenciaSupervisor:DEP12&sortby=FechaInicio&order=desc&limit=1
- Datos que se reciben: 
Id
        Nombre
        Documento
        Cargo
        SedeSupervisor
        DependenciaSupervisor
        Tipo
        Estado
        DigitoVerificacion
        FechaInicio
        FechaFin
        CargoId: {
            Id
            Cargo
        }

**Comment by stevencol** [comment]
4.
- información necesaria: información persona de contratación: 
- Como se obtiene : http://[pruebasapi.intranetoas.udistrital.edu.co:8104/v1/supervisor_contrato?query=DependenciaSupervisor:DEP636&sortby=FechaInicio&order=desc&limit=1](http://pruebasapi.intranetoas.udistrital.edu.co:8104/v1/supervisor_contrato?query=DependenciaSupervisor:DEP636&sortby=FechaInicio&order=desc&limit=1)

- Datos que se reciben: 
Id
        Nombre
        Documento
        Cargo
        SedeSupervisor
        DependenciaSupervisor
        Tipo
        Estado
        DigitoVerificacion
        FechaInicio
        FechaFin
        CargoId: {
            Id
            Cargo
        }

**Comment by stevencol** [comment]
5.
-información necesaria: informacion del pago

- Como se obtiene :

- Datos que se reciben: 




6.

- información necesaria: informacion del Banco

- Como se obtiene :

- Datos que se reciben:

**Comment by stevencol** [comment]
7.

- información necesaria: vigencia cdp

- Como se obtiene :

- Datos que se reciben:
 8.

- información necesaria: vigencia rp/ numero rp/numero crp
 numero cdp ?= base de datos argo.contrato_disponibilidad se obtiene con numero de contrato
- Como se obtiene : 

- Datos que se reciben:

**Comment by stevencol** [comment]
## Se realizan correcciones solicitadas 

- Se elimina fuete de información para persona de contratación: (no es necearía por el momento ) 
-   Se corrige  fuente de consulta info  para ordenador
- Se  agrega fuente de consulta info  de valor contrato
-  Se  agrega fuente de consulta info  de contrato }

### Se agrega fuentes al tabla excel:
[Feunte de datos](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EfmouqE12IJHpivHOKMndboBUuuscldzAO2zIbIqSG4W3A?e=gGihb5)

**Comment by JuanCamiloMartinezLopez** [comment]
@stevencol Buen trabajo
