### ISSUE TITLE
Definir usuarios y roles con Control Interno para vista históricos cumplidos en producción

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/Cumplidos_y_certificaciones_documentacion#86]
Se requiere realizar la definición de usuarios y roles con Control Interno para vista históricos cumplidos en producción

**Sub Tareas**

- [x] Concertar reunión con el cliente.
- [x] Desarrollar la reunión con el cliente.

**Criterios de aceptación**

- [x] Usuarios y roles definidios.
- [x] Entrega de usuarios y roles a Control Interno.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se ha hablado con control interno para obtener los usuarios, Jhon nos cuenta que el usuario que ellos abarcan un usuario general de control interno.

- Este usuario se entrego al Juan Camilo , pero al momento de organizar con Funcionamiento se realiza la duda si ese usuario esta activo.
- Se pregunta a control interno si ese usuario esta activo , pero efectivamente no esta activo , y se comunico con funcionamiento , estos pidieron que entonces se otorgara un usuario activo personal para darle el rol.
- Se ha pedido a control interno este usuario y quedamos a espera de la información para seguir.

**Comment by jcmurilloa** [comment]
Entendido @mantnicot, pendiente generar seguimiento a respuesta de control interno.

**Comment by mantnicot** [comment]
Se ha podido comunicar con Jhon con respecto a la petición de usuario y comenta que se queda a espera de aprobación del jefe de la oficia Guillermo

**Comment by mantnicot** [comment]
Gracias a le gestión del lider tecnico , se ha podido asignar el usuario para la oficina y se ha dado entrega formar del usuario



![Image](https://github.com/user-attachments/assets/e4aee8aa-af52-4f02-b1e4-88e264660655)

**Comment by jcmurilloa** [comment]
Muy buena gestión equipo.
