### ISSUE TITLE
Actualizar mockup módulo certificaciones DVE

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/Cumplidos_y_certificaciones_documentacion#87]
Se requiere generar la actualización del mockup del módulo certificaciones DVE, teniendo en cuenta la actualización de los formatos por parte del SIGUD. 

**Sub Tareas**

- [x] Actualizar el diseño del mockup inicial con base en las actualizaciones.
- [x] Presentar el mockup al equipo SoS.
- [x] Realizar ajustes según comentarios del equipo SoS.
- [x] Presentar al equipo el mockup definitivo para presentar al cliente.

**Criterios de aceptación**

- [x] Mockup aprobado por equipo SoS.
- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se han revisado los nuevos formatos aprobados por el sigud y el unico cambio es la muestra del nombre de jefe de la oficina



![Image](https://github.com/user-attachments/assets/ae4d8fa1-4aef-4b9e-844a-fc24f563e660)



![Image](https://github.com/user-attachments/assets/8656c16a-705f-48fa-8949-4d45ee4cec0f)


Por lo cual los mockups no cambian , pero se han realizado las mejoras para facilidad del usuario



![Image](https://github.com/user-attachments/assets/f9b4dba6-2ffb-499c-a7a0-b11f1abb1382)
![Image](https://github.com/user-attachments/assets/39b22519-6772-4d91-8c36-fc81e736ebe6)
![Image](https://github.com/user-attachments/assets/7a9f4a53-b4b0-4135-a42a-27461213e346)



(Carpeta de mockups)[https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EjH3Stz4tllFiQILWV67NwIBKyUfWNHQj-qksNgj4GUFOg?e=7sDR60]

**Comment by jcmurilloa** [comment]
Muy buen diseño @mantnicot, lo repasaremos en la próxima sesión Review SoS.

**Comment by jcmurilloa** [comment]
Excelente trabajo @mantnicot, se incluyeron opciones importantes y certificado aprobado por SIGUD
