### ISSUE TITLE
Actualización de manuales del módulo Cumplidos CPS

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/Cumplidos_y_certificaciones_documentacion#88]
Se requiere generar la actualización de los manuales del módulo Cumplidos CPS, según obervaciones realizadas

**Sub Tareas**

- [x] Levantar requerimientos de ajuste de manuales.
- [x] Generar solicitud de actualización con responsable.
- [x] Realizar seguimiento a la actualización de manuales.

**Criterios de aceptación**

- [x] Manuales actualizados.
- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se ha realizado la reunión con Viviana, 17/07/2024 , se dará fecha 18/07/2024 para dar respuesta a cuando se entregan los manuales

**Comment by jcmurilloa** [comment]
Buen trabajo @mantnicot, quedamos entonces atentos a la documentación de los manuales actualizados.

**Comment by mantnicot** [comment]
En al reunión se ha definido poder actualizar los manuales existentes de cada rol , y así mismo poder dar actualización a los videos del contratista pues estos solo muestran la subida del informe de gestión pero falta la carga de documentos.


Se ha hablado con Juan Camilo a petición de las credenciales de los usuarios para que Viviana pueda realizar las pruebas y toma de pantallazos para los manuales y se ha establecido que se creara en pruebas un entorno en el cual ella pueda pueda probar.

Se queda a espera a este entorno y poder dar pie a la actualización de los manuales

**Comment by jcmurilloa** [comment]
Por favor estar atento al desarrollo del entorno de pruebas por parte del equipo de desarrollo para retomar el contacto con la responsable.

**Comment by jcmurilloa** [comment]
Se hace necesario trasladar de sprint la issue debido a estabalización del ambiente de pruebas.

**Comment by mantnicot** [comment]
Se ha establecido la entrega para el día 21 / 08 / 2024 de parte de la persona responsable

**Comment by jcmurilloa** [comment]
@mantnicot Se realizo la entrega de los manuales el día establecido? a la espera de tus comentarios.

**Comment by mantnicot** [comment]
Se ha tenido un retraso en al entrega de los manuales al parecer por falta de organización de parte de comunicaciones



![Image](https://github.com/user-attachments/assets/a04b37f2-3e28-4745-941e-5ee0de89ed0d)


se ha dado el link y se espera pronta entrega

**Comment by jcmurilloa** [comment]
Esperemos que la espera no supere este semana y podamos contar con este material muy pronto.

**Comment by mantnicot** [comment]
Se ha podido entregar los manuales de actualizados de cumplidos cps

[Manuales actualizados](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EiyUKOtREUlCvobMGmyjXmYBlYEbJm9xyswYWZqci3KVqg?e=36ynSL)

**Comment by jcmurilloa** [comment]
Excelente gestión @mantnicot!
