### ISSUE TITLE
Ajustar modelo de revisión de cumplidos proveedores - Parte II

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#89]
Se requiere realizar los ajustes indicados por los DBA al modelo [v2](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/Ev4_Hq5y6RZJq2PLBUGKR8oBqaU2gk4ro1W-iK_1y2zmcg?e=g2PN1I)

**Sub Tareas**

- [x] Revisar los ajustes indicados por los dba en el [kb](https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=62102) y segun lo indicado en el [daily](https://udistritaleduco-my.sharepoint.com/:v:/g/personal/juacmartinezl_udistrital_edu_co/EaP0zADAiJRBiejGElnTm2QBdZbcrjn1Jsxxo6LK7ls0FA?e=roztqV)

**Criterios de aceptación**

- [x] Carpeta con la nueva versión del modelo con los ajustes indicados

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by stevencol** [comment]
Se inicia con actividad:


Se realizan cambios indicados quedando de la siguiente manera :

![image](https://github.com/user-attachments/assets/83a3faad-248a-43e2-b6f3-c8713fee5e5c)


- pendiente por indicar origen de responsable id, y numero de contrato

**Comment by stevencol** [comment]
Se relizan correciones solicitadas : 



![Image](https://github.com/user-attachments/assets/deecc851-ac2a-4d0f-a885-236833fc392f)

- Se cargan archivos a carpeta de Onedrive correspondiente 
[carpeta](https://udistritaleduco-my.sharepoint.com/personal/computo_udistrital_edu_co/_layouts/15/onedrive.aspx?FolderCTID=0x012000126D0396B17002409C7255322B2A7B42&id=%2Fpersonal%2Fcomputo%5Fudistrital%5Fedu%5Fco%2FDocuments%2FINVERSI%C3%93N%2FPROYECTOS%20DE%20INVERSI%C3%93N%2FGERENCIA%20DE%20PROYECTOS%2FPROYECTOS%20OAS%2FPROYECTO%20CUMPLIDOS%20Y%20CERTIFICACIONES%2F2024%2FEjecuci%C3%B3n%2FGesti%C3%B3n%20t%C3%A9cnica%2FCUMPLIDOS%2FProveedores%2FModelos%20de%20base%20de%20datos%2FRevisi%C3%B3n%20cumplidos%20proveedores%2FV3)

**Comment by stevencol** [comment]
Correcciones ultimo ajuste:

![Image](https://github.com/user-attachments/assets/e506632a-5c0d-4917-a932-48ccebcb12c8)


- carpeta de Onedrive correspondiente 
[carpeta](https://udistritaleduco-my.sharepoint.com/personal/computo_udistrital_edu_co/_layouts/15/onedrive.aspx?FolderCTID=0x012000126D0396B17002409C7255322B2A7B42&id=%2Fpersonal%2Fcomputo%5Fudistrital%5Fedu%5Fco%2FDocuments%2FINVERSI%C3%93N%2FPROYECTOS%20DE%20INVERSI%C3%93N%2FGERENCIA%20DE%20PROYECTOS%2FPROYECTOS%20OAS%2FPROYECTO%20CUMPLIDOS%20Y%20CERTIFICACIONES%2F2024%2FEjecuci%C3%B3n%2FGesti%C3%B3n%20t%C3%A9cnica%2FCUMPLIDOS%2FProveedores%2FModelos%20de%20base%20de%20datos%2FRevisi%C3%B3n%20cumplidos%20proveedores%2FV3)

**Comment by JuanCamiloMartinezLopez** [comment]
@stevencol Buen trabajo.
