### ISSUE TITLE
Ajustar modelo de evaluación y estructura de evaluación de cumplidos proveedores - Parte II

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#90]
Se requiere realizar los ajustes indicados por los DBA al modelo [v3](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/Egwn-6KClytJiAqjntcfJDYBocPJsTZ_7IZN5BULvIITAg?e=TDqymZ)

**Sub Tareas**

- [x] Revisar los ajustes indicados por los dba en el [kb](https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=62102) y segun lo indicado en el [daily](https://udistritaleduco-my.sharepoint.com/:v:/g/personal/juacmartinezl_udistrital_edu_co/EaP0zADAiJRBiejGElnTm2QBdZbcrjn1Jsxxo6LK7ls0FA?e=roztqV)

**Criterios de aceptación**

- [x] Carpeta con la nueva versión del modelo con los ajustes indicados

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by faidercamilo26** [comment]
Se revisan los cambios indicados por los DBA, se realizan las correcciones correspondientes, se agregan los comentarios a todas las columnas de las tablas para seguir los lineamientos. Se agregan las capturas de los modelos corregidos a la carpeta [V4](https://udistritaleduco-my.sharepoint.com/personal/computo_udistrital_edu_co/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fcomputo%5Fudistrital%5Fedu%5Fco%2FDocuments%2FINVERSI%C3%93N%2FPROYECTOS%20DE%20INVERSI%C3%93N%2FGERENCIA%20DE%20PROYECTOS%2FPROYECTOS%20OAS%2FPROYECTO%20CUMPLIDOS%20Y%20CERTIFICACIONES%2F2024%2FEjecuci%C3%B3n%2FGesti%C3%B3n%20t%C3%A9cnica%2FCUMPLIDOS%2FProveedores%2FModelos%20de%20base%20de%20datos%2FEvaluaci%C3%B3n%20cumplidos%20proveedores%2Fv4) de los modelos.



![Image](https://github.com/user-attachments/assets/cf44be69-871b-47fc-82f2-3bb2eb103872)



![Image](https://github.com/user-attachments/assets/28e43f0b-29a6-42a4-9a4a-3fa10ab2ef20)

**Comment by JuanCamiloMartinezLopez** [comment]
@faidercamilo26 Buen trabajo
