### ISSUE TITLE
Inmersión y apropiación del negocio en cuanto a desarrollo de pruebas para proyectos

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/Cumplidos_y_certificaciones_documentacion#92]
Se requiere realizar la Inmersión y apropiación del negocio en cuanto a desarrollo de pruebas para proyectos

**Sub Tareas**

- [x] Repasar grabación de la sesión
- [x] Repasar documentación relacionada

**Criterios de aceptación**

- [x] Análisis y resumen del negocio

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by mantnicot** [comment]
Se ha podido ver toda la reunión que se tuvo y analizado la documentación.

[Documentación](https://github.com/udistrital/sga_documentacion/issues/347)

Se puede ver que el proceso de desarrollo con base a pruebas, esta en un estado muy nuevo y de adaptación , también se puede observar que hasta ahora el enfoque esta más en el apartado técnico que de análisis , pues se puede ver que hasta ahora se esta tocando en el lenguaje GO , a diferencia del profesor Daza que lo uso en Python.


El proceso de creación debe ser , primero crear escenarios de pruebas con base a los endpoints y comparativo de los json que se crea y json que debería traer , principalmente en la estructura.
Después se hace una muestra de los resultados y el tipo de error del mismo.


Se queda abierta la posibilidad de poder usar en mids y no solo en crud's , por lo cual se estará realizando el otros equipos estas pruebas de escenarios.

**Comment by jcmurilloa** [comment]
Muy buen documento @mantnicot, estaremos atentos al avance de este aspecto para la inmersión desde tu rol de analista.
