### ISSUE TITLE
Ajustar revision_cumplidos_proveedores_crud al modelo aprobado.

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#96]
Se requiere realizar el ajuste de  [revision_cumplidos_proveedores_crud](https://github.com/udistrital/revision_cumplidos_proveedores_crud) de acuerdo al [modelo aprobado](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/ErMfMzRRHC9NoeMwEbP7UogBrNog0vu09ZqUUUBXvVjHEw?e=ND1poj) 

**Sub Tareas**

- [x] Realizar ajuste a los modelos y comprobar su funcionamiento.
- [x] Realizar conexión y pruebas en base de datos en pruebas.
- [x] Registrar peticiones en el workspace de Postman

**Criterios de aceptación**

- [x] Ajustes realizados.
- [x] Peticiones base en el workspace
- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by stevencol** [comment]
# 🏁 Inicio De actividad 🏁
 **Se inicia con eliminación de Atributos de la tabla cumplido proveedor:**
![image](https://github.com/user-attachments/assets/44272104-e420-4b4d-8d04-ce90825fbe49)   
 
![image](https://github.com/user-attachments/assets/7fa27b33-75f7-4cef-8569-b896c4fbd03c)


**Se renombra modelo, relaciones y controlador de estado_soporte a estado_cumplido**
![image](https://github.com/user-attachments/assets/fcc7d837-ed03-4448-92e2-4a52d7ff6dc8)

**Comment by stevencol** [comment]
Prueba Post  estado_cumplido:
![image](https://github.com/user-attachments/assets/516deef8-ccf9-4382-9a84-46381e5fe89e)

**Comment by stevencol** [comment]
Prueba Get estado_cumplido:
![image](https://github.com/user-attachments/assets/59c1a736-5f2f-4b35-8a68-42e869caea8c)

**Comment by stevencol** [comment]
Se presento un problema al insertar un registro en estado_cumplido, ya que hubo un error en el modelo de base de datos, y el nombre estaba de tipo int, se corrige  model/bd local  y se actualiza en la carpeta correspondiente 
![image](https://github.com/user-attachments/assets/f9db80df-9677-4a70-81d0-afab61b4945c)

**Comment by stevencol** [comment]
## estado_cumplido
*Se  presentaron algunos inconvenientes : al hacer el softdelete* en  **estado_cumplido**
se modifica puntero que causaba el error al realizar el softdelete

*Antes:*
``` GO

func DeleteEstadoCumplido(id int) (err error) {
	fmt.Println("si entro " , id)
	o := orm.NewOrm()
	v := EstadoCumplido{Id: id}
	// ascertain id exists in the database
	if err = o.Read(&v); err == nil {
		var num int64
		v.Activo = false
		if num, err = o.Update(v); err == nil {
			fmt.Println("Number of records deleted in database:", num)
		}
	}
	return
}


```
*Ahorra:*
``` GO

func DeleteEstadoCumplido(id int) (err error) {
	fmt.Println("si entro " , id)
	o := orm.NewOrm()
	v := EstadoCumplido{Id: id}
	// ascertain id exists in the database
	if err = o.Read(&v); err == nil {
		var num int64
		v.Activo = false
		if num, err = o.Update(&v); err == nil {
			fmt.Println("Number of records deleted in database:", num)
		}
	}
	return
}


```

*Funcionalidad:*
![test](https://github.com/user-attachments/assets/cacdb5fb-720c-4f1d-bcbc-a2d7ce181c46)

**Comment by stevencol** [comment]
## cumplido_proveedor

Se modifica y se prueban todos los metodos:
![test](https://github.com/user-attachments/assets/021c3c9d-e18e-4278-98b4-8094cfd97569)

**Comment by stevencol** [comment]
## soporte_pago

![test](https://github.com/user-attachments/assets/589429f8-76f0-4837-b438-141ec35c034e)

**Comment by stevencol** [comment]
## comentario_soporte
![test](https://github.com/user-attachments/assets/667a168b-c09a-44a3-a779-929626d52d56)

**Comment by stevencol** [comment]
## cambio_estado_cumplido
![test](https://github.com/user-attachments/assets/4672779f-16f9-4ea2-94dc-0cec48b9a864)

**Comment by stevencol** [comment]
*Se realizan las tareas requeridas para esta Issue   por lo que se da como finalizada.* ✅

**Comment by JuanCamiloMartinezLopez** [comment]
@stevencol Buen trabajo
