### ISSUE TITLE
Creación de servicio para la generación de documento autorización de giro

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/Cumplidos_y_certificaciones_documentacion#98]
Se requiere realizar el desarrollo del servicio para generar el documento pdf de autorización de giro en el endpoint  /ordenador/certificado-aprobacion-pago

**Sub Tareas**

- [ ] Utilizar [gofpdf](https://github.com/phpdave11/gofpdf) para la generacion del documento [autorizacion de giro](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EdfdMH-A2_9MtZlRp8jbnZEBglcH2w819JW6yxoTAAgwwg?e=fhSd52)
- [ ] Crear una función externa la controlador y helper para la creación del documento.
- [ ] Tomar como ejemplo el [repositorio](https://github.com/udistrital/sga_inscripcion_mid/blob/develop/services/generar_recibo.service.go).

**Criterios de aceptación**

- [ ] Servicio para la generación del documento.
- [ ] Issue documentado.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by jcmurilloa** [comment]
Buen dia. Por favor recuerden que las issues deben ser culminadas en el respectivo sprint, hoy estamos iniciando el sprint 14 y aún no se culmina esta tarea.

**Comment by stevencol** [comment]
Se inicia con actividad

**Comment by stevencol** [comment]
Se avanza con actividad, con algunas dificultades  , ya que la tabla se dibuja con coordenadas y luego con las coordenadas  escribe el texto y las img, también se tiene dificultades con caracteres especiales ya que no se logra configurar utf8,  se deja el avance realizado hasta ahora
![image](https://github.com/user-attachments/assets/8f4cca4f-8997-46e0-9198-57371c7c9853)

**Comment by stevencol** [comment]
Se avanza en la generación del documento, pero surge un problema ya que el heder no se genera al crear otra pagina 
![image](https://github.com/user-attachments/assets/6893e0e7-c029-4e40-952b-4f22451d80e7)
[tabla.pdf](https://github.com/user-attachments/files/16474396/tabla.pdf)

**Comment by stevencol** [comment]
Se termina documento, con funcionalidad temporal, el documento ya se completa con datos de prueba 
![test](https://github.com/user-attachments/assets/b0c7ca24-7f4e-4db1-88a5-0001902c0e3b)

**Comment by JuanCamiloMartinezLopez** [comment]
@stevencol Buen trabajo.
